### ISSUE TITLE
Problem with castling during the game.

### ISSUE THREAD

**Issue by Emalios** [niklasf/python-chess#1005]
I have a small gui for my chess playground, so I start with the basic fen:
"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR"

For each move I use this line to update the board:
```python
            uci = chess.Move.from_uci(self.last_pos + pos)
            if uci in self.board.legal_moves:
                self.board.push(uci)
```
No problem with this code but, after few moves when I want to castle, I can't. 
The fen: 
"rnbqkbnr/pp1p2pp/2p2p2/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w - - 0 4"

And the move_stack:
```
[Move.from_uci('e2e4'), Move.from_uci('e7e5'), Move.from_uci('f1b5'), Move.from_uci('c7c6'), Move.from_uci('g1f3'), Move.from_uci('f7f6')]
```

I don't know why the board don't let me castle, am i doing something wrong ?

**Comment by niklasf** [comment]
That's because there are no castling rights specified in the initial FEN, and so there are no castling rights in the resulting FEN either:
```
rnbqkbnr/pp1p2pp/2p2p2/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w - - 0 4
^                                                       ^ ^
 \                                                     /   \
  board                                 castling rights     en passant square
```

For example `KQk` in `rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1` means that White has king-side castling rights (`K`), White has queen-side castling rights (`Q`), and black has only king-side castling rights (`k`).

**Comment by Emalios** [comment]
> That's because there are no castling rights specified in the initial FEN, and so there are no castling rights in the resulting FEN either:
> 
> ```
> rnbqkbnr/pp1p2pp/2p2p2/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w - - 0 4
> ^                                                       ^ ^
>  \                                                     /   \
>   board                                 castling rights     en passant square
> ```
> 
> For example `KQk` in `rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1` means that White has king-side castling rights (`K`), White has queen-side castling rights (`Q`), and black has only king-side castling rights (`k`).

Thank you very much for the good explanation !
