### ISSUE TITLE
rtd Dcumentation: not able to switch between versions

### ISSUE THREAD

**Issue by kraktus** [niklasf/python-chess#1006]
On https://python-chess.readthedocs.io/en/latest/ it's not possible to switch between lib versions due to missing `jQuery`, probably a mishap when it was generated (or temporary error when pulling jQuery? was not able to find where it comes from).

Maybe a doc rebuild will fix it?

**Comment by niklasf** [comment]
Looks like I introduced this regression by updating to Sphinx 6, due to https://github.com/readthedocs/sphinx_rtd_theme/issues/1253.
