### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by MarkZH** [niklasf/python-chess#1012]
Is there a planned date for the next release of python-chess? The changes that are already merged into the `master` branch would allow for merging some changes in lichess-bot.

**Comment by niklasf** [comment]
@MarkZH, @johndoknjas, @dubslow: Hi all, thanks for your PRs and sorry for the delay on reviews and the next release. I hope to get to it in the next couple weeks and again more frequently after that.

**Comment by MarkZH** [comment]
No problem. Thanks for all your work.

**Comment by niklasf** [comment]
And it's published: https://github.com/niklasf/python-chess/releases/tag/v1.10.0

**Comment by MarkZH** [comment]
Awesome! Thanks!
