### ISSUE TITLE
board/move: is_enpassant()?

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#102]
Hi,

is there a way to know if a given move is a "ep-capture"?
From board, i can only see "has_legal_en_passant()" ...do i overlook something?

**Comment by niklasf** [comment]
Hi Jürgen,

Yes, there is board.is_en_passant(move). Hope that helps.

Best regards,
Niklas

**Comment by LocutusOfPenguin** [comment]
thanks!
picochess can be more precise now => closed
