### ISSUE TITLE
(NO ISSUES, IT CAN BE CLOSED) (NO) bugs in parse_san and push_uci in a specific positon

### ISSUE THREAD

**Issue by alexawake** [niklasf/python-chess#1038]
two issues one in parse_san and one in push_uci 
using a specific position and a move in two formats "Qaxb2" and "a2b2"

# CODE
```python
import chess

FEN = "3kb3/1p2bpQ1/5p2/4pP2/3pP2K/P2P4/qN2B2P/2q5 w - - 4 35"

boa = chess.Board()
    
boa.set_fen (FEN)
print (boa)

print (boa.parse_san("Qaxb2"))

boa.push_san("Qaxb2")
boa.push_uci("a2b2")

#    raise IllegalMoveError(f"illegal san: {san!r} in {self.fen()}")
# chess.IllegalMoveError: illegal san: 'Qaxb2' in 3kb3/1p2bpQ1/5p2/4pP2/3pP2K/P2P4/qN2B2P/2q5 w - - 4 35
# chess.IllegalMoveError: no matching legal move for a2b2 (a2 -> b2) in 3kb3/1p2bpQ1/5p2/4pP2/3pP2K/P2P4/qN2B2P/2q5 w - - 4 35
```

**Comment by MarkZH** [comment]
In the initial FEN, it is white's turn to move, but the queen on a2 is black.

**Comment by alexawake** [comment]
yes, its the turn that is wrong in the FEN string, so please close the ISSUE.
Actually in the pgn the move is 35. Bf1 Qaxb2. I have to investigate the sequence of push and pops in the script that is playing that.
