### ISSUE TITLE
Trouble understanding results from UCI engines

### ISSUE THREAD

**Issue by dubiousjim** [niklasf/python-chess#104]
Hi, I'm having trouble understanding how to work with the results from a UCI engine. I'm testing with Stockfish 8 64-bit POPCNT, but I could also test with Komodo 8 64-bit POPCNT, too, if that helps.

```
>>> from chess import Board
>>> import chess.uci as U

>>> def open_stockfish(pv=1, contempt=0):
  e = U.popen_engine('stockfish')
  e.uci()
  e.setoption({'MultiPV':pv, 'Threads':4, 'Hash':pv*128, 'Ponder':False, 'Contempt':7+contempt//2})
  return e

>>> def open_komodo(pv=1, contempt=0): # contempt can be -200..200
  e = U.popen_engine('komodo')
  e.uci()
  e.setoption({'MultiPV':pv, 'Threads':4, 'Hash':pv*128, 'Ponder':False, 'OwnBook':False, 'Drawscore':-7-contempt})
  return e

>>> def score(i, pv):
  return round(i.info['score'][pv].cp/100.0, 2)

>>> def best_moves(b, engine=None, pv=1, depth=20, opener=open_stockfish):
  e = opener(pv) if engine is None else engine
  if not e.info_handlers:
    e.info_handlers.append(U.InfoHandler())
  i = e.info_handlers[0]
  e.position(b)
  e.go(depth=depth)
  res=[(b.san(ms[0]), score(i,k)) for k,ms in i.info['pv'].items()]
  if engine is None:
    e.quit()
  return res

>>> def eval_position(b, engine=None, depth=20, opener=open_stockfish):
  e = opener(1) if engine is None else engine
  if not e.info_handlers:
    e.info_handlers.append(U.InfoHandler())
  i = e.info_handlers[0]
  m = b.pop()
  e.position(b)
  e.go(searchmoves=(m,), depth=depth+0)
  res=score(i, 1)
  b.push(m)
  if engine is None:
    e.quit()
  return res

>>> b = Board()
>>> all(b.push_san(m) for m in "d4 d5 c4 dxc4 e3".split())
True
>>> print(b)
r n b q k b n r
p p p . p p p p
. . . . . . . .
. . . . . . . .
. . p P . . . .
. . . . P . . .
P P . . . P P P
R N B Q K B N R


>>> [eval_position(b,depth=10,opener=open_stockfish) for _ in range(10)]
[0.62, 0.6, 0.69, 0.44, 0.4, 0.64, 0.33, 0.5, 0.56, 0.4]
```

Why is the evaluation of the position so unstable? I tried with a few different builds of Stockfish (v7 and v8); and Komodo behaves the same way.

Also, I would expect that if I query:

```
>>> best_moves(b, pv=3, depth=10)
[('c5', -0.38), ('Nf6', -0.38), ('e6', -0.38)]
```

(By the way, does that mean the absolute evaluation of the position after Black moves ...c5 is -.38? Or that it's -.38 from Black's perspective (and so, +.38)? Or that it's .38 worse than the position before the move?)

Then if I did:

```
>>> b.push_san('c5')
>>> eval_position(b,depth=10)
```

I should get the output of -0.38. But this doesn't happen. Perhaps this just reflects the earlier problem of unstable evaluations.

I'm not sure whether the problem here is with python-chess, or with my UCI engines (though as I said I tried this with a couple of engines, including different builds, still I see some instability in their output even when interacting with them on the command line), or both of those are alright and it's just my understanding of the results that's defective. But I thought I'd ask.

**Comment by dubiousjim** [comment]
I made a comment:

> still I see some instability in their output even when interacting with them on the command line

However, experimenting some more, I see that the command-line results from these engines are stable, so long as I enter `ucinewgame` and re-submit the position every time before asking for an evaluation. Alternatively, if I quit the engine and always submit the request with a new instance. Otherwise, the engines cache some of their previous work, so you can't expect:

```
position blahblah
go yada yada
go yada yada
```

to deliver the same results for the two invocations of `go yada yada`, even if the `go` request specified a max depth to query.

However, none of this explains the varying responses I was getting through the python-chess interface, as shown above, because in that case, each query was submitted to a newly-spawned instance of the engine.

**Comment by niklasf** [comment]
So I finally got to look at this.

First of all, scores are given from the point of view of the side to move.

With multiple threads some instability is to be expected, especially at lower depths. Conversely using a single thread will give completely deterministic results (at least for Stockfish).

If you evaluate a position, and then play the best move and evaluate again, the first score and the flipped second score will be similar most of the time, especially for larger depths. But of course this is not guaranteed. (Otherwise, inductively, the engine would know the evaluation of a "perfect" game of chess.)

**Comment by dubiousjim** [comment]
Thanks for your response to this. I can confirm that, as you say, when the engines are opened with a single thread, then `eval_position` returns deterministic results. But I am still surprised that the results vary so much when using multiple threads. I realize that multi-threading in general introduces indeterminacy, but it wasn't obvious that chess engines would be using the multiple threads in a way that was vulnerable to this (e.g., by having shared, writable, unlocked memory). But it appears that they are. Still, it's also surprising that the results cover so wide a range. Even if I increase the depth to 20, Stockfish 8 returns results ranging from 0.35 to 0.63. A third of a pawn is a substantial spread. I haven't confirmed yet that there's any issue here with python-chess; the problem may be entirely with my engine(s). But whoever's fault it is, should I be concluding that it's not safe to rely on multi-threaded operation of the chess engines for evaluations that need to be finer-grained than 30 centipawns?

**Comment by niklasf** [comment]
Probably. And single threaded evaluations will be determistic, but that doesn't imply that they are reliable or that a 30 cp difference is meaningful. (Since depth 20 is still quite low, and also since chess engine evaluations have to be taken with a grain of salt anyway.)
