### ISSUE TITLE
Support for chess engine tournaments

### ISSUE THREAD

**Issue by johnwbyrd** [niklasf/python-chess#105]
This seems to be a very clever project.  It seems that your project has provided all the ingredients to run a cross-platform UCI chess tournament, without the tournament logic itself.  Is this a planned feature, or am I merely overlooking this as existing functionality?

**Comment by niklasf** [comment]
python-chess is intended to provide the building blocks, not the tools themselves. (As an exception, some small examples are included for self-test and documentation.)
