### ISSUE TITLE
Documentation incorrect for chess.Board.turn

### ISSUE THREAD

**Issue by sylthiel** [niklasf/python-chess#1053]
The docs for [chess.Board.turn](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.turn) claim that this attribute is of the type Color and returns chess.WHITE or chess.BLACK

This does not appear to be the case:

```
s = chess.Board()
print(s.turn) #  prints True
s.push(chess.Move.from_uci('e2e4'))
print(s.turn) #  prints False
```

Which means that s.turn should be read as s.is_white_to_move?

Oh, I'm an idiot, that's the enum value of chess.WHITE and chess.BLACK.

**Comment by niklasf** [comment]
Yep. I would prefer more distinguished values, but it's a performance tradeoff.
