### ISSUE TITLE
flipping the board

### ISSUE THREAD

**Issue by prashant-saxena** [niklasf/python-chess#1055]
Hi,
Windows 10
Python 3.12.0
chess 1.9.4

The default orientation of board is black as opponent. To make white as opponent
```python
board = chess.Board()
print(board.fen())
board.apply_mirror()
print(board.fen())
``` 
output
```
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR b KQkq - 0 1
```
It's only changing the starting side to black.
Another way to flip the board
```
board = board.transform(chess.flip_vertical)
board = board.transform(chess.flip_horizontal)
print(board.fen())
```
output is
```
RNBKQBNR/PPPPPPPP/8/8/8/8/pppppppp/rnbkqbnr b - - 0 1
```
This correctly flips the board(position and color) but castling is gone and now when getting the legal moves:
```
for m in board.legal_moves:
    print(str(m))
```
don't know what kind of output is this?
```
g1h3
g1f3
b1c3
b1a3
```
How do I flip the board correctly?

Cheers

**Comment by niklasf** [comment]
The answer from https://github.com/niklasf/python-chess/issues/1054#issuecomment-1846021213 also applies here: With these methods you're changing the abstract/mathematical position. You probably just want to change the way it is displayed.
