### ISSUE TITLE
Board.is_legal not recognizing legal castling moves

### ISSUE THREAD

**Issue by dubiousjim** [niklasf/python-chess#106]
Here is a board where it is legal for White to castle kingside:

```
>>> b=Board(fen='rn1qk1nr/ppp2ppp/3bp3/3p1b2/3P4/3BPN2/PPP2PPP/RNBQK2R w KQkq - 2 5')
>>> m=Move.from_uci('e1h1')
>>> b.is_legal(m)
False
```

So the move is correctly recognized as illegal. An earlier edit of this issue hadn't noticed that the move was ending in h1 rather than g1, so I misdescribed the problem then. However, there is still an issue, for notice:

```
>>> b.san(m)
'O-O'
>>> b.push(m)
```

These shouldn't work, but they do.

I'm using python-chess version 0.15.4, but I don't see any discussion of this bug in release notes for more recent releases.

**Comment by niklasf** [comment]
In standard chess this castling move is supposed to be `e1g1`. `board.san()` does not test for legality and works (by chance).

You can use board.parse_uci() to take the context into account:

```python
>>> b.parse_uci("e1h1")
Move.from_uci('e1g1')
```

Or you can switch to Chess960 representation of castling moves:

```python
>>> b = Board(..., chess960=True)
>>> b.is_legal(m)
True

**Comment by dubiousjim** [comment]
Thanks, I saw my mistake. I have a bunch of errors using `Board().variation_san` on another board's `move_stack` to turn move history into PGN-style strings. I just pulled this example at random from the odd results. In general, I would have expected `Board().variation_san(b.move_stack)` to always just work when `b` is a legal board; and it doesn't; your comments may help me figure out something more careful that does work.

**Comment by niklasf** [comment]
Ah, I see. That's annoying. Moves on board.move_stack are normalized and might not work with other boards or even the same board. I'll see what I can do.

**Comment by dubiousjim** [comment]
The move stack of the troublesome board was:

```
In [306]: b.move_stack
Out[306]: 
deque([Move.from_uci('d2d4'),
       Move.from_uci('d7d5'),
       Move.from_uci('g1f3'),
       Move.from_uci('c8f5'),
       Move.from_uci('e2e3'),
       Move.from_uci('e7e6'),
       Move.from_uci('f1d3'),
       Move.from_uci('f8d6'),
       Move.from_uci('e1h1')])
```

**Comment by dubiousjim** [comment]
As your earlier comment suggested, `Board(chess960=True).variation_san(b.move_stack)` seems to be a quick fix for the problem that led me here. In a future version, I'd suggest adding this as a method on board `b`.

**Comment by niklasf** [comment]
Cool. In addition some of the changes in v0.16.0 make 6fd0b15a3b58664f6695b82b1da9d36f496511f5 rather trivial. So in the future move stacks will always be compatible with their own board and boards of the same type.
