### ISSUE TITLE
Is this expected or simply a bug?

### ISSUE THREAD

**Issue by djokester** [niklasf/python-chess#1067]
![image](https://github.com/niklasf/python-chess/assets/17949650/15bb38a5-4691-4851-9d3f-c08b9bf57cdb)

**Comment by niklasf** [comment]
Expected.

For `board.is_legal(move)` and similar methods, `move` needs to be legal in the position of `board`. But it has already been played/pushed, and playing it again would not be legal. Instead, do any checks before pushing.

It could be argued that this should at least throw an exception, but always double-checking legality would have a substantial performance cost.
