### ISSUE TITLE
Feature request: new argument for chess.svg.board()

### ISSUE THREAD

**Issue by toolonely** [niklasf/python-chess#1074]
I would like a `show_FEN: bool = False` argument that will explicitly draw the FEN string either above or below the board in the resulting svg code. Thanks.

**Comment by toolonely** [comment]
On a second thought, if the board isn't loaded with a FEN, but with a game (sequence of moves), I'd also like the last move that was made displayed.

**Comment by niklasf** [comment]
Sorry, I don't think it makes sense as part of the SVG for most users.
