### ISSUE TITLE
Lichess WDL

### ISSUE THREAD

**Issue by fsmosca** [niklasf/python-chess#1085]
This can be out of scope on python chess, but would like to ask how the lichess model was created? Is it from lichess games? What player ratings? What time control?

```
def wdl(self, *, model: WdlModel = "sf", ply: int = 30) -> Wdl:
```

I plan to create a model based from lichess games with some criteria, but perhaps I can just use the current model.

Thanks.

**Comment by niklasf** [comment]
https://github.com/lichess-org/lila/pull/11148 is the pull request that added (or rather updated it) in lila.
