### ISSUE TITLE
Converting UCI to SAN.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [niklasf/python-chess#1088]
Hi.
I need to have the SAN move of the last pushed.
```python
import chess
b=chess.board()
b.push_san('Nf3')
...
# other pushes
...
l=b.peek()
```

Could I have this l in SAN format instead of UCI?

Many thanks. Gabe.

**Comment by niklasf** [comment]
Creating SAN requires the position for context. So instead of

```
b.peek().uci()
```
you would have to do something like
```

**Comment by GabrieleBattaglia** [comment]
Fine. I'll try it. Thanks.
