### ISSUE TITLE
Checking a move.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [niklasf/python-chess#1089]
Hi again and I apologize for this basic questions.
import chess
b=chess.Board()
my_move="e4"

How can I check if my_move is a legal move?
my_move in b.legal_moves
Does match the kinds

If I have lm in list(b.legal_moves)
It's also false.
Gabe.

**Comment by niklasf** [comment]
See https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.parse_san:
```python
try:
    the_move = b.parse_san("e4")
except ValueError:
    # Illegal
else:
    # Legal
```

**Comment by GabrieleBattaglia** [comment]
Thanks.
