### ISSUE TITLE
RANK_ATTACKS[king][king | bb_c] & Error

### ISSUE THREAD

**Issue by cemox** [niklasf/python-chess#109]
Hello,

First of all, thank you very much for this wonderful project.

When the game starts from new game position everything is ok, but when you start from a setup position (legal of course), it gives the below error. My code used to work without any problem with the previous version of python-chess.

Another thing is that when you set up a position, one of or both or none of the players might have castling rights. There must be a way of granting and removing castling rights in a given position. 

Best regards,

__init__.py", line 3522, in generate_castling_moves
    RANK_ATTACKS[king][king | bb_c] &
KeyError: 288232575174967296

**Comment by cemox** [comment]
I added chess.Board.clear() command before loading a new position and it works for now.

**Comment by niklasf** [comment]
Thanks for reporting this. I am still intrested in the cause of this problem. How did you setup the position? (Also if possible a piece of code to reproduce the problem would be amazing.)

---

You can set castling rights by setting a [mask for the rook squares](https://python-chess.readthedocs.io/en/latest/core.html#Board.castling_rights) (e.g. `board.castling_rights = chess.BB_A1 | chess.BB_H1`) or by using [board.set_castling_fen()](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.set_castling_fen).

**Comment by niklasf** [comment]
I (blindly) made generate_castling_moves() a bit more robust in 3f29d7a3bc09c87cdec79cb5fb355538f2daa8e3.
