### ISSUE TITLE
Add Html Represenation to Boards

### ISSUE THREAD

**Issue by gawebb-dstl** [niklasf/python-chess#1096]
Add ` _repr_html_` function to `SvgWrapper`. This allows chess boards to viewed in sphinx galleries. 
```
def _repr_html_(self):
    return self`
```

**Comment by niklasf** [comment]
Sure, done. If this can be done in general, perhaps it's a good idea for Sphinx Galleries to also just support `_repr_svg_`?

**Comment by gawebb-dstl** [comment]
Thanks, I agree. I think there is a [PR](https://github.com/sphinx-gallery/sphinx-gallery/pull/1138) in Sphinx Galleries for that change but it has stalled.
