### ISSUE TITLE
Threefold repetition detection and fifty-move rule

### ISSUE THREAD

**Issue by jromang** [niklasf/python-chess#11]
First I would like to thank you for this great lib ! We are using it in picochess :-)
Would it be possible to implement threefold repetition detection and fifty-move rule ? (juste like the is_stalemate() or is_game_over() methods)

**Comment by winapiadmin** [comment]
> Hi [@jromang](https://github.com/jromang), PicoChess looks pretty awesome, from what I can tell without a DGT board. Maybe I should get one, finally.
> 
> I have always wanted to build Zobrist hashes incrementally to allow building a repitition table in an efficient way. I did that now.
> 
> The old attribute `board.halfmove_clock` remains.
> 
> The next version of python-chess v0.4.0 has `can_claim_draw()`, `can_claim_fifty_moves()` and `can_claim_threefold_repitition()`.
> 
> Details: `is_game_over()` will still return False, because those draws need to be claimed. A threefold repitition can be claimed when it occurs but also when it could occur with the next legal move. It's too late to claim a draw if the game ended in a different way.
> 
> Aditionally I added `is_seventyfive_moves()` and `is_fivefold_repitition()`. Those drawing rules were only recently (July) introduced. They end the game (and affect `is_game_over()`) even without a claim. Other ways of ending a game take precedence.
> 
> Niklas

You just did it.... partially, but not use incremental?

Years later, you refactored Polyglot and still not use incremental hashing. (https://github.com/niklasf/python-chess/blob/master/chess/__init__.py#L2282-L2325)
