### ISSUE TITLE
SVG knights have a default

### ISSUE THREAD

**Issue by ornicar** [niklasf/python-chess#110]
![](https://i.imgur.com/5Qni7ow.png)

Reproducible on https://backscattering.de/web-boardimage/board.svg?fen=nN6/8/8/8/8/8/8/8&size=1024

**Comment by niklasf** [comment]
This had already been [fixed](https://github.com/niklasf/python-chess/pull/108) by @ProgramFOX, but I then forgot about it. Updated the web-boardimage repo, my personal server and drake.
