### ISSUE TITLE
module 'chess.pgn' has no attribute 'tell'

### ISSUE THREAD

**Issue by JavierYepez** [niklasf/python-chess#1101]
Hi, Im having a problem with the PGN module. This code gives me an error telling that `tell()` attribute doesn't exists.

`AttributeError: module 'chess.pgn' has no attribute 'tell'`

```python
import chess
import chess.pgn

with open(test, 'r') as pgn_file:
    while True:
        offset = chess.pgn.tell()
        game = chess.pgn.read_headers(pgn_file)
        if not game:
            break
```

But this code works fine which means that the PGN module is imported:

```python
import chess
import chess.pgn

with open(test, 'r') as pgn_file:
    while True:
        # offset = chess.pgn.tell()
        game = chess.pgn.read_headers(pgn_file)
        if not game:
            break
```

**UPDATE**
The only functions available are: 
`skip_game(handle: TextIO) -> bool`
`read_headers(handle: TextIO) -> Optional[Headers]`
`read_game(handle: TextIO) -> Optional[Game]`

Library:
chess  1.10.0 pyhd8ed1ab_1 conda-forge

**Comment by niklasf** [comment]
In the example, `pgn` refers to a file object, as in:

```python
pgn = open("data/pgn/kasparov-deep-blue-1997.pgn")
```

**Comment by JavierYepez** [comment]
You are absolutely right. I'm a bit blind. Thank you
