### ISSUE TITLE
Pylint alerts corrections as part of intervention experiment

### ISSUE THREAD

**Issue by evidencebp** [niklasf/python-chess#1109]
I'd like to conduct a software engineering experiment regarding the benefit of Pylint alerts removal.
The experiment is described [here](https://github.com/evidencebp/pylint-intervention/).
In the experiments, Pylint is used with some specific alerts, files are selected for intervention and control.
After the interventions are done, one can wait and examine the results.

I'm asking your approval for conducting the interventions in your repositories.The interventions are expected to benefit the project and will submitted in PR for approval.

See the [planed internetions](https://github.com/evidencebp/pylint-intervention/blob/main/interventions/candidates/niklasf_python-chess_interventions_September_28_2024.csv).

Is it OK if I'll fix the alerts?

**Comment by niklasf** [comment]
Hi, yes, contributions like that are generally welcome. Just note that part of the changes may be rejected upon review.

And also note that occasionally linters including pylint were already used to make improvements to python-chess, so I would expect most remaining findings to be low severity. I don't know if this affects your experiment in any way.

**Comment by evidencebp** [comment]
Thanks!

You are right regarding possible low severity.
The static analysis use case sees removing any of them as beneficial.
This is part of what we would like to check.
From a research point of view, seeing that the removal is not beneficial is also interesting.

**Comment by evidencebp** [comment]
@niklasf , I created a small [PR](https://github.com/niklasf/python-chess/pull/1110) with minor fixes.

Please see if they are OK.

In order to remove human bias in intervention target selection, we use a script to choose them.
I would like to also consult you regarding bigger interventions.

chess\syzygy.py, chess\gaviota.py has the too-many-lines.
The benefit of short files is well established in software enegiring.
Both files are already structured with classes in them.
I guess that they are in the same file since they are related.
However, are you ok with putting each class in a file of its own?

Similarly, chess\variant.py, chess\svg.py, and chess\pgn.py have functions with too many branches.
They implement chess logical cases.
Is it OK to move some of the cases into their own functions, seperating the code into smaller parts?

**Comment by niklasf** [comment]
I don't think splitting those files is a good idea. They indeed group functions and classes in logical modules.

Splitting long/complex functions could be helpful, but only if the new parts do something that's sufficiently self-contained, so that it actually makes things easier to reason about and not just adds useless indirection.

**Comment by evidencebp** [comment]
Ok, I'm glad I asked before.
I looked like a deliberate design.
