### ISSUE TITLE
Can't use variants

### ISSUE THREAD

**Issue by salvador-dali** [niklasf/python-chess#111]
After installing python-chess library with `pip install python-chess` and verifying that I have the latest version 

```
import chess
chess.__version__  # '0.16.2'
```

I see that I can't use variants `board = chess.variant.GiveawayBoard()` results in `'module' object has no attribute 'variant'`. I am on ubuntu, using python 2.7.12 |Anaconda 4.2.0 (64-bit)

Any idea what's wrong here?

**Comment by niklasf** [comment]
Hi, any of the submodules also have to be imported, e.g. `import chess.variant`. Please let me know if that works.

**Comment by salvador-dali** [comment]
Cool thank you. Everything works (might make sense to add this to documentation)
