### ISSUE TITLE
Error while parsing UCI options

### ISSUE THREAD

**Issue by Torom** [niklasf/python-chess#1112]
Since 1.11.0 there is an error when parsing UCI options. This occurs, for example, with Fairy-Stockfish:

```python
Exception parsing option min
Traceback (most recent call last):
  File "/home/torsten/.pyenv/versions/3.12.6/lib/python3.12/site-packages/chess/engine.py", line 1382, in parse_min_max_value
    return int(number) if number else None
           ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'i'
```

The reason for this is that in the UCI option `UCI_Variant` the word `min` occurs in chess variants:

```
option name UCI_Variant type combo default chess var 3check [...] var mini var minishogi var minixiangqi [...] var torpedo
```

The following letter is an `i` and is therefore recognized by python-chess as the value for the `min` keyword.
Code to reproduce:

```python
import chess.engine

with chess.engine.SimpleEngine.popen_uci('fairy-stockfish') as engine:
    engine.configure({'Threads': 1})
```

**Comment by MarkZH** [comment]
@Torom I just submitted a PR to fix my mistake. Please test to make sure it fixes the problem.
