### ISSUE TITLE
List of board positions in polyglot opening book

### ISSUE THREAD

**Issue by GabrielPereyra** [niklasf/python-chess#112]
From the polyglot opening book, I want to create a dictionary that maps a fen to the main entry in the book:

```python
import chess.polyglot
fen_to_best_move = dict()

with chess.polyglot.open_reader("data/polyglot/performance.bin") as book:
    for board in boards_in_polyglot_book:
        fen_to_best_move[board.fen()] = book.find(board)
```

From reading the docs and source, it isn't clear to me if there is an easy way to do this without exhaustively checking if boards are in the book. Let me know if there is a good way to do this.

Thanks!

**Comment by niklasf** [comment]
Since the entries do not store the position (only the hash) probably the best you can do is traversing the reachable nodes. So something like this:

```
import chess
import chess.polyglot

def traverse(book, d, board):
    epd = board.epd()

    if not epd in d:
        try:
            move = book.find(board).move()
        except IndexError:
            pass
        else:
            print(epd, move)
            d[epd] = move

            for move in board.legal_moves:
                board.push(move)
                traverse(book, d, board)
                board.pop()

book = chess.polyglot.open_reader("data/polyglot/performance.bin")
fen_to_best_move = {}
traverse(book, fen_to_best_move, chess.Board())
```

**Comment by GabrielPereyra** [comment]
This is beautiful - thanks!

**Comment by GabrielPereyra** [comment]
Follow up question: when I run your script, I get 38326 (board, move) pairs. However, if I run:

```python
print len(book)
```

I get 92954. I'm missing some values with this traversal? Thanks!

**Comment by niklasf** [comment]
Yes, any number of entries can be unreachable (going from the starting position and staying in book) or have weight 0.

I've got to admit that numbers for this book are a bit surprising, though. So I cross checked using PolyGlot 1.4.70b, but it checks out.

**Comment by GabrielPereyra** [comment]
Another question: Do you have any details or references on how the polyglot book is computed? I'm guessing using stockfish or another engine, but it would be great to know the search depth, search time, or nodes computed for each position.

Thanks again for your help!

**Comment by cja000** [comment]
Hi Gabriel,
As far as I know polyglot is only a 'book'. I mean, it only has positions not evaluations. It is used to know percentages of most common moves from one position.
You can have a look at the specification: [Polyglot book format](http://hgm.nubati.net/book_format.html)

**Comment by dsjoerg** [comment]
@GabrielPereyra as far as I know Polyglot is the _format_ for an opening book.  So there can be many books computed in many different ways.  To know how it was computed you'd have to ask the people who produced it.
