### ISSUE TITLE
Black pawn colors are not the correct color

### ISSUE THREAD

**Issue by balbirthomas** [niklasf/python-chess#1124]
Is the [black pawn](https://github.com/niklasf/python-chess/blob/master/chess/svg.py#L19) missing a `fill="#000"` ? At least this seems to be the problem when the `chess` module is being used in Emacs `pygn-mode` ( kindly see [issue 212](https://github.com/dwcoates/pygn-mode/issues/212) ).

**Comment by niklasf** [comment]
Hi. This was already fixed via 614d718be06d0b9ff471e70e66cd54c2cc6f5dfb which is part of v1.9.2.
