### ISSUE TITLE
Variants, Racing King. Incorrect draw detection

### ISSUE THREAD

**Issue by salvador-dali** [niklasf/python-chess#114]
There are a few cases where Racing King variant report incorrect variant-ending due to the stalemate

 - `4Q1K1/8/7k/4R3/8/5B2/8/3N4 b - - 0 0`
 - `1Q4R1/5K2/4B3/8/8/3N4/8/k7 b - - 0 0`
 - `8/kr6/q2n4/8/7K/3r4/3bb3/8 w - - 0 0`
 - `7R/3R4/5K2/B1k5/5N2/8/2N3Q1/5B2 b - - 0 0`
As you see, here white/black has to move, but can't because it is in a stalemating position. Notice that in the first example white already reached the last position, but it is still a draw because black has the last chance to move.

**Comment by niklasf** [comment]
Thanks, these are some intresting cases.

I was going by the lichess.org rules, where stalemate is a draw, except during the "last chance". Is Racing Kings played differently elsewhere?

I think the other positions behave as expected, i.e. they are ended by stalemate but not by a special variant ending condition. I added some tests.

**Comment by salvador-dali** [comment]
> I think the other positions behave as expected, i.e. they are ended by stalemate but not by a special variant ending condition

I think either I have not explained myself properly or your misunderstood me. I will try to rephrase. `board.is_variant_draw()` returns `0` for all these positions. It should return `True` because this is a stalemate.

> lichess.org rules, where stalemate is a draw, except during the "last chance"

Based on [lichess](https://en.lichess.org/variant/racingKings) explanation "When white moves their king to the eight row, and black moves directly after that also their king to the last row, the game is a draw" which suggests that black has a last chance to move. So as far as I understood, if the white finished the race, black should have a chance to move. If he can't move, this is a stalemate and should be a draw.

**Comment by niklasf** [comment]
The `is_variant_*` are for special variant end conditions. 5a45c12468fb1ed59e9fd37b5ee532d142d79df1 shows a couple of other methods to determine if the game is over by standard conditions.

Regarding the rules for the last chance, the text might be ambiguous. But it can be easily tested (and you'll find that indeed stalemate is irrelevant during the last-chance move).

**Comment by salvador-dali** [comment]
Thank you. It looks like my issue was a false alarm.
Also you are right about stalemate at the last move. I tested it on lichess and their score tells that it does not count: https://en.lichess.org/mNmE9EBH#51

**Comment by niklasf** [comment]
Cool. In anyway it was useful to check this.
