### ISSUE TITLE
Variants, Racing King. Allows illegal positions

### ISSUE THREAD

**Issue by salvador-dali** [niklasf/python-chess#115]
Positions like these are considered illegal. Here black won, white has done the next move and reached the last row (but it is already too late) and now black has to moves. The game should have stopped 2 moves ago, and this position is illegal.
 - `3krQK1/8/8/8/1q6/3B1N2/1b6/1R4R1 b - - 0 0`

I have not checked whether RK variant allows pawns, more than 2 pieces, more than 1 queen from one side. These positions also should be illegal.

**Comment by niklasf** [comment]
Makes sense to exclude these cases. They can now be detected using `board.is_valid()` and `board.status()`.
