### ISSUE TITLE
SVG questions & feature requests

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#116]
Hi,
I have a bunch of questions & feature requests:

- is the SVG support more or less guaranteed to continue in future releases? (background: i can remember its said "experimental" like its now with variants).
- can the svg board be made responsive? If yes, how? I see you need to give Width,Height coordinates at the startup inside (but i prefer it scales on a surrounding div for example)
- I would like to draw arrows (like its on lichess). How to do this? Or can you provide an api for this?

Jürgen

**Comment by niklasf** [comment]
Hi Jürgen, I think SVG support is quite useful (especially in combination with IPython), so it's here to stay. As for the feature requests, both are possible, but it might be a while before I get to implement them. Niklas

**Comment by niklasf** [comment]
Thanks to @rheber we now have support for arrows.

**Comment by LocutusOfPenguin** [comment]
that's really great. Thanks!

**Comment by niklasf** [comment]
`size` now defaults to `None` in `chess.svg.board(..., size=None)` and will produce scalable SVGs with a `viewBox`.

That should conclude this issue.
