### ISSUE TITLE
Variants, Racing King. Finished positions should have 0 legal moves.

### ISSUE THREAD

**Issue by salvador-dali** [niklasf/python-chess#118]
All of these positions are final (the game already finished) and thus should not have any legal moves from them:

 - 1k5b/5b2/8/8/8/8/3N3K/N4B2 w - - 0 0
 - 4K3/8/8/6Q1/3N2R1/8/1k6/N2nR3 b - - 0 0
 - B4K2/8/5R2/1k6/8/n7/7R/8 b - - 0 0
 - 4QK2/8/8/8/6B1/3N4/k3N3/1r6 b - - 0 0
 - 2r1k3/7b/6q1/1r6/8/7K/5b2/5R2 w - - 0 0
 - 5N1K/1kb1Q3/8/8/7N/7q/8/8 w - - 0 0
 - 4qQK1/3k4/8/2n5/8/8/1n6/8 b - - 0 0
 - 4BK2/8/8/5R2/8/2k5/3n4/7Q b - - 0 0
 - K7/8/2Q5/8/1k6/5N2/4B1R1/3n2R1 b - - 0 0
 - kr4R1/8/2b5/1n6/2B2b1K/8/N7/3n2R1 w - - 0 0
 - 1k6/3q4/3b1K2/8/8/8/2N5/8 w - - 0 0
 - 1k6/3q4/3b1K2/8/8/8/2N5/8 b - - 0 0
 - kr6/7K/8/8/8/2q5/5N2/1r4R1 w - - 0 0
 - kr6/7K/8/8/8/2q5/5N2/1r4R1 b - - 0 0

But the `legal_moves` generates moves for them.

```
for fen in strange_fens:
    print len(chess.variant.RacingKingsBoard(fen).legal_moves)
```

I assume that the same problem might happen in other variants. A simple check `board.is_game_over()` before generating legal_moves might solve the problem.

**Comment by rheber** [comment]
Calling is_game_over in generate_legal_moves causes an infinite loop because generate_legal_moves is called by is_game_over.

**Comment by niklasf** [comment]
Yeah, that's a bit annoying. I introduced `board.is_variant_end()` to break the cycle and finally fixed this. Also for the other variants.

Hopefully this doesn't introduce other issues. I'll hold off a bit on the next release.

One subtle change is that a position like `4Q1K1/8/7k/4R3/8/5B2/8/3N4 b - - 0 1` is no longer considered stalemate. The game is simply over by variant end condition.

![image](https://cloud.githubusercontent.com/assets/402777/23305057/3cd4cc4c-fa9d-11e6-83f1-5f0a8f8985e6.png)
