### ISSUE TITLE
Advice needed - catch the crush reason

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#119]
picochess doing this:

        bit_board = Board(message.fen)
        move_text = bit_board.san(message.move)

this leads to the following error:

  File "/home/pi/picochess/dgtpi.py", line 128, in display_move_on_clock
    move_text = bit_board.san(message.move)
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 2744, in san
    self.push(move)
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 2219, in push
    self._set_piece_at(move.to_square, piece_type, self.turn, promoted)
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 994, in _set_piece_at
    piece_index = (piece_type - 1) * 2
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

NOW:
i dont say its a problem from python-chess, for example, it could be the "fen" &"move" doesnt suit eachother. But if i want to get more details, i need to try-catch this possible error/expection.

Do y have an idea, to get it abit more close? I dont want to catch ANY error (bad style). This one was a "TypeError", but maybe other expections can also happen? Is there a way to secure the program better? So, im asking for some advice (and i dont have this "fen, move" ready - picochess crushed here).

Jürgen

**Comment by LocutusOfPenguin** [comment]
For the moment i'm trying this:

        bit_board = Board(message.fen)
        if bit_board.is_legal(message.move):
            move_text = bit_board.san(message.move)
        else:
            logging.warning('illegal move found fen: {} move: {}'.format(message.fen, message.move))
            move_text = 'err {}'.format(message.move.uci()[:4])

This will help me track down if thats a picochess problem or not.
But perhaps this check should be inside python-chess san function?

**Comment by niklasf** [comment]
Checking `is_legal` (or at least `is_pseudo_legal`) is the way to go. Since checking legality takes a little bit of time I do not want to do it by default. I think I can make `san()` a little more robust, though ...

**Comment by niklasf** [comment]
`san()` and `push()` should now no longer raise, even for illegal moves. (Obviously it will still be intresting to find out how picochess could send illegal moves in the first place).

**Comment by LocutusOfPenguin** [comment]
thanks!

well, when i put the object (board & fen) to the queue - using board.copy(), it seems to be valid.
But the (later) queue-pull sometimes(!) giving me a completely changed board back.
I expect its changed from engine (uci) cause the result looks like an engine manipulated it, but i cant explain this behaviour right now :-(
