### ISSUE TITLE
Try to get performance improvements into CPython

### ISSUE THREAD

**Issue by niklasf** [niklasf/python-chess#121]
* [x] `msb(x)`
  - ~http://bugs.python.org/issue29782~ :cry:
  - http://bugs.python.org/issue31031 :tada:
  - Potential to revive attempt at using intrinsics with instructions from previous ticket
  - https://github.com/python/cpython/commit/794e7d1ab2d7afe70fe0dd87ca8174ac860413e4 landed
* [x] `popcount()`
  - http://bugs.python.org/issue29882 :balloon: 
* [x] `lsb()`
  - `(bb & -bb).bit_length() - 1` is good enough
* [ ] `bool(BB_SQUARES[sq] & mask)`
  - ~http://bugs.python.org/issue19915~ :cry:

**Comment by rpdelaney** [comment]
Curious, have you given `pypy` a try?

**Comment by niklasf** [comment]
In general? pypy seems to perform better than CPython in some benchmarks, and worse in others. On my machine it's very good in the perft tests, but somehow relatively slower running the same tests on Travis CI.

Specifics:

`msb(x)` could potentially be optimized: https://github.com/mozillazg/pypy/blob/60769541e4df8c2bcd673b1914f0b529eb4e778b/pypy/objspace/std/intobject.py#L464-L474

The remaining bit operations (`popcount()` and `bool(BB_SQUARES[sq] & mask)`) would require adding new methods or types. So any change would have to land in CPython first, before it is ported to pypy.

**Comment by niklasf** [comment]
After 3 years the patch for faster popcount (bpo-29882) landed :tada:

**Comment by niklasf** [comment]
https://github.com/python/cpython/commit/794e7d1ab2d7afe70fe0dd87ca8174ac860413e4 landed, so `msb(_)` will use intrinsics starting in Python 3.10 :tada:

**Comment by bartekspitza** [comment]
Is PyPy at all supported? I tried using it but `No matching distribution found for chess` when `pypy -mpip install chess`

**Comment by bartekspitza** [comment]
Sorry I'm dumb, the package name is of course not `chess` but `python-chess`, so I guess then pypy should work?

**Comment by niklasf** [comment]
@bartekspitza The distribution name of the latest version is actually `chess` (`python-chess` is historical).

It will however require Python 3.7 (i.e., a very recent version of pypy3). I assume that's the reason why your pypy is finding a compatible distribution only for the historical python-chess.

pypy is not run in CI, so I guess not officially supported, but there's no CPython-specific black magic in this library either. So it should just work.

**Comment by bartekspitza** [comment]
Ah ok makes sense, thanks.
