### ISSUE TITLE
How to resume using UCI engine after interrupting a search?

### ISSUE THREAD

**Issue by dubiousjim** [niklasf/python-chess#123]
If I open Stockfish using chess.uci, and start a synchronous search, and then get bored and hit control-C, it seems to kill something from the `concurrent.futures` module stored in the variable `chess.uci.Engine.pool`. The result is that I can no longer use python-chess's uci framework: even if I kill the Stockfish process that was interrupted and open a new one, it's still not usable. I see:

```
try:
    ...:   e.go(movetime=10*1000)
    ...: except KeyboardInterrupt:
    ...:   e.stop()
    ...:   raise
    ...: 
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-24-58cd15881355> in <module>()
      1 try:
----> 2   e.go(movetime=10*1000)
      3 except KeyboardInterrupt:

/Users/jim/Library/Python/3.5/lib/python/site-packages/chess/uci.py in go(self, searchmoves, ponder, wtime, btime, winc, binc, movestogo, depth, nodes, mate, movetime, infinite, async_callback)
   1238 
-> 1239         return self._queue_command(command, async_callback)
   1240 

/Users/jim/Library/Python/3.5/lib/python/site-packages/chess/uci.py in _queue_command(self, command, async_callback)
    903         else:
--> 904             return future.result()
    905 

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py in result(self, timeout)
    399 
--> 400             self._condition.wait(timeout)
    401 

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py in wait(self, timeout)
    292             if timeout is None:
--> 293                 waiter.acquire()
    294                 gotit = True

KeyboardInterrupt: 

During handling of the above exception, another exception occurred:

EngineTerminatedException                 Traceback (most recent call last)
<ipython-input-24-58cd15881355> in <module>()
      2   e.go(movetime=10*1000)
      3 except KeyboardInterrupt:
----> 4   e.stop()
      5   raise

/Users/jim/Library/Python/3.5/lib/python/site-packages/chess/uci.py in stop(self, async_callback)
   1267                     raise EngineTerminatedException()
   1268 
-> 1269         return self._queue_command(command, async_callback)
   1270 
   1271     def ponderhit(self, async_callback=None):

/Users/jim/Library/Python/3.5/lib/python/site-packages/chess/uci.py in _queue_command(self, command, async_callback)
    902             return future
    903         else:
--> 904             return future.result()
    905 
    906     def uci(self, async_callback=None):

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py in result(self, timeout)
    403                 raise CancelledError()
    404             elif self._state == FINISHED:
--> 405                 return self.__get_result()
    406             else:
    407                 raise TimeoutError()

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py in __get_result(self)
    355     def __get_result(self):
    356         if self._exception:
--> 357             raise self._exception
    358         else:
    359             return self._result

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/thread.py in run(self)
     53 
     54         try:
---> 55             result = self.fn(*self.args, **self.kwargs)
     56         except BaseException as e:
     57             self.future.set_exception(e)

/Users/jim/Library/Python/3.5/lib/python/site-packages/chess/uci.py in command()
   1265 
   1266                 if self.terminated.is_set():
-> 1267                     raise EngineTerminatedException()
   1268 
   1269         return self._queue_command(command, async_callback)

EngineTerminatedException:
```

What's the best way to work around this? I would like to be able to sometimes do a control-C, without having to re-launch my whole Python session to clean up afterwards.

**Comment by dubiousjim** [comment]
The second error in the above stack trace (the `EngineTerminatedException`) is what one sees when trying to use any uci stuff after once doing a `KeyboardInterrupt`. Even on a new uci engine process.

**Comment by niklasf** [comment]
SIGINT propagates and already kills the engine process, so you can not send `stop` to the already dead process.

You can recover by starting a new process.

**Comment by dubiousjim** [comment]
Huh. What I was saying above was that things seem to be mucked up after doing a ctrl-C, even if I did start a new engine process. I had the impression that all the engine processes were sharing some resource that itself needed to be refreshed in some way.

But I just now tried to demonstrate this and am not able to do so:

```
>>> stockfish = open_stockfish(pv=1, threads=1, hash=256)
>>> stockfish.info_handlers.append(U.InfoHandler())
>>> stockfish.position(Board())
>>> try:
   ...:   stockfish.go(movetime=10*1000)
   ...: except KeyboardInterrupt:
   ...:   stockfish.kill()
   ...: 
^C
>>> stockfish.is_alive()
False
>>> stockfish = open_stockfish(pv=1, threads=1, hash=256)
>>> stockfish.info_handlers.append(U.InfoHandler())
>>> stockfish.position(Board())
>>> stockfish.go(movetime=4*1000)
```

The last step is where I was expecting to see the `EngineTerminatedException`. But I don't, the search works ok. So maybe there's just an error in my own (larger) codebase, where I've forgotten that I'm still using a cached value of the old, now dead stockfish process.

Sorry for the noise.

**Comment by niklasf** [comment]
Ah, sorry ... I tried to answer this in a hurry and missed that you already tried making new instances. They should really be independent. Please let me know if you find out more.

**Comment by brianprichardson** [comment]
Does issuing the 'stop' command to Stockfish apply in this context?

I have only recently started using Python, and am still trying to understand all of the different ^c behavior.  It seems to change if in python v ipython in cmd, and again under Spyder, and again when running Keras, etc.

**Comment by dubiousjim** [comment]
Here's where I've gotten with this.

Method 1. I created a class that wraps chess.uci.Engine; when creating it I don't supply it with a concrete Engine but rather with a factory function that generates the Engine. I save this factory function. Then this wrapper class passes any commands like .go(...) onto the current Engine instance. If doing so raises an EngineTerminatedException, then I assert that the old Engine's process.is_alive() is False, and create a new Engine instance using the saved factory function. Then I can re-issue the command that failed. Here is some of the code:

```
class Engine2:
  def __init__(self, factory, pv, threads):
    self.factory = factory
    self.pv = pv
    self.threads = threads
    self.engine = factory(pv, threads)
    assert isinstance(self.engine, U.Engine)
    self.info_handlers = self.engine.info_handlers
  def quit(self, async_callback=None):
    try:
      return self.engine.quit(async_callback)
    except U.EngineTerminatedException:
      return self.engine.terminate(async_callback)
  def is_alive(self):
    return self.engine.is_alive()
  def restart(self):
    assert not self.engine.process.is_alive()
    print("Restarting UCI Engine", file=sys.stderr)
    self.engine = self.factory(self.pv, self.threads)
  ...
  def go(self, searchmoves=None, ponder=False, wtime=None, btime=None, winc=None, binc=None, movestogo=None, depth=None, nodes=None, mate=None, movetime=None, infinite=False, async_callback=None):
    try:
      return self.engine.go(searchmoves, ponder, wtime, btime, winc, binc, movestogo, depth, nodes, mate, movetime, infinite, async_callback)
    except U.EngineTerminatedException:
      self.restart()
      return self.go(searchmoves, ponder, wtime, btime, winc, binc, movestogo, depth, nodes, mate, movetime, infinite, async_callback)
```

This works all right. One perhaps awkward thing is that the Engine isn't re-created when the KeyboardInterrupt happens, but later, when you try to invoke it again for the first time *after* the KeyboardInterrupt.

Method 2. I'm still looking to see if there's some way to catch the interrupt when it happens, and gracefully send a "stop" command to the UCI engine, without having its process be killed and need to be re-generated. So far as I've been able to tell, this would require subclassing concurrent.futures.ThreadPoolExecutor, and may also require using ctypes. I'm not sure if it's possible do this cleanly even then. I'm still looking into it, out of curiosity.

I did try registering my own signal handler for the KeyboardInterrupt, but this doesn't seem to help. You can prevent the interrupt from propagating, but then control isn't returned to the thread that's waiting for the uci.Engine to give a result. If you do propagate the interrupt, then you get the EngineTerminatedException from the UCI Engine. Trying to tell the UCI Engine to "stop" before you propagate the interrupt doesn't work. In that case, waiting for the result from "stop" will itself raise the EngineTerminatedException. (And calling "stop" asynchronously doesn't help. If you propagate the interrupt before waiting for the result from "stop", the UCI Engine process will die just as if no "stop" were involved. If you wait for the result from "stop" before propagating the interrupt, this is the same as issuing the "stop" synchronously.) This is all going from memory of my experimentation, but I think it's right.

I tried to modify Method1 so that we could at least re-generate the Engine when the KeyboardInterrupt happens, rather than when the Engine is next asked to do something. I think that could work, but interestingly in a fragment like this:

```
res = stockfish.go(movetime=60*1000, async_callback=True)
try:
  res.result()
except KeyboardInterrupt:
  print(stockfish.engine.process.is_alive())
  res2=stockfish.stop(async_callback=True)
```
you'll see "True" be printed: the UCI Engine process hasn't yet died when our exception block is called. And if you waited for `res2.result()` (or called `stop` synchronously) before leaving the exception block, you'd get an EngineTerminatedException.

**Comment by niklasf** [comment]
I have pushed some changes that allow creating the engine in a new process group, so it will survive a keyboard interrupt.

Then it becomes pretty straight forward, like you are planning in method 2.

```python
import chess.uci
import os

engine = chess.uci.Engine(lambda engine: chess.uci.PopenProcess(engine, "stockfish", preexec_fn=os.setpgrp))

try:
    print("go:", engine.go(depth=32))
except KeyboardInterrupt:
    print("stopping ...")
    engine.stop()
    print("stopped.")

print("alive:", engine.is_alive())

print("second go:", engine.go(depth=10))
```

Unfortunately due to a limition in the backport of `concurrent.futures` this will not work in Python 2. (The engine process will live, but the wait on `engine.go()` will keep blocking).

**Comment by niklasf** [comment]
This version should be working across Python 2/3 and Unix/Windows:

```python
from __future__ import print_function

import chess.uci
import os
import time
import subprocess

def polling_wait(future):
    """Wait on a future so that it can be interrupted even in Python 2."""
    while future.running():
        time.sleep(0.1)
    return future.result()

# Prevent signal propagation from parent process
kwargs = {}
try:
    # Windows
    kwargs["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP
except AttributeError:
    # Unix
    kwargs["preexec_fn"] = os.setpgrp

engine = chess.uci.Engine(lambda engine: chess.uci.PopenProcess(engine, "stockfish", **kwargs))

try:
    print("go:", polling_wait(engine.go(depth=32, async_callback=True)))
except KeyboardInterrupt:
    print("stopping ...")
    engine.stop()
    print("stopped.")

print("alive:", engine.is_alive())

print("second go:", polling_wait(engine.go(depth=10, async_callback=True)))
```

**Comment by dubiousjim** [comment]
That's great. Thanks!

**Comment by niklasf** [comment]
Some more progress: Using *any* timeout, even a long one, makes the wait interruptible in Python 2. I am doing that now internally.

I'll test the `sepgrp` some more tonight and possibly make it available more conveniently as an argument to `popen_engine`.
