### ISSUE TITLE
Doubly invoking Engine.process.wait_for_return_code()

### ISSUE THREAD

**Issue by dubiousjim** [niklasf/python-chess#125]
I was reading the source for uci.py, and was puzzled by the fact that (using PopenProcess, not sure about MockProcess or SpurProcess), the Engine.on_terminated is only called after the block:

```
        # this is in PopenProcess._receiving_thread_target
        if self.is_alive():
            self.terminate()
            self.wait_for_return_code()
```

But then Engine.on_terminated will first thing itself call `self.process.wait_for_return_code()`. I see that it's not a problem to call `wait_for_return_code` twice on a Popen object. I was just wondering about the logic of this. Is there some specific reason to call it both at the end of the Popen thread main loop, and also in the Engine `on_terminated` handler? Or is this just an accident of how the code developed, that doesn't hurt anything the way it is? (Or perhaps it's relevant to the other two process thread objects, that I'm ignoring.)

This is not a bug, I was just curious, and didn't know where to ask.

**Comment by niklasf** [comment]
`MockProcess` (testing only) and `SpurProcess` behave in the same way, i.e. it should be guaranteed that `wait_for_return_code()` is not blocking in/after `on_terminated`.

We could add another method to get the return code (if already present) or `None` and call that. But if that's only for internal use then we don't really need it.
