### ISSUE TITLE
Syzygy endgame tablebase probing

### ISSUE THREAD

**Issue by niklasf** [niklasf/python-chess#13]
Something I'd really like to have in the future is pure-Python [Syzygy endgame tablebase](https://chessprogramming.wikispaces.com/Syzygy+Bases) probing.

At the moment I can't find a specification of the format, so the only available real documentation is the original C probing code: https://github.com/syzygy1/tb. It will take some time and effort to understand and port that ...

**Comment by niklasf** [comment]
In the meantime [https://github.com/official-stockfish/Stockfish](Official Stockfish) adopted Syzygy tablebases. So the probing code can be seen in action, there.

**Comment by HenryJia** [comment]
Hi,

Do you just want the tablebase probing code or do you want the table base generating code as well?

**Comment by niklasf** [comment]
Hi @HenryJia, in my opinion pure Python generating code probably won't be very useful and also probably slow and inefficient. Probing an already generated file is going to be much more common.
