### ISSUE TITLE
AttributeError: 'str' object has no attribute 'drop'

### ISSUE THREAD

**Issue by HackySid** [niklasf/python-chess#135]
`while move not in board.legal_moves()`  raises AttributeError: 'str' object has no attribute 'drop'.The move i entered was in 'str' format (e4). The error is not encountered if I convert a uci string to this type of move.

**Comment by HackySid** [comment]
the move which is valid for the operation on type(move) returns <Class 'chess.Move'>

**Comment by HackySid** [comment]
Are we not expected to directly enter the  algebraic notation? @niklasf

**Comment by HackySid** [comment]
Ok! the legal moves should be converted to string and `board.push_san()` must be used

**Comment by niklasf** [comment]
Yes, or `board.parse_san()`.
