### ISSUE TITLE
self.return_code is not set when calling quit() on uci engine

### ISSUE THREAD

**Issue by cash** [niklasf/python-chess#136]
It looks like it is only set in on_terminated() which is never used.

**Comment by niklasf** [comment]
`on_terminated()` is called when the engine process is closed, for example here: https://github.com/niklasf/python-chess/blob/master/chess/engine.py#L165

So it should work. Does it not?

**Comment by cash** [comment]
I'm getting None for the return_code. I haven't tried debugging yet.

**Comment by cash** [comment]
Sorry about this. Bug in my code. python-chess is working as expected.
