### ISSUE TITLE
board.uci(move, chess960=True) - possible bug?

### ISSUE THREAD

**Issue by lakinwecker** [niklasf/python-chess#137]
If you have a node for castling in a pre-existing game, and you call:

`cur_node.board().uci(cur_node.move, chess960=True)` it will not translate the castling move into chess960 format, because `cur_node.board()` already has the castling move applied to it, so the checks to see if the king/rook are in the right spots will fail.

**Comment by niklasf** [comment]
You have to use the board before the move, so that the move is actually a legal move for that position. This is because in actual Chess960 the rook position needs to be known.

**Comment by niklasf** [comment]
I've added a convenience method `node.uci(chess960=...)`.
