### ISSUE TITLE
question: how can I walk through moves from pgn? 

### ISSUE THREAD

**Issue by kreedz** [niklasf/python-chess#142]
So I'm read pgn file: 
```
pgn_file = open('pgn.pgn')
game = chess.pgn.read_game(pgn_file)
```
What should I do now to iterate over every move?
Now I can get the board from starting position: `game.board()`. But I want to do that for every move.
Is it possible?
I read the docs, but it's not a clear for me how to approach my goal.

**Comment by niklasf** [comment]
If you need only the moves of the mainline you can use: [`for move in game.main_line()`](https://python-chess.readthedocs.io/en/latest/pgn.html#chess.pgn.GameNode.main_line).

If you need more you can use visitors or traverse the tree like in the README example. Feel free to ask more info.

**Comment by kreedz** [comment]
Thank you for quick response!
That was what exactly I needed.

My main target was to get svg for every move.
So now I did it in this way:
```
svgs = []
board = chess.Board()
for move in game.main_line():
    svgs.append(chess.svg.board(board=board))
    board.push_uci(move.uci())

**Comment by niklasf** [comment]
Looks good. You could start with `board = game.board()` so that it works with different starting positions.

**Comment by LocutusOfPenguin** [comment]
isnt: "board.push(move)" not better?

**Comment by niklasf** [comment]
Ah, thanks. I missed that. Yes, it's more efficient.

**Comment by fritut08** [comment]
I have a follow-up question:
How does one traverse through all moves (not just those of the mainline but including all variations)?
I want to be able to export the SAN of every move and all the comments but did not really find anything about this in the documentation or maybe I simply did not know what to look for (I am not very experienced with Python).
