### ISSUE TITLE
wrong castling for an uci960 position

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#143]
Im using python-chess to correct castling rights. But for this uci960 pos, it doesn't work.

import chess
b = chess.Board('1r1k1r2/5p2/8/8/8/8/3N4/R5KR b KQkq - 0 1', True)
b
results in: Board('1r1k1r2/5p2/8/8/8/8/3N4/R5KR b KQ - 0 1', chess960=True)

Black can castle to both sides, but i get both false

**Comment by niklasf** [comment]
In Chess960 kings start on the same file. So KQkq is not possible in this case, since once king must have moved. python-chess gives precedence to kings starting on the e-file and then to white.

**Comment by LocutusOfPenguin** [comment]
im sorry, i cant understand...
python chess assume, the bK moved from g8 to d8?
and your "precedence" is its not "wk from d1 to g1", yes?

Can this logic be turned off? I prefer to decide on the position as given, not any preferences (it would also be possible that a rook is moved before means "preference on the KQkq" only(!)

This happening at position setup, and i want to assume that castling is possible as long the starting fen wouldnt speak against it (no deeper logic, what might happened before - that can be wrong by preference choosen)

**Comment by niklasf** [comment]
I am saying that `1r1k1r2/5p2/8/8/8/8/3N4/R5KR b KQkq - 0 1` is not a legal Chess960 position (as it can not arise from any Chess960 starting position via a series of legal moves). Instead of raising an error, python-chess uses ~the~ a maximum set of possible castling rights.

**Comment by LocutusOfPenguin** [comment]
ok, understand (both cant castle).
But noone can know if W or B or none ... can castle, that depends on the history of the game.

For picochess usage, i would like to ignore the detail check , and just accept castling for both.
Surely, if castling can be ...no R => cant castle...thats clear.
You're right this isnt legal .... but even me, been supprised, i cant castle with B....what an user would think (esp. cause we don't give out the castling status) ;-)
Frankly, for usage this wrong both castling is easier to understand as the pure logical check of history.
You assume, if only one can castle, it must be W ...but an user doesnt see this logic.

Therefore i asked for a flag (with is by standard) "strict check". I would then turn it off, for uci960, & pos setup something like this.

**Comment by niklasf** [comment]
Ok, I see.

I don't like having many feature flags, but I'll check if other software (Stockfish, ChessX, maybe some others) would be compatible and then maybe just remove the check alltogether.

**Comment by niklasf** [comment]
Ok, so Stockfish and lichess.org can handle this just fine. So I decided to relax the validation. (Unfortunately not ChessX, but Chess960 support is relatively new there).
