### ISSUE TITLE
reading headers

### ISSUE THREAD

**Issue by mptedesco** [niklasf/python-chess#145]
I am having some difficulty with headers.  When I try to read event, site, date, round, white and black I get back ?.  However the result header reads in fine.  Just posted an analysis program using python-chess:

https://github.com/mptedesco/python-chess-analysis

Here is an example of what is happening...

This code...

```python
print "Event:",game.headers["Event"]
print "Site:",game.headers["Site"]
print "Date:",game.headers["Date"]
print "Round:",game.headers["Round"]
print "White:",game.headers["White"]
print "Black:",game.headers["Black"]
print "Result:",game.headers["Result"]
print "Quality of White Play:",round(whitequality*100,1),"%"
print "White made",whiteinaccuracies,"inaccuracies,",whitemistakes,"mistakes, and", whiteblunders,"blunders."
print "Quality of Black Play:",round(blackquality*100,1),"%"
print "Black made",blackinaccuracies,"inaccuracies,",blackmistakes,"mistakes, and", blackblunders,"blunders."
```

results in this...

```
Event: ?
Site: ?
Date: ????.??.??
Round: ?
White: ?
Black: ?
Result: 1-0
Quality of White Play: 95.7 %
White made 0 inaccuracies, 2 mistakes, and 0 blunders.
Quality of Black Play: 91.4 %
Black made 7 inaccuracies, 1 mistakes, and 0 blunders.
```

I have tested with multiple PGNs and get the same result.

I am reading the pgn as follows...

```python
with open (path+pgnfile) as infile, open ("clean.pgn", "w") as outfile:
    for line in infile:
        if not line.isspace():
            outfile.write(line)

infile.close()
outfile.close()

pgnin = open (path+"clean.pgn")
game = chess.pgn.read_game(pgnin)
```

Any thoughts?  Thanks in advance.

**Comment by niklasf** [comment]
Hi, can you please also provide `clean.pgn`? Btw. I noticed you write `clean.pgn` and read `path+"clean.pgn"`.

Also note that removing all empty lines from a PGN can alter the meaning (because usually games are seperated by empty lines).

**Comment by mptedesco** [comment]
Thanks for the quick response!

Attached are the two pgn files - the "test6" original file and the "clean.pgn" the program writes.

good point re. writing and opening the file - I'll edit that for consistency

At the moment the program is just processing a single game at a time but this will be an issue when I try to batch process multiple games.  This was a workaround because I found that when I was looping through a game with:

while not node.is_end():

it was interpreting the blank line between the headers and the game notation as the end of the game

Operator error on my part I am sure and I would love to not make the clean.pgn

[pgns.zip](https://github.com/niklasf/python-chess/files/1167954/pgns.zip)

**Comment by niklasf** [comment]
Ah! Both issues can be fixed by specifying the correct file encoding (since both files start with an UTF-8 BOM).

In Python 3 this would be:

```python
import chess.pgn

with open("test6.pgn", encoding="utf-8-sig") as pgn:
    game = chess.pgn.read_game(pgn)

print(game)
```

```
[Event "Leon 30th"]
[Site "Leon"]
[Date "2017.07.09"]
[Round "2.5"]
[White "So, Wesley"]
[Black "Anand, Viswanathan"]
[Result "1-0"]
[ECO "A08"]
[WhiteElo "2810"]
[BlackElo "2783"]
[PlyCount "45"]
[EventDate "2017.07.07"]
[EventType "k.o. (rapid)"]
[EventRounds "2"]
[EventCountry "ESP"]
[SourceTitle "CB28_2017"]
[SourceDate "2017.07.01"]
[SourceVersion "1"]
[SourceVersionDate "2017.07.01"]
[SourceQuality "1"]

1. Nf3 d5 2. g3 c5 3. Bg2 Nf6 4. O-O g6 5. c4 dxc4 6. Qa4+ Bd7 7. Qxc4 Qb6 8. Nc3 Bg7 9. d3 O-O 10. Be3 Rc8 11. Rab1 Be6 12. Qh4 Qa6 13. Ng5 Nbd7 14. Nxe6 fxe6 15. Qc4 Qxc4 16. dxc4 Rab8 17. Rfd1 Ne5 18. b3 b6 19. Nb5 a6 20. Bf4 Nfg4 21. Na7 Rc7 22. Nc6 Rbc8 23. Nd8 1-0
```

In Python 2:

```python
import io
import chess.pgn

with io.open("test6.pgn", encoding="utf-8-sig") as pgn:
    game = chess.pgn.read_game(pgn)
```

**Comment by mptedesco** [comment]
Thank you!  That was what I was doing wrong.  Much appreciated.  Killed two bugs with one stone.
