### ISSUE TITLE
Question: Should peek() return null move?

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#146]
Hi,

when i do a 
b = chess.Board()
b.peek()

i get an IndexError
The docu saying nothing about this. Should i test first for empty stack?
=> I would have expected a null move not something i have to catch ;-)

But ways are ok for me...so, its just a Q (or a hint for improvement?)
At least the docu should handle this, no?

Jürgen

**Comment by niklasf** [comment]
Thanks. I updated the docs. Raising `IndexError` is quite natural:

```python
>>> empty = []
>>> empty.pop()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: pop from empty list
```
