### ISSUE TITLE
Problem with FEN and en passant which exists but is not legal

### ISSUE THREAD

**Issue by ChameleonRed** [niklasf/python-chess#152]
I found during testing that FEN for 1. e4 should be:

https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation
En passant target square in algebraic notation. If there's no en passant target square, this is "-". If a pawn has just made a two-square move, this is the position "behind" the pawn. This is recorded regardless of whether there is a pawn in position to make an en passant capture.[2]

"Therefore, an en passant target square field may have a square name even if there is no pawn of the opposing side that may immediately execute the en passant capture."

but fen for e4 is:
b = chess.Board()
b.push_san('e4')
Move.from_uci('e2e4')
b.fen()
'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1'

Should be rather:
'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1'

This happen when I encode you board to position:
    def test_from_board_to_fen_initial_e4(self):
        board = chess.Board()
        board.push_san('e4')
        chess_position = ChessPosition.from_chess_board(board)
        print(hex(chess_position.bits))
        fen = ChessPosition.to_fen(chess_position.bits)
        self.assertEqual(board.fen(), fen)

Output (do not study it is just to show execution flow - result on the end):
0x1345743100000001888888889bcdecb9fff700080000ffff

Failure
Traceback (most recent call last):
  File "C:\root\Python36-64\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\root\Python36-64\lib\unittest\case.py", line 601, in run
    testMethod()
  File "C:\Users\Cezary Wagner\PycharmProjects\stockfish-proxy\src\test_chess_position.py", line 29, in test_from_board_to_fen_initial_e4
    self.assertEqual(board.fen(), fen)
  File "C:\root\Python36-64\lib\unittest\case.py", line 821, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\root\Python36-64\lib\unittest\case.py", line 1194, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\root\Python36-64\lib\unittest\case.py", line 666, in fail
    raise self.failureException(msg)
AssertionError: 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1' != 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1'
- rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
?                                                      ^
+ rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1

**Comment by niklasf** [comment]
This is actually intentional (see [X-FEN](https://en.wikipedia.org/wiki/X-FEN#Encoding_en-passant), #96 and #66).

**Comment by ChameleonRed** [comment]
Maybe better is add xfen to API than fen since name is different than result?

**Comment by niklasf** [comment]
To be clear, I believe this is a design mistake in the FEN spec.

Does this cause any real problems for you? I am always intrested in cases where this incompability is actually relevant.

**Comment by ChameleonRed** [comment]
It is not mistake of FEN notation that is how it is design.

XFEN is designed other way.

For me it is not problem but is API name lead to mistake since FEN != XFEN I fall in this trap :)
