### ISSUE TITLE
Disable logging in v0.19

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#153]
Hi,
before i was able to disable such lines:
2017-08-11 12:12:50.198   DEBUG        uci - on_line_received: <PopenProcess at 0x7f381c04a908 (pid=24458)> >> info depth 28 currmove e7e5 currmovenumber 1

with
`logging.getLogger('chess.uci').setLevel(logging.INFO)`

But it seems to no longer work (after i updated to v0.19)
How to do it?

**Comment by niklasf** [comment]
Ah, my mistake. Please try `chess.engine` instead of `chess.uci` and see if that works.

**Comment by LocutusOfPenguin** [comment]
yep. Thanks
