### ISSUE TITLE
Position evaluation

### ISSUE THREAD

**Issue by stevexyz** [niklasf/python-chess#155]
I'm experimenting with machine learning and for the purpose I would need to feed the model with the board position evaluation.

From [engine communication documentation](https://python-chess.readthedocs.io/en/latest/uci.html) seems the output received from the engine is the best and ponder moves, while I would need the value of the evaluation.

Even better would be to be able to have the evaluation of all the possible legal moves (or a subset of it) at once (e.g. stockfish with MultiPV option can give them as you want). Obviously in this case the current position evaluation is the score of the best move.

**Comment by niklasf** [comment]
Hi. Yes, that's possible like so:

```python
import chess.uci

engine = chess.uci.popen_engine("stockfish")

engine.setoption({"MultiPV": 3})

info_handler = chess.uci.InfoHandler()
engine.info_handlers.append(info_handler)

board = chess.Board()
engine.position(board)

engine.go(movetime=5000)
print(info_handler.info["pv"])
print(info_handler.info["score"])
```

Sample output:
```
{1: [Move.from_uci('d2d4'), Move.from_uci('g8f6'), Move.from_uci('c2c4'), Move.from_uci('e7e6'), Move.from_uci('g1f3'), Move.from_uci('d7d5'), Move.from_uci('e2e3'), Move.from_uci('f8e7'), Move.from_uci('c4d5'), Move.from_uci('e6d5'), Move.from_uci('f1d3'), Move.from_uci('b8c6'), Move.from_uci('b1c3'), Move.from_uci('e8g8'), Move.from_uci('a2a3'), Move.from_uci('c8d7'), Move.from_uci('c1d2'), Move.from_uci('e7d6'), Move.from_uci('c3b5')], 2: [Move.from_uci('g1f3'), Move.from_uci('d7d5'), Move.from_uci('d2d4'), Move.from_uci('e7e6'), Move.from_uci('c2c4'), Move.from_uci('g8f6'), Move.from_uci('e2e3'), Move.from_uci('f8e7'), Move.from_uci('c4d5'), Move.from_uci('e6d5'), Move.from_uci('f1d3'), Move.from_uci('b8c6'), Move.from_uci('a2a3'), Move.from_uci('c8g4'), Move.from_uci('h2h3'), Move.from_uci('g4f3'), Move.from_uci('d1f3'), Move.from_uci('e8g8'), Move.from_uci('e1g1'), Move.from_uci('a7a6')], 3: [Move.from_uci('e2e4'), Move.from_uci('e7e6')]}
{1: Score(cp=22, mate=None), 2: Score(cp=22, mate=None), 3: Score(cp=28, mate=None)}
```
The PVs are the actual lines. `info["pv"][3][0]` would be the first move of the third line, `info["score"][3]` would be the corresponding eval. All evals are from the point of view of the side to move.

**Comment by stevexyz** [comment]
Great!!
Hope this evening I've time to test it.
Thank you very much Niklas!!
