### ISSUE TITLE
Question: Ponderhit use

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#159]
Hi,
i would like to bring "pondering on players time" (permament brain) to picochess.
Now i have the following "understanding problem"

When the engine played its move, i start "engine.ponder" with infinite time (similar to analysis mode).
As far i understand if the user plays the current best move from the engine, i should send a "ponderhit" command , to let the engine go from ponder to think mode. If the player plays something else, its easy - just stop the pondering engine, and restart thinking.

=>
But how to set the time to think for the engine incase of a ponderhit?

**Comment by niklasf** [comment]
First to clarify something, an example session:

The engine goes first and reports `bestmove e2e4 ponder e7e5`. So 1. e4 is played and the engine indicates it expects the response will be 1...e5. (Or at least it wants to ponder that move.)

So you let it: `position startpos moves e2e4 e7e5`, `go ponder` will let the engine ponder what it wanted.

Now the user indeed plays `1... e5`. That is the move you gave it to ponder. *This* means you should send `ponderhit`.

> As far i understand if the user plays the current best move from the engine, i should send a "ponderhit"

 The current best move by the engine is not relevant for this.

---

To answer your question: You can send search parameters along with ponder, like `go ponder depth 22 movetime 20000`. The depth and movetime will only be activated after `ponderhit`. However the time counts from the start of the ponder search, so:

`go ponder movetime 1000`, wait longer than 1s, `go ponderhit` will immediately let the engine stop the search.

**Comment by LocutusOfPenguin** [comment]
thanks for yr explaination!

I see y only responsible to send this "ponderhit" to the uci engine. But for me, this is ODD. I expect to send times , when the user played its move. How can i know the times, during he begin to think?
The current uci implemenation leads to "quicker" , not "stronger" (the time the engine spend in pondering (permanent brain) shouldnt effect the thinking time alltogether. Now its more like both clocks are running.

Well, thats all nothing with you (im abit disappointed how this uci is implemented). Anyway i learned i dont need to send "ponder with ultimate time" like im doing on analysis.

Lets close this ticket.

**Comment by niklasf** [comment]
Agreed.
