### ISSUE TITLE
Excluding opening moves from PGN

### ISSUE THREAD

**Issue by Mk-Chan** [niklasf/python-chess#160]
Is there a way to recognize opening moves in a PGN and exclude them? I tried to get a file containing a list of PGNs of a lot of ECOs, match it with the value in the "ECO" header of the game I am trying to analyze and try a strategy of counting moves and skipping them in the game's PGN.

But then I had trouble counting the moves in the ECO pgn because I had to play out the game until the end and keep a counter. Maybe I am doing it wrong and missing some API(I looked at the PGN docs too) but that seems like too much work to just count the number of moves?

Also, another issue I faced is that many ECO are separated into subdivisions (C60 is Ruy Lopez but it has >= 8 variations inside C60 itself!) so the above attempt isn't even a reliable solution.

Is this even the right place to ask such issues? Or should I email?

**Comment by niklasf** [comment]
The issue tracker is alright for this kind of discussion.

Depending on what you're tying to do, how about keeping a set of seen positions (or their hashes)? If a position occurs for the second time, then it's likely to be an opening position, although not nescessarily a theoretical one.

**Comment by Mk-Chan** [comment]
I want to analyze the performance of a player by going through pgns and i figured it would be good to ignore theoretical opening moves for the same. Any ideas how i would exclude such moves?

**Comment by sshivaji** [comment]
I think other python libraries are better for this use case. Have a look at
https://github.com/mcostalba/chess_db. You can build a PGN index from a PGN
file. My tree supports bad PGNs -
https://github.com/sshivaji/chess_db/tree/prod

What you would do is build a PGN index from a set of master games. Then you
can query by any position and then find out if the position is in the
opening by the number of moves played, and you can figure out a cutoff.

**Comment by Mk-Chan** [comment]
Thanks for the suggestion! I'll give that a shot

**Comment by Mk-Chan** [comment]
@sshivaji This seems to work, thanks!
