### ISSUE TITLE
Board.fen() doesn't output correct en passant square

### ISSUE THREAD

**Issue by martsberger** [niklasf/python-chess#162]
`Board.fen()` outputs a `-` for the en passant square if there is no legal en passant move, but every reference I can find for the FEN spec says the en passant square should be populated any time a pawn advances two squares, whether there is a legal en passant capture on that square or not.

This is important because it means the FEN generated by python-chess is not compatible with other libraries that follow the standard.

Easy fix on line 2225 in chess/__init__.py
```
epd.append(SQUARE_NAMES[self.ep_square] if self.has_legal_en_passant() else "-")
```
should be
```
epd.append(SQUARE_NAMES[self.ep_square] if self.ep_square else "-")
```

**Comment by Mk-Chan** [comment]
We've had this discussion before and the conclusion was reached that
python-chess is following X-FEN rather than the original (If I'm not wrong).

Maybe it would be good to provide both via a flag or by having a separate
xfen function?

**Comment by Mk-Chan** [comment]
Refer to https://github.com/niklasf/python-chess/issues/152

**Comment by martsberger** [comment]
Sorry I missed the other issue. I agree that a flag for producing fen instead of xfen would be useful.

This causes a real problem, for example, when building an application with python-chess on the backend and chess.js on the front end I can't validate that the position is the same using the fen string. I suppose I could bug chess.js to add an option for xfen 😄

**Comment by Mk-Chan** [comment]
Could easily split it into FEN and X-FEN but waiting for @niklasf 's input

**Comment by niklasf** [comment]
The FEN specification says that the implementation should be aware of irrelevant en passant squares, even though it's not required to completely describe the position. I maintain that's a flaw.

It just so happens that python-chess is even able to provide irrelevant ep squares. Since it comes up once in a while I'll ponder adding a method for that.

Meanwhile see https://github.com/niklasf/python-chess/issues/66#issuecomment-192999948 for a workaround, and of course X-FEN support in chess.js is nice in and of itself.

**Comment by martsberger** [comment]
I've seen two good arguments in favor of your implementation of fen in this comment thread. Unfortunately, the spec was made differently. Even though you think the spec is flawed, not following it makes your library more difficult to interface from other libraries that do.

Is there a problem with changing the signature of `Board.fen` so that it is:
```
def fen(self, promoted=None, xfen=True):
```
So that users of your library can call `board.fen(xfen=False)` to get a fen representation that meets the fen spec without writing their own outside helper function?

**Comment by niklasf** [comment]
So now `board.fen(en_passant="legal")` (unchanged default), `board.fen(en_passant="fen")` and `board.fen(en_passant="xfen")` are supported. Docs: https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.fen

**Comment by martsberger** [comment]
Thanks! You're awesome for being so responsive and making this change.
