### ISSUE TITLE
chess.move() send from bestmove @laser engine

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#163]
Hi,
i dont know if thats a problem, but on "laser" engine, Jeff also sending statistics on bestmove like so:

cerr << std::setw(22) << "Hash hit rate: " << getPercentage(searchStats.hashHits, searchStats.hashProbes)

and many more of this kind
and then:
cout << "bestmove theEngineBestMove" << endl

This results in a chess.Move() type, but if i do a print(move), i get all these lines printed.

Should you or jeff or both/none of you change something?

**Comment by niklasf** [comment]
This is just a cosmetic issue. Everything should work fine.

You can supress stderr like so:

```python
import subprocess

engine = chess.uci.popen_engine("./laser", stderr=subprocess.DEVNULL)
```

Or in Python 2:

```python
import os    
    
null = open(os.devnull, "w")
engine = chess.uci.popen_engine("./laser", stderr=null) 
```

**Comment by LocutusOfPenguin** [comment]
great. works with devnull. Thanks
