### ISSUE TITLE
Question: EngineTerminatedException

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#164]
Hi,
i still have problems with this Terminated. Its from #154
When i send a "stop" i get this exception from time to time (sadly very few, and i dont know how to do it again).

Btw. what exactly does it mean? Cause i dont send a kill, terminate etc to the engine, so it should be still alive.

My Log saying:
2017-09-10 10:21:26.931   ERROR     engine - stop: Engine terminated
2017-09-10 10:21:26.933   ERROR     engine - callback: Engine terminated

using this:
https://github.com/LocutusOfPenguin/picochess/blob/5774d771e1644f9aa8da23bff92fc4c4d8a8fc58/uci/engine.py

In these "is_*" functions, NOW put these checks inside (using idle, pondering). Perhaps y can provide this api yourself => get the state of engine?!? Is that used correctly?

But i dont get the other logging.errors, only this Terminate Exception.

Jürgen

**Comment by niklasf** [comment]
Hi, is this with Stockfish?

**Comment by LocutusOfPenguin** [comment]
Hi,
well..yes! (but that doesnt matter).
In meantime, i updated my code incl. to use some of the above is_* functions (using direct towards python-chess). But i not feel safe, asking for class-vars inside a lib from outside.

see here:
https://github.com/LocutusOfPenguin/picochess/blob/master/uci/engine.py

Jürgen
