### ISSUE TITLE
Is it possible to iterate over all FENs in Syzygy table?

### ISSUE THREAD

**Issue by salvador-dali** [niklasf/python-chess#166]
I have a syzygy WDL endgame table (just for example I uploaded the [file KPPPPvK.rtbw](https://ufile.io/rpzsu)) and for my own purposes I need to iterate over all FENs in this table and see the results for each position.

I see from the documentation that I can probe this table for various positions:

```
import chess.syzygy
with chess.syzygy.open_tablebases("data/endgame_tables") as tablebases:
    for pos in ['5k2/5P2/8/5P2/8/5P2/K4P2/8 w - -', '7k/7P/7P/7P/7P/8/8/K7 w - -']:
        print(tablebases.probe_wdl(chess.Board(pos + ' 0 1')))
```

but can't figure out how can I iterate over all positions in this table. Is it possible to do with this library (or maybe anyone knows any other library that I can use)?

**Comment by niklasf** [comment]
You could just independently enumerate all KPPPPvK positions (possibly excluding some symmetry), but this is probably infeasible in Python in any reasonable amount of time.
