### ISSUE TITLE
InfoHandler currmove doesn't work in a for loop. 

### ISSUE THREAD

**Issue by kalegood** [niklasf/python-chess#167]
this, from the docs with the addition of currmove, works. 
```
with info_handler:
        if 1 in info_handler.info["score"]:
                print("Score: ", info_handler.info["score"][1].cp)
                print("Mate: ", info_handler.info["score"][1].mate)
                print("Move: ", info_handler.info["currmove"])
```
However, this throws a KeyError. 
```

for x in range(0, 3):
    with info_handler:
        if 1 in info_handler.info["score"]:
                print("Score: ", info_handler.info["score"][1].cp)
                print("Mate: ", info_handler.info["score"][1].mate)
                print("Move: ", info_handler.info["currmove"])
```

**Comment by niklasf** [comment]
Hi. Are you using this during search? If so, the loop increases the chances of hitting the dictionary while `currmove` is not set.

You could just test that it really is set (`if "currmove" in info_handler.info`), catch the exception or use `info.get("currmove")`.

**Comment by kalegood** [comment]
This says it's not set. If I am understanding correctly (I'm a copy-paste programmer), I've stopped the engine and told python to wait (just for redundancy). However, it looks like currmove isn't getting set. 

`
import chess
import chess.uci
import time

engine = chess.uci.popen_engine("stockfish")
engine.uci()

info_handler = chess.uci.InfoHandler()
engine.info_handlers.append(info_handler)

board = chess.Board('rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 2')
   
info_handler = chess.uci.InfoHandler()
engine.info_handlers.append(info_handler)   

multifen = ('rnbqkbnr/pp1ppppp/8/2p5/4P3/8/8/RNBQKBNR w KQkq c6 0 2','rnbqkbnr/pp1ppppp/8/2p5/4P3/RRRRRRRR/PPPP1PPP/7K w KQkq c6 0 2')    

for x in multifen:
    engine.position(board)
    engine.go(movetime=2000, async_callback=True, )
    time.sleep(3)
    with info_handler:
        if 1 in info_handler.info["score"]:
                if "currmove" in info_handler.info:
                    print("currmove is set. VICTORY!")
                else:
                    print("currmove is not set")
        else:
            print("No info in info handler")
                #~ print("Move: ", info_handler.info["currmove"])
    
                
`

**Comment by niklasf** [comment]
To be clear, the engine can send information about the move it is currently looking at, `currmove`. There's no guarantee that the move is also good. Furthermore it's completely optional: Engines do not have to send this info.

For example Stockfish only sends it after about 3000 ms:

https://github.com/official-stockfish/Stockfish/blob/0e949ac2c956dc5ac03dc9da7050d895b3fb964a/src/search.cpp#L835-L838

If you want the best move according to the engine, you can reliably use:

```python
bestmove, _ = engine.go(movetime=2000)
```

This will wait exactly the right time.

**Comment by kalegood** [comment]
Ah, yes. I guess currmove does sort of imply current, eh. Thanks for your time and work on the project.
