### ISSUE TITLE
is_zeroing and is_capture operation outputs

### ISSUE THREAD

**Issue by bhathiya** [niklasf/python-chess#169]
I'm using python-chess to analyze a game.

I have my code like this, and I expect 3 boolean outputs.

    print("is_castling: " + unicode(board.is_castling(node.move)));
    print("is_zeroing: " + unicode(board.is_zeroing(node.move)));
    print("is_capture: " + unicode(board.is_capture(node.move)));

But this is what I get.

    is_castling: False
    is_zeroing: 4194304
    is_capture: 4194304

When I use bool() to wrap above values, it always returns true.
What am I missing here?

**Comment by niklasf** [comment]
Hi, I've modified the functions to strictly return bools in the future.

However the real issue seems to be something else, because interpreting their return value as bools should work. And indeed it does in a quick test. A self contained example or some more context would be helpful to debug this.

**Comment by bhathiya** [comment]
Please find the script below.

```
#!/usr/bin/python

import chess;
import chess.pgn;
import chess.uci;

pgn_string = "1. e4 c6 2. d4 d5 3. Nc3 dxe4 4. Nxe4 Bf5 5. Ng3 Bg6 6. h4 h6 7. f4 e6 8. Nf3 Nd7 9. h5 Bh7 10. Bd3 Bxd3 11. Qxd3 Ngf6 12. Bd2 c5 13. O-O-O Qc7 14. dxc5 Bxc5 15. Ne5 Rd8 16. Qe2 O-O 17. Nd3 Bd6 18. Kb1 Nc5 19. Nxc5 Bxc5 20. Rdf1 Bd4 21. Bc1 Nd5 22. Rf3 Rfe8 23. Re1 Nf6 24. Ne4 Qc6 25. Nxf6+ Bxf6 26. Ref1 e5 27. fxe5 Rxe5 28. Qf2 Rxh5 29. g4 Rb5 30. Rb3 a6 31. a4 Rxb3 32. cxb3 Qe4+ 33. Ka2 Rc8 34. Re1 Qxg4 35. Rg1 Bd4 36. Qxf7+ Kxf7 37. Rxg4 Rxc1 38. Rxd4 Rc7 39. b4 g5 40. Rd6 Kg7 41. b5 axb5 42. axb5 Kh7 0-1";

try:
     from StringIO import StringIO  # Python 2
except ImportError:
     from io import StringIO  # Python 3

pgn = StringIO(pgn_string);
first_game = chess.pgn.read_game(pgn);
pgn.close();
print(pgn_string);
node = first_game;
board = node.board();
print("\n");

engine = chess.uci.popen_engine("/usr/games/stockfish");
engine.uci();
print(engine.name);
print("\n");

a = 0;
while not node.is_end() and a < 2:
    print("White Turn: " + unicode(board.turn));
    print("Move pair Number: " + unicode(board.fullmove_number));
    node = node.variation(0);
    board.san(node.move);
    board = node.board();
    print(unicode(board));
    print("Move: " + unicode(node.move));
    print("is_castling: " + unicode(board.is_castling(node.move)));
    print("is_zeroing: " + unicode(board.is_zeroing(node.move)));
    print("is_zeroing: " + unicode(bool(board.is_zeroing(node.move))));
    print("is_capture: " + unicode(board.is_capture(node.move)));
    print("is_capture: " + unicode(bool(board.is_capture(node.move))));
    print("\n");
    a = a + 1;
```

Here is the output:

> bhathiya@bhathiya-x1:/apps/chess$ ./BoolCheck.py 
> 1. e4 c6 2. d4 d5 3. Nc3 dxe4 4. Nxe4 Bf5 5. Ng3 Bg6 6. h4 h6 7. f4 e6 8. Nf3 Nd7 9. h5 Bh7 10. Bd3 Bxd3 11. Qxd3 Ngf6 12. Bd2 c5 13. O-O-O Qc7 14. dxc5 Bxc5 15. Ne5 Rd8 16. Qe2 O-O 17. Nd3 Bd6 18. Kb1 Nc5 19. Nxc5 Bxc5 20. Rdf1 Bd4 21. Bc1 Nd5 22. Rf3 Rfe8 23. Re1 Nf6 24. Ne4 Qc6 25. Nxf6+ Bxf6 26. Ref1 e5 27. fxe5 Rxe5 28. Qf2 Rxh5 29. g4 Rb5 30. Rb3 a6 31. a4 Rxb3 32. cxb3 Qe4+ 33. Ka2 Rc8 34. Re1 Qxg4 35. Rg1 Bd4 36. Qxf7+ Kxf7 37. Rxg4 Rxc1 38. Rxd4 Rc7 39. b4 g5 40. Rd6 Kg7 41. b5 axb5 42. axb5 Kh7 0-1
> 
> 
> Stockfish 7 64
> 
> 
> White Turn: True
> Move pair Number: 1
> ♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜
> ♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟
> . . . . . . . .
> . . . . . . . .
> . . . . ♙ . . .
> . . . . . . . .
> ♙ ♙ ♙ ♙ . ♙ ♙ ♙
> ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖
> Move: e2e4
> is_castling: False
> is_zeroing: 268435456
> is_zeroing: True
> is_capture: 268435456
> is_capture: True
> 
> 
> White Turn: False
> Move pair Number: 1
> ♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜
> ♟ ♟ . ♟ ♟ ♟ ♟ ♟
> . . ♟ . . . . .
> . . . . . . . .
> . . . . ♙ . . .
> . . . . . . . .
> ♙ ♙ ♙ ♙ . ♙ ♙ ♙
> ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖
> Move: c7c6
> is_castling: False
> is_zeroing: 4398046511104
> is_zeroing: True
> is_capture: 4398046511104
> is_capture: True

**Comment by niklasf** [comment]
Looks like the moves are tested in the context of the new board (after the move), while they should be tested with the board they were played on.

**Comment by bhathiya** [comment]
Could you please help me understand what exactly I should fix in above script?

**Comment by niklasf** [comment]
Yes, that should work for example.

 I admit that this is easy to get wrong and unfortunately it's a silent error, too. Perhaps I can add some assertions without slowing things down too much ...

**Comment by bhathiya** [comment]
Awesome. Thank you.

**Comment by bhathiya** [comment]
Btw, this library is awesome and very useful. Thank you for writing (and sharing) it. :)

**Comment by qwertyquerty** [comment]
I'm not sure this is fixed, because after loading a board from FEN, all of the output will always be True here.

**Comment by niklasf** [comment]
Can you please give a concrete example?

```python
>>> import chess
>>> board = chess.Board("5B1Q/3Q2N1/8/8/6q1/2k5/8/1K6 b - - 0 1")
>>> move = board.parse_san("Qe4+")
>>> board.is_zeroing(move)
False
>>> board.is_capture(move)
False
```
