### ISSUE TITLE
Question about perft speed

### ISSUE THREAD

**Issue by andersfylling** [niklasf/python-chess#173]
Can I ask how many nodes or moves per second this engine has?

**Comment by niklasf** [comment]
Just to give you a ballpark figure, I get around 280k nps on my machine (single thread, no transposition table). So not very good to build a chess engine, nonetheless useful as a general purpose library.

**Comment by andersfylling** [comment]
Oh wait is that with legal + illegal generated nodes. or just the number of nodes generated by perft at a given depth divided by time spent? @niklasf

**Comment by niklasf** [comment]
It's the actual perft number divided by the time spent. I used

```
python examples/perft/perft.py --threads 1 examples/perft/random.perft --max-nodes 10000
```

to measure this. (`--max-nodes` is just to select varying examples from the [perft reference file](https://raw.githubusercontent.com/niklasf/python-chess/master/examples/perft/random.perft)).
