### ISSUE TITLE
A possible bug in chess.svg.Arrow()

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#174]
```
import chess
import chess.svg
import IPython

chessboard = chess.Board()
chessboardSVG = chess.svg.board(board=chessboard,
                                arrows=chess.svg.Arrow(tail=(chess.E2, chess.E4),
                                                       head=(chess.E2, chess.E4)))

IPython.display.SVG(chessboardSVG)
```

I have run this code in the Jupyter Notebook App on my local server with Python 3 as my kernel. The SVG image produced was displayed correctly (i.e., the arrow on the chessboard was displayed correctly). However, I don't understand why the field names `tail` and `head` must have the same values. Isn't more logical that `tail` would need just `chess.E2` and `head` would need just `chess.E4`?

**Comment by niklasf** [comment]
Hi, the function takes a list of arrows, e.g.

```
arrows=[chess.svg.Arrow(chess.E2, chess.E4)]
```

Your code doesn't error because Arrow (as a namedtuple) is iterable, and the code handling it is pretty generic.

**Comment by PedanticHacker** [comment]
Maybe in the future we'll try to implement circles, too?

**Comment by niklasf** [comment]
Just to clarify what I meant by list of tuples: `arrows=[(chess.E2, chess.E4)]` would also be accepted.

Circles are already drawn if head and tail are the same. I documented that just now.
