### ISSUE TITLE
Remaining XBoard API

### ISSUE THREAD

**Issue by Mk-Chan** [niklasf/python-chess#182]
I wanted to make a checklist of the remaining API (xboard commands). Sorry if this is a little large but it's taken directly from [the spec](http://www.open-aurec.com/wbforum/WinBoard/engine-intf.html#8).
Xboard -> Engine commands:

- [x] xboard
- [x] protover
- [ ] accepted/rejected
- [x] new
- [x] variant
- [x] quit
- [x] random
- [x] force
- [x] go
- [x] playother
- [x] white
- [x] black
- [x] level
- [x] st
- [x] sd
- [x] nps
- [x] time
- [x] otim
- [x] usermove
- [x] ? - implemented as `stop()`
- [x] ping
- [x] draw
- [x] result
- [x] setboard
- [ ] edit
- [ ] hint
- [ ] bk
- [x] undo
- [x] remove
- [x] hard
- [x] easy
- [x] post
- [x] nopost
- [x] exit
- [x] analyze
- [x] name
- [x] rating
- [ ] ics
- [x] computer
- [x] pause/resume
- [x] memory
- [x] cores
- [x] egtpath
- [x] option

Engine -> Xboard commands (Parsing required):

- [x] feature \<features\>
- [x] Illegal move/Illegal move (REASON): MOVE
- [x] Error (ERRORTYPE): COMMAND
- [x] move <move>
- [ ] \<result\> {COMMENT}
- [x] resign
- [x] offer draw
- [ ] ics messages

**Comment by Mk-Chan** [comment]
No wonder it's much easier to code UCI, this is quite a mess!

**Comment by PedanticHacker** [comment]
Who uses XBoard, anyway? UCI is the future! ;)

**Comment by PedanticHacker** [comment]
I looked into this and found out that it is an overkill to implement the whole XBoard specification in Python and support the old XBoard spec and the new spec. You must realize that XBoard only runs on *nix machines (Mac, Linux). You have to take Windows users into consideration, too. Well, then you need to implement the WinBoard specification as well. So much code!

My proposal is this. Since we have UCI specification fully implemented, we can just implement a UCI adapter. Take a look at this: http://wbec-ridderkerk.nl/html/details1/PolyGlot.html

**Comment by Mk-Chan** [comment]
Winboard is the same as xboard in terms of protocol. Anyway, I too was a
bit put off after I actually listed the thing exhaustively and implementing
an adaptor(UCI -> XB) is not a bad idea. I'm up for coding that. Will wait
for Niklas' input for now.

On Oct 26, 2017 17:25, "Boštjan Mejak" <notifications@github.com> wrote:

I looked into this and found out that it is an overkill to implement the
whole XBoard specification in Python and support the old XBoard spec and
the new spec. You must realize that XBoard only runs on *nix machines (Mac,
Linux). You have to take Windows users into consideration, too. Well, then
you need to implement the WinBoard specification as well. So much code!

My proposal is this. Since we have UCI specification fully implemented, we
can just implement a UCI adapter. Take a look at this:
http://wbec-ridderkerk.nl/html/details1/PolyGlot.html

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/niklasf/python-chess/issues/182#issuecomment-339641974>,
or mute the thread

**Comment by PedanticHacker** [comment]
Something interesting: http://hgm.nubati.net/cgi-bin/gitweb.cgi?p=polyglot.git;a=summary

**Comment by PedanticHacker** [comment]
"Polyglot" is an opening book format (also implemented in python-chess) and "PolyGlot" is an UCI adapter. We should not mix these two terms if Niklas decides he is okay with PolyGlot UCI adapter implementation.

**Comment by PedanticHacker** [comment]
Maybe even UCI2WB as an UCI adapter?

**Comment by niklasf** [comment]
Sure, adapters are cool, and some already exist. But XBoard also has some features that UCI does not have, so I think a direct protocol implementation is good to have.

**Comment by PedanticHacker** [comment]
I know this is off-topic here, but... Niklas, can you merge my 3 pull requests?

**Comment by Mk-Chan** [comment]
You know your message here is now going to persist beyond the resolution of your pull request, has notified people not concerned with it (me) and will remain here until the completion of the Xboard protocol API unless you delete it right?

**Comment by Mk-Chan** [comment]
Interestingly enough, we were joking around in HG Muller's monthly tourney and he told me that uci engines can send xboard commands to the GUI via `info string xboard <any xboard cmd>`

Want to take a stab at it @niklasf ?

**Comment by PedanticHacker** [comment]
Interesting stuff! Is this ment for Winboard as well?

**Comment by Mk-Chan** [comment]
As I said before, Xboard and Winboard are the same thing. Winboard is simply the windows version of Xboard.

**Comment by gbtami** [comment]
@PedanticHacker xboard and winboard are chess GUI programs communicating with engines via CECP protocol.

Btw. there is a newer CECP document maintained by HGM here http://hgm.nubati.net/CECP.html
It organized in a different way and contains some stuff not in the old one.

**Comment by Mk-Chan** [comment]
@gbtami there are some new options yea and it looks much better presented. Thanks for this.

**Comment by Mk-Chan** [comment]
So I've been getting quite busy and haven't really found the time to get to the two major features(non ics related): pondering and variants. I'll get to them soon but i just wanted to comment here as a reminder.

**Comment by ZirconiumX** [comment]
Something important that's forgotten here is the `#` command for debugging. python-chess tries to parse lines beginning with `#` when they should be ignored, which makes it choke on the debugging/statistics code in Dorpsgek.

**Comment by gbtami** [comment]
@ZirconiumX added it to https://github.com/niklasf/python-chess/pull/270

**Comment by Mk-Chan** [comment]
As of #272 pondering is left

**Comment by Mk-Chan** [comment]
Pondering is handled by #277 but testing is remaining. The difficulties I faced have been mentioned at the bottom of that PR. So now that main commands for protover 2 should be handled completely.

**Comment by niklasf** [comment]
I couldn't find a good way to test this easier. I guess it's fine for now ... maybe we'll find something eventually.

**Comment by niklasf** [comment]
I think the remaining commands should only be implemented if specifically requested.

**Comment by thomasahle** [comment]
How is "Error (ERRORTYPE): COMMAND" handled?
It seems that currently we just throw
```
<XBoardProtocol (pid=97059)>: Unexpected engine output: Error (ERRORTYPE): COMMAND
```
and crash.
Maybe exiting quickly is the best option.

**Comment by Mk-Chan** [comment]
This API is deprecated in favor of the engine one. Are you using an older version of python-chess?
