### ISSUE TITLE
Something small to fix on PyPI website

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#194]
On PyPI website for python-chess, I found this...

Features

Supports Python 2.6+, Python 3.3+ and PyPy.

IPython notebook integration. SVG rendering docs.

Please fix "IPython notebook integration" to say "IPython/Jupyter Notebook integration"
Thanks. ;)

******************

Also, this...

Make and unmake moves.

>>> Nf3 = chess.Move.from_uci("g1f3")
>>> board.push(Nf3)  # Make the move

>>> board.pop()  # Unmake the last move
Move.from_uci('g1f3')

Please add a period at the end of those in-line comments in the example code.

******************

Also, this sentence needs a comma:
With the new rules from July 2014[!!!comma here!!!] a game ends drawn (even without a claim) once a fivefold repetition occurs or if there are 75 moves without a pawn push or capture.

**Comment by niklasf** [comment]
The page on PyPI is generated from README.md, so it will be fixed with the next release.
