### ISSUE TITLE
Spelling of 'Repetition?'

### ISSUE THREAD

**Issue by mixographer** [niklasf/python-chess#20]
Hi Niklasf,

I don't know if it matters, or if you can spell the class both ways in future, but I think repitition is spelled repetition. A pull-request in picochess was broken because the requestor spelled repitition the correct way. I don't know what the right answer is, since the correct way was a typo since it's not the name of the method. Just an FYI. Anyway, thanks for python-chess. 

Jimmy

**Comment by niklasf** [comment]
Hi Jimmy,

thanks for reporting this. I would have never noticed.

I fixed the spelling. The next release will include `can_claim_threefold_repetition` and `is_fivefold_repetition` but also aliases with the incorrect spelling.

The release after that will have those aliases removed. I'll mention it in the changelog again.

Niklas
