### ISSUE TITLE
How to get the name of the moved piece?

### ISSUE THREAD

**Issue by bhathiya** [niklasf/python-chess#200]
When parsing a PGN, and looping steps one by one, is there a straightforward way to get the name (abbreviation) of the piece that was moved at last on the board, instead of doing some String manipulation? 

for example,

```
Input --> Output
Nf3 --> N
e4e5 --> P or (empty)
Ke1e2 --> K 
```
Thanks.

**Comment by niklasf** [comment]
Hi. How about something like `board.piece_at(move.from_square).symbol()`?

**Comment by PedanticHacker** [comment]
I tried this and got an
AttributeError: 'NoneType' object has no attribute 'symbol'

The code was:
>>> import chess
>>> board = chess.Board()
>>> move = board.push_san("Nf3")
>>> board.piece_at(move.from_square).symbol()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'symbol'

**Comment by niklasf** [comment]
I meant:
```python
>>> import chess
>>> board = chess.Board()
>>> move = board.parse_san("Nf3")
>>> board.piece_at(move.from_square).symbol()  # Look before the move is played.
'N'
```

**Comment by PedanticHacker** [comment]
Ah, yes.

**Comment by bhathiya** [comment]
Perfect! Thanks a lot.
