### ISSUE TITLE
error when using board.pieces()

### ISSUE THREAD

**Issue by moneydance** [niklasf/python-chess#21]
board = chess.Board()
    bishops = board.pieces(chess.BISHOP, chess.WHITE)

throws error 

Traceback (most recent call last):
  File "/Users/benajaminpusey/PycharmProjects/Test/Chess_Project/chess_project.py", line 98, in <module>
    bishops = board.pieces(chess.BISHOP, chess.WHITE)
  File "build/bdist.macosx-10.9-intel/egg/chess/__init__.py", line 897, in pieces
    
AttributeError: 'Board' object has no attribute 'piece_mask'

**Comment by moneydance** [comment]
seems like it should be calling peices_mask

**Comment by niklasf** [comment]
Thanks for reporting this! There were only test for pieces_mask directly.

**Comment by moneydance** [comment]
Quick question. How would you suggest using the pieces function and A piece-square table like so 

pawn_table =[
[0,  0,  0,  0,  0,  0,  0,  0 ],
[50, 50, 50, 50, 50, 50, 50, 50],
[10, 10, 20, 30, 30, 20, 10, 10],
[5,  5, 10, 25, 25, 10,  5,  5 ],
[0,  0,  0, 20, 20,  0,  0,  0 ],
[5, -5, -10, 0,  0, -10, -5,  5],
[5, 10, 10, -20, -20, 10, 10, 5],
[0,  0,  0,  0,  0,  0,  0,  0 ]
]

I'm not sure how to do this efficiently since pieces returns a mask and not the coordinates that pieces are located at.

**Comment by niklasf** [comment]
So I am assuming you are trying to create an evaluation function for an experimental engine? The most efficient way would probably be:

1. Calculate the score once (however inefficient that is with iterating over squares and [file_index() and rank_index()](http://python-chess.readthedocs.org/en/latest/core.html#chess.file_index)). Alternatively you could use a one-dimensional array for the pawn table.
2. Then do incremental updates of the score after each relevant move.

Maybe also https://github.com/thomasahle/sunfish could intrest you.

**Comment by moneydance** [comment]
Hi thanks for the advice it was very helpful. I'm tweaking my evaluate function now to account for castling and I'm wondering if I am checking for a sides castling ability correctly. Would this be a correct way to set a boolean to check if the white side can still castle? 

castling_w = board.castling_rights & chess.CASTLING_WHITE != 0

Also this was a great way of quickly setting up the board_representation for my AI thanks for building this :)!

**Comment by niklasf** [comment]
That is correct.

Sometims I prefer `castling_w = bool(board.castling_rights & chess.CASTLING_WHITE)` or directly

```
if board.castling_rights & chess.CASTLING_WHITE:
    # ...
```

It's always good to hear people are building intresting things with python-chess :+1:
