### ISSUE TITLE
Unwanted "Date" and "Round" header if it is not need when "UTCDate" and no "Round" - tested on lichess database.

### ISSUE THREAD

**Issue by ChameleonRed** [niklasf/python-chess#212]
Compare this two file in diff tool to see that "Date" and "Round" is added without reason.

1. "Date" is not need if "UTCDate".
2. "Round" is not need - not all games is played in round system.

See problem here is pure lichess data:

```
[Event "Rated Bullet tournament https://lichess.org/tournament/YWcrGds9"]
[Site "https://lichess.org/1HCVcYtr"]
[White "arabella_chestimira"]
[Black "derya-66"]
[Result "1-0"]
[UTCDate "2017.08.31"]
[UTCTime "22:00:01"]
[WhiteElo "1526"]
[BlackElo "1560"]
[WhiteRatingDiff "+21"]
[BlackRatingDiff "-15"]
[ECO "D30"]
[Opening "Queen's Gambit Declined"]
[TimeControl "60+0"]
[Termination "Normal"]

1. d4 { [%eval 0.28] [%clk 0:01:00] } 1... d5 { [%eval 0.28] [%clk 0:01:00] } 2. c4 { [%eval 0.27] [%clk 0:01:00] } 2... e6 { [%eval 0.28] [%clk 0:00:59] } 3. Nf3 { [%eval 0.29] [%clk 0:01:00] } 3... Nf6 { [%eval 0.33] [%clk 0:00:58] } 4. g3 { [%eval 0.16] [%clk 0:01:00] } 4... Nc6 { [%eval 0.28] [%clk 0:00:57] } 5. Bg2 { [%eval 0.07] [%clk 0:01:00] } 5... Bd6 { [%eval 0.34] [%clk 0:00:57] } 6. O-O { [%eval 0.4] [%clk 0:01:00] } 6... O-O { [%eval 0.37] [%clk 0:00:56] } 7. cxd5 { [%eval 0.22] [%clk 0:01:00] } 7... exd5 { [%eval 0.19] [%clk 0:00:54] } 8. Nc3 { [%eval -0.07] [%clk 0:00:59] } 8... Ng4? { [%eval 1.22] [%clk 0:00:53] } 9. Bg5?! { [%eval 0.53] [%clk 0:00:59] } 9... f6?! { [%eval 1.16] [%clk 0:00:51] } 10. Bd2 { [%eval 1.15] [%clk 0:00:56] } 10... h5? { [%eval 2.66] [%clk 0:00:49] } 11. h3 { [%eval 2.28] [%clk 0:00:55] } 11... f5? { [%eval 4.95] [%clk 0:00:46] } 12. Nh4? { [%eval 2.38] [%clk 0:00:55] } 12... g5? { [%eval 4.25] [%clk 0:00:44] } 13. hxg4? { [%eval 1.88] [%clk 0:00:54] } 13... hxg4? { [%eval 4.28] [%clk 0:00:43] } 14. Ng6 { [%eval 3.8] [%clk 0:00:52] } 14... Rf6?? { [%eval 7.31] [%clk 0:00:40] } 15. Ne5? { [%eval 4.32] [%clk 0:00:51] } 15... Qf8? { [%eval 6.53] [%clk 0:00:37] } 16. Nxc6? { [%eval 4.21] [%clk 0:00:50] } 16... bxc6 { [%eval 4.1] [%clk 0:00:36] } 17. Nxd5? { [%eval 2.46] [%clk 0:00:49] } 17... Rh6? { [%eval 4.15] [%clk 0:00:34] } 18. Nc3?! { [%eval 3.57] [%clk 0:00:43] } 18... Qf7? { [%eval 6.1] [%clk 0:00:33] } 19. Bxg5 { [%eval 5.87] [%clk 0:00:42] } 19... Rh8?! { [%eval 6.53] [%clk 0:00:30] } 20. Bxc6 { [%eval 6.46] [%clk 0:00:40] } 20... Qh5?? { [%eval 9.6] [%clk 0:00:28] } 21. Re1?? { [%eval 6.26] [%clk 0:00:33] } 21... Qh1+?? { [%eval 19.42] [%clk 0:00:26] } 22. Bxh1 { [%eval 18.8] [%clk 0:00:30] } 22... Rxh1+ { [%eval 20.47] [%clk 0:00:24] } 23. Kxh1 { [%eval 20.14] [%clk 0:00:30] } 23... Kg7 { [%eval 21.27] [%clk 0:00:18] } 24. Qb3 { [%eval 20.9] [%clk 0:00:29] } 24... Bd7 { [%eval 20.66] [%clk 0:00:16] } 25. e4 { [%eval 22.28] [%clk 0:00:28] } 25... Rh8+ { [%eval 24.18] [%clk 0:00:14] } 26. Kg2 { [%eval 23.24] [%clk 0:00:27] } 26... Rh3 { [%eval 30.39] [%clk 0:00:09] } 27. exf5 { [%eval 28.09] [%clk 0:00:25] } 27... Bxg3?! { [%eval #2] [%clk 0:00:08] } 28. fxg3?! { [%eval #5] [%clk 0:00:24] } 28... Bc6+ { [%eval #5] [%clk 0:00:06] } 29. d5 { [%eval #4] [%clk 0:00:22] } 29... Bxd5+ { [%eval #4] [%clk 0:00:05] } 30. Qxd5 { [%eval #3] [%clk 0:00:21] } 30... c6 { [%eval #2] [%clk 0:00:04] } 31. Qd7+ { [%eval #1] [%clk 0:00:21] } 31... Kf8 { [%eval #1] [%clk 0:00:02] } 32. Re8# { [%clk 0:00:21] } 1-0
```

Here is same game after `str(game)` where game = `chess.pgn.readgame()`.

```
[Event "Rated Bullet tournament https://lichess.org/tournament/YWcrGds9"]
[Site "https://lichess.org/1HCVcYtr"]
[Date "????.??.??"]
[Round "?"]
[White "arabella_chestimira"]
[Black "derya-66"]
[Result "1-0"]
[UTCDate "2017.08.31"]
[UTCTime "22:00:01"]
[WhiteElo "1526"]
[BlackElo "1560"]
[WhiteRatingDiff "+21"]
[BlackRatingDiff "-15"]
[ECO "D30"]
[Opening "Queen's Gambit Declined"]
[TimeControl "60+0"]
[Termination "Normal"]

1. d4 { [%eval 0.28] [%clk 0:01:00] } 1... d5 { [%eval 0.28] [%clk 0:01:00] } 2. c4 { [%eval 0.27] [%clk 0:01:00] } 2... e6 { [%eval 0.28] [%clk 0:00:59] } 3. Nf3 { [%eval 0.29] [%clk 0:01:00] } 3... Nf6 { [%eval 0.33] [%clk 0:00:58] } 4. g3 { [%eval 0.16] [%clk 0:01:00] } 4... Nc6 { [%eval 0.28] [%clk 0:00:57] } 5. Bg2 { [%eval 0.07] [%clk 0:01:00] } 5... Bd6 { [%eval 0.34] [%clk 0:00:57] } 6. O-O { [%eval 0.4] [%clk 0:01:00] } 6... O-O { [%eval 0.37] [%clk 0:00:56] } 7. cxd5 { [%eval 0.22] [%clk 0:01:00] } 7... exd5 { [%eval 0.19] [%clk 0:00:54] } 8. Nc3 { [%eval -0.07] [%clk 0:00:59] } 8... Ng4 $2 { [%eval 1.22] [%clk 0:00:53] } 9. Bg5 $6 { [%eval 0.53] [%clk 0:00:59] } 9... f6 $6 { [%eval 1.16] [%clk 0:00:51] } 10. Bd2 { [%eval 1.15] [%clk 0:00:56] } 10... h5 $2 { [%eval 2.66] [%clk 0:00:49] } 11. h3 { [%eval 2.28] [%clk 0:00:55] } 11... f5 $2 { [%eval 4.95] [%clk 0:00:46] } 12. Nh4 $2 { [%eval 2.38] [%clk 0:00:55] } 12... g5 $2 { [%eval 4.25] [%clk 0:00:44] } 13. hxg4 $2 { [%eval 1.88] [%clk 0:00:54] } 13... hxg4 $2 { [%eval 4.28] [%clk 0:00:43] } 14. Ng6 { [%eval 3.8] [%clk 0:00:52] } 14... Rf6 $4 { [%eval 7.31] [%clk 0:00:40] } 15. Ne5 $2 { [%eval 4.32] [%clk 0:00:51] } 15... Qf8 $2 { [%eval 6.53] [%clk 0:00:37] } 16. Nxc6 $2 { [%eval 4.21] [%clk 0:00:50] } 16... bxc6 { [%eval 4.1] [%clk 0:00:36] } 17. Nxd5 $2 { [%eval 2.46] [%clk 0:00:49] } 17... Rh6 $2 { [%eval 4.15] [%clk 0:00:34] } 18. Nc3 $6 { [%eval 3.57] [%clk 0:00:43] } 18... Qf7 $2 { [%eval 6.1] [%clk 0:00:33] } 19. Bxg5 { [%eval 5.87] [%clk 0:00:42] } 19... Rh8 $6 { [%eval 6.53] [%clk 0:00:30] } 20. Bxc6 { [%eval 6.46] [%clk 0:00:40] } 20... Qh5 $4 { [%eval 9.6] [%clk 0:00:28] } 21. Re1 $4 { [%eval 6.26] [%clk 0:00:33] } 21... Qh1+ $4 { [%eval 19.42] [%clk 0:00:26] } 22. Bxh1 { [%eval 18.8] [%clk 0:00:30] } 22... Rxh1+ { [%eval 20.47] [%clk 0:00:24] } 23. Kxh1 { [%eval 20.14] [%clk 0:00:30] } 23... Kg7 { [%eval 21.27] [%clk 0:00:18] } 24. Qb3 { [%eval 20.9] [%clk 0:00:29] } 24... Bd7 { [%eval 20.66] [%clk 0:00:16] } 25. e4 { [%eval 22.28] [%clk 0:00:28] } 25... Rh8+ { [%eval 24.18] [%clk 0:00:14] } 26. Kg2 { [%eval 23.24] [%clk 0:00:27] } 26... Rh3 { [%eval 30.39] [%clk 0:00:09] } 27. exf5 { [%eval 28.09] [%clk 0:00:25] } 27... Bxg3 $6 { [%eval #2] [%clk 0:00:08] } 28. fxg3 $6 { [%eval #5] [%clk 0:00:24] } 28... Bc6+ { [%eval #5] [%clk 0:00:06] } 29. d5 { [%eval #4] [%clk 0:00:22] } 29... Bxd5+ { [%eval #4] [%clk 0:00:05] } 30. Qxd5 { [%eval #3] [%clk 0:00:21] } 30... c6 { [%eval #2] [%clk 0:00:04] } 31. Qd7+ { [%eval #1] [%clk 0:00:21] } 31... Kf8 { [%eval #1] [%clk 0:00:02] } 32. Re8# { [%clk 0:00:21] } 1-0
```

That what is added:

```
[Date "????.??.??"]
[Round "?"]
```

**Comment by PedanticHacker** [comment]
First of all, there is no `chess.pgn.readgame()` function. There is, however, a `chess.pgn.read_game()` function (notice the underscore `_` in the function name).

Second of all, the PGN parser should be fixed. My best bet is to remove lines `1027` and `1028` in `chess/pgn.py`.

Line `1027` in `chess/pgn.py`: `game_headers["Date"] = "????.??.??"`
Line `1028` in `chess/pgn.py`: `game_headers["Round"] = "?"`

These lines are in the body of the `chess.pgn.scan_headers()` function in `chess/pgn.py`.

**Comment by PedanticHacker** [comment]
I have made a patch to fix this. I hope Niklas likes it and accepts it. Then wait for the new version of python-chess to be available on PyPI (probably version bump to 0.20.2 from 0.20.1). Then everyone is going to be happy. :)

**Comment by cja000** [comment]
Hi,

It seems to be a problem with lichess. It does not follow the PGN standard.
'Date' and 'Round' are mandatory. Those fields are part of the Seven Tag Roaster (STR):
http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8.1.1

Sorry PedanticHacker, but IMHO I wouldn't remove those two lines.

**Comment by PedanticHacker** [comment]
Then blame it on lichess.com, I guess.

**Comment by gbtami** [comment]
This issue has nothing to do with lichess. This is about how python-chess creates .pgn. If python-chess wants to conform to pgn standard **export** format, then it's output is OK and this issue can be closed as _invalid_ IMO.

**Comment by PedanticHacker** [comment]
Let's leave the decision to Niklas.

**Comment by niklasf** [comment]
I don't like the mandatory seven tag roster. Not all tags always make sense, especially in online chess, as can be seen in the lichess export. (Why add millions of `[Round "-"]` to one of the already largest PGN collections in the world? What is ` [Date ...]`?)

On the other hand I wanted to make it easy to produce conformant PGNs by default.

How about this?
* When reading existing PGNs, only put the headers that were actually present. If a default is required `game.headers.get("Date", "????.??.??") could be used. This would be a breaking change.
* But when creating a new game (`game = chess.pgn.Game()`) keep populating it with the default headers.
* As always, any headers can be manually deleted `del game.headers["Date"]`

**Comment by PedanticHacker** [comment]
> This would be a breaking change.

Why?

**Comment by niklasf** [comment]
Previously `game = chess.pgn.read_game(file); print(game.headers["White"])` was safe. You could rely on having a default value. Now it would raise `KeyError` if the header was not found.

**Comment by PedanticHacker** [comment]
@ChameleonRed, you can't change the PGN standard and remove the mandatory `Date` and `Round` tags from the roster. It looks bad when that data is not there and you get that stupid question marks as a result, but hey, that's the standard.

```
Standard: PGN
Authors: Interested readers of the Internet newsgroup rec.games.chess
Coordinator: Steven J. Edwards (send comments to sje@world.std.com)
```

Send this guy an e-mail asking him to remove `Date` and `Round` as mandatory tags in the PGN standard. Until then, python-chess and other libraries that parse PGN data will be forced to provide the seven tag roster, no matter what.

**Comment by cja000** [comment]
I think that it is a good idea to leave the tags of existing games as they are but for new games create the standard ones.
There could be a warning reading PGNs without the mandatory tags.

**Comment by Mk-Chan** [comment]
Just to inform you Steven Edwards is no longer with us. He passed away last year

**Comment by niklasf** [comment]
Done that in v0.21.0 (without runtime warnings).

**Comment by gbtami** [comment]
Let me describe why I think this change is problematic.
Let say I collected some .pgn from different sources to produce a big one. It can happen that some of them contains games with some missing tags from seven tag roster. There is no problem here, PGN import format spec enables this and chess.pgn.read_pgn() can read them. Now I create my big .pgn (concatenated games of .pgn files a read before) using chess.pgn.FileExporter() So far so good.

And here comes the surprise.  If I want to use chess.pgn.scan_offsets() on my just created big .pgn I got less game offsets then the number of games I have! This is because python-chess itself say: "The PGN standard requires each game to start with an Event tag. So does this scanner." But chess.pgn.FileExporter() doesn't know about this and produced non PGN export format file :(

If you think this is just one theoretical problem here is a link about how missing tags from seven tag roster caused problem: https://www.chess.com/forum/view/help-support/pgn-problem

**Comment by niklasf** [comment]
True. It was possible to run into trouble with that previously, but now it's possible even without manually tweaking/shuffling headers. I made a new issue #216.

**Comment by niklasf** [comment]
Trying to adjust my own private projects to keep producing valid 7 tag rosters made me reconsider this. It can be tricky.

So if you have good reasons to diverge from the spec you now have to do it explicitly again:
```
del game.headers["Date"]
del game.headers["Round"]
```

**Comment by ChameleonRed** [comment]
It is bad that you add headers since it is not excepted by user - not agree with you in this subject :)

**Comment by ddugovic** [comment]
As a user, I expect a chess program to export valid PGN (unless I specify otherwise, and there are good reasons to do so).

**Comment by gbtami** [comment]
Maybe a compromise can be to add a new keyword argument (strict_pgn_export_format=True) to chess.pgn.StringExporter() and chess.pgn.FileExporter() to let users explicitly ask for producing .pgn output without creating new empty seven tag roster tags.
