### ISSUE TITLE
Get square from mouse click

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#215]
I'm writing a chess GUI and I'm just implementing piece movement for the SVG chessboard powerred by python-chess. I am using Python 3.6.3, PyQt5 5.9.1 and this newest python-chess 0.21.

How can I get the file index & the rank index of a square on the SVG chessboard from a mouse click? Is that index data even possible to collect like this?

**Comment by niklasf** [comment]
Assuming the board is in the top left corner, not flipped and without coordinate margin (`board(..., flipped=False, coordinates=False)`), then `floor(x / width * 8)` is the file index.

**Comment by PedanticHacker** [comment]
I've done some testing and it turns out that if `coordinates=True`, this pushes the board from the top left corner exactly 40px on the `x` axis and exactly 40px on the `y` axis.

**Comment by PedanticHacker** [comment]
`floor(x / width * 8)`
Please elaborate on what is `x` and `width` here?
