### ISSUE TITLE
line breaking bad when writing pgn 

### ISSUE THREAD

**Issue by slm-git** [niklasf/python-chess#217]
When using the "columns" parameter of FileExporter/StringExporter the output can have the move number separated from the move text.

For example:

```
1. e4 e5 2. Nf3 Nc6 3. Bc4 d6 4. 
d3 Be7 5. Nc3 Nf6
```

rather than the preferable:

```
1. e4 e5 2. Nf3 Nc6 3. Bc4 d6 
4. d3 Be7 5. Nc3 Nf6
```

I believe this could be fixed in StringExporter -> visit_move()

```
    def visit_move(self, board, move):
        if self.variations or not self.variation_depth:
            # Write the move number.
            if board.turn == chess.WHITE:
                self.write_token(str(board.fullmove_number) + ". " + board.san(move) + " ")
            elif self.force_movenumber:
                self.write_token(str(board.fullmove_number) + "... " + board.san(move) + " ")
            else:
                # Write the SAN.
                self.write_token(board.san(move) + " ")

            self.force_movenumber = False
```

**Comment by niklasf** [comment]
This behavior is correct according to the PGN spec (the move numbers are seperate tokens). Here's an example game in export format: http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c2.3

**Comment by slm-git** [comment]
You are correct that this behavior isn't explicitly forbidden by the PGN standard. It's more of a simple common sense issue. 

But it's no problem for me to just fork and run the fix locally.

**Comment by niklasf** [comment]
Just to clarify: It's not only implicitly allowed, it's mandatory for byte equivalence in export format. That's why I think I should keep the behavior as is.

You can also override visit_move without maintaining a fork, if you like. Untested:

```python
class MyStringExporter(chess.pgn.StringExporter):
    def visit_move(self, board, move):
        pass # Your patch

pgn = game.accept(MyStringExporter())
```

**Comment by slm-git** [comment]
Ah, thanks. Overriding is better idea.

In rereading the PGN specification I see now that I misinterpreted the purpose of PGN export. It's really just for storage, it's not designed for readability to be the primary function.
