### ISSUE TITLE
Xboard end states

### ISSUE THREAD

**Issue by Mk-Chan** [niklasf/python-chess#218]
Xboard records the state of the program so we should provide the programmer some way to check whether the game has ended or not.

I know that one can access the `board` member and check for each end state (checkmate, 50-move, 75-move, threefold, stalemate, insufficient material). But in the case the engine chooses to resign or accept a draw (by agreement) `board` is not helpful. In this case it is simple, the Xboard class can provide a wrapper API to check for any kind of end state (the normal ones + draw and resign).

The problem I have is that through a contrived sequence, such a scenario can occur:
```
-> User calls go()
-> User waits for go() to end
-> Control returns to user
-> Engine offers draw
```
In such a case, how is it possible to inform the user that the engine has offered a draw? I don't think it's acceptable to expect the user to multi-thread to handle such a scenario by conditional waiting in one thread on a flag.

**Comment by Mk-Chan** [comment]
Unless it's illegal to offer draw during the opponent's turn?

**Comment by PedanticHacker** [comment]
Why is everyone talking about XBoard and/or Winboard? These are all CECP commands. What do these GUIs (XBoard and Winboard) have to do with CECP?

**Comment by Mk-Chan** [comment]
Because CECP is the protocol Xboard/Winboard used therefore it is AKA the Winboard/Xboard protocol check it out here: http://hgm.nubati.net/CECP.html, http://hgm.nubati.net/newspecs.html, https://en.wikipedia.org/wiki/Chess_engine#Interface_protocol, etc...

**Comment by niklasf** [comment]
If that's allowed (I have no idea) then it's indeed hard to fit into the request/response scheme. Perhaps another handler that's called from an engine thread? Unfortunately, like the info handler, it would make it easy for inexperienced users to run into data races. But I don't know what else we can do that's portable across Python 2 and  3 😞

@PedanticHacker All the XBoard vs. Winboard vs. CECP vs. "UCI is the future" add little to the dicussion of the issue at hand. Better make a new issue, if you've got a question.

**Comment by Mk-Chan** [comment]
The exact line that caused this confusion is this:

```
And at the end of a search the engine can print the move it has decided to play, possibly accompanied by a draw offer, or it can decide to terminate the game.
```

From http://hgm.nubati.net/CECP.html
So the terminate the game will be a `result xyz` and the draw offer will be `offer draw`.
The problem is since this occurs _after_ the best move, is not intrinsically synchronous (since the opponent can ignore it to decline) and the wording seems to imply that it can be sent anytime after it's own move but before it's next move, I don't even think an info handler kind of thing is good to handle it.

I'll ask HGM to clarify and hopefully some tips

**Comment by Mk-Chan** [comment]
It is in fact illegal to offer draw during the opponent's turn but engines are a somewhat special case because of the FIDE rules:
```
A player wishing to offer a draw shall do so after having made a move on the chessboard and before stopping his clock and starting the opponent’s clock. An offer at any other time during play is still valid but Article 12.6 must be considered. No conditions can be attached to the offer. In both cases the offer cannot be withdrawn and remains valid until the opponent accepts it, rejects it orally, rejects it by touching a piece with the intention of moving or capturing it, or the game is concluded in some other way.
```
Now obviously engines don't press clocks and GUIs are designed to press clocks the instant they receive a best move from the engine. It is clear engines can't be handled the same way as the FIDE rules dictate. I have sent a message to HGM asking for some advice on the matter.

**Comment by Mk-Chan** [comment]
So there doesn't seem to be anything else besides providing an async handler/variable for the user to check with another thread.

So an info-handler type thing? The control of how to handle it will have to be passed on to the user.
