### ISSUE TITLE
The SVG chessboard does not have any animation

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#219]
The current state of the SVG chessboard is that it's a static SVG image. It would be wonderful if someone would implement drag&drop or click&click behaviour for the pieces so that they can be moved on the SVG chessboard.

I was inspecting the SVG code that is produced by `chess.svg.board` function and found in Google Chrome an `SVGElement` property collection that holds this properties `onclick`, `ondrag`, `ondrop`. After clicking on the three dots in either `onclick: (...)`, `ondrag: (...)` or `ondrop: (...)` threw an
`[Exception: TypeError: Illegal invocation at SVGElement.remoteFunction (<anonymous>:2:14)]`, so I guess there is something to make animation possible in the SVG chessboard. Currently there is none and we get errors.

Anyone wanna take a stab at this?

**Comment by niklasf** [comment]
That's out of scope for python-chess. Even having `chess.svg` is a bit of a stretch, but I think it's generally lightweight/useful enough. Custom attributes could be added by using one of Python's XML tree libraries.
