### ISSUE TITLE
uci stop() issue

### ISSUE THREAD

**Issue by Ghotrix** [niklasf/python-chess#22]
Engine would not stop() in such scenario:
engine.go(async_callback=True) with finite depth or time.
engine.stop() hanging forever...

**Comment by niklasf** [comment]
Thanks for reporting this. There are two bugs here:

 1. `engine.stop()` does not work, so it still takes what ever finite time was set.
 2. It also hangs forever.

With a quick test I could only reproduce the first one.

Can you provide some more concrete code to help reproduce the second? Are you using Stockfish?

**Comment by Ghotrix** [comment]
Oh.. I missed one detail. Hope next snippet of code will clarify this.

```python
#!/usr/bin/env python3

from chess import uci, Board
import time

_wtime = 300000
_btime = 300000

engine = uci.popen_engine('/usr/bin/stockfish')
engine.position(Board())
command = engine.go(wtime=_wtime, btime=_btime, async_callback=True)
start = time.time()
command.result()
print('{} seconds'.format(time.time() - start))
#will finish in sensible time, approx. 11 seconds for me

engine.ucinewgame()
engine.position(Board())
command = engine.go(ponder=True, wtime=_wtime, btime=_btime, async_callback=True)
start = time.time()
#assuming pondermiss scenario when we want to stop here
engine.stop()
print('{} seconds'.format(time.time() - start))
```

with ```ponder=True``` ```command.result()``` and ```engine.ponderhit()``` will also hang

**Comment by niklasf** [comment]
The concrete code helps a lot.

I fixed pondering mode. `engine.go(ponder=True)` no longer blocks forever and no longer has a result. Pondering can be stopped using `engine.stop()` or switched to normal search using `engine.ponderhit()`. The best move will be the result of the `stop` or `ponderhit` command respectively.

Remaining issue: *There is still no sensible way to stop a finite async normal search*.

**Comment by Ghotrix** [comment]
Does ```ponderhit()``` suppose to return? According to UCI documentation it should only switch search to normal mode.

**Comment by niklasf** [comment]
Yeah, the documentation needed to be updated. Pushed it now.

**Comment by niklasf** [comment]
By the way: I don't really like the *may-return-if-this-or-that-but-not-if*-stuff. It may be sensible if one knows the UCI protocol and just uses it in non-async mode. But maybe I should consider redesigning the async stuff.

**Comment by Ghotrix** [comment]
No, I mean that documentation on uci part of python-chess is good according to [uci protocol](http://wbec-ridderkerk.nl/html/UCIProtocol.html). ```ponderhit()``` should be changed :)

**Comment by niklasf** [comment]
Ah, I see. That was intended, though.

The point of this is: `go ponder` searches in the background. `engine.go(ponder=True)` returns and finishes immediately and has no result. Async or not.

Later `ponderhit` is equivalent to `go with the correct position` and the only place to return a result, really.

**Comment by LocutusOfPenguin** [comment]
Hi. I downloaded the latest version of your lib to my fork (picochess).
But for me, i cant stop the engine when i call it with "go( time.uci() )".
=> It waits until the time is over. For example go(10secs) & send "stop" after 2sec, doesn't stop the engine => engine.stop() using 8secs then.

With "search forever", there isn't such problem to stop (using it in analyse mode).

Do i do something wrong?

**Comment by niklasf** [comment]
Hi. You are doing nothing wrong. This is exactly the remaining problem here.

At the moment commands are queued and your `stop` will only get executed after `go` already completed.

This has been pending for a while, because it will be some work to rewrite the uci module with this in mind.

At the moment picochess has its own UCI handling. Are you trying to replace that? If so I'd be intrested to see what an ideal UCI API would look like from picochess's point of view and see if that would be useful in general.

**Comment by LocutusOfPenguin** [comment]
thanks for QUICK answering.

I like what you did!

I'm the "lead" of development with "analyse mode", and so on. picochess made some big progress in the newest past (esp. cause of your lib, thanks again).
Therefore i used your new V0.8 api, with uci (changed it towards using yours), and i gonna use more (like ponderhit). You can see abit of my plans at #99 picochess.
Maybe my implementation is not the best, but its working so far.
I will ask shiv to join this discussion.

So, we already using yr V0.8 UCI component.
I also send you a skype request (maybe its not your account, maybe, thats not the best way, but we picochess developers using it - quick&easy).

**Comment by LocutusOfPenguin** [comment]
today i did the following (play a game with a2-a4 ; a7-a5 in analysis mode.
The system is with the infohandler system (firing events on Best_Move for example)

1) after enter a2-a4, i send a STOP , => no events (ok!)
2) Move (a4) done on system, and i send "new_game", "position(startpos moves a4)", and "go(ponder)" to engine
3) Engine sends me all this Handler events... (saying pls play "e5").... => ok!
4) after entering "a7-a5", again sending "stop" but now, he has a "e5" bestmove to send me , hmm
5) like 2) ... do Move(a5) send "new game", pos (moves a4 a5) and go ponder to engine
6) now the handler sends out a "e5" move, even i setup a different position with 5 before).

Complex explain? Sorry, didnt wanted to post the log here. Anyway my Question is:
Shouldn't be the system be reset after i send a new position to it?? I tried also with/without "newgame", no difference.
For me, it still wants to send out something old afterwards. Can you understand? Do i miss something?

**Comment by niklasf** [comment]
Hi. A quick update: Currently working on that rewrite. `ucinewgame` just tells the engine to reset its hashtable and has no other effect on search status.

**Comment by LocutusOfPenguin** [comment]
Hello, how far is the "rewrite"? Can we help?

**Comment by niklasf** [comment]
Hi.

Sorry this is taking so long.  I'll get back to it soon. So far I've implemented some basics using `asyncio`: https://gist.github.com/niklasf/2ad19e725e2c0d77d88f. Still some major TODOs left, before it is even usable.

python-chess v0.9.0 comes with some extra debugging assertions. Can you test again if we get any extra information about the errors?

Best,
Niklas

**Comment by niklasf** [comment]
Hi,

with commit  #1000 this is finally fixed. Not using `asyncio` for now, so the API looks very similar.

From the changelog:

Most notably in async mode multiple commands can be executed at the same time (e.g. `go infinite` and then `stop` or `go ponder` and then `ponderhit`).

`go infinite` and `go ponder` will now wait for a result, i.e. you may have to call `stop` or `ponderhit` from a different thread or run the commands asynchronously.

`stop` and `ponderhit` no longer have a result.

Best,
Niklas
