### ISSUE TITLE
pip install python-chess[stockfish]

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#221]
What does this do? I don’t understand this command.

**Comment by PedanticHacker** [comment]
Does this installs the Stockfish engine for me? So where is Stockfish engine installed then?

**Comment by niklasf** [comment]
If you literally found `pip install python-chess[stockfish]` somewhere that's a mistake.

`pip install python-chess[engine]` will install python-chess with engine support (i.e. with the `chess.uci` and `chess.xboard` modules). It's an optional feature.

**Comment by PedanticHacker** [comment]
Ah, yes. Silly me. Thanks.
