### ISSUE TITLE
The square does not change color when King in check

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#222]
```
import chess
import chess.svg
import IPython

chessboard = chess.Board()
chessboard.push_san("e4")
chessboard.push_san("f5")
chessboard.push_san("Qh5")

chessboardSVG = chess.svg.board(board=chessboard)
IPython.display.SVG(chessboardSVG)
```

I have played around in Jupyter Notebook and did a test. I wanted to know if the King's square color changes if the King is in check. The code above puts Black's King in check. So, 1. e4 f5 2. Qh5+.

The square does not change color, even though the SVG has this inline CSS:
```
<style>
  .check {
    fill: url(#check_gradient);
  }
</style>
```

Is that a bug or am I missing something?

**Comment by niklasf** [comment]
Using it like that, you have to manually set the check square:

```python
chess.svg.board(board=chessboard, check=chess.E8)
```

If you type just
```python
chessboard
```
in your console, this will be done automatically, depending on the chess variant.

**Comment by PedanticHacker** [comment]
```
import chess
import chess.svg
import IPython

chessboard = chess.Board()
chessboard.push_san("e4")
chessboard.push_san("f5")
chessboard.push_san("Qh5")

chessboardSVG = chess.svg.board(board=chessboard, check=chessboard)
IPython.display.SVG(chessboardSVG)
```

If I manually set the check square by `chess.svg.board(board=chessboard, check=chess.E8)`, it works. However, the upper code does not work. I was guessing you meant `check=chessboard` when you said "if you type just `chessboard`". Please correct me if I'm wrong.

**Comment by niklasf** [comment]
No, I really meant exactly what I said:

![image](https://user-images.githubusercontent.com/402777/32891632-b4299d84-cad3-11e7-8d8b-4f352da4eb75.png)

**Comment by PedanticHacker** [comment]
Ah! Now I get it. Thanks. :)

**Comment by niklasf** [comment]
Sure thing :)

**Comment by PedanticHacker** [comment]
I'm gonna take a stab at hacking the SVG code to make it interactive. I'm gonna make some `onclick` properties and `ondrag` properties and stuff like that. If I manage to make it work, I'll give you the code.
