### ISSUE TITLE
How to apply the gradient color to the checked King square?

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#223]
```python
#! /usr/bin/env python

"""
This module is the execution point of the chess GUI application
named Chess Titan.
"""

import sys

import chess
import chess.svg

from PyQt5.QtCore import pyqtSlot, Qt
from PyQt5.QtSvg import QSvgWidget
from PyQt5.QtWidgets import QApplication, QWidget


class MainWindow(QWidget):
    """
    Create a surface for the chessboard.
    """
    def __init__(self):
        """
        Initialize the chessboard.
        """
        super().__init__()

        self.setWindowTitle("Chess GUI")
        self.setGeometry(300, 300, 800, 800)

        self.widgetSvg = QSvgWidget(parent=self)
        self.widgetSvg.setGeometry(10, 10, 600, 600)

        self.boardSize = min(self.widgetSvg.width(),
                             self.widgetSvg.height())
        self.coordinates = True
        self.margin = 0.05 * self.boardSize if self.coordinates else 0
        self.squareSize = (self.boardSize - 2 * self.margin) / 8.0

        self.board = chess.Board()
        self.pieceToMove = [None, None]

    @pyqtSlot(QWidget)
    def mousePressEvent(self, event):
        """
        Handle left mouse clicks and enable moving chess pieces by
        clicking on a chess piece and then the target square.

        Moves must be made according to the rules of chess because
        illegal moves are suppressed.
        """
        if event.x() <= self.boardSize and event.y() <= self.boardSize:
            if event.buttons() == Qt.LeftButton:
                if self.margin < event.x() < self.boardSize - self.margin and self.margin < event.y() < self.boardSize - self.margin:
                    file = int((event.x() - self.margin) / self.squareSize)
                    rank = 7 - int((event.y() - self.margin) / self.squareSize)
                    square = chess.square(file, rank)
                    piece = self.board.piece_at(square)
                    coordinates = "{}{}".format(chr(file + 97), str(rank + 1))
                    if self.pieceToMove[0] is not None:
                        move = chess.Move.from_uci("{}{}".format(self.pieceToMove[1], coordinates))
                        if move in self.board.legal_moves:
                            self.board.push(move)
                            if self.board.is_check():
                                print("Check!")
                        piece = None
                        coordinates = None
                    self.pieceToMove = [piece, coordinates]
                else:
                    # Envoke the paint event.
                    self.update()
        else:
            QWidget.mousePressEvent(self, event)

    @pyqtSlot(QWidget)
    def paintEvent(self, event):
        """
        Draw a chessboard with the starting position and then redraw
        it for every new move.
        """
        self.boardSvg = chess.svg.board(board=self.board,
                                        size=self.boardSize).encode("UTF-8")
        self.widgetSvg.load(self.boardSvg)


if __name__ == "__main__":
    chessTitan = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(chessTitan.exec_())
```

This code creates an SVG chessboard in an application window. It allows the pieces to be moved according to the rules of chess. Use the left mouse button to click on a piece and again the left mouse button to click on the target square. If the move if valid, the piece will move to that square.

Currently, if there is check, I print out "Check!". How can I instead of printing "Check!" make that gradient color on the square that the checked King is on (either the White or the Black King)?

I know that the `chess.svg.board()` function has this `check` argument which marks a given square, say `chess.E8`, as being in check (only logical if a King is on that square and is really in check). But now I wonder whether this `check` argument can be somehow applied later? Is there a `mark_as_check` or something like that to be used after the fact for a given square? I've looked and haven't found anything. So, how can I implement this?

**Comment by PedanticHacker** [comment]
An answer would be nice before closing this issue.

**Comment by niklasf** [comment]
Qt's SVG renderer supports only a subset of the SVG spec (SVG Tiny). A small change to python-chess should make it work.

**Comment by PedanticHacker** [comment]
The one above? Can’t seem to find it. Where is the change?

**Comment by niklasf** [comment]
Nvm, I was one step ahead.

1. You can use `self.boardSvg = self.board._repr_svg_()` or use a customized version of its implementation: https://github.com/niklasf/python-chess/blob/fc696a4ef219f9342f5689141501c19d20b794a7/chess/__init__.py#L3161-L3165
2. Then you would have noticed that the check gradient still does not work. But it does after the patch I meant: fc696a4ef219f9342f5689141501c19d20b794a7

**Comment by PedanticHacker** [comment]
Can you make a new version bump? 0.21.2 perhaps? This fix is very important. Also, the function name _repr_svg_() looks very ugly. Can you rename it to repr_svg()?

**Comment by dsblank** [comment]
The name `_repr_svg_()` is specified by IPython so that the instance will automatically render in a Jupyter Notebook. See, for example: https://jupyter.brynmawr.edu/services/public/dblank/CS371%20Cognitive%20Science/2016-Fall/Programming%20a%20Chess%20Player.ipynb

**Comment by niklasf** [comment]
Combined with some further changes to arrows (draw them manually), `chess.svg` should now be fully SVG Tiny compatible. I released that as v0.21.2.

**Comment by PedanticHacker** [comment]
Thank you! :)

**Comment by PedanticHacker** [comment]
This is not related to python-chess per se, but I want to know why is my code so CPU hungry. After some moves, the CPU goes crazy on me. The CPU gets hot really fast. I know that this is because that for every move made the whole board needs to be redrawn. I made this quick hack just to make the chessboard interactive. Now I want to optimize it and I need a little bit of your help.

Is there any other solution not to invoke the paint event everytime a new move is made and redraw the whole board on the paint event call?

**Comment by niklasf** [comment]
You probably shouldn't be using paintEvent like that. QSvgWidget can draw itself just fine. Try replacing

```python
    @pyqtSlot(QWidget)
    def paintEvent(self, event):
```

with

```python
    def updateBoard(self):
```

And call `self.updateBoard()` instead of `self.update()`. Also call `self.updateBoard()` once at the end of `__init__`.

**Comment by PedanticHacker** [comment]
Niklas, you are a genius! I've fixed my code according to your instructions and now the CPU fan is silent as a mouse. :)

I am observing that the gradient color for the check square is not so distinguishable if the King is on the black square. Can you make the color of the black squares a different color than it is? I think that the forest green color (hex value #228B22) would be best.

**Comment by PedanticHacker** [comment]
Niklas, you are a genius! I've fixed my code according to your instructions and now the CPU fan is silent as a mouse. :)

**Comment by barot66** [comment]
in the below code if I want to drow Arrow in the bord what are the changes required?

    def _repr_svg_(self): 
         import chess.svg 
         lastmove = self.peek() if self.move_stack else None 
         check = self.king(self.turn) if self.is_check() else None 
         return chess.svg.board(board=self, lastmove=lastmove, check=check, size=400)

**Comment by barot66** [comment]
@niklasf @PedanticHacker @jnavila 

in the below code if I want to drow Arrow in the bord what are the changes required?


        self.boardSize = min(self.widgetSvg.width(),self.widgetSvg.height())
        coordinates = "{}{}".format(chr(file + 97), str(rank + 1))
        lastmove = self.board.peek() if self.board.move_stack else None
        check = self.board.king(self.board.turn) if self.board.is_check() else None
        self.chessboardSvg = chess.svg.board(self.board, size = self.boardSize, lastmove=lastmove,
                                             check=check, coordinates = self.coordinates).encode("UTF-8")
        self.drawBoardSvg=self.widgetSvg.load(self.chessboardSvg)
