### ISSUE TITLE
MultiPV scores

### ISSUE THREAD

**Issue by jackalsh** [niklasf/python-chess#23]
When using MultiPV score for engine, can't get scores of those lines, but only variations themselves.

**Comment by niklasf** [comment]
Thanks for reporting this, @jackalsh! This wasn't clear to me from the UCI specification, but all engines seam to provide scores relative to the current pv.

The new way to get the score of the best move is:
```
with info_handler as info:
    if 1 in info["score"]:
        cp = info["score"][1].cp
```
