### ISSUE TITLE
Get captured pieces

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#231]
Is there a (simple) way in python-chess to get captured pieces? I want to display an SVG image for each captured piece.

**Comment by Mk-Chan** [comment]
For every piece type(pawn,knight...queen) just popcount the bitboard(in BaseBoard) and subtract from the maximum number of that piece type.

For variants that modify the number of pieces you'll just have to count how many of each piece.

**Comment by PedanticHacker** [comment]
Thanks. 😉
