### ISSUE TITLE
`arrows` argument name is not correct

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#232]
Having an `arrows` argument of the `chess.svg.board()` function is not correct, because we can draw a circle with the same argument (and a circle is not an arrow). I therefore suggest we rename this argument to `markings` and accommodate other things.

**Comment by niklasf** [comment]
I prefer `arrows` anyway.

**Comment by PedanticHacker** [comment]
Maybe `indicators`? 🤔
