### ISSUE TITLE
No notification of empty game

### ISSUE THREAD

**Issue by igoralmeida** [niklasf/python-chess#243]
I'm trying to crawl a PGN file an ran into an interesting issue: empty games are silently ignored! This was a bit surprising when adding the games to a database (sqlite3) because I was told the game already existed :)

Here's a clean file:
```
[Event "freechess.org"]
[Site "-"]
[Date "2017.4.14"]
[Round "?"]
[White "Krakonkas"]
[Black "GuestMPZQ (Player)"]
[Result "*"]
[PlyCount "0"]



[Event "freechess.org"]
[Site "-"]
[Date "2017.4.16"]
[Round "?"]
[White "GuestWVVL (Player)"]
[Black "GuestTNMT"]
[Result "1-0"]
[PlyCount "32"]

1.e4 e5 2.Nf3 Nf6 3.Nxe5 Nxe4 4.Nxf7 Kxf7 5.Qf3+ Nf6 6.Bc4+ Ke8 7.O-O d6 8.d3
Nc6 9.Bg5 Be7 10.Bxf6 Ne5 11.Bb5+ c6 12.Qh5+ g6 13.Qg5 Nf7 14.Re1 Nxg5 15.Bxe7
Kf7 16.Bxd8 c5 1-0
```

So doing something like this
```
In [12]: pgn=open('clean.pgn')

In [13]: g=chess.pgn.read_game(pgn)

In [14]: g
Out[14]: <chess.pgn.Game at 0x7efcb6b891d0>

In [15]: print(g)
[Event "freechess.org"]
[Site "-"]
[Date "2017.4.16"]
[Round "?"]
[White "GuestWVVL (Player)"]
[Black "GuestTNMT"]
[Result "1-0"]
[PlyCount "32"]

1. e4 e5 2. Nf3 Nf6 3. Nxe5 Nxe4 4. Nxf7 Kxf7 5. Qf3+ Nf6 6. Bc4+ Ke8 7. O-O d6 8. d3 Nc6 9. Bg5 Be7 10. Bxf6 Ne5 11. Bb5+ c6 12. Qh5+ g6 13. Qg5 Nf7 14. Re1 Nxg5 15. Bxe7 Kf7 16. Bxd8 c5 1-0
```

So when going through what `scan_offsets()` gives me, I will effectively get the same game object twice. If I could get some sort of notification that `read_game` skipped an incomplete/invalid game, the code could just continue with the next offset. If not, I will not be able to easily tell if I'm really trying to add an existing game or just that I got one (or more) invalid games in between. Any suggestions?

**Comment by niklasf** [comment]
Intresting, thanks for reporting. I attempted to fix this, but it will require some further testing before I can release it. Mostly to ensure it does not regress on other (invalid) games.

**Comment by igoralmeida** [comment]
Tested, works fine with the many empty games in my pgn file. I noticed it adds a line with a single `*` where the moves would be, but that's not a problem.

Thanks a lot!

**Comment by niklasf** [comment]
Sounds good. `*` is the proper way to indicate unkown/unterminated outcome of the game. (That entirely empty line would not be strictly valid.)

**Comment by igoralmeida** [comment]
I see, thanks again.
