### ISSUE TITLE
 Question: "invert" colors

### ISSUE THREAD

**Issue by stevexyz** [niklasf/python-chess#245]
I've the need to analyze the board just with white perspective, meaning that when I have a board with black to move I should "invert it" in order that all the reasoning will be made as if it was white to move. After that I have addionally to "invert" also the move found....

There is a way - or anyway - what is the best way to do it in python-chess?

Hope I was clear enough else please ask for clarification.

Thank you!

**Comment by Mk-Chan** [comment]
One way I can think of to accomplish that is get the FEN of the position, flip all the cases for each piece's letter (p <-> P, k <-> K ... ), flip the castling rights, the enpassant square and the side to move then reparse it.

If you want to do it efficiently you'd probably have to `bitswap` all piece bitboards, color bitboards and occupancy bitboard and then swap the color bitboards. Flip the `turn`, `castling_rights`, `ep_square`, and I'm not exactly sure what the `promoted` member is for. There may be even more depending on the internals but if you don't want to dabble in it, just get the standard FEN, flip that and reparse it like in the first way.

**Comment by stevexyz** [comment]
In the meantime I wrote this function that seems to work:
```python
def fen_invert_position( fenstring ):
    v = (fenstring.swapcase()).split()
    a = v[0].split("/")
    return a[7]+"/"+a[6]+"/"+a[5]+"/"+a[4]+"/"+a[3]+"/"+a[2]+"/"+a[1]+"/"+a[0] +" "+ \
           ( "b" if v[1].upper=="w" else "w" ) +" "+ \
           v[2] +" "+ \
           ( "-" if v[3]=="-" else (v[3][0]+str(8-int(v[3][1]))) )
```

**Comment by niklasf** [comment]
Looks like a useful operation to have in general. I implemented it as `mirror()`, so you can now do:

```python
mirrored = board.mirror()
```

Your FEN based implementation is also fine. Theres a small problem with en-passant:
```
original: r1bq1r2/pp2n3/4N2k/3pPppP/1b1n2Q1/2N5/PP3PP1/R1B1K2R w KQ g6

actual:   r1b1k2r/pp3pp1/2n5/1B1N2q1/3PpPPp/4n2K/PP2N3/R1BQ1R2 b kq G2
expected: r1b1k2r/pp3pp1/2n5/1B1N2q1/3PpPPp/4n2K/PP2N3/R1BQ1R2 b kq g3
```

**Comment by niklasf** [comment]
@Mk-Chan: `promoted` is also a bitboard. It distinguishes pieces that were promoted from pawns. Strictly speaking that's irrelevant in standard chess, although it *could* be intresting to know sometimes. It's mostly for variants (like Crazyhouse) where it can be important.

**Comment by Mk-Chan** [comment]
I see, thanks! Also I really have no idea on variants besides FRC ;p don't mind me

**Comment by PedanticHacker** [comment]
This is a nice feature. Maybe a new version bump? 0.22.1 perhaps?

**Comment by stevexyz** [comment]
Good for the new function! 

In the meantime (before seeing your implementation) just for the records I've corrected the previous function and made it a bit more "pythonic": :)
```python
def fen_invert_position(fenstring):
    v = fenstring.swapcase().split()
    return '/'.join((v[0].split("/"))[::-1]) + " " 
           + ("b" if v[1].upper()=="W" else "w") + " " 
           + v[2] + " " 
           + ("-" if v[3]=="-" else v[3][0].lower()+str(9-int(v[3][1])))
```
