### ISSUE TITLE
Slow board tested with line_profiler under 100 games of 10e6

### ISSUE THREAD

**Issue by ChameleonRed** [niklasf/python-chess#246]
Full report:
[slow_performance_board_fen_scan.txt](https://github.com/niklasf/python-chess/files/1507212/slow_performance_board_fen_scan.txt)

I tested chess.pgn and found performance problems.  First seek position is slow - I replaced it and speed up 10x times at least I am want to process https://database.lichess.org/.

Second I processed some game and want analyze them but still code is slow since this.

Let it be my testing code:

```
if __name__ == '__main__':
    profile_lines = True
    if profile_lines:
        profiler = LineProfiler()
        profiler.add_module(sys.modules[__name__])
        profiler.add_module(sys.modules['chess.pgn'])
        profiler.add_module(sys.modules['chess'])
        profiler.enable_by_count()
    main()
    if profile_lines:
        profiler.print_stats(stripzeros=True)
```

Test is result is such (100 of 10e6):

```
File: C:/Users/Cezary Wagner/PycharmProjects/chess-lichess-eval-parse/sandbox/create_tree/s01_create_tree.py
Function: position_from_game at line 146

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   146                                           def position_from_game(game):
   147      6691     23592517   3526.0     57.6      board = game.board()
   148      6691     17332967   2590.5     42.3      fen = board.fen()
   149      6691        24184      3.6      0.1      position = fen.rsplit(' ', 2)[0]
   150      6691         5603      0.8      0.0      return position

Total time: 28.1081 s
```

It is about 68% of main.

```
100      7576383  75763.8     11.5              game = chess.pgn.read_game(pgn)
200      6690     41028422   6132.8     62.4                      position_str = position_from_game(node)

```

**Comment by ChameleonRed** [comment]
Can you improve performance of pgn scan?

**Comment by ChameleonRed** [comment]
I am prepared some new API and looks I achieve speed records - I done some assumptions and I am not doing moves calculation. Whatever current speed without parallel processing is very good.

41150.72 200001 616709590 PerfectPgnGameParser
44171.59 200001 616709590 PerfectPgnGameOffsetsLineParser

41k/s and 44k/s is game extracted speed over 2000001 and the last is file progress.

In chess.pgn it is slower - not matter since board processing is about 22 games/s after parallel I can get 160 games/s == 12h per 1M. I think that it can be 10-100x faster with caching maybe 10kx faster. I will try it soon. Major bottleneck is enumerating positions and it is the hardest place to optimize. as you seen pgn scan is many times faster with PerfectPgnGameParser or PerfectPgnGameOffsetsLineParser. In addition there is accurate progress measurement.

It will be very nice if board/position will be faster.

**Comment by niklasf** [comment]
Impressive results, and even more so if it also works on abitrary streams. (Definitely feel free to share the code 😄).

What operations on board/position do you mean specifically?

**Comment by ChameleonRed** [comment]
You have complete report on top of this thread for board/position - you can see lines of your code and my callers.

Results was very good I little improve it about 10% I need 33s per 900k games to transform it into binary format which speed up to 5.5s per 900k for caching. Now I am testing board caching since it is real bottleneck.
