### ISSUE TITLE
Travis stalling tests

### ISSUE THREAD

**Issue by Mk-Chan** [niklasf/python-chess#249]
Occasionally Travis CI stalls some tests after completing the following script line successfully:
```
if [[ $PERFT -ne 1 ]]; then coverage run --source chess test.py -vv; fi
```

It fails to retrieve the exit code which should be printed as follows:
```
The command "if [[ $PERFT -ne 1 ]]; then coverage run --source chess test.py -vv; fi" exited with 0.
```

It says instead:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

This indicates to me that some test case did not actually `TearDown` properly or something. Since we tear down the Stockfish and Crafty tests with `terminate` which probably translates to SIGTERM, maybe we should instead SIGKILL it if SIGTERM fails for 5 seconds. Or even just SIGKILL directly

**Comment by Mk-Chan** [comment]
I think we can test this by adding a print or something before we wait for the `is_terminated` condition variable and after it terminates at the lowest level(in engine.py) then push a bunch of spurious commits to a temporary branch. I haven't been able to reproduce it on my machine either so it's a bit hard to test. What do you think?

**Comment by niklasf** [comment]
Restarted tests a couple of times after https://github.com/niklasf/python-chess/compare/7b47775be7590bb61405a51b2e1cae8d89ec9ccf...5eada1c799efda05b049bf2f309a490368443a10. So far I haven't seen further stalls.

**Comment by niklasf** [comment]
Just seen it again, so it's only rarer at best.

**Comment by niklasf** [comment]
It's been a while since the last stalled test, but it just happened again: https://travis-ci.org/niklasf/python-chess/jobs/419535950

Now that the tests are split we can see that it was hanging after `coverage run --source chess --append -m doctest README.rst`.

**Comment by Mk-Chan** [comment]
I don't get it, the doctest searches for the
```
>>> <python stuff>
<output>
```
lines and makes sure the <output> matches the actual output for <python stuff> right? Why would that be an intermittent bug?

**Comment by niklasf** [comment]
No idea. Maybe it's `coveralls`, so the next command, that's hanging. Added an `echo` in between, so we will definitely know if the doctests exited.

**Comment by niklasf** [comment]
https://travis-ci.org/niklasf/python-chess/jobs/462928149

**Comment by niklasf** [comment]
https://travis-ci.org/niklasf/python-chess/jobs/465300963 (UciEngineTestCase)

**Comment by Mk-Chan** [comment]
You think this might be an issue with the callback mechanism?

**Comment by niklasf** [comment]
That or somehow one of the background threads is not exiting (or both). But I don't see how that's possible.

**Comment by niklasf** [comment]
https://travis-ci.org/niklasf/python-chess/jobs/475737560 (XboardEngineTestCase): [log.txt](https://github.com/niklasf/python-chess/files/2729686/log.txt)

**Comment by Mk-Chan** [comment]
So as far as we know it seems to fail in one of the engine test cases each time doesn't it?

**Comment by niklasf** [comment]
Yep. Both UCI and XBoard. That's good to know. I'll keep adding links here, whenever I see a stalled test. But for now I have little motivation to dig deeper with the asyncio based engine API in the pipeline ...
