### ISSUE TITLE
How to use pondering

### ISSUE THREAD

**Issue by ThePlasmaRailgun** [niklasf/python-chess#254]
I am currently writing a terminal based chess program using Stockfish as my UCI engine, and I was wondering how I would be able to utilize the pondering function of Stockfish. 
To my understanding, the commands you'd send for a normal ponder through UCI would be:
```python
#engine is engine, main board is board
engine.position(board)
move = <get engine move tuple>
board.push(move[0]) #Push the engine's move
board.push(move[1]) #Push the ponder move so we can update position and let the engine ponder
engine.position(board) #Give the engine its ponder move and set it to ponder
engine.go(ponder=True, <other options>)
if (<player moved ponder>):
    engine.ponderhit()
else:
    board.pop()
    board.push(<player's move>)
    engine.stop()
    engine.position(board)
    engine.go(<options>)
```
Would this be correct?
Thanks for the help. Your module has been absolutely invaluable to me.

**Comment by niklasf** [comment]
That looks exactly right. Pretty verbose, but that's because it's directly following the UCI protocol without abstraction.

**Comment by ThePlasmaRailgun** [comment]
Thank you so much for your help and this awesome library!
