### ISSUE TITLE
Don't throw error on unknown variant

### ISSUE THREAD

**Issue by Akababa** [niklasf/python-chess#255]
For example, when it encounters a [FICS wild](http://www.freechess.org/Help/HelpFiles/wild.html) variant tag it gives up and throws an error on every move, when in reality all of those variants are legal chess positions (minus castling rules). I can PR this if the owner agrees that it should attempt to read the file as a normal chess game instead (and maybe warning to stderr)

**Comment by niklasf** [comment]
Perhaps we can specifically accept Wilds without any warning? (Provided the PGNs always have an appropriate FEN tag.)

**Comment by Akababa** [comment]
Yeah that would work, but I also think for unrecognized variants with a FEN it can just default to normal chess. As it stands now I have to preprocess pgns or edit python-chess source. Thoughts?

**Comment by ddugovic** [comment]
@Akababa Python-chess does move validation, which for unrecognized variants would be different.

**Comment by Akababa** [comment]
Actually for the majority of FICS wild only the initial position is different, hence my suggestion to default to normal chess rules.

**Comment by ddugovic** [comment]
Right, and I agree with Niklas that maybe for "wild" variants we may accept them without a warning?

**Comment by Akababa** [comment]
Pardon my ignorance but here's what I think [read_game ](https://github.com/niklasf/python-chess/blob/master/chess/pgn.py#L771)does now:

- on unknown header, raise ValueError without parsing the rest of the headers, and try to start with a normal chess.Board

Here's what I think it should do:

- on unknown header, raise the error/warning but don't modify anything

Is it right?

**Comment by niklasf** [comment]
Wilds are now accepted without warning.

Other than that the default is to log *(not raise)* an error and add it to `game.errors`. Parsing continues. That behavior can be overriden like so:

```python
class SilentGameModelCreator(chess.pgn.GameModelCreator):
    def handle_error(self, error):
        pass # Ignore errors

game = chess.pgn.read_game(Visitor=SilentGameModelCreator)
```

Or the log can be disabled (usually not recommended):

```python
import logging

logging.getLogger("chess.pgn").setLevel(logging.CRITICAL)
```
