### ISSUE TITLE
Public API for "engine status"

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#256]
Hi,

im refering to this:
https://github.com/niklasf/python-chess/commit/14aed3aad48468a4527bb9df1b19dc755f32f117
and
https://github.com/niklasf/python-chess/issues/164

To prevent thread problems i want to have an api to test the status of engines from my program.
Right now i use something like "is_waiting", "is_pondering", "is_thinking", and test for vars inside your lib. That is not very safe.

Also i see y have several *.wait() functions , like "search started" see your commit. Can this be documented (at least) or also put inside an api (in case these functions are for internal usage).

Jürgen

**Comment by Mk-Chan** [comment]
I agree, there should be a public API for querying the engine states. Something like

while engine.get_state() == THINKING:
    Wait()

**Comment by niklasf** [comment]
Mhh, I am not a fan. Doing

```
while engine.get_state() == THINKING:
    Wait()
assert engine.get_state() != THINKING
```

on a thread is not even guaranteed to pass the assertion in all cases. Another thread may have started a second search inbetween.

Perhaps we can come up with a more misuse resistant API.

**Comment by niklasf** [comment]
I wasn't even referring to that. The same thing applies to:

```
engine.wait_till_state(WAITING)
assert engine.get_state() == WAITING
```

Without synchronization anything can be scheduled in between those two lines.

*Maybe* achieving something like this is possible.

```
with engine.wait_till_state(WAITING):
    assert engine.get_state() == WAITING
```

**Comment by Mk-Chan** [comment]
I see what you mean, but we aren't handling multithreaded controlling of the same engine instance in any case are we?

**Comment by Mk-Chan** [comment]
What I want to understand is how something can come in between (speculative)
```
 engine.wait_till(WAITING)
 assert engine.is_stopped()
```
When two threads are not supposed to be controlling the same `engine` object

**Comment by brianprichardson** [comment]
It looks like the UCI protocol does not guarantee the engine is "stopped" ("stop" says as soon as possible, which is not really defined), unless you issue a "quit" to terminate the engine entirely.  CECP (Xboard/Winboard) has more appropriate commands.  Incidentally, there is another "pico" chess
[http://nanochess.org/chess3.html#pico](url)

What are you trying to do?

**Comment by LocutusOfPenguin** [comment]
Thats "Toledo picochess" ...a mixture of Manik (his toledo sword) & Me (pico chess) :-)

**Comment by Mk-Chan** [comment]
@brianprichardson The engine is supposed to stop after `bestmove x [ponder y]`. It is not supposed to start pondering by itself.

**Comment by brianprichardson** [comment]
I stand corrected about UCI.
Thanks.

**Comment by Mk-Chan** [comment]
Any thoughts on the above @niklasf ?

**Comment by niklasf** [comment]
Sorry, nothing specific. It will require some experimentation to see what works. Vaguely related: Now that we no longer need to support Python 2, we could (at least internally) use asyncio. That might simplify things.

**Comment by Mk-Chan** [comment]
Hmm... Alright, but leaving the impl aside, is the framework alright?

Create a classification for the different engine states.
Allow the programmer to inject a callback into the command queue.
Prevent/handle multithreaded access to same engine process.

**Comment by LocutusOfPenguin** [comment]
i still dont understand why @Mk-Chan last 3.Jan code doesnt work. Nothing else my terrible while loop (see above) doing too, and since then i dont have problems - but its ugly and i must use code from inside the lib without an api.

Nevertheless i would prefer to use asyncio ...but for the moment there are cheaper solutions, no?
speaking about asyncio ...what the current status of https://github.com/niklasf/python-asyncdgt please?

**Comment by Mk-Chan** [comment]
I actually don't know @LocutusOfPenguin , can you highlight the block of code in your repo so we can see where exactly the issue is? If you have 2 threads who are controlling your engine or you are using async_callback, I don't think we can guarantee a stop and assert yet

**Comment by LocutusOfPenguin** [comment]
I use this:
https://github.com/LocutusOfPenguin/picochess/blob/master/uci/engine.py
These "is_SOME" functions starting around line 230 asking for internal (!) states of the python-chess lib. Therefore i said "not safe" and since i use these "is_SOME" functions, i seem to not get these https://github.com/niklasf/python-chess/issues/164 problems anymore. I expect a race condition somewhere, so i cant be 100% sure. 

https://github.com/LocutusOfPenguin/picochess/blob/master/picochess.py
around line 210 => stop_search function, is an example of this terrible while loop

I only have one engine class & var, but as y can see from uci.py, i have this aync_callbacks (calling callback function)

Since this issue is relative old, its not too easy for me, to provide good examples...But the issue still is unsolved

**Comment by LocutusOfPenguin** [comment]
Basically, to prevent python-chess errors like "engine is already started" when i issue a "go" 
(a problem i had in past) but now no longer (or maybe sometimes cause of race)

because

now i have allover these guards (=while) to come to a safe&known state. These whiles using the internal values of python-chess - which leads to a) i dont know, if i choosed the correct way/vars and b) they not safe to keep forever - that was the main thing to ask for this api.

Even it works with guards i should find the cause of these situations, and there is still todo's inside uci.
But thats a different story.

**Comment by Mk-Chan** [comment]
Do you have a stack trace?

**Comment by LocutusOfPenguin** [comment]
no, sorry

**Comment by Mk-Chan** [comment]
My problem is how does your assert fail if we ourselves wait on exactly the same condition:

https://github.com/niklasf/python-chess/blob/master/chess/uci.py#L1012

**Comment by niklasf** [comment]
Not going to happen with `chess.uci` or `chess.xboard`, but something to keep in mind for #339.
