### ISSUE TITLE
Feature Request: Move output in different format here: Long algebraic

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#257]
Hi,
refering to:
https://en.wikipedia.org/wiki/Chess_notation

some picochess users want to get a long notation for the moves.
I can choose to get "Nf3" or "g1f3" right now. Can i also get an output in this long algebraic form?

Jürgen

**Comment by Mk-Chan** [comment]
That seems quite just put the from square and a dash after the piece character

**Comment by LocutusOfPenguin** [comment]
yes, i know its not hard to do it MYSELF.
I need to check for capture, check and form such string..but i think, it should be part of the python-chess lib :-)

**Comment by Mk-Chan** [comment]
At this rate we'll need a locale file for every output loaded dynamically at runtime after a set_locale() function :grin:

**Comment by LocutusOfPenguin** [comment]
i use this:
https://github.com/jromang/picochess/blob/master/dgt/iface.py
get_san() / move()

its not done very well...i wont win a software price, but its good enough, haha
(nor do i win it with the other locate functions for my clock strings)

My point is...i should just say "move.san('de_de') to get "Sf3" instead of "Nf3"
I dont need a super solution but its up to (for example) niklasf to come up with a fancy version if he wants.

**Comment by LocutusOfPenguin** [comment]
Well, i opened this issue cause i think, it should be part of lib not each lib-user doing it himself.

For the locate, i did it already and im ok with it. I dont need more - the only output the user gonna see from this lib are moves and i only support 6 languages. As y see, i dont even win alot of source lines if i have this lib-function - its just my feeling should be part of lib - hope y understand.

Same for this long version move text, i was asking here. For sure, i can do this myself if its said, "no this feature i dont want to implement cause of XYZ".

**Comment by Mk-Chan** [comment]
Actually I think it's ok I'm just waiting for Niklas

**Comment by niklasf** [comment]
I agree that a function for long algebraic notation would be useful.

Localization is of course useful as well, but I don't want to do it yet. It's often very application specific.
