### ISSUE TITLE
Interfacing an UCI Python chess engine to python-chess on Linux

### ISSUE THREAD

**Issue by mdoege** [niklasf/python-chess#261]
Hi!

Is there an easy way to interface an UCI chess engine written in Python to the python-chess chess.uci.popen_engine() method? This problem came up in relation to picochess and the PyTuroChamp chess engine (which itself uses python-chess): https://github.com/mdoege/PyTuroChamp/issues/4

I was thinking that maybe this could be solved via a binary wrapper program, e.g. written in C for POSIX, that pipes stdin and stdout between python-chess and the actual Python chess engine. However, my C skills are quite rusty, so I wanted to find out if the python-chess developers have considered interfacing to scripting language-based engines.

Thanks!
Martin

**Comment by niklasf** [comment]
Hi. It should be possible with pure Python. Something like this:

```python
engine = chess.uci.popen_engine(["python.exe", "main-python-file.py"])
```

**Comment by mdoege** [comment]
Hi Niklas!

Yes, this is for a Raspberry Pi running picochess on Raspbian, combined with a DGT chess board.

> It should be possible with pure Python.

Ok, thanks. So apparently the problem is that picochess seems to he hardwired to look for binaries. As far as I see there is currently no way to pass a list as an argument to the picochess popen_engine call.

So it looks like python-chess is okay, but I would either have to fork picochess to allow multiple arguments to popen_engine or go with my original idea of keeping picochess as it is and writing a wrapper.

It's a bit ironic that both picochess and PyTuroChamp use python-chess, yet it is so difficult to get them to talk to each other. 😃

**Comment by niklasf** [comment]
Final note about this: Another way to implement accepting multiple argument would be allowing arbitrary shell commands (`chess.uci.popen_engine("python engine.py", shell=True)`). Perhaps that's easier to do for picochess.
