### ISSUE TITLE
How can I force chess.pgn.read_game to ignore errors and not to parse pgn with errors?

### ISSUE THREAD

**Issue by salvador-dali** [niklasf/python-chess#264]
I have a big amount of pgn games which I am parsing with read_game function. Unfortunately a tiny amount of them has errors. Sadly the reader still tries to parse them and apparently it is a [valid behavior](http://python-chess.readthedocs.io/en/latest/pgn.html):

> The parser is relatively forgiving when it comes to errors. It skips over tokens it can not parse. Any exceptions are logged.

This results in a few corrupted games being added. I would rather completely ignore them. Is there a way to achieve this behavior?

**Comment by niklasf** [comment]
Most errors are added to a list `game.errors` that you could check. Does this help?

**Comment by salvador-dali** [comment]
Yes, thank you very much.

It works perfectly. Not sure whether this is obvious for others, but at least for me it would be nice to see this in the docs in the `read_game` section. Also maybe some explanation about how to overwrite standard logger: "Any exceptions are logged".

**Comment by niklasf** [comment]
I added a small hint to the docs.
