### ISSUE TITLE
Bug about threefold repetition 

### ISSUE THREAD

**Issue by kn-sq-tb** [niklasf/python-chess#265]
a bug I found in python-chess, version 0.22.1

the problem is in __init__.py, definition of the Board class. More precisely, in the method _transposition_key  (lines 3136-3141). The problem is that self.promoted should not be part of the transposition key, since by the FIDE law of chess, there is no difference between pieces that have been promoted, and pieces that were there from the beginning. This gives problems when determining whether a draw by threefold repetition can be claimed, or whether the position is a draw by fivefold repetition. To solve the problem, you just need to remove self.promoted from the transposition key. This might give problems with some chess variants where the promoted pieces are relevant, I don't know, I didn't check that part of the source. But for standard chess, it should not be there. In the following, a sample code where the bug really appears.

    import chess
    b = chess.Board()
    b.set_fen("5R2/3P4/8/8/7r/7r/7k/K7 w - - 0 1")
    print(b)
    # in this position, White is about to promote a Pawn to a Rook.
    b.push_san('d8=R')
    # now the new Rook is marked as 'promoted piece', so it is not identical to the other Rook
    fenstring = b.fen()
    # the fen does not remember that the new Rook is a 'promoted piece'. 
    c=chess.Board()
    c.set_fen(fenstring)
    # c has the very same position as b, except that the two Rooks in c are identical, in b they are not.
    print(b == c)
    # this returns False. Very bad sign!
    # now let's try to make a threefold repetition.
    b.push_san('Rg4')
    b.push_san('Rf6')
    b.push_san('Rgh4')
    b.push_san('Rdf8')
    b.push_san('Rg4')
    b.push_san('Rd6')
    b.push_san('Rgh4')
    b.push_san('Rdd8')
    b.push_san('Rg4')
    b.push_san('Rf6')
    b.push_san('Rgh4')
    b.push_san('Rdf8')
    b.push_san('Rg4')
    b.push_san('Rd6')
    b.push_san('Rgh4')
    b.push_san('Rdd8')
    print(b)
    # the same position was repeated three times, according to FIDE rules, it can be claimed as a draw.
    print(b.can_claim_threefold_repetition())
    # but this command returns false! A bug.
    # let's try the very same moves on the board c
    print(c)
    c.push_san('Rg4')
    c.push_san('Rf6')
    c.push_san('Rgh4')
    c.push_san('Rdf8')
    c.push_san('Rg4')
    c.push_san('Rd6')
    c.push_san('Rgh4')
    c.push_san('Rdd8')
    c.push_san('Rg4')
    c.push_san('Rf6')
    c.push_san('Rgh4')
    c.push_san('Rdf8')
    c.push_san('Rg4')
    c.push_san('Rd6')
    c.push_san('Rgh4')
    c.push_san('Rdd8')
    print(c)
    print(c.can_claim_threefold_repetition())
    # now this returns true, here the behavior is correct.

**Comment by niklasf** [comment]
Thanks for reporting. I'll make a release with the fix right away.

**Comment by brianprichardson** [comment]
@niklasf thank you so much for all of your continuing work on python-chess.  I am utilizing it more and more with my feeble attempts at riding on the coattails of those working on Alpha Zero chess.
Best regards.
