### ISSUE TITLE
read_game() in pgn.py support UCI moves in addition to SAN

### ISSUE THREAD

**Issue by brianprichardson** [niklasf/python-chess#266]
Still not up to speed with GitHub, but can you change pgn.py to try UCI move format after SAN around line 980 per below (it seems to work for me):

                # Parse SAN tokens.
                try:
                    move = board_stack[-1].parse_san(token)
                except ValueError:
                    try:
                        move = board_stack[-1].parse_uci(token)
                    except ValueError as error:
                        visitor.handle_error(error)
                #else:
                visitor.visit_move(board_stack[-1], move)
                board_stack[-1].push(move)

It currently fails with a pgn like this:

[Event "CCRL 40/4"]
[Site "CCRL"]
[Date "2006.05.24"]
[Round "1"]
[White "Aristarch 4.50"]
[Black "Chess Tiger 15"]
[Result "1/2-1/2"]

g1f3 c7c5 e2e4 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3 e7e6 c1e3 a7a6 g2g4 h7h6 d1f3 b8d7 f1e2 d8c7 f3h3 d6d5 e4d5 f8b4 e3d2 c7b6 d5e6 b6d4 e6d7 c8d7 e1c1 d4b6 d2e3 b4c5 h3g3 c5e3 f2e3 e8g8 g4g5 h6g5 g3g5 f8e8 d1d3 f6h7 c3d5 h7g5 d5b6 d7c6 h1g1 g5h3 g1g3 h3f2 b6a8 f2d3 c2d3 e8a8 g3g5 g7g6 g5c5 g8g7 h2h4 a8h8 h4h5 f7f5 d3d4 g6h5 d4d5 c6e8 c5c7 e8f7 d5d6 g7f6 d6d7 h8d8 c7b7 f6e7 e2a6 f7d5 b7b6 d8d7 a6e2 d7c7 c1d2 d5a2 b6h6 c7d7 d2e1 a2b3 h6h7 e7e6 h7d7 e6d7 e2h5 d7e6 h5d1 b3a2 e1f2 e6e5 f2f3 a2f7 d1c2 f7d5 f3g3 d5c4 c2b1 c4d5 b1d3 d5b3 d3b5 e5e4 g3f2 f5f4 b5c6 e4e5 e3e4 1/2-1/2

I have been trying to clean up some quite large pgn collections and have been removing move numbers and as much superfluous text as possible.
Edit: Although I suppose SAN is more compact than UCI with things like lots of pawn moves.

Thanks.

**Comment by niklasf** [comment]
In general I'd rather keep the current behavior and reject such an invalid PGN. Perhaps it could be made easier to swap out the parser ...

**Comment by brianprichardson** [comment]
Ah, I understand.

How might we better address parsing various move formats (SAN and UCI) in the same pgn file, or is that something which should be cleaned up by pre-processing with other utilities like pgn-extract or SCID?

**Comment by ddugovic** [comment]
It's best to reject invalid PGN, although if the move parser were easier to replace @brianprichardson could replace it to input SAN, LAN, RAN, UCI, postal, etc. https://en.wikipedia.org/wiki/Chess_notation#Recording_moves

**Comment by niklasf** [comment]
I assume you moved on by now. In any case the latest development version allows overriding `parse_san` in the visitor:

```python
class UciPgnVisitor(chess.pgn.GameModelCreator):
    def parse_san(board, san):
        return board.parse_uci(san)  # only uci format

game = chess.pgn.read_game(file, Visitor=UciPgnVisitor)
```

**Comment by brianprichardson** [comment]
Hello.  I think I understand what this is doing.  My Python is rudimentary, so I'm really clear on the "visitor" notion.  Regardless, will this now accept either SAN or UCI move formats in PGN files?

**Comment by gbtami** [comment]
With minor modification, yes.
```python
class MyPgnVisitor(chess.pgn.GameModelCreator):
    def parse_san(self, board, move):
        if move[:2] in SQUARE_NAMES and move[2:4] in SQUARE_NAMES:
            return board.parse_uci(move)  # only uci format
        else:
            return board.parse_san(move)  # only san format

game = chess.pgn.read_game(file, Visitor=MyPgnVisitor)
```

**Comment by niklasf** [comment]
I am coming around on adding this natively.
