### ISSUE TITLE
Impossible to set color of arrow in SVG.

### ISSUE THREAD

**Issue by ChameleonRed** [niklasf/python-chess#267]
`        svg = chess.svg.board(board=self.board, lastmove=lastmove, check=check, size=None, coordinates=False, arrows=((chess.E2, chess.E4),))`

I can render board but cannot set arrows colors. It will be nice to have to show different aspects.

**Comment by niklasf** [comment]
If your client supports CSS you can pass a stylesheet to the style argument:

```
.arrow {
  stroke: #ff0000;
  fill: #ff0000;
}
```

Otherwise you can use xml.etree.ElementTree to work on the SVG or just textually `.replace("#888", "#ff0000")` the color.
