### ISSUE TITLE
Arrow on SVG looks little ugly ...

### ISSUE THREAD

**Issue by ChameleonRed** [niklasf/python-chess#268]
It will nice to see arrow below pieces.

![obraz](https://user-images.githubusercontent.com/1080880/38768957-7510cc7e-3ffb-11e8-91ee-54c5521656b6.png)

**Comment by niklasf** [comment]
Sorry, but I prefer the arrows on top, especially when it goes to an adjacent square.

**Comment by ChameleonRed** [comment]
Lichess prefer arrows below maybe it should be configurable?
