### ISSUE TITLE
Parameter order for "go" in uci

### ISSUE THREAD

**Issue by rgerkin** [niklasf/python-chess#27]
Something I snuck into my pull request was a change to the order in which "searchmoves" is appended to the command string in the uci.  I found that searchmoves was clobbering other parameters like depth and movetime when appended first, as in the current code.  In other words:  

```go searchmoves [moves] depth 20 movetime 5000```

was ignoring the depth and movetime values completely.  I changed it to:  

```go depth 20 movetime 5000 searchmoves [moves]```

then it worked fine.  I changed the order of the commands in 00ee993c3f921f94286de2f540bc7bf7ab6c4170, which is currently causing an AssertionError due to a syntax check (uci.py, line 607) not allowing that order of commands.  However, I think that is the correct order, due to the inability to get the engine I am using (stockfish) to work as intended using the existing code.

**Comment by niklasf** [comment]
Well spotted. I don't think this is stated in the UCI protocol documentation, but Stockfish [expects it to go last](https://github.com/official-stockfish/Stockfish/blob/master/src/uci.cpp#L116), indeed.

Would you mind spinning that off into a seperate pull request and adjusting the failing test? We could get that fixed first, then.
