### ISSUE TITLE
Is there a place to download 7 piece Syzygy tablebases?

### ISSUE THREAD

**Issue by salvador-dali** [niklasf/python-chess#275]
In [changelog ](https://github.com/niklasf/python-chess/blob/master/CHANGELOG.rst) you mentioned 

> Experimental support for 7 piece Syzygy tablebases

I was not successful to find these tablebases. Do you have any link?

**Comment by niklasf** [comment]
Yes, some of the tables have been shared here: http://talkchess.com/forum/viewtopic.php?t=66797. Other tables are still beeing generated. There's also a mirror hosted by Lichess: http://tablebase.lichess.ovh/tables/standard/7/

You will need well over 20 Terabyte of disk space to store all the tables, once they have been completed.

Note that it's very likely that there are still bugs, so you'll have to take the results with a grain of salt.
