### ISSUE TITLE
GiveawayBoard FEN: castling field should be "-"

### ISSUE THREAD

**Issue by ProgramFOX** [niklasf/python-chess#276]
Castling is invalid in antichess. However, the GiveawayBoard FEN still has a castling field that can look like "KQkq". That's inconsistent with the FENs on Lichess, that always have "-" for antichess castling fields (which makes more sense, imo).

**Comment by niklasf** [comment]
This is the default, but you're saying it shouldn't be allowed ever, for example even when a FEN with castling rights is given?

**Comment by ProgramFOX** [comment]
Oh. No, I'm not saying that... I guess _I_ messed up by passing a FEN that initially had castling rights. My bad!
