### ISSUE TITLE
Problems using polyglot

### ISSUE THREAD

**Issue by svatty89** [niklasf/python-chess#280]
Hello! First of all. I'm newbee to programming. Relatively. I'm interested in it with all my heart. Deeply, but don't judje, please. It's dissapointing that i can't figure out what to do myself. Even though, I have documentation. But i get stuck, anyway. Please, give me some feedback, help me to understand what's wrong.  
I would like to write some code as in documentation. Exactly the same thing. Simply. I do get something like :+1: 
>>> import chess
>>> import chess.polyglot
>>>
>>> board = chess.Board()
>>>
>>> with chess.polyglot.open_reader("data/polyglot/performance.bin") as reader:
...    for entry in reader.find_all(board):
...        print(entry.move(), entry.weight, entry.learn)
e2e4 1 0
d2d4 1 0
c2c4 1 0
-----------------
but what i get is an error. These  lines above are working. But when i type "chess.polyglot.Entry" - it doesn't. work. It tells that there's is a class with that name. That's all i get.
It writes nothing about attributes "key", "raw_move",  "weight", "learn". So, it does nothing at all. What i would like to get is entry for best moves. And i would like to represent them on board - the next step. What i should do? How can i do this? Or, more exactly, can i get full list of these moves? 
find_all(board, minimum_weight=1, exclude_moves=()) doesn't work too.  What should code lines be to achieve this goal(get the list of best moves)? Please, write some code line, because i can't figure out it for myself. What code should be there BEFORE the staitment "find_all(board, minimum_weight=1, exclude_moves=())"? Is there should be anything? 
 Thanks in advance. I'm very interested in Python Chess. Very. Please, give me some help.

**Comment by niklasf** [comment]
Hi. Can you say what exactly you want to achieve? If you want to find all book moves in the starting position that is exactly what the code example you copied does.

**Comment by svatty89** [comment]
Hello! What exactly i want to do? Yes, this code example helps to find all possible moves in the starting position, but what i want is to get all moves after the starting one - i mean for position after the first move, then for position after the second one and so on up to the end of game tree representation.
  I would like to say something off top. Your lib is something of a great beauty. I wish I was able to undersdand more about how to work with it. I feel something deeply inspiring about your lib in general. It's a deep thing. The more i will know about it's structure, the more i will feel what i feel now. Thank you, niklasf for your work!
