### ISSUE TITLE
Variation not detected

### ISSUE THREAD

**Issue by lfaber91** [niklasf/python-chess#282]
Hi

I have a problem with python-chess which seems to not detect variations. For example with the following pgn game (taken from a rezal game I played as Black ;-):

```
1. e4 d5 2. exd5 Qxd5 3. Nc3 Qa5 4. d4 Nf6 5. Bd3 Nc6 6. Nge2 Bg4 7. f3 Bh5 8.O-O O-O-O 9. Bb5 (9. Nb5 a6 10. Na3 Nxd4 $11) 9... Qb6 (9... Nxd4 $142 $5 10.Nxd4 e5 $17) 10. Bxc6 {(19')} Qxc6 {(35')} 11. Bf4 e6 12. Qc1 h6 13. a4 a6 14.Be5 Bd6 15. Qe3 Bg6 16. Nf4 Bxe5 (16... Bxc2 $143 17. Rfc1 Qb6 18. Bxf6 gxf6 19. Rxc2 Bxf4 20. Qxf4 Rxd4 21. Qe3 $16) 17. dxe5 Nd7 18. Nxg6 fxg6 19. Rfd1 g5 20. Kf2 {(1h35)} Rhf8 {(1h37)} 21. h3 Rf5 22. Qa7 Qb6+ 23. Qxb6 Nxb6 24. Rxd8+ Kxd8 25. Rd1+ Ke7 26. Re1 Nd7 27. Re4 Rxe5 28. Rb4 Nc5 29. Ne4 (29. a5 $5 $11) 29... Nxe4+ $17 30. fxe4 {(1h50)} b6 {(1h52)} 31. Rc4 Kd6 32. Rd4+ Kc6 33. Ke3 Rc5 34. Kd3 g4 35. h4 Rh5 36. g3 g5 37. hxg5 Rxg5 38. Ke3 h5 39. Kf4 Rc5 40. Rd2 {(1h57)} a5 {(1h59)} 41. Rh2 Kd6 42. Re2 Rc4 43. Kg5 $2 (43. Rd2+ $142 Ke7 44. b3 $15) 43... Ke5 $19 44. Kxh5 Rxe4 (44... Rxa4 $6 45. Kxg4 Rb4 46. c3 Rxe4+ 47. Rxe4+ Kxe4 48. Kh5 $19) 45. Rxe4+ $4 (45. Rh2 $19) 45... Kxe4 46. Kxg4 e5 47. Kh5 (47. b3 c5 48. Kh5 $19) 47... Kf3 48. g4 e4 49. g5 e3 50. g6 e2 51. g7 e1=Q 52. g8=Q Qh1+ 53. Kg6 Qg2+ 54. Kf7 (54. Kf5 Qxc2+ 55. Kf6 Qxb2+ 56.Ke7 $19) 54... Qxg8+ 55. Kxg8 Ke3 56. Kf7 Kd2 57. c4 Kc2 58. c5 bxc5 $8 59. Ke6 Kb3 (59... Kxb2 $142 60. Kd5 Kb3 $19) 60. Kd5 c4 61. Kc5 c6 62. Kd4 Kxb2 63. Kxc4 Ka3 64. Kc5 Kxa4 (64... Kxa4 65. Kc4 c5 $19) 0-1
```

the variation at move 9 (9. Nb5) is not detected by the small following code (taken from the website), see attachment:

[test_py_chess.txt](https://github.com/niklasf/python-chess/files/2006742/test_py_chess.txt)
next_node.starts_variation() always returns false.

Thank you for examining this issue (if you confirm it is one).
By the way, thanks for the great job !

**Comment by niklasf** [comment]
Hi, I added an example to clarify: 311de5eed88254c7191acb54d6ebfe15def402ea. To check if a node has any branches itself use `len(node.variations) > 1`.

**Comment by niklasf** [comment]
> Ok, but the problem is that even if I use the workaround you mentioned, the Nb5 move in my game is never "catched" as the starting move of the variation (I used debugger with pycharm and verified this).

Here it's working as expected. Can you maybe show a screenshot?

**Comment by lfaber91** [comment]
Hum...not possible for the moment for obvious reasons ;-) I will tell you
tonight

2018-05-16 9:58 GMT+02:00 Niklas Fiekas <notifications@github.com>:

**Comment by lfaber91** [comment]
Here is the screenshots of debugger in pycharm with my game and yours
[python-chess_issue_282.pdf](https://github.com/niklasf/python-chess/files/2010497/python-chess_issue_282.pdf)

**Comment by niklasf** [comment]
Thanks, I assume you're referring to the string representations and I see now how this could be confusing. Even though it only shows the line starting at the node, i.e. excluding the current move, the move is there as `node.variations[1].move`. You can probably check this by expanding the debug output.

I'll think about a way to make this more natural.

**Comment by lfaber91** [comment]
You're right. Thanks for answering my issue which can be closed.
