### ISSUE TITLE
UnicodeDecodeError UTF-8 error on parsing PGN file

### ISSUE THREAD

**Issue by mphuget** [niklasf/python-chess#283]
Hello everyone, 

I took some PGN files from https://www.pgnmentor.com/files.html#openings and try to parse them, some of them run smoothly, but for some, I got the really annoying UTF-8 encoding error. Obviously, I change my open(file) by open(file, encoding="utf-8") but the error remains

If you want to test, you can try on these files: 

Alekhine2Nc3-d5.pgn
AlekhineOther3.pgn
Bird.pgn
BishopsOpening.pgn
Bogo4Bd2.pgn
BudapestGambit.pgn
Caro-Kann2c4.pgn
Dunst.pgn
English1b6.pgn
English1c6.pgn
English1e6-2Nf3-d5.pgn
English1e6Main.pgn
English1f5.pgn
English1Nf6-2Nc3.pgn
English1Nf6-2Nf3.pgn
EnglishFlohr-Mikenas.pgn

Does somebody have an idea why it still does not work? 

Thanks for your answers

**Comment by niklasf** [comment]
Hi, I checked `Alekhine2Nc3-d5.pgn` and it looks like it is ISO-8859-1 rather than UTF-8. Alternatively, if the encoding is ever broken beyond repair, you can check out the various ways that [`open()`](https://docs.python.org/3/library/functions.html#open) can deal with `errors`.
