### ISSUE TITLE
Polyglot. Game-Tree move.

### ISSUE THREAD

**Issue by svatty89** [niklasf/python-chess#284]
I have allready asked about searching game-tree for positions. I got an answer which included code line. This code line is following:

``` 
>>> import chess
>>> import chess.polyglot
>>> with chess.polyglot.open_reader("C:/Users/жл/Downloads/python-chess-master/data/polyglot/Book_Formula12/Formula12.bin") as book:
	board = chess.Board()
	while True:
		try:
			entry = book.find(board)
		except IndexError:
			break
		else:
			print(entry.move())
			board.push(entry.move())
```

It exctracts the main line. Allright. Here it is. Our main line. I get the following. 
e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3 a7a6 c1e3 e7e5 d4b3 c8e6 f2f3 f8e7 d1d2 b8d7 g2g4 h7h6 e1c1 b7b5 h2h4 d7b6. I do pop() method back to the move "c8e6". Then i want instead of f2f3 to get for example to choose the following move - Qg4. And  after doing that to get all variation presented in the file for this my new line - after my Qg4 move. So, what i'm i to do if i need to get not the main line only, but  variations too? Because if i repeat the mainline code i will get the same list.  The idea is to get a new list(s) - the list(s) of variations for the fist move, for the second move, for the third move and so on. Suppose, i got mainline, then got back 5-10 chodes backward and i used "board.push" method. And what i want exactly is to know variations AFTER THAT move, what should i type then into interpreter?
Is it possible? 

Suppose i have a debut database file. I think this task is called exctracting all variations from n-node of a particular game tree.  I can do the first move - suppose, i search the polyglot file and the result tells me that i have an option of choosing beetween 20 different moves. Then i pick up the one from the given list of 20 different moves(20 is a lot, but it is e.g) and I want to have candidates for my second move. Then for the third one. And so on.  I imagine a game tree with nodes and process of passing trought it from beggining to the end, choosing variants i like to choose(those ones that are presented in the database of a polyglot file of course). 

What i mean is this idea of moving along the nodes of a search tree as in this article/ https://chessprogramming.wikispaces.com/Search+Tree/  using code lines, polyglot files and this wonderful lib of course.  Formula is relatively simple/ I choose first node, then get candidates for the second, pick one from the list and then - get the new candidates and so on.  

And one more thing. Can i not only get any candidate for my move included in the polyglot database, butalso to choose it for myself using push method and then AFTER THAT check if there are some continuations? It really means to me a lot to find it out.. Very sorry if any links for other sources are forbiden, but i mean this(https://chess-db.com/public/explorer.jsp?interactive=true&avelo=2700 - for the first, for the second move...and so on). The only difference is that datebase is of less size and we want to get the same search idea using code.

**Comment by svatty89** [comment]
Please, let me know, if these ideas are possible to make using python-chess. And sorry for not greeting at the start of my message. Appologizing for this.  I was tired. Thank's for your attention.

**Comment by niklasf** [comment]
Hey, no worries about formalisms. I added a small [example](https://github.com/niklasf/python-chess/blob/master/examples/polyglot_tree.py) to the repository:

```
$ python polyglot_tree.py ../data/polyglot/performance.bin --depth 3
├─ e4
│ ├─ e5
│ │ ├─ Nf3
│ ├─ c5
│ │ ├─ Nf3
│ │ ├─ Nc3
│ │ ├─ c3
├─ d4
│ ├─ Nf6
│ │ ├─ c4
│ │ ├─ Nf3
│ │ ├─ Bg5
├─ c4
│ ├─ Nf6
│ │ ├─ d4
```

**Comment by svatty89** [comment]
Hi! Thank you for the answer and the code both. As i only started working with lib, i want ask maybe elementary question. First of all i should open my polyglot file with biz. extention, right? Is it allright if i will use for this purpose this line as it showed in code exapmple in the docs -- "chess.polyglot.open_reader(path)"? Or should i use different way to open file? Only then if i made no mistake i can use other code example above(i mean tree form representation code now)?  I ask this because i don't see in the example the step on which file is opened. In your message i see the path, but it doesn't look like python code. And i guess you are using linux. The second question. As i may see, this example is for depth3. What parameters i need to change to make depth4 or depth24 or another depth for example? So, maybe this question a bit silly, because i haven't executed this example in the python interpreter yet. I will do it know to see if this parameter "level" in the line 13 is the way to change the depth of the representation. I feel that i on my way to be able to do simple things with the lib - the same ones that one can do playing online chess. Only one thing is left - to understand how to get the trees of various depth.  So, i have two question left. What should i type to open polyglot file? And what to change in the  the code exaple to get desireable depth of the tree form representation?

**Comment by niklasf** [comment]
If you look carefully, the example does `chess.polyglot.open_reader(path)` by means of Pythons command line argument parser `parser.add_argument("book", type=chess.polyglot.open_reader)`. Either is fine.

You can change the default depth here `parser.add_argument("--depth", type=int, default=5)` or pass an argument `--depth 24` on the command line. Yes, I am personally using Linux, but this this will work regardless of the operating system.

If you have general Python questions you might get answers more efficiently on other sites, for example Stackoverflow. I am still happy to help with python-chess related stuff.
