### ISSUE TITLE
Engine.position does not send full moves history.

### ISSUE THREAD

**Issue by SashaMN** [niklasf/python-chess#286]
According to the docs:

> Instead of just the final FEN, the initial FEN and all moves leading up to the position will be sent, so that the engine can detect repetitions.

But in the code https://github.com/niklasf/python-chess/blob/master/chess/uci.py#L859 we see:

```
if board.is_irreversible(move):
    break
```

Lc0 (leela chess zero) engine always requires at least last 8 moves. So maybe we need an option to control this behavior of Engine.position? Or just send full history always.

I have also tried to comment these two lines. But sometimes python-chess produces incorrect uci command. So probably need to fix smth else.

**Comment by SashaMN** [comment]
Yeah, Lc0 uses last 8 moves for evaluation and the other history to detect repetitions and etc.
Lc0 can work even with the last move only. But we have tested, and it probably works weaker because of this issue.

**Comment by niklasf** [comment]
Alright. I don't wanna go back to sending the full history (#97), but I guess it can't hurt to always send at least 8 moves (even though having such a special number is a bit hacky).

Will likely release this tonight.

**Comment by Mk-Chan** [comment]
Why not take a parameter to ascertain how many moves back to look? And keep it default to 0 which would imply just the final FEN. That way seems the most flexible to me.

**Comment by ddugovic** [comment]
Also theoretically you don't need to include pawn moves or captures in the move history, only positions after pawn moves or captures.

**Comment by niklasf** [comment]
@ddugovic Yes, this was the previous behavior. Then Lc0 wanted a way to get at least 8 moves anway.

I am starting to think the best way sending the entire history, always, and just fixing the performance issue with that. Gonna ponder it some more ...

**Comment by niklasf** [comment]
v0.23.7 now always sends the entire history from the root position.
