### ISSUE TITLE
Gaviota tablebases when there are two possible en passant captures

### ISSUE THREAD

**Issue by bjoernholzhauer** [niklasf/python-chess#290]
It appears that in when probing Gaviota tablebases there may be an issue when there are two possible en-passant moves on the board. I was processing endgames from a couple of 100,000s of games and I ran into a position (FEN '8/8/8/8/5pPp/8/5K1k/8 b - g3 0 61'  or more precisely into '8/8/8/8/5p1p/8/5KPk/8 w - - 0 61', where g2-g4 is a potential move to consider), where black has two possible e.P. captures.

It appears that the Gaviota tablebase functions do not deal with this correctly, while everything seems fine for the Syzygy tablebases. I am not sure whether this is an issue on the python-chess side or an issue with the actual tablebases. I found a discussion online that discussed an issue that was not quite the same, but indicated that en passant captures might at some point have posed an issue for Gaviota tablebases. Since that was in 2012 it might no longer be an issue and the situation appeared different (it had to do with situations, where the en passant captures where the only moves changing the evaluation and in any case resulted in wrong evaluations).

The error I get is

`Traceback (most recent call last):

  File "<ipython-input-406-5a534f4f1dd5>", line 4, in <module>
    tablebases.probe_dtm(myboard)

  File "C:\ProgramData\Anaconda3\lib\site-packages\chess\gaviota.py", line 1588, in probe_dtm
    dtm = self.egtb_get_dtm(req)

  File "C:\ProgramData\Anaconda3\lib\site-packages\chess\gaviota.py", line 1760, in egtb_get_dtm
    removepiece(ys, yp, j)

  File "C:\ProgramData\Anaconda3\lib\site-packages\chess\gaviota.py", line 1373, in removepiece
    del ys[j]

IndexError: list assignment index out of range`

This is some code to re-produce the issue (I did not have a separate system to test this on):
`import chess.gaviota
tablebases = chess.gaviota.open_tablebases(directory="D:/gaviota/")
tablebases.open_directory(directory="D:/gaviota//3/")
tablebases.open_directory(directory="D:/gaviota/4/")
tablebases.open_directory(directory="D:/gaviota/5/")

# With two en-passant captures this is a problem
myboard = chess.Board('8/8/8/8/5pPp/8/5K1k/8 b - g3 0 61')
myboard.has_legal_en_passant()
tablebases.probe_dtm(myboard)
# Using get_dtm also does not help
tablebases.get_dtm(myboard)

# With one en-passant capture this is not a problem
myboard2 = chess.Board('8/8/8/8/5pP1/8/5K1k/8 b - g3 0 61')
myboard2.has_legal_en_passant()
tablebases.probe_dtm(myboard2)

# Shifted 1 file to the left: With two en-passant captures this is a problem
myboard3 = chess.Board('8/8/8/8/4pPp1/8/4K1k1/8 b - f3 0 61')
myboard3.has_legal_en_passant()
tablebases.probe_dtm(myboard3)

# Shifted 1 file to the left: With one en-passant captures this is not a problem
myboard4 = chess.Board('8/8/8/8/4pP2/8/4K1k1/8 b - f3 0 61')
myboard4.has_legal_en_passant()
tablebases.probe_dtm(myboard4)

# The problem is not that the en passant moves are the only winning moves 
# (here - changed king positions - almost anything wins, still a problem)
myboard5 = chess.Board('K7/8/8/6k1/5pPp/8/8/8 b - g3 0 61')
myboard5.has_legal_en_passant()
tablebases.probe_dtm(myboard5)`

I faced the issue with package version 0.23.5 in Python 3.6 under Windows 10.

**Comment by niklasf** [comment]
Thanks this excellent and detailed bug report, @bjoernholzhauer! The issue was that the position was not restored before probing the second capture. Fixed and released in v0.23.6.
