### ISSUE TITLE
Unexpected Behaviour when using board.mirror() on Crazyhouse Pockets

### ISSUE THREAD

**Issue by QueensGambit** [niklasf/python-chess#294]
Thank you very much for your great work!
We're currently using your library for the game-mode 'Crazyhouse' for our university project and it's a great pleasure.

Today, I unfortunately faced the problem that if you `mirror()` a Crazyhouse board, the pockets will be reset.
Is this behaviour intended?

Here's a short demonstration:

```
from chess.variant import CrazyhouseBoard

# create a new CrazyhouseBoard and add pawn to white's pocket
board = CrazyhouseBoard()
board.pockets[chess.WHITE].add(chess.PAWN)

print(board.pockets)
# > [CrazyhousePocket(''), CrazyhousePocket('p')]

# flip the board state
board = board.mirror()

print(board.pockets)
# > [CrazyhousePocket(''), CrazyhousePocket('')]

**Comment by niklasf** [comment]
Hi, thanks for reporting. I made a bugfix release `v0.23.7`.
