### ISSUE TITLE
Help with saving SVG to file

### ISSUE THREAD

**Issue by ThePlasmaRailgun** [niklasf/python-chess#297]
Hello everyone,
I'm writing a discord bot for playing chess and wanted to be able to render the board as an svg and then export it to an actual file or a file object to send in a discord message.

The docs seem sadly lacking on this, showing only how to display an SVG in Ipython. I need to export the SVG in to a file-like object in binary mode to export to discord: [discord File object](https://discordpy.readthedocs.io/en/rewrite/api.html#file)

Any help is appreciated, thanks.

**Comment by niklasf** [comment]
Hi, you can use:

```
>>> import chess
>>> import chess.svg
>>> 
>>> board = chess.Board()
>>> 
>>> svg = chess.svg.board(board)
```

Then `svg` is a string that you can write to a file in text mode.

**Comment by niklasf** [comment]
... and `svg.encode("utf-8")` to get bytes.
