### ISSUE TITLE
Help using UCI

### ISSUE THREAD

**Issue by mzfr** [niklasf/python-chess#298]
I am trying to use UCI engine but I can't understand how to do it.

In one of the example in the docs you it says `engine = chess.uci.popen_engine("/usr/bin/stockfish")` meaning I should have a chess engine within my system which I don't want to. 

For remote UCI docs says I should use spur but still it connects to the engine within a system.

Is there a way I can use any online engine with python-chess UCI ?

**Comment by niklasf** [comment]
Hi. So you have Stockfish installed on a server that you can SSH into? In the example from the docs, did you replace `localhost` with the remote servername?
```
shell = spur.SshShell(hostname="localhost", username="username", password="pw")
engine = chess.uci.spur_spawn_engine(shell, ["/usr/bin/stockfish"])
```

**Comment by mzfr** [comment]
I got it. `So you have Stockfish installed on a server that you can SSH into?` this line helped me :slightly_smiling_face: Thanks
