### ISSUE TITLE
stop engine thinking on 2 condition

### ISSUE THREAD

**Issue by gitIssueReport** [niklasf/python-chess#301]
I noticed that the "go" method only wants one argument to stop thinking and i wanted to know if there is possibility that for example we could stop it when "movetime" and the "depth" both reaches specified value ?

I tried to find "time" and "depth" in engine response in custom MyEngine but the stop method there just stops the engine and i can't reach my commands after go(infinite=True, async_callback=False). I want to do it syncronously
Here is my code in MyEngine

    def on_line_received(self, buf):
        # Careful: This can be called from a different thread
            
         # getting depth from engine response
        depth = 0
        if "depth" in buf:
            begin_with_depth = buf.split("depth ", 1)[1]
            array = begin_with_depth.split(" ")
            for word in array:
                depth = word
                break

        # getting time from engine response
        engine_think_time = 0
        if " time" in buf:
            begin_with_time = buf.split("time ", 1)[1]
            array = begin_with_time.split(" ")
            for word in array:
                engine_think_time = word
                break

        if int(engine_think_time) > 15000 and int(depth) > 30:
            super(MyEngine, self).stop()

        super(MyEngine, self).on_line_received(buf)

**Comment by gitIssueReport** [comment]
I could to handle this situation by using below AbortableSleep() class that is suggested by Jamie Cockburn (thanks to him).
Instead of stopping the engine in my custom MyEngine i awaked the main thread sooner and stopped the engine there.
but still if there is a better solution i happy to know that. thank you

https://stackoverflow.com/a/28480718/9968608

**Comment by Mk-Chan** [comment]
The purpose of `go movetime` and `go depth` were to create separate modes for the engine. They were not meant to be used in conjunction. In fact the XBoard protocol explicitly states that the corresponding settings (`st` and `sd`) are orthogonal and should both be respected individually (UCI does not explicitly say so). So I would say you cannot do this according to the spec, and therefore, the API.

What you could do instead is run the engine asynchronously with one condition and blocking-wait on the future until the second condition. If you absolutely must do it synchronously, you'll have to hack the API.

**Comment by gitIssueReport** [comment]
Thanks for the info Mk-Chan
