### ISSUE TITLE
[HELP Wanted]

### ISSUE THREAD

**Issue by glennsamuel32** [niklasf/python-chess#303]
Hello everyone,

Is there a python-chess script that can cut the starting moves of a pgn and insert a FEN ?
A user can then input the number of plies to be cut.

For example...

[Event "Soviet Union"]
[Site "Soviet Union"]
[Date "1977.??.??"]
[Round "?"]
[White "Garry Kasparov"]
[Black "Malshikov"]
[Result "1-0"]
[ECO "B39"]
[SetUp "1"]
[FEN "rr4k1/pbR1p1bp/3p2p1/Pp1P1p2/4P3/4B3/P3BPPP/5RK1 w - - 0 20"]
[PlyCount "63"]
[EventDate "1977.??.??"]

{[#]} 20. f3 Bf6 21. Rfc1 a6 22. Rd7 Kf7 23. Rcc7 Bc8 24. Rd8 Bb7 25. Rxb8 Rxb8
26. Ba7 Ra8 27. Be3 Bc8 28. g4 fxg4 29. fxg4 Ke8 30. g5 Be5 31. Kg2 Bd7 32. Bb6
Bg7 33. h4 Be5 34. Kf3 Bc8 35. Ke3 Bd7 36. h5 Bh2 37. Bd4 Bg1+ 38. Kd3 Bxd4 39.
Kxd4 Kd8 40. Rc1 e5+ 41. dxe6 Bxe6 42. hxg6 hxg6 43. Rc6 Ke7 44. Rc7+ Ke8 45.
a3 Rb8 46. Rc6 b4 47. Rb6 Rxb6 48. axb6 Bc8 49. axb4 Kd7 50. Bg4+ Kd8 51. Bxc8
1-0

I'm trying to create a middle-game Test suite and I have about 750,000 pgns to include.
Chessbase can do it but only manually and one game at a time, and so that's not a solution.

Thanks...

**Comment by niklasf** [comment]
```
#!/usr/bin/python

import chess.pgn
import sys

SKIP_PLIES = 40
FILENAME = sys.argv[1]

pgn = open(FILENAME)
out = chess.pgn.FileExporter(sys.stdout)

def skip_nodes(game, plies):
    node = game
    for _ in range(plies):
        if node.variations:
            node = node.variations[0]
        else:
            return
    return node

while True:
    game = chess.pgn.read_game(pgn)
    if game is None:
        break

    node = skip_nodes(game, SKIP_PLIES)
    if node:
        node.accept_subgame(out)
```

**Comment by glennsamuel32** [comment]
That's great !! Thanks a lot niklasf !!
Could I have the cut pgn written to a file ?
Right now, when I run "python cut.py test2.pgn" , I only get output in the terminal.

[Event "5 min, rated"]
[Site "Engine Room"]
[Date "2017.03.26"]
[Round "?"]
[White "Sokoudjou, Brainfish 190317 64"]
[Black "HlTMaN, Toltec 200317"]
[Result "1-0"]
[Annotator "game 259, depth=21 val=51 filter=\[30/99999\] s"]
[BlackElo "2520"]
[ECO "C78"]
[EventDate "2017.03.28"]
[EventType "blitz"]
[PlyCount "325"]
[WhiteElo "2622"]
[FEN "r1bqk2r/1ppp1ppp/p1n2n2/2b1p3/B3P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 1 6"]
[SetUp "1"]

6. c3 d6 7. O-O O-O 8. Re1 b5 9. Bc2 h6 10. h3 Re8 11. Nbd2 a5 12. Nf1 d5 13.
exd5 Nxd5 14. Ng3 Nf6 15. a3 Bb7 16. Be3 Bf8 17. Qe2 a4 18. Rad1 Bd6 19. Bb1
Rb8 20. Ne4 Na5 21. Ba2 Bc6 22. Nfd2 Nxe4 23. Nxe4 Nb3 24. f3 f5 25. Nxd6 Qxd6
26. Qc2 Bd5 27. c4 Bf7 28. Bxb3 axb3 29. Qc3 f4 30. Ba7 b4 31. axb4 Rxb4 32.
Ra1 Rb7 33. Ra5 Bg6 34. Rd5 Qb4 35. Qxb4 Rxb4 36. Bc5 Ra4 37. h4 Kh7 38. Ba3
Rb8 39. Kf2 Raa8 40. Bc5 Rd8 41. Rexe5 Bxd3 42. Re7 Bxc4 43. Rd4 Bb5 44. Kg1
Ra1+ 45. Kh2 Rd1 46. Rxf4 R8d7 47. Rxd7 Bxd7 48. Rb4 Be6 49. Bd4 c6 50. Bc3 Rd7
51. Kg3 Bd5 52. h5 g6 53. hxg6+ Kxg6 54. Rg4+ Kh7 55. Kf2 Be6 56. Rf4 Bd5 57.
Rf8 Re7 58. f4 Rf7 59. Rxf7+ Bxf7 60. f5 Bd5 61. g4 c5 62. Ke3 c4 63. Bd4 Bc6
64. Be5 Bg2 65. Kf2 Ba8 66. Kg3 Bc6 67. Kh4 Bd5 68. Bd4 Kg8 69. Kh5 Kh7 70. Kh4
Kg8 71. Be5 Bf3 72. Kh5 Kf8 73. Bd6+ Kf7 74. Be5 Kf8 75. Bc3 Kf7 76. Bb4 Kf6
77. Bc3+ Kf7 78. Bd4 Bd1 79. Be5 Be2 80. Kh4 Bf3 81. Kg3 Be4 82. Bd4 Bc6 83.
Kh4 Bf3 84. Bc3 Bd5 85. Bb4 Kg7 86. Bd2 Kf7 87. Bxh6 c3 88. Bc1 c2 89. Bf4 Bf3
90. Kh5 Kf6 91. Bg5+ Kg7 92. Kh4 Bg2 93. Kh5 Bf1 94. Bf4 Kf7 95. Be3 Be2 96.
Kg5 Bd3 97. Kh6 Kf6 98. Bg5+ Kf7 99. Bc1 Bf1 100. Kh5 Be2 101. Bg5 Kg7 102. Bf4
Bd3 103. Bd2 Bf1 104. Bh6+ Kf6 105. Kh4 Bc4 106. Bg5+ Kg7 107. Kg3 Kh7 108. Kh3
Bd5 109. Kh4 Bc4 110. Bc1 Bf1 111. Be3 Kg8 112. Kg5 Kf7 113. Kh5 Be2 114. Bh6
Kf6 115. Bg5+ Kg7 116. Bf4 Kg8 117. Bh6 Bf1 118. Kh4 Bg2 119. Kg3 Kh7 120. Be3
Bd5 121. g5 Kg7 122. Kg4 Kf7 123. Bf4 Be4 124. Bd2 Kg7 125. Bc1 Bd3 126. Kf4
Bf1 127. Bd2 Bh3 128. Ke5 Kf7 129. Bf4 Bg4 130. g6+ Kg7 131. Bg5 Bh3 132. Bf4
Bg2 133. Bg5 Bc6 134. Be3 Bd7 135. Bg5 Bc6 136. Bf4 Bb5 137. Ke6 Bd3 138. Bg5
Bc4+ 139. Ke5 Be2 140. Be3 Bd3 141. Bd2 Bc4 142. Bc1 Bf1 143. Bf4 Ba6 144. Bg5
Bb7 145. Bd2 Bc8 146. Bc1 Bd7 147. Be3 Bc6 148. Bd2 Bb5 149. Bf4 Ba4 150. Kd4
Kf6 151. Bh6 Be8 152. Kc3 Kxf5 153. Kxb3 c1=Q 154. Bxc1 Bxg6 155. Bd2 Ke4 156.
Ka4 Be8+ 157. Ka5 Kd3 158. Be1 Bc6 159. b3 Ke2 160. Bh4 Kd2 161. b4 Kc3 162. b5
Bxb5 163. Kxb5 1-0

**Comment by glennsamuel32** [comment]
Ignore the above post...
Did "python cut.py test2.pgn > C:\chess.pgn"
and it works fine.
Much obliged niklasf !!

**Comment by niklasf** [comment]
Yes, you can pass an opened writable file to `chess.pgn.FileExporter(open("out.pgn", "w"))` instead of `sys.stdout`. Or from the command line redirect the console output to a file: `python cut.py test2.pgn > out.pgn`. (Careful, both these invocations would overwrite and existing file!)
