### ISSUE TITLE
[HELP Wanted]

### ISSUE THREAD

**Issue by glennsamuel32** [niklasf/python-chess#304]
Hello @niklasf 

This request is more complex.
It is regarding the ChessOK IDea program -- http://chessok.com/?p=21230
This program does a deep analysis of the root node but can only output the results in a tree format (aqt) or into FEN positions.
As the aqt format is a closed proprietary format, could python-chess join the FEN positions to the pgn ?

For example, take the pgn below...

[Event "Soviet Union"]
[Site "Soviet Union"]
[Date "1977.??.??"]
[Round "?"]
[White "Garry Kasparov"]
[Black "Malshikov"]
[Result "1-0"]
[ECO "B39"]
[PlyCount "22"]
[EventDate "1977.??.??"]

1. e4 c5 2. Nf3 Nc6 3. d4 cxd4 4. Nxd4 g6 5. c4 Bg7 6. Be3 Nf6 7. Nc3 Ng4 8.
Qxg4 Nxd4 9. Qd1 Ne6 10. Rc1 d6 11. b4 O-O 1-0

The analysis has been done for white's next move -- move 12
I have exported it to epd...
[IDea.zip](https://github.com/niklasf/python-chess/files/2334494/IDea.zip)

Would it be possible to join the FEN positions to the pgn and output the resulting pgns ?

Thanks again niklasf...

**Comment by niklasf** [comment]
Unlike you're previous question (#303) there's no ready-made solution. `game.end().board()`, `board.push(move)`,  `board.fen()`, `board.pop()`, `game.end().add_variation(move)` might all come in handy and I am happy to answer questions about any of them.
