### ISSUE TITLE
Evaluation of board

### ISSUE THREAD

**Issue by MrTrushka** [niklasf/python-chess#305]
Hi. How can i get an evaluation of board? Like at image

![image](https://user-images.githubusercontent.com/16525914/45588247-646db600-b91a-11e8-838a-ba426c6a55b1.png)

**Comment by MrTrushka** [comment]
\>>> engine = chess.uci.popen_engine("stockfish")
\>>> info_handler = chess.uci.InfoHandler()
\>>> engine.info_handlers.append(info_handler)
\>>> engine.position(chess.Board())
\>>> engine.go(movetime=1000)
BestMove(bestmove=Move.from_uci('e2e4'), ponder=Move.from_uci('e7e6'))
\>>> info_handler.info["score"][1]
Score(cp=34, mate=None)

Is it an evaluation of 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'? 
or 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1'?

**Comment by ddugovic** [comment]
Take a look at https://github.com/rpdelaney/python-chess-annotator/blob/master/annotator/__main__.py#L182

**Comment by niklasf** [comment]
@MrTrushka It's the evaluation of the initial position, from the point of view of the side to move.
