### ISSUE TITLE
How to properly calculate the margin value for an application?

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#311]
@niklasf, please explain, why does the **margin** have to be **20**. In my code, if my **margin** value is **20** when coordinates are enabled, I get unwanted results (**the left mouse click does not select the proper square**). 

https://github.com/niklasf/python-chess/blob/2ed580d06d9cf72ce1f542eff888dc0578755a19/chess/svg.py#L145

Also, why **2 * margin**?

https://github.com/niklasf/python-chess/blob/2ed580d06d9cf72ce1f542eff888dc0578755a19/chess/svg.py#L146

Is there a formula to calculate this margin for my own application?

**Comment by niklasf** [comment]
The value is 20 when the square size is 45 or the total width of the image is 400. Perhaps you are scaling the board. The margin then scales proportionally.

```
margin = 20 * width / 400
```

There's twice the margin because there is a margin on the left *and* on the right, or on the top *and* bottom respectively.

**Comment by PedanticHacker** [comment]
And how can I get the real_width value?

**Comment by niklasf** [comment]
By `real_width` I mean the actual size of the image in your application. The default is 400.

**Comment by PedanticHacker** [comment]
Why don't you hardcode this in python-chess then? So like
`margin = 0.05 if coordinates else 0`

**Comment by niklasf** [comment]
Yes, it's all relative to something and could as well be relative to 1. But in absence of explicit width and height SVGs are rendered at the size of their internal coordinates. We don't want a board that's one pixel wide in that case ;)

**Comment by PedanticHacker** [comment]
Since my application's SVG chessboard is not 400×400, but rather 800×800 – does that mean my square size is bigger as well? For a 400×400 board, the square size is 45 – so is my square size then 90?

**Comment by niklasf** [comment]
Yes.

**Comment by PedanticHacker** [comment]
Is it possible to get the clicked square of the SVG board upon a mouse click? Say I click on the e4 square – how can I get what square have I clicked on? I’m coding in PyQt5 and using the QMousePressEvent.x() and QMousePressEvent.y() give me inaccurate results. The coordinates are off and the circle is drawn on the adjacent square, rather than the one I have clicked on, i.e. if my click is not made on the dead center of the square. I really need your assistance.

**Comment by niklasf** [comment]
This is out of scope for python-chess which is really not concerned with user interfaces.

Anyway, some advice: Try to make it work without the coordinate margin first. Once that works you can easily deal with the margin by adding or subtracting (depending on the coordinate system) the margin once to the x and y coordinates before doing your calculation.

**Comment by PedanticHacker** [comment]
`real_margin = 20 * real_width / 400`
Is this correct? In the case of calculating the real margin in my application I don't divide by 360? Please explain.
