### ISSUE TITLE
Colored arrows

### ISSUE THREAD

**Issue by kayhayen** [niklasf/python-chess#315]
First of all, thanks for the wonderful library that I enjoy using.

Would it be possible, acceptable, to expose the arrow color for SVG drawing as a method? I am aiming at coloring moves by popularity with multiple arrows.

```
            ET.SubElement(svg, "polygon", {
                "points": " ".join(str(x) + "," + str(y) for x, y in marker),
                "fill": "#888",
                "opacity": "0.5",
                "class": "arrow",
            })
```

Seems I want to modify `fill` and opacity. Using `Arrow` class has no point currently, so maybe nobody really doe, but adding elements to it, could break compatibility, I am not sure a namedtuple can have defaults on everything supported. So a `ColoredArrow` could be used. I would be willing to make the change myself, but are you willing to merge it for a stable release?

**Comment by niklasf** [comment]
Sounds good. We can make breaking changes between releases, so I wouldn't mind if `Arrow` can no longer be a named tuple. It should still be possible to allow simple (unnamed) tuples as arguments to `chess.svg.board(*, arrows=....)`.

**Comment by kayhayen** [comment]
In my dirty patch, I got away with as little as this:

```
-    for tail, head in arrows:
+    for arrow in arrows:
+        if len(arrow) == 2:
+            tail, head = arrow
+            color = "#888"
+        else:
+            tail, head, color = arrow
+
         tail_file = chess.square_file(tail)
         tail_rank = chess.square_rank(tail)
         head_file = chess.square_file(head)
@@ -233,7 +239,7 @@
                 "cy": str(yhead),
                 "r": str(SQUARE_SIZE * 0.9 / 2),
                 "stroke-width": str(SQUARE_SIZE * 0.1),
-                "stroke": "#888",
+                "stroke": color,
                 "fill": "none",
                 "opacity": "0.5",
             })
@@ -270,7 +276,7 @@
 
             ET.SubElement(svg, "polygon", {
                 "points": " ".join(str(x) + "," + str(y) for x, y in marker),
-                "fill": "#888",
+                "fill": color,
                 "opacity": "0.5",
                 "class": "arrow",

```

If the color needs to be in the arrow class, I would have to change that one as well, ideally in a way that it does change the `len()` and unpacking. Probably overloading `__init__` with arguments that have some defaults (still intending on adding opacity mayhaps), would be good enough to achieve that. Tuples suck at optional stuff. I am going to make `None` behave as `#888` then.

I didn't succeed in changing the color of the rectangle part of the array yet. I will try and turn this into a PR with a documentation update included, so you can properly play with it too and guide me there.
