### ISSUE TITLE
collections deprecation warning

### ISSUE THREAD

**Issue by rpdelaney** [niklasf/python-chess#318]
Running `pytest` on python-chess-annotator gives me this:

```
/usr/local/lib/python3.7/site-packages/chess/pgn.py:509
  /usr/local/lib/python3.7/site-packages/chess/pgn.py:509: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working      
    class Headers(collections.MutableMapping):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
pytest isn't telling me which of my tests triggered this warning. If you need to know I can dig into it more.

**Comment by niklasf** [comment]
Thanks. Fixed on 0.23.x and master, and will make sure to make (at least) one release before Python 3.8 is out (end of January).
