### ISSUE TITLE
Add support for the reversed() built-in on appropriate iterators

### ISSUE THREAD

**Issue by rpdelaney** [niklasf/python-chess#319]
https://docs.python.org/3/library/functions.html#reversed
```
reversed(seq)

    Return a reverse iterator. seq must be an object which has 
a __reversed__() method or supports the sequence protocol 
(the __len__() method and the __getitem__() method with integer 
arguments starting at 0).
```
As discussed offline, I'm planning on implementing support for this built-in with a PR when I can get the time.

Discussion in #95 might be relevant.

**Comment by niklasf** [comment]
It does a different thing now: It iterates over nodes, where it previously was iterating over nodes. So might as well change the name, which I always wanted to do anyway.
