### ISSUE TITLE
Feature Request: function to get the wdl index for a board

### ISSUE THREAD

**Issue by oscardssmith** [niklasf/python-chess#328]
I am currently using python-chess to prototype using a Neural Network based off of Leela Chess as a way to compress sysygy tables. This project would be much easier if there was a way from getting the index for a TB position from the board. Is there any easy way to do this? I understand that this probably isn't a widely desired feature, but having at least a non-exported method would make it much easier for me. Even better (although admittedly less likely) is a way to turn one of these indices into a valid fen or board. that has that index.  Thanks

**Comment by niklasf** [comment]
That sounds like an intresting use case. I somehow doubt that neural networks will be able efficiently compress Syzygy tables (let alone losslessly), but don't let that stop you.

As for the actual feature request: A Syzygy table can contain up to 8 (2 sides, 4 files for the leading pawn) subtables. An index into the appropriate subtable is computed, not an index into the whole table. So I am not sure if that helps you.

**Comment by oscardssmith** [comment]
The NN call easily get 98% accuracy. (I'm currently using general chess nets). the idea is that by storing that the net knows the answer. this should allow for much more effective rle

**Comment by oscardssmith** [comment]
I also decided to implement my own index system to better take advantage of repeated pieces.
