### ISSUE TITLE
engine.go(movetime = 2000) returns None

### ISSUE THREAD

**Issue by aditya1709** [niklasf/python-chess#333]
I am new to chess and chess engines in general. I am trying to integrate a chess engine with a GUI I built. After few successful exchange of moves with the engine, stockfish throws a None for bestmove and ponder.

**Comment by niklasf** [comment]
Just to confirm: The return value is `None` or `None, None`? The latter would indicate that there is just no legal move - mate or stalemate.

Probably will need code to reproduce this.
