### ISSUE TITLE
feature request: add an optional parameter search order to Game.accept 

### ISSUE THREAD

**Issue by till314** [niklasf/python-chess#334]
Visitors would be more useful (for me at least) if you were able to set the order in which variations are being visited. E.g. for

1.e4 (1. d4 (1.c4  c5) d5) e5

any of the orders below (currently you use 3 I believe) can be useful

1 e4 e5 d4 d5 c4 c5                            (main variation before sub-variations)
2 e4 d4 c4 c5 d5 e5                            (nested sub-variations)  
3 e4 d4 d5 c4 c5 e5                            (sequential sub-variations)

Adding an optional search_order parameter to accept (and perhaps accept_subgame) would be one 
way to achieve this. Another would be to an extra field search_order for visitors.

**Comment by niklasf** [comment]
The existing visitors would only work with PGN-order, so I don't think that's a good fit. The search_order field would prevent misuse, but can't be supported by `read_game`.

Maybe instead there could be iterators on `GameNode`? Would that work for your use case?

**Comment by niklasf** [comment]
Marking as wontfix for now. The use case is not super common, and it can relatively easily be implemented outside of python-chess. I would recommend doing that, instead of patching `GameNode.accept()`, but YMMV.
