### ISSUE TITLE
Convert InfoHandler.Info to SAN using Stockfish

### ISSUE THREAD

**Issue by MrT201509** [niklasf/python-chess#342]
Hi,
I have some trouble with the output from InfoHandler.Info. I wanted to generate a move-list such in other chess-programs e.g. 1. d4 d5 2. Nf3 e6 3. Ne5 ... 

The InfoHandler.Info-Output is 

"{1: [Move.from_uci('d2d4'), Move.from_uci('d7d5'), Move.from_uci('g1f3'), Move.from_uci('e7e6'), Move.from_uci('f3e5'), Move.from_uci('g8f6')]}"

I extract the move with the Python-Code:

class MyHandler(chess.uci.InfoHandler):
    def post_info(self):
        # Called whenever a complete info line has been processed.
        print(self.info['pv'])
        for item in self.info['pv']:
            print(self.info['pv'][item])
            for move in self.info['pv'][item]:
                print(board.san(move))
        super().post_info()   # Release the lock

For the first two moves the output is correct: "d4 d5 Nf3 e6". 
Exactly in the 3rd move UCI("f3e5") of the knight I get the following error message:

"File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chess/__init__.py", line 2458, in _algebraic
    san = PIECE_SYMBOLS[piece].upper()
TypeError: list indices must be integers or slices, not NoneType".

Probably I have some knots in my mind :) Good you please help me?

BTW: Thank you very much for this fantastic Python-Chess-Library. I'm creating a chess-program for training openings on my iMac, because there are no good program for this platform available. I use Python an the GraphicsView-Framework of Qt. The GUI for moving pieces is ready, so I want to integrate Stockfish as chess-engine. For move generation and validation, for the UCI- and PNG-and Polyglot-Integration I use your great Library.

Best wishes
Daniel

**Comment by niklasf** [comment]
Hi Daniel,

I think the issue is here:
```
for move in self.info['pv'][item]:
    print(board.san(move))
    # we have to do board.push(move) before computing the next san!
```

Try `print(board.variation_san(self.info["pv"][item]))` (or manually push).

Niklas

**Comment by MrT201509** [comment]
Hi Niklas,

 

thanks for your answer.

 

Your tipp is exactly what I need. Thanks a lot.

 

Greetings

Daniel

 

Datum: Samstag, 22. Dezember 2018 um 21:30
Cc: Daniel Nowak <Nowak.Daniel@gmx.de>, Author <author@noreply.github.com>

 

Hi Daniel,

I think the issue is here:
for move in self.info['pv'][item]:
    print(board.san(move))
    # we have to do board.push(move) before computing the next san!
Try print(board.variation_san(self.info["pv"][item])) (or manually push).

Niklas
