### ISSUE TITLE
Skipped tests show warnings when Crafty or Stockfish do not exist

### ISSUE THREAD

**Issue by niklasf** [niklasf/python-chess#349]
Upstream bug: https://bugs.python.org/issue35721

---

* [x] https://github.com/python/cpython/pull/11553

**Comment by Mk-Chan** [comment]
Related to the Travis stalling issue?

**Comment by niklasf** [comment]
It's a minor asyncio bug, only with the new engine API.

**Comment by niklasf** [comment]
Fixed in Python 3.7.
