### ISSUE TITLE
[RFE] Defense Functions for BaseBoard

### ISSUE THREAD

**Issue by themadhatterz** [niklasf/python-chess#354]
Unsure if the right place for feature asks.
I'm starting to work on my own bot to play chess and I really like the library!

Is there any intention to add defense oriented functions similar to the attacks/attacked functions in BaseBoard?

Like
BaseBoard.is_defended_by(self, color, square)

Thanks!

**Comment by Mk-Chan** [comment]
Defend and attack are exactly the same. Defense is attack by pieces of the same color as the piece on the square you're looking at, attack is by the opposite color.

**Comment by themadhatterz** [comment]
Ok I get it. So if I have a black piece, claim it as white and I'll get other black pieces that are defending it. Thanks for blowing my mind.
