### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by mtutnid** [niklasf/python-chess#355]
```
import chess.engine

board = chess.Board("r1b1k2r/1pqp1ppp/p1n1pn2/8/4P3/2NBB3/PPP1NPPb/R2Q1RK1 w kq - 0 10")
engine = chess.engine.SimpleEngine.popen_uci(r"C:\Program Files (x86)\Arena\Engines\LCZERO\lc0.exe")
info = engine.analyse(board, chess.engine.Limit(time=10))
print(info["score"])
```

Gives a keyerror for score if there is only one legal move (example FEN) with the Leela engine. Works fine with Stockfish 10. I'm not sure whether it's a problem with the Leela Engine, but I know that analysis mode with this engine in Chess Arena works fine.

**Comment by niklasf** [comment]
Can you please [enable logging](https://python-chess.readthedocs.io/en/latest/engine.html#logging) and share the output, just to be sure?

**Comment by mtutnid** [comment]
@niklasf I ommited the options as it would get lengthy.
```
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:chess.engine:<UciProtocol (pid=8336)>: Connection made
DEBUG:chess.engine:<UciProtocol (pid=8336)>: << uci
DEBUG:chess.engine:<UciProtocol (pid=8336)>: >> id author The LCZero Authors.
DEBUG:chess.engine:<UciProtocol (pid=8336)>: >> uciok
DEBUG:chess.engine:<UciProtocol (pid=8336)>: << position fen r1b1k2r/1pqp1ppp/p1n1pn2/8/4P3/2NBB3/PPP1NPPb/R2Q1RK1 w kq - 0 10
DEBUG:chess.engine:<UciProtocol (pid=8336)>: << go movetime 1000
WARNING:chess.engine:<UciProtocol (pid=8336)>: stderr >> Found pb network file: C:\Program Files (x86)\Arena\Engines\LCZERO/cecd7987b364d27030ad5a0baee86e1246871fdc6231844263c69d6e7a6db687
WARNING:chess.engine:<UciProtocol (pid=8336)>: stderr >> Creating backend [cudnn]...
DEBUG:chess.engine:<UciProtocol (pid=8336)>: >> bestmove g1h1
Traceback (most recent call last):
  File "enginetest.py", line 9, in <module>
    print(info["score"])
KeyError: 'score'
```

**Comment by niklasf** [comment]
Thanks. So @Mk-Chan was right, Lc0 simply didn't report any score :(

In this case you could use the (flipped) score the previous or following position. But I don't think python-chess should do that automatically. Or maybe the Lc0 devs could be convinced to handle this differently.

**Comment by mtutnid** [comment]
@Mk-Chan I doubt it as if I feed the same position twice I get back a centipawn value

```
import chess.engine
import logging

logging.basicConfig(level=logging.DEBUG)
engine = chess.engine.SimpleEngine.popen_uci(r"C:\Program Files (x86)\Arena\Engines\LCZERO\lc0.exe")
board = chess.Board("r1b1k2r/1pqp1ppp/p1n1pn2/8/4P3/2NBB3/PPP1NPPb/R2Q1RK1 w kq - 0 10")
info = engine.analyse(board, chess.engine.Limit(time=1))
board = chess.Board("r1b1k2r/1pqp1ppp/p1n1pn2/8/4P3/2NBB3/PPP1NPPb/R2Q1RK1 w kq - 0 10")
info = engine.analyse(board, chess.engine.Limit(time=1))
print(info["score"])
```
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:chess.engine:<UciProtocol (pid=11388)>: Connection made
DEBUG:chess.engine:<UciProtocol (pid=11388)>: << uci
DEBUG:chess.engine:<UciProtocol (pid=11388)>: >> id author The LCZero Authors.
DEBUG:chess.engine:<UciProtocol (pid=11388)>: >> uciok
DEBUG:chess.engine:<UciProtocol (pid=11388)>: << position fen r1b1k2r/1pqp1ppp/p1n1pn2/8/4P3/2NBB3/PPP1NPPb/R2Q1RK1 w kq - 0 10
DEBUG:chess.engine:<UciProtocol (pid=11388)>: << go movetime 1000
WARNING:chess.engine:<UciProtocol (pid=11388)>: stderr >> Found pb network file: C:\Program Files (x86)\Arena\Engines\LCZERO/cecd7987b364d27030ad5a0baee86e1246871fdc6231844263c69d6e7a6db687
WARNING:chess.engine:<UciProtocol (pid=11388)>: stderr >> Creating backend [cudnn]...
DEBUG:chess.engine:<UciProtocol (pid=11388)>: >> bestmove g1h1
DEBUG:chess.engine:<UciProtocol (pid=11388)>: << position fen r1b1k2r/1pqp1ppp/p1n1pn2/8/4P3/2NBB3/PPP1NPPb/R2Q1RK1 w kq - 0 10
DEBUG:chess.engine:<UciProtocol (pid=11388)>: << go movetime 1000
DEBUG:chess.engine:<UciProtocol (pid=11388)>: >> info depth 2 seldepth 2 time 24 nodes 2 score cp -111 hashfull 0 nps 41 tbhits 0 pv g1h1 h2d6
DEBUG:chess.engine:<UciProtocol (pid=11388)>: >> bestmove g1h1 ponder h2d6
-111

**Comment by mtutnid** [comment]
@Mk-Chan @niklasf Seems like you are right, but it's weird that you have to send the same command twice to force it to analyze the position

**Comment by niklasf** [comment]
That's wierd behavior, but by Lc0, not by python-chess. See how it sends info with score only the second time. Also after `time` 24 milliseconds, instead of the 1000 milliseconds it was told to think. Maybe the eval is in the hashtable the second time around?

**Comment by mtutnid** [comment]
No clue, I'll ask around at Lc0

**Comment by borg323** [comment]
This is the result of network loading taking some time to complete. lc0 loads the network when `ucinewgame` is received, but as a fallback also after the first `go` command. Note that `ucinewgame` should be followed by an `isready` command.
BTW, the actual lc0 bug (not printing an `info` line before `bestmove`) was fixed a few weeks ago, and should work with the latest release.

**Comment by niklasf** [comment]
@borg323 Thanks for the insight. Will fix and send ucinewgame as expected by Lc0.

**Comment by Mk-Chan** [comment]
I don't think the not printing any info is a bug so to say. My engines exhibit the same behavior

**Comment by niklasf** [comment]
@Mk-Chan Yeah, it's not a violation of the protocol, but a "bug" in the sense that it was not intended behavior.

@mtutnid Can you please confirm that 00c1fddb18d4e86092922fb4f0de6ad7e1cf145e fixes this by sending ucinewgame and waiting for the engine to be ready?

**Comment by mtutnid** [comment]
Will do it in 5 hours, when I'm home

**Comment by borg323** [comment]
In the UCI spec I see (in the `bestmove` description):
```
	Directly before that the engine should send a final "info" command with the final search information,
	the the GUI has the complete statistics about the last search.
```

**Comment by mtutnid** [comment]
> @mtutnid Can you please confirm that [00c1fdd](https://github.com/niklasf/python-chess/commit/00c1fddb18d4e86092922fb4f0de6ad7e1cf145e) (pushed to master) fixes this by sending ucinewgame and waiting for the engine to be ready?

Works nicely when I use game identifiers

**Comment by niklasf** [comment]
Awesome, thanks for the initial report and testing!

(And latest master will also send ucinewgame once, if not using game identifiers.)
