### ISSUE TITLE
[RFC] Engine API extension: inject FEN and evaluation

### ISSUE THREAD

**Issue by ddugovic** [niklasf/python-chess#356]
A friend who plays correspondence chess wondered if there is a way to inject into an engine's hash table a (FEN, depth, evaluation) tuple so he can force the engine to stop searching drawn (or suspected to be drawn) positions.

As far as I know this isn't part of the XBoard or UCI protocols, nor am I aware of any engine currently supporting it (if I add this capability to my SF fork, I'll advise) but it does sound like a useful feature for long-running analyses.  Actually, being able to extract the same could also be useful.

**Comment by niklasf** [comment]
Something similar is in fact part of the XBoard protocol:

> **setscore SCORE DEPTH**
>
> This command instructs the engine to treat future search requests on the current position (also when it is encountered inside a larger search tree) upto the given DEPTH as if these result is SCORE centi-Pawn in favor of the side that has the move in this position. It is entirely up to the engine to decide when the effect of this option should expire. (E.g. it could last upto the next "new" or "quit" command, or even into future sessions until the user explicitly clears it through an engine-defined option.) This command will only be sent to engines that have requested it through the setscore feature.

-- https://www.gnu.org/software/xboard/engine-intf.html

However I am not aware of any XBoard engine that actually supports it, nor is it part of the UCI protocol, which probably means we're out of luck.

You could hack something like that for SF, either through UCI options (say some input options for FEN and score and depth, and a button, or an option for an input CSV file with a list of positions and scores), or a custom UCI command. python-chess would support the former, or `protocol.send_line("custom command")` for the custom command.

**Comment by Mk-Chan** [comment]
I wouldn't inject into the TT since that can be overwritten. Perhaps we could offer a parameter which python-chess itself handles and prevents the engine from searching at all.

**Comment by niklasf** [comment]
In any case the engine has to support it.
