### ISSUE TITLE
Standalone Python-Chess 

### ISSUE THREAD

**Issue by rsocor01** [niklasf/python-chess#358]
Hi,

I'm working on a chess program that uses Python Chess to do chess move validations. I'm using a console in my program to read back the output from Python Chess. If I want to send this program to someone else, they would need to install Python in their PCs. Is there a way to get around this issue? The most obvious solution would be to have a standalone executable version of Python Chess, but I don't know if it exists. Any help is greatly appreciated. 

Thank you, 

Robert

**Comment by gbtami** [comment]
Read this https://docs.python-guide.org/shipping/freezing/
Maybe try http://www.pyinstaller.org first.

**Comment by niklasf** [comment]
> I'm using a console in my program to read back the output from Python Chess.

Which programming language are you using to do that?

**Comment by rsocor01** [comment]
Niklasf, I'm using Visual Studio, VB.NET. I can read the output of a command prompt console. I'm entering one line python commands and reading the output back in VB.Net. It works.

Pyinstaller looks promising. I'll check on that.

**Comment by scitronboy** [comment]
Also this isn't really specific to python-chess. You might have better luck asking somewhere else, like a VB.NET forum.

**Comment by rsocor01** [comment]
scitronboy, yes, this is specific to Python-Chess since I'm trying to run Python-Chess in a target computer without forcing the user to install Python in his computer.

After doing some research I started playing with PyInstaller. PyInstaller doesn't work with functions, but it works with sys.argv. I wrote my own small scripts that call Phython-Chess using sys.argv and so far it is working fine. :)

**Comment by scitronboy** [comment]
@rsocor01 no it isn't specific to python-chess because it is specific to _any_ python module.

**Comment by niklasf** [comment]
I agree with @scitronboy, it would be the same for packaging and using any other pure Python library.

Also I have to say this is an unusual thing to do. I don't know VB.NET, but there must be some way to get this done within the language or at least within the .NET ecosystem ... On the other hand, if you get it working, why not? :man_shrugging:
