### ISSUE TITLE
Convert UCI string to string

### ISSUE THREAD

**Issue by rayran1234** [niklasf/python-chess#359]
I had a question about checking for UCI string outputs. I can't seem to compare the output of the UCI string. Is there a way to convert the UCI string into a regular string? I know that UCI string isn't a regular string. I hoping to be able to convert a UCI string into a string and also convert a string into a UCI string.

I get the following error when I perform the code below:

```
> elf len(uci) == 4 and '@' == uci[1]:
> TypeError: object of type 'Move has no len()
```

```python
move = self.engine.go(movetime=2000, depth = self.level).bestmove
temp_move = chess.Move.from_uci(move)
    if temp_move == "g8f6":
        print("HELLO")
    else:
        print("NOOO")
```

**Comment by rayran1234** [comment]
Hi,
Thank you for the help. Also, I'm using UCI engine communication because I've been working on it lately. I may switch to the new engine API once I've finished this task.

Also, I have another question, when I try to export a game, I seem to be getting an error.

> assert piece_type, "san() and lan() expect move to be legal or null, but got {}". format(move,self.fen())

```
game = chess.pgn.Game()
game.headers["Event"] = "Example PGN game "
game.headers["Date"] = "2/4/2019"
game.headers["White"] = "Player1"
game.headers["Black"] = "AI"
node = game 

Nf3 = chess.Move.from_uci("g1f3")
board.push(Nf3)
node = game.add_variation(Nf3)   #To update pgn file with new moves
node = node.add_variation(Nf3)   #may not actually need this

new_pgn = open("./test.pgn", "w", encoding="utf-8") 
exporter = chess.pgn.FileExporter(new_pgn)
game.accept(exporter)
```
But when I do the following, my Results section is empty

>  [Result "*"]

```
game = chess.pgn.Game()
game.headers["Event"] = "Example PGN game "
game.headers["Date"] = "2/4/2019"
game.headers["White"] = "Player1"
game.headers["Black"] = "AI"
new_pgn = open("./test.pgn", "w", encoding="utf-8") 
exporter = chess.pgn.FileExporter(new_pgn)
game.accept(exporter)
node = game 

Nf3 = chess.Move.from_uci("g1f3")
board.push(Nf3)
node = game.add_variation(Nf3)   #To update pgn file with new moves
node = node.add_variation(Nf3)   #may not actually need this
```

**Comment by niklasf** [comment]
For the first issue, the error message should contain more context, including a stacktrace with the line that triggered the issue, the move and the FEN of the position. In any case it seems to be caused by this:

```python
node = node.add_variation(Nf3)   #may not actually need this
```
That's like playing `1. Nf3 Nf3`, which is not legal.

For the second issue, you can set `game.headers["Result"]` just like any other header. In particular:
```python
game.headers["Result"] = board.result()
```

There's also a shortcut for creating all those variations, if you have a `board` that the entire game has been played on:
```python
game = chess.pgn.Game.from_board(board)
game.headers["Event"] = ...
```

**Comment by rayran1234** [comment]
Thank you for your help!
