### ISSUE TITLE
Tablebase probing

### ISSUE THREAD

**Issue by hsartliam** [niklasf/python-chess#36]
Hi,

I have a question concerning the probing of syzygy tablebases. The method probe_dtz sometimes takes more than 10 times longer depending on which side is to move. E.g. with the code below I get approximately 0.05s for white to move and 1.5s for black to move. Am I missing something or is this kind of strange?

    import chess, chess.syzygy
    import time

    with chess.syzygy.Tablebases("data/syzygy") as tb:
        start = time.time()
        for i in range(100):
            tb.probe_dtz(chess.Board("8/8/3rk3/8/8/2Q1K3/8/8 w - - 0 1"))
        end = time.time()

        start2 = time.time()  
        for i in range(100):           
            tb.probe_dtz(chess.Board("8/8/3rk3/8/8/2Q1K3/8/8 b - - 0 1"))
        end2 = time.time()

    print(end - start, end2 - start2)

**Comment by niklasf** [comment]
Hi,

this is not unexpected. I can reproduce your results: `0.05317807197570801 1.009963035583496`

From the point of view of a tablebase those are two completely different positions.

[8/8/3rk3/8/8/2Q1K3/8/8 w - - 0 1](https://syzygy-tables.info/?fen=8/8/3rk3/8/8/2Q1K3/8/8%20w%20-%20-%200%201) is DTZ 39 and takes about 400 loops in [decompress_pairs()](https://github.com/niklasf/python-chess/blob/master/chess/syzygy.py#L765).
[8/8/3rk3/8/8/2Q1K3/8/8 b - - 0 1](https://syzygy-tables.info/?fen=8/8/3rk3/8/8/2Q1K3/8/8%20b%20-%20-%200%201) is DTZ 44 and takes about 4500 loops.

This is the kind of thing that is blazingly fast in C, but accessing the memory map in each iteration is very slow in Python. It would be worthwhile trying to micro-optimize that main loop to improve the overall performance and reduce the gap between probing times.

By the way the positions with [completely swapped colors](https://syzygy-tables.info/?fen=8/8/3RK3/8/8/2q1k3/8/8%20b%20-%20-%200%201) indeed have the expected symmetry for DTZ and decompression time.

Best,
Niklas

**Comment by hsartliam** [comment]
Thanks.
