### ISSUE TITLE
Missing chess.engine in PIP loaded version

### ISSUE THREAD

**Issue by alohawild** [niklasf/python-chess#360]
I tried to find how I might have created the problem. It appears just not to work....

```
Traceback (most recent call last):
  File "/Users/blah/PycharmProjects/wildchess/stockfish.py", line 2, in <module>
    import chess.engine
ModuleNotFoundError: No module named 'chess.engine'
```

code from an example:

```python
import chess
import chess.engine

engine = chess.engine.SimpleEngine.popen_uci("stockfish")

board = chess.Board()
while not board.is_game_over():
    result = engine.play(board, chess.engine.Limit(time=0.100))
    board.push(result.move)

engine.quit()
```

Have no way forward as I can load libraries except Engine.

**Comment by niklasf** [comment]
Hi, can you please check and provide the output of the following program?

```
import chess

print(chess.__version__)
```

**Comment by alohawild** [comment]
Using pycharm...On Mac...

/Users/blah/anaconda3/bin/python /Users/blah/PycharmProjects/wildchess/version.py
0.24.2

**Comment by niklasf** [comment]
That explains it. The new `chess.engine` API has only been introduced recently, in version 0.25.0. `pip install --upgrade python-chess` should update to the latest version.

**Comment by alohawild** [comment]
Sorry for missing the update. It is working fine now.

**Comment by alohawild** [comment]
Pycharm working on mac after using:
pip install --upgrade python-chess --user
