### ISSUE TITLE
Add individual square corner constants/methods

### ISSUE THREAD

**Issue by scitronboy** [niklasf/python-chess#363]
It would be useful (at least for my application) to have constants for the corners of individual squares (there would be 81: 9 x 9). I realize this is would be trivial and usually pointless, but if I submitted a PR with my ideas would there be a chance of it being accepted? We could even create another module to hold it, i.e. `chess.extra` or `chess.other` . Here's **one example** of a possible method/function:
    
lower left corner of A1 would equal 0
upper right corner of H8 would equal 80

then to compute the corner of a square:

    # generic corner constants
    CORNER_LL = 0 # lower left
    CORNER_LR = 1 # lower right
    CORNER_UL = 9 # upper left
    CORNER_UR = 10 # upper right

    def corner_of(square, corner):
        return square + square // 8 + corner

then `corner_of(chess.SQUARE, chess.GENERIC_CORNER_CONSTANT)` would return the integer id for that corner. For example, `corner_of(chess.H8, chess.CORNER_UR)` would return `80`, the upper right corner of square H8.

There could be other methods for using square corners, too (like getting the corner of a square that is closest to a certain other square, for example). Do you think there would be any point incorporating features like this into python-chess? (I would use this feature for board navigation algorithms.)

By the way, congratulations on the amazing repo/module! It's really useful.

**Comment by niklasf** [comment]
Thanks for considering to upstream this. It feels a bit too specialized to include, and I don't really want to start `chess.extra`.

**Comment by scitronboy** [comment]
I do agree. If I think of anything else that would make this idea worth it, I'll comment again. Thanks for considering the idea!
