### ISSUE TITLE
what should I use instead of _stack

### ISSUE THREAD

**Issue by kohlerm** [niklasf/python-chess#364]
stack got renamed to _stack which should not be used. What should I use instead?

**Comment by niklasf** [comment]
How have you been using `stack`?

**Comment by kohlerm** [comment]
https://github.com/so-much-meta/lczero_tools/blob/master/src/lcztools/_leela_board.py 
does
Changing it _stack seems to work

**Comment by kohlerm** [comment]
Ok maybe it does not really need it. That code does not make sense to me

**Comment by niklasf** [comment]
Ok ... so it looks like `LeelaBoard` already uses internals like `_transposition_key`. So I guess it might as well use `_stack`. It will work fine. The only issue is that I don't want to guarantee API stability of these implementation details.

If you can avoid using "private" methods that's even better.

**Comment by niklasf** [comment]
Would adding a new `history` parameter to `board.copy(...)` help simplifying this?

**Comment by kohlerm** [comment]
@so-much-meta What do you think?

**Comment by niklasf** [comment]
In any case this feature is now included in v0.26.0. Let me know if it does not suffice.
