### ISSUE TITLE
extracting comments from a PGN

### ISSUE THREAD

**Issue by ChrisWhittington** [niklasf/python-chess#367]
after .....

```python
game=chess.pgn.read_game(pgn)
board=game(board)
for move in game.mainline_moves():
 board.push(move)
```

I'm stumped as to how get at the comments, evaluation etc that's in the PGN for each move

is there any example code?
thanks, probably I'm overlooking something

**Comment by niklasf** [comment]
Use `for node in game.mainline():` and there will be `node.move`, `node.comment` [etc](https://python-chess.readthedocs.io/en/latest/pgn.html#chess.pgn.GameNode).

**Comment by ChrisWhittington** [comment]
Thanks, works perfectly
