### ISSUE TITLE
SVG drawing

### ISSUE THREAD

**Issue by ChrisWhittington** [niklasf/python-chess#368]
1. chess.svg.board(board=board, squares=squares)

if square set includes the position of a black piece, the black cross is unviewable against the black piece. Save for a little pixel or two if the piece is small enough to not cover the X.

not quite sure what to suggest as a fix. Maybe XOR against piece colour, or check if square black occupied and use white cross.

2. Does anybody know a good viewer for svg? At the moment I put them into a browser, but then have to refresh the browser. Sumatra, which is good as an auto-updating PDF viewer won't accept svg files, and I've so far (using svglib) not been able to convert svg to pdf

3. How to display several svg's on one page?

**Comment by ChrisWhittington** [comment]
1; addendum, Black X on White KIng background not very visible

**Comment by niklasf** [comment]
(1) How about a little white border?

![image](https://user-images.githubusercontent.com/402777/53680067-2866bb80-3cd6-11e9-88ae-3cc9847c9c6c.png)

(2, 3) I'd recommend using [jupyter-notebooks](https://jupyter.org/). It works very well with Python. See the screenshot above, or this example: https://jupyter.brynmawr.edu/services/public/dblank/CS371%20Cognitive%20Science/2016-Fall/Programming%20a%20Chess%20Player.ipynb

**Comment by ChrisWhittington** [comment]
1. thanks, looks good.

2. I'm using VS2015, mostly because it handles joint Python, C+ relatively easily. But, unless I didn't find it yet, there's no built in console screen. Well, maybe there is, but hunting down features in VS is very tedious. It's main disadvantage is debugging, single step and so on, is practically impossible because it requires MS symbol tables (download times in rural France terrible) and program running in debug mode is incredibly slow as to be unusable. I usually switch from Jupyter to VS when program reaches a certain siorze I want C+ features
