### ISSUE TITLE
Can the application be deployed on Openshift? Am facing errors while deploying.

### ISSUE THREAD

**Issue by srini1986** [niklasf/python-chess#370]
Can the application be deployed on Openshift? Am facing errors while deploying.
ERROR: don't know how to run your application.
--
Please set either APP_MODULE, APP_FILE or APP_SCRIPT environment variables, or create a file 'app.py' to launch your application.
oc new-app https://github.com/niklasf/python-chess.git
Am trying to deploy this as an openshift application. Can someone help me with this please?

**Comment by niklasf** [comment]
This is a library, not an application. I am not sure what you would expect it to do, once it is deployed.

**Comment by srini1986** [comment]
I am sorry. I mistook this as an application for a game of chess that can be deployed. I am just trying to deploy pre-built applications from github just to see how it has been built and how it works. Thank you for the clarification.
