### ISSUE TITLE
Engine.analyse does not respect multipv argument

### ISSUE THREAD

**Issue by svangordon** [niklasf/python-chess#372]
Currently, it is not possible to get multiple positions by passing a `multipv` argument to `EngineProtocol.analyse`. As follows:

```
import chess
import chess.engine

multipv = 3
engine = chess.engine.SimpleEngine.popen_uci("stockfish", debug=True)
board = chess.Board("r2qr1k1/pb2npp1/1pn1p2p/8/3P4/P1PQ1N2/B4PPP/R1B1R1K1 w - - 2 15")
analyse = engine.analyse(board, chess.engine.Limit(depth=20), multipv=3)
analysis = engine.analysis(board, chess.engine.Limit(depth=20), multipv=3)
print("multipv value:", multipv)
print('number of analyse lines:', len(analyse))
print('number of analysis lines:', len(analysis.multipv))
# multipv value: 3
# number of analyse lines: 1
# number of analysis lines: 3

engine.quit()
```

I'm pretty sure that the source of the error is in the [way that `EngineProtocol.analyse` calls `EngineProtocol.analysis`](https://github.com/niklasf/python-chess/blob/master/chess/engine.py#L740). `EngineProtocol.analyse` takes a `multipv` argument, but it doesn't pass that argument to `EngineProtocol.analysis`, so `EngineProtocol.analysis` will always run with the default `multipv` argument:
```
analysis = yield from self.analysis(board, limit, game=game, info=info, root_moves=root_moves, options=options)
```
Because there's no way to set the `MultiPV` option, as it is a managed option and trying to set it throws `EngineError: cannot set MultiPV which is automatically managed`, this will always be one.

I'm pretty sure that all that's needed to fix it is to pass the `multipv` argument to `analysis`. I'd be happy to submit a pull request!

**Comment by niklasf** [comment]
Thanks. Excellent bug report and the issue was exactly that.
