### ISSUE TITLE
2-fold repetition

### ISSUE THREAD

**Issue by ChrisWhittington** [niklasf/python-chess#373]
2-fold repetition checker would be very useful, maybe in two parts. A quick and dirty one that just look for pieces shuffling (eg not using hash indeces) and if that came back true, then user option to call the slower hashed version to verify.

**Comment by niklasf** [comment]
Added a simple version as `Board.is_repetition(count=3)`.

(cc @QueensGambit, since the possibility of adding an API like this came up in our discussion on #338)

**Comment by QueensGambit** [comment]
Thank you for the notification!
