### ISSUE TITLE
Calling Game.setup(board) returns an error 

### ISSUE THREAD

**Issue by forhavu** [niklasf/python-chess#374]
I'm reading from a pgn file with multiple games, and I'm checking the header to create a variant board and then calling game.setup(board) to update the board to the variant.

Here is the relevant code 
```game = chess.pgn.read_game(pgn)
        variant = game.headers["Variant"]
        board = chess.variant.find_variant(variant)
        game.setup(board)
```

and here is the error I get

```Traceback (most recent call last):
  File "main.py", line 55, in <module>
    game.setup(board)
  File "/home/forhavu/.local/lib/python3.5/site-packages/chess/pgn.py", line 429, in setup
    fen = board.fen()
TypeError: fen() missing 1 required positional argument: 'self'
```

As far as I can tell this shouldn't be an issue with my own code, but I apologize if it is.  Not entirely sure what is going on.

**Comment by niklasf** [comment]
`find_variant` will return a class, but `game.setup()` requires an instance.

```
VariantBoard = chess.variant.find_variant(variant)
board = VariantBoard()
game.setup(board)
```

Depending on the context there might also be a better way to do this.

**Comment by forhavu** [comment]
Well this is embarassing - seems I've made an extra silly mistake.  Reading the pgn already made the board the correct variant board, I psyched myself and thought I needed to do these extra steps.  Sorry to waste time, thanks for the help :)
