### ISSUE TITLE
Pin detection

### ISSUE THREAD

**Issue by fsmosca** [niklasf/python-chess#375]
Trying to generate positions where the side to move pins one or more of the pieces of the side not to move, using is_pinned(color, square). Example.
r4r2/pp1q1ppk/5b1p/2p1pP1Q/2Pp2R1/1P1n2P1/P2N1P1P/R1B3K1 w - - 0 1 
![image](https://user-images.githubusercontent.com/22366935/54288532-97031d80-45e2-11e9-853e-7edbaeb2020c.png)
White to move, it seems like the white Queen on H5 pins the black pawn at H6. If so, I think it is wrong because the black pawn at H6 has nothing to capture a white piece at G5.

An example where a pawn is pinned by a queen.
![image](https://user-images.githubusercontent.com/22366935/54289971-1d206380-45e5-11e9-96fe-fbca672bff35.png)
Ref. https://en.wikipedia.org/wiki/Pin_(chess)

**Comment by niklasf** [comment]
Thanks for reporting. What you're seeing is actually intended. `pin()` and `is_pinned()` are quite low level, not considering the possible movements of the piece at all. (It can even be used without any piece on the given square).

> Detects if the given **square** is pinned to the king of the given color.

**Comment by fsmosca** [comment]
Whether it is intended or not, the pinned pawn is still wrong. Anyway I skipped detecting a pinned piece if it is a pawn.
