### ISSUE TITLE
Inconsistent parsing of epd

### ISSUE THREAD

**Issue by fsmosca** [niklasf/python-chess#376]
Given epd1 with bm in uci format.
```
epd1='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - bm e2e4;'

b, ei = chess.Board().from_epd(epd1)

ei['bm']
[Move.from_uci('e2e4')]

```
No problem, but for epd2 with same bm uci format but different move there is problem.
```
epd2='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - bm b1c3;'

b, ei = chess.Board().from_epd(epd2)
Traceback (most recent call last):
...
ValueError: illegal san: 'b1c3' in rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
```

In epd1 the correct bm is e4.

**Comment by gbtami** [comment]
e2e4 is valid SAN but b1c3 is not and EPD expects to use SAN.
http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c16.2.4

**Comment by fsmosca** [comment]
I can see this regarding SAN.

> 8.2.3.3: Basic SAN move construction
> A basic SAN move is given by listing the moving piece letter (omitted for pawns) followed by the destination square. Capture moves are denoted by the lower case letter "x" immediately prior to the destination square; pawn captures include the file letter of the originating square of the capturing pawn immediately prior to the "x" character.

**Comment by niklasf** [comment]
That's correct, so strictly speaking it would have to be:

```
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - bm Nc3;
```

However the current master branch does (and the next release will) also accept UCI notation.
