### ISSUE TITLE
KeyError exception

### ISSUE THREAD

**Issue by pascalgeo** [niklasf/python-chess#377]
I think there is a missing colon in engine.py, line 1687:the following should work
engine.send_line("level {} {}:{:02d} {}".format(limit.remaining_moves or 0, base_mins, base_secs, increment))

**Comment by niklasf** [comment]
Thanks for reporting.

**Comment by pascalgeo** [comment]
Thank you. I confirm I can now play with an xboard engine like Phalanx connected to a real wooden board (Novag Citrine) which is great.
