### ISSUE TITLE
Wrong time per move for xboard engine

### ISSUE THREAD

**Issue by pascalgeo** [niklasf/python-chess#378]
When setting a fixed time per move with an xboard engine, for example with 
`chess.engine.Limit(time=4) `
I notice the engine gets 100 times that value, where the correct command is `st 4`
The offending code may be at line 1703 in engine.py : 
`engine.send_line("st {}".format(int(limit.time * 100)))`
Other surrounding lines may be also to be checked.
This bug raises this kind or error : 
File "/usr/lib/python3.5/asyncio/tasks.py", line 404, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by scitronboy** [comment]
I think that's because most engines use hundredths of a second for their time limit unit?

**Comment by pascalgeo** [comment]
Refering to [http://hgm.nubati.net/CECP.html](url), or [http://www.open-aurec.com/wbforum/WinBoard/engine-intf.html#11](url) time is in second. I checked with gnuchess and phalanx, both use seconds.

**Comment by niklasf** [comment]
Ugh ... the CECP spec uses centiseconds almost everywhere, but not here. Fixed.
