### ISSUE TITLE
Horde Chess false STATUS_PAWNS_ON_BACKRANK status

### ISSUE THREAD

**Issue by Wisling** [niklasf/python-chess#381]
variant.py line 459
if not self.pawns & chess.BB_RANK_8 and not self.occupied_co[chess.BLACK] & chess.BB_RANK_1:
(don't remove flag if any black pieces are on rank 1)
should be
if not self.pawns & chess.BB_RANK_8 and not self.occupied_co[chess.BLACK] & self.pawns & chess.BB_RANK_1:
(don't remove flag if any black pieces that are pawns are on rank 1)

**Comment by niklasf** [comment]
Thanks, good catch!

**Comment by ddugovic** [comment]
Apologies if this is a dumb question, but does the Horde variant also support old Lichess games (where Black was a horde of pawns)?

**Comment by niklasf** [comment]
Here only White can be the Horde. (At least until someone actually needs it, and requests or implements it.)
