### ISSUE TITLE
[Help] Update zobrist hash with move

### ISSUE THREAD

**Issue by matjazmav** [niklasf/python-chess#383]
Is there a function that update previously calculated zobrist hash with move? I couldn't found one, so I'm trying to implement one my self, but I don't understand indexing that function `hash_board` uses.

I had overriden method `ZobristHasher.__call__` to call just `hash_board` method, because I care only about figure positions on the board.

This is `hash_board` snippet from [here](https://python-chess.readthedocs.io/en/latest/_modules/chess/polyglot.html).

```
def hash_board(self, board):
  zobrist_hash = 0

  for pivot, squares in enumerate(board.occupied_co):
    for square in chess.scan_reversed(squares):
      piece_index = (board.piece_type_at(square) - 1) * 2 + pivot
      zobrist_hash ^= self.array[64 * piece_index + square]

  return zobrist_hash
```

So I have implemented following function, but I'm not sure how can I calculate `i_pivot` and `j_pivot`.
```
def update_zobrist_hash(hash, board: chess.Board, move: chess.Move, *, _table=POLYGLOT_RANDOM_ARRAY):
  
  # how to properly calculate i_pivot & j_pivot?                 
  i_pivot = move.from_square
  i = (board.piece_type_at(move.from_square) - 1) * 2 + i_pivot
  hash ^= _table[64 * i + move.from_square]

  j_pivot = move.to_square
  j = (board.piece_type_at(move.to_square) - 1) * 2 + j_pivot
  hash ^= _table[64 * j + move.to_square]

  return hash 
```

Can someone give me some tip? Thanks :)

**Comment by Mk-Chan** [comment]
So that's a partial update, you need to update castling rights, enpassant, side to move and xor out a piece if captured as well

**Comment by matjazmav** [comment]
@Mk-Chan I want to hash only figure position on board.

**Comment by Mk-Chan** [comment]
Ok then I guess you on have to handle the castling case (because the room also moves)

**Comment by niklasf** [comment]
A compromise would be to hash positions incrementally, but compute and xor the hashes for en passant and castling rights from scratch. This is what python-chess was doing, before incremental hashing was removed.
