### ISSUE TITLE
Mild bug(?) / inaccuracy in PGN exporter

### ISSUE THREAD

**Issue by serversideapps** [niklasf/python-chess#384]
https://lichess.org/forum/lichess-feedback/mild-bug--inaccuracy-in-python-chess-pgn-exporter#1

**Comment by niklasf** [comment]
I added a test for this (abaf369cd2c5670d3802aa0de2443f27b9dfdcf7), but it passes. Do you have a reproducible example?

**Comment by serversideapps** [comment]
This report was a blunder on my part. Exporting with `columns=None` indeed fixed my problem, but the problem itself was not the fault of your project. Sorry about that.
