### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by pascalgeo** [niklasf/python-chess#386]
First I confirm xboard handling is working correctly, checked with hundreds of games.
I encountered an exception when Phalanx plays against Crafty, exception raised because Phalanx did not played in the assigned time + 10 sec (if I understood python-chess code correctly).

If I send 'st 3' to Phalanx it replies by 'Setting **average** time to 3.000000 seconds' which is wrong, 3 sec is mandatory, not an average. In this simple position 'setboard 8/2R5/8/8/1Pk5/4KB2/8/8 b - - 2 85' Phalanx takes too long to reply with black and it replies for example 'move c4b5' but too late (20 sec), triggering the error 'concurrent.futures._base.TimeoutError'. In that case, either my program handles the error, or would it be a good option to automatically have the faulty engine lose the game in python-chess code ?
So either there is a new parameter in engine.play() like 'autoAdjudicateOnTimeOut=False', or it would be nice to add a comment in the documentation stating that the exception TimeoutError has to be handled by the user.

**Comment by niklasf** [comment]
Yes, that's correct.

It's briefly mentioned way down in the fine print: https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.SimpleEngine. A nicer alias for the exception type is `asyncio.TimeoutError`.

**Comment by pascalgeo** [comment]
Thank you for the explanation, I had not notice this part of the documentation.
