### ISSUE TITLE
parallel/delayed with uci engines

### ISSUE THREAD

**Issue by ChrisWhittington** [niklasf/python-chess#387]
problems with using in parallel, engines ....
engines = []
for i in range(n_workers):
            engines.append(chess.engine.SimpleEngine.popen_uci(rootdir + 'UCI-Chess-Engines/stockfish-10-win/Windows/' + 'stockfish_10_x64'))
....
            n_epd = len(input_epd_list)
            n_chunk = int(n_epd / n_workers)
            output_epds = Parallel(n_jobs=n_workers)(delayed(evaluate_epds)\
                (input_epd_list[id*n_chunk : min((id+1)*n_chunk, n_epd)], engines[id]) for id in range(n_workers))

Works fine for n_workers = 1, but falls over for n_workers = 2
streams of Python errors, like:
TypeError: can't pickle _thread.lock objects
_pickle.PicklingError: Could not pickle the task to send it to the workers.
Exception in thread QueueFeederThread:

**Comment by niklasf** [comment]
Looks like joblib tries to seralize the function and everything it captures, but `EngineProtocol` is not serializable. There might be workarounds, but how about switching from `SimpleEngine` to the async API? For example:

```python
import asyncio
import chess
import chess.engine

async def main():
    tasks = [
        "6k1/pb3pp1/1p2p2p/1Bn1P3/8/5N2/PP1q1PPP/6K1 w - - 0 24",
        "5R2/3P4/8/8/7r/7r/7k/K7 w - - 0 1",
        # ...
    ]

    results = {}

    async def worker():
        _, engine = await chess.engine.popen_uci("stockfish")

        while tasks:
            fen = tasks.pop()
            board = chess.Board(fen)
            results[fen] = await engine.analyse(board, chess.engine.Limit(time=1.0))

        await engine.quit()

    n_workers = 2
    await asyncio.gather(*(consumer() for _ in range(n_workers)))
    print(results)

asyncio.set_event_loop_policy(chess.engine.EventLoopPolicy())
asyncio.run(main())
```

**Comment by ChrisWhittington** [comment]
ok, thanks, I'll give that a go in the next few days and report back
