### ISSUE TITLE
Status of uci.py?

### ISSUE THREAD

**Issue by i-tub** [niklasf/python-chess#389]
While browsing through the repository, I was surprised not to find chess/uci.py, so I looked at the history, and found it was removed around v0.26.0. I'm not objecting to that, but what seemed strange to me was that I have installed 0.27.3 (using pip), and it still has that file! So has it been truly removed, or not? The commit tagged v0.27.3 does _not_ have the file.

I suppose I need to update my script to use the new API anyway...

**Comment by scitronboy** [comment]
The latest version does not have uci.py.  Instead, it has engine.py which
contains uci and xboard.

**Comment by niklasf** [comment]
Yep, that's correct.

To be sure I just confirmed that the recent archives published on PyPI do not contain `uci.py`. It's wierd that pip left the old file lying around.

**Comment by i-tub** [comment]
Interesting, I just went to https://pypi.org/project/python-chess/#files and downloaded both files. The tarball doesn't have uci.py, but the wheel does:

    $ wget https://files.pythonhosted.org/packages/71/a8/c22e1cdc1de9b2a5a9dcdbcb2450775c7ee003439f25a6f6cb9c6e548f81/python_chess-0.27.3-py3-none-any.whl
    --2019-03-26 12:54:46--  https://files.pythonhosted.org/packages/71/a8/c22e1cdc1de9b2a5a9dcdbcb2450775c7ee003439f25a6f6cb9c6e548f81/python_chess-0.27.3-py3-none-any.whl
    Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.21.63, 2a04:4e42:46::319
    Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.21.63|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 143747 (140K) [binary/octet-stream]
    Saving to: ‘python_chess-0.27.3-py3-none-any.whl’

    100%[=======================================================================================================================================================================================================================================>] 143,747     --.-K/s   in 0.004s

    2019-03-26 12:54:46 (33.7 MB/s) - ‘python_chess-0.27.3-py3-none-any.whl’ saved [143747/143747]

    $ unzip -l python_chess-0.27.3-py3-none-any.whl
    Archive:  python_chess-0.27.3-py3-none-any.whl
      Length      Date    Time    Name
    ---------  ---------- -----   ----
       125590  03-21-2019 10:25   chess/__init__.py
         8729  01-14-2019 17:49   chess/_engine.py
        86411  03-21-2019 10:25   chess/engine.py
        60852  01-14-2019 14:59   chess/gaviota.py
        40165  03-20-2019 09:58   chess/pgn.py
        26777  01-29-2019 13:25   chess/polyglot.py
        18978  03-06-2019 17:32   chess/svg.py
        66205  03-09-2019 21:23   chess/syzygy.py
        41077  01-23-2019 22:15   chess/uci.py
        30306  03-19-2019 17:42   chess/variant.py
        47654  01-17-2019 18:52   chess/xboard.py
        35147  03-21-2019 10:25   python_chess-0.27.3.dist-info/LICENSE.txt
        11682  03-21-2019 10:25   python_chess-0.27.3.dist-info/METADATA
           92  03-21-2019 10:25   python_chess-0.27.3.dist-info/WHEEL
            6  03-21-2019 10:25   python_chess-0.27.3.dist-info/top_level.txt
         1222  03-21-2019 10:25   python_chess-0.27.3.dist-info/RECORD
    ---------                     -------
       600893                     16 files

    $ wget https://files.pythonhosted.org/packages/93/69/eb7741a1927e1a22ba8d2b37bae35e516c91a3ecd664d1a5f3fad5d629be/python-chess-0.27.3.tar.gz
    --2019-03-26 12:55:48--  https://files.pythonhosted.org/packages/93/69/eb7741a1927e1a22ba8d2b37bae35e516c91a3ecd664d1a5f3fad5d629be/python-chess-0.27.3.tar.gz
    Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.21.63, 2a04:4e42:46::319
    Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.21.63|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 138995 (136K) [binary/octet-stream]
    Saving to: ‘python-chess-0.27.3.tar.gz’

    100%[=======================================================================================================================================================================================================================================>] 138,995     --.-K/s   in 0.004s

    2019-03-26 12:55:48 (31.6 MB/s) - ‘python-chess-0.27.3.tar.gz’ saved [138995/138995]

    $ tar tzf python-chess-0.27.3.tar.gz
    python-chess-0.27.3/
    python-chess-0.27.3/CHANGELOG.rst
    python-chess-0.27.3/LICENSE.txt
    python-chess-0.27.3/MANIFEST.in
    python-chess-0.27.3/PKG-INFO
    python-chess-0.27.3/README.rst
    python-chess-0.27.3/chess/
    python-chess-0.27.3/chess/__init__.py
    python-chess-0.27.3/chess/engine.py
    python-chess-0.27.3/chess/gaviota.py
    python-chess-0.27.3/chess/pgn.py
    python-chess-0.27.3/chess/polyglot.py
    python-chess-0.27.3/chess/svg.py
    python-chess-0.27.3/chess/syzygy.py
    python-chess-0.27.3/chess/variant.py
    python-chess-0.27.3/python_chess.egg-info/
    python-chess-0.27.3/python_chess.egg-info/PKG-INFO
    python-chess-0.27.3/python_chess.egg-info/SOURCES.txt
    python-chess-0.27.3/python_chess.egg-info/dependency_links.txt
    python-chess-0.27.3/python_chess.egg-info/top_level.txt
    python-chess-0.27.3/setup.cfg
    python-chess-0.27.3/setup.py

**Comment by niklasf** [comment]
Aha! Thanks, that's a good hint. Will check my build script. Maybe it's my responsibility to clean/delete the target directory before running `setup.py`?

**Comment by niklasf** [comment]
So indeed it is recommended to

```
$ rm -rf build
$ python setup.py sdist bdist_wheel
```

until https://github.com/pypa/wheel/issues/147 is fixed.

Future wheels should not have this issue and won't contain `uci.py` or a couple of other stale files. I'll also mention it in the changelog.

**Comment by i-tub** [comment]
Thanks! I'm glad the mystery is solved.
