### ISSUE TITLE
Result header not read from game moves

### ISSUE THREAD

**Issue by foxwoods369** [niklasf/python-chess#39]
If there is a result at the end of the game moves, this code is supposed to pick it up:
 # Set result header if not present, yet.
if "Result" not in game.headers:
game.headers["Result"] = token
However, Result is always set to '*' by default in the headers, so this is never run. Could this please be updated to check for none and for an unknown result?

Thanks.

**Comment by niklasf** [comment]
Thanks! Probably never came across an instance where these two were different, so this went unnoticed.
