### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by niklasf** [niklasf/python-chess#390]
* [x] Drop support for Python 3.4, which is now past its end of life. We can then use the `typing` module that was introduced in 3.5.
* [x] Type hints:
  * [x] core
  * [x] polyglot
  * [x] svg
  * [x] variant
  * [x] engine
  * [x] syzygy
  * [x] gaviota
  * [x] pgn
* [x] Mypy passing:
  * [x] core
  * [x] polyglot
  * [x] svg
  * [x] variant
  * [x] engine
  * [x] syzygy
  * [x] gaviota
  * [x] pgn
* [x] Run mypy in CI
* [x] Do not resolve aliases in documentation (https://github.com/sphinx-doc/sphinx/issues/6518)
* [x] Annotate data members in documentation
* [x] ~Consider newtypes~

**Comment by PedanticHacker** [comment]
As you mentioned, you have issues with Mypy. Are you running Mypy 0.700?

**Comment by PedanticHacker** [comment]
@niklasf, can you paste the log for me to see for what types does the Mypy type checker fails?

**Comment by niklasf** [comment]
Missing stdlib typings:
* [ ] https://github.com/python/typeshed/issues/3644

**Comment by PedanticHacker** [comment]
I don't think we can tick the engine.py module as being passed by mypy just yet, because the mypy that I use spits 2 errors out:
```
engine.py:701: error: "BaseTransport" has no attribute "write"
engine.py:702: error: "BaseTransport" has no attribute "write"

```
The code in engine.py lines 699--702 is:
```
stdin = self.transport.get_pipe_transport(0)
assert stdin is not None, "no pipe for stdin"
stdin.write(line.encode("utf-8"))
stdin.write(b"\n")
```

**Comment by niklasf** [comment]
Ah, yes, the returned type of `get_pipe_transport()` depends on the argument. Added ignore.
