### ISSUE TITLE
Faster way to get positions in a matrix

### ISSUE THREAD

**Issue by rtadewald** [niklasf/python-chess#392]
First of all, thanks for this impressive library. 

Right now, I'm using it to train a Deep Reinforcement Learning method and I'm looking for a fast method to gather the positions for the pieces as numpy.arrays of 64 lenght.

I'm using the following code:
```
def _vectorize_board(self, board=None):
        pos_stack = np.zeros((64, 12))
        if board != None:
            a = 0
            for color in [True, False]:
                for p in range(1, 7):
                    pos_stack[list(board.pieces(p, color)), a] = 1
                    a += 1
        return pos_stack
```
(This return a 64 x 12 matrix, one for each peace, with 0 and 1 indicating the presence of the piece)

Do you guys know a faster way?
Thanks

**Comment by niklasf** [comment]
I did the following when I last needed something like this:

```python
np.array([
    board.pieces(piece_type, color).tolist()
    for color chess.COLORS
    for piece_type chess.PIECE_TYPES
], dtype=bool)
```
It seems to be ~20% faster, here.

**Comment by rtadewald** [comment]
Thanks, my friend! I'll update here. The format is ok!
