### ISSUE TITLE
Change ELO rating

### ISSUE THREAD

**Issue by aditya1709** [niklasf/python-chess#393]
Is there a way I can set the ELO rating for the engine to operate at? Or is there a way to vary it indirectly by changing the amount of time it takes to calculate the next move?

**Comment by niklasf** [comment]
Other than time/depth/node limits this depends on the engine. For example Stockfish offers skill levels from 1 to 20.

```python
 engine.configure({"Skill Level": 1})
```

**Comment by aditya1709** [comment]
Thank you. I had a follow up question, is there a way of understanding what the ELO rating is at different skill levels? Like if the chosen engine is stockfish 8 with an ELO of 3000, how would different skill levels change this?

**Comment by ddugovic** [comment]
That answer depends (in part) upon your hardware.  One way to attempt to understand would be to run the engine against a puzzle test suite and compare results with human results.

I don't have human results, but here's a puzzle test runner:
https://github.com/niklasf/python-chess/blob/master/examples/bratko_kopec/bratko_kopec.py

**Comment by gbtami** [comment]
You can find some numbers here https://groups.google.com/forum/#!topic/picochess/AixKpYnCrRo
