### ISSUE TITLE
Analysis in sync mode : avoid blocking

### ISSUE THREAD

**Issue by pascalgeo** [niklasf/python-chess#394]
I only use sync mode given I don't feel at ease with asyncio (and I have Python 3.5). I want to test engines with positions and get exactly when the engine finds the best move, without changing its mind a few minutes later.

so I start an engine : 
`engine = chess.engine.SimpleEngine.popen_xboard(cmd, timeout=30)`
and the way I make it work is:
```
with engine.analysis(board) as analysis:
if not analysis.inner._queue.empty():
    info = analysis.next()
else:
    info = None
```

Note that I found the workaround `if not analysis.inner._queue.empty()` to avoid `analysis.next()` blocking forever (I got a position with a mate and after founding the mate, the engine remains silent forever, freezing my program).

So would it possible and pertinent to add a call like analysis.empty() and document it ? (I should not have to use _queue.empty(), and this could help others to understand analysis.next() may be blocking forever with no timeout available).

**Comment by niklasf** [comment]
To find the right solution: What is your stop condition, i.e. under which circumstances wouldn't you want to wait for further analysis?

**Comment by pascalgeo** [comment]
I want to stop the analysis if: 
best move == best move of epd AND for the next 120 sec, the bm does not change
OR the engine did not find the bm after 10 or 15 minutes (I use test suites like LCTII, BT2450, etc.)

**Comment by niklasf** [comment]
Alright, looks like `empty()` might be useful even when using asyncio. Added.

**Comment by pascalgeo** [comment]
Thank you.
