### ISSUE TITLE
Problem with castling moves in polyglot opening books

### ISSUE THREAD

**Issue by bmdanielsson** [niklasf/python-chess#398]
Hi,

I found a bug in the handling of castling moves in polyglot opening books. If the move e1a1 is found in an opening book it is always converted to e1c1 (queen side castling) even when the piece on the e1 square is not a king.

The problem can be seen with the Performance.bin book (http://rebel13.nl/dl.html?file=dl/Performance.7z) and the position "1r1qr1k1/1b2bp1n/p2p2pB/1pnPp2p/P1p1P3/R1P2NNP/1PBQ1PP1/4R1K1 w - - 0 1".

Version: 0.27.3

**Comment by niklasf** [comment]
Thanks for reporting. You can now optionally provide a board as context to `entry.move(board=...)`. I'll try to come up with a more satisfying solution soon.

**Comment by niklasf** [comment]
Actually I think it's worth breaking the API for this. `entry.move` is now an attribute, no longer a method, and it will just work automatically.
