### ISSUE TITLE
Wrong fen sent to engine when doing infinite analysis

### ISSUE THREAD

**Issue by bmdanielsson** [niklasf/python-chess#399]
Hi,

`engine = chess.engine.SimpleEngine.popen_uci('./marvin')`
`fenstr = 'r1b1kb1r/ppp3pp/2N2n2/1B4q1/4pP2/8/PPPPQ1PP/R1B1K2R b KQkq f3 0 1'`
`engine.play(chess.Board(fen=fenstr), chess.engine.Limit(time=0.1))`

With the code above the engine will receive the fen string "r1b1kb1r/ppp3pp/2N2n2/1B4q1/4pP2/8/PPPPQ1PP/R1B1K2R b KQkq - 0 1" in the position command. The en-passant square 'f3' is missing. 

The en-passant capture is illegal but it can still cause problems when an engine is using it's own book. In that case it will fail to find the position in the opening book even if it's present.

**Comment by niklasf** [comment]
I suppose it doesn't hurt to always include the ep square. Done.
