### ISSUE TITLE
Incorrect castling san move?

### ISSUE THREAD

**Issue by pmz** [niklasf/python-chess#403]
With a rank 1 like so:
R N B Q K . . R
board.push_san("Kg1") returns ValueError: illegal san: 'Kg1'
but board.push_san("Kh1") properly castles king side. Of course, "O-O" works as well.

This is confusing to me. My understanding is that this is the way to castle in a chess960 game?
But I'm playing a classical game of chess (chess960=False), so castling should be done by moving the king to g1.

What am I missing?

**Comment by niklasf** [comment]
SAN for castling is O-O (kingside) and O-O-O (queenside). If anything it's a bug that Kh1 is accepted. Will fix.

**Comment by pmz** [comment]
Thanks for the quick reply @niklasf 
And thanks for python-chess, this is a great project.
