### ISSUE TITLE
Question on engine.play()

### ISSUE THREAD

**Issue by fsmosca** [niklasf/python-chess#405]
Can engine.play() able to stream search info like engine.analysis()? If so how?

The goal is to let the engine play naturally without stop command interruption and without the command `setoption name UCI_AnalyseMode value true` and then capture those search info live.

**Comment by niklasf** [comment]
No, this is currently not implemented.

Assuming you're using Stockfish that's not a problem. There is no difference between analysis and play mode, except that it enables the `Analysis Contempt` contempt option (which defaults to Both, the same as in play).

`engine.analysis()` also takes a `Limit` as the second argument and will allow the engine to use its natural time management.

**Comment by fsmosca** [comment]
I am aware of the engine.analysis() with limit, this is close to what I need, but it is sending `setoption name UCI_AnalyseMode value true`

**Comment by niklasf** [comment]
Yes, but is there an engine where it actually does anything? It makes no difference unless you're also setting `Analysis Contempt`.

**Comment by fsmosca** [comment]
In my engine Deuterium, if UCI_AnalyzeMode is set to true, it returns repeat_score if there are 2 or more repetitions, but in normal play it returns repeat_score early if there is 1 repetition encountered.

**Comment by niklasf** [comment]
Alright. For now I just made a minimal change to allow `engine.configure({"UCI_AnalyseMode": False})` or setting it in the `options` argument.

**Comment by fsmosca** [comment]
Thanks.
