### ISSUE TITLE
change color of circle in SVG

### ISSUE THREAD

**Issue by 7points** [niklasf/python-chess#406]
Hi,
with the original svg-module it seems to be not possible to change the color of the circle (arrow with identical from/to). Because of it, on a "Black & White"-board the circle disappears on dark squares.
My suggestion: add  the line "class": "mark" to the svg-module at the end of ET.SubElement(svg, "circle", { . . . 
Then the color of the circle can be changed by adding stroke and fill to  a css-string.
for example:
.mark {
  stroke: #959fff;
  fill: #959fff;
}

**Comment by niklasf** [comment]
Makes sense. Before I add it, did you know that the color can also bet set like this?

```
chess.svg.board(arrows=[
    chess.svg.Arrow(chess.E2, chess.E4, color="red"),
    chess.svg.Arrow(chess.E2, chess.E2, color="blue"),
])
```

**Comment by 7points** [comment]
Yeah, I knew that.
But if you want to realize different color combinations for the chessboard, its best you have direct access via svg-style-parameter. Another advantage: now you can fill the circle, if wanted.

**Comment by niklasf** [comment]
And one final question: Do you see any issues with using `circle { ... }` as the selector?

**Comment by 7points** [comment]
I only added in svg.py line 257 "class": "mark",
and tested with following svg-style parameter:
black_and_white = '''
.square.light {
fill: #cacaca;
}
.square.dark {
  fill: #898989;
}
.square.light.lastmove {
  fill: #c3d889;
}
.square.dark.lastmove {
  fill: #92b167;
}
.check {
  fill: url(#check_gradient);
}
.arrow {
  stroke: #ff5858;
  fill: #ff5858;
}
.mark {
  stroke: #959fff;
  fill: #959fff;
}
'''

Without the css-style the circle remains grey, I can't see any disadvantage.

**Comment by niklasf** [comment]
Sure, but why not do
```
circle {
stroke: #959fff;
fill: #959fff;
}
```
instead?

**Comment by 7points** [comment]
You're right, instead of mark, circle is better understandable.
That means, in svg.py you would have to add  "class": "circle" (in analogy to the arrow).

**Comment by niklasf** [comment]
No, I mean you can already use `circle`. It's a selector for the element name.

**Comment by 7points** [comment]
You're right, the dot must not be placed in front of the selector. I did not know that.
Thanks for your help.

**Comment by 7points** [comment]
Your tip to omit the dot does not really work, because when rendering, the color of the black Queen is partially changed too. I think, the best is to add a line with "class":  "mark" as I mentioned above.

**Comment by niklasf** [comment]
Ah, sorry. I thought all the pieces were using paths only. Added `circle` as a class.
