### ISSUE TITLE
How to use engine with CREATE_NO_WINDOW

### ISSUE THREAD

**Issue by fsmosca** [niklasf/python-chess#407]
I have a chess GUI built from PySimpleGUI/Tkinter, convert the src.py (I use the chess.engine.SimpleEngine.popen_uci()) to exe using pyinstaller, run the exe, when I let the engine runs to search for best move, it would create a console window, see image below. I am on window 7 OS.

![image](https://user-images.githubusercontent.com/22366935/57206366-cab55f00-6ff7-11e9-8eca-45a81c3fcca3.png)

To suppress that window, there is a parameter in Python 3.7 called creationflags in subprocess.Popen(), https://docs.python.org/3/library/subprocess.html#subprocess.Popen. If I will use my way of running an engine I will start something like below with creationflags=subprocess.CREATE_NO_WINDOW:
```
engine_fn = 'uci_chess_engine.exe'
proc = subprocess.Popen(engine_fn, bufsize=1, 
                    stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT, universal_newlines=True,
                    creationflags=subprocess.CREATE_NO_WINDOW)
```
Is there a way to disable such window when using chess.engine module? Thank you.

**Comment by gbtami** [comment]
In PyChess we use subprocess.STARTF_USESHOWWINDOW https://docs.python.org/3/library/subprocess.html#subprocess.STARTUPINFO 
The difference is described at https://stackoverflow.com/questions/7006238/how-do-i-hide-the-console-when-i-use-os-system-or-subprocess-call

**Comment by niklasf** [comment]
Any extra keyword arguments to [`popen_uci(..., **popen_args)`](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.SimpleEngine.popen_uci) should be passed along to Popen.

**Comment by fsmosca** [comment]
Thanks, it worked.
