### ISSUE TITLE
Premature 3 Fold Repetition Game End?

### ISSUE THREAD

**Issue by Neuro-Dynamics** [niklasf/python-chess#412]
I found that python chess is reporting board.is_game_over(claim_draw=True) => True before an actual 3-fold repetition has happened.

Here is code to reproduce the issue:

```
import chess.pgn

pgn = open("3FRep.pgn")
game = chess.pgn.read_game(pgn)
board = game.board()

for move in game.mainline_moves():
    board.push(move)

print(board)
print(board.is_game_over(claim_draw=True))
```

```
[Event "3Fold Rep Test"]
[Site "?"]
[Date "May 17, 2019 04:49:22 PM"]
[Round "1"]
[White "Stockfish 8"]
[Black "Stockfish 8"]
[Result "1/2-1/2"]

1. d4 Nf6 2. c4 e6 3. Nf3 b6 4. g3 Be7 5. Bg2 Bb7 6. O-O O-O 7. Nc3 Ne4 8. Qc2
Nxc3 9. Qxc3 c5 10. Rd1 d6 11. Qd3 Nc6 12. d5 exd5 13. cxd5 Nb4 14. Qb1 Ba6 15.
e4 Be2 16. Rd2 Bxf3 17. Bxf3 Bg5 18. Rd1 Bxc1 19. Rxc1 a5 20. Be2 Qd7 21. Re1
Rfe8 22. a4 Re7 23. Bb5 Qg4 24. Ra3 h5 25. h4 Rc8 26. Rc3 Qg6 27. b3 Rf8 28. Rf3
Qh7 29. Rfe3 f6 30. Qd1 Ref7 31. f4 Re7 32. e5 fxe5 33. fxe5 Qc2 34. Qe2 Qxe2
35. R3xe2 Rd8 36. Bc4 Rxe5 37. Rxe5 dxe5 38. Rxe5 g6 39. Kf2 Kf7 40. Re6 Kg7 41.
Rxb6 Nxd5 42. Ra6 Rf8+ 43. Ke2 Nc3+ 44. Ke3 Nd1+ 45. Ke4 Rf5 46. Rxa5 Nf2+ 47.
Ke3 Ng4+ 48. Ke4 Re5+ 49. Kf3 Rf5+ 50. Ke2 Rf2+ 51. Ke1 Rc2 52. Rxc5 Ne3 53. a5
Ng2+ 54. Kd1 Ne3+ 55. Ke1 Ng2+ 56. Kf1 Ne3+
```

Can be tested with the attached pgn file which is one move short (57. Ke1) of a 3-fold repetition.
[3FRep-test.zip](https://github.com/niklasf/python-chess/files/3193383/3FRep-test.zip)

This happens with other games as well.

**Comment by niklasf** [comment]
This is correct.

https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.can_claim_threefold_repetition:
> Draw by threefold repetition can be claimed if the position on the board occured for the third time **or if such a repetition is reached with one of the possible legal moves**.

You might find [`is_repetition()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.is_repetition) useful:
> Unlike `can_claim_threefold_repetition()`, this does not consider a repetition that can be played on the next move.

**Comment by Neuro-Dynamics** [comment]
Thank you for the response niklasf.

The problem is not with can_claim_threefold_repetition, but with the fact that is_game_over reports True when the game is NOT over yet.

**Comment by niklasf** [comment]
Are you calling `is_game_over(claim_draw=True)`?

**Comment by Neuro-Dynamics** [comment]
Yes, that's the code above. 

`print(board.is_game_over(claim_draw=True))`

I suspect is_game_over(claim_draw=True) is calling can_claim_threefold_repetition, which is why it reports the game is over.

**Comment by niklasf** [comment]
Yes, as intended. By FIDE rules a draw can be claimed (because there is a legal move that will repeat for the third time), and so the draw is claimed.

If you really don't want that, the least verbose way I can think of is `board.is_game_over() or board.can_claim_fifty_moves() or board.is_repetition()`.

**Comment by Neuro-Dynamics** [comment]
Ok, I guess. I have no problem with the work around, I have been using it.

Maybe this is just another use case that is not covered by is_game_over(). This is particularly obvious when using engines which will not claim a draw but will make the actual move. Using is_game_over() to check if the game has ended over a repetition will not work for what seems to be its intended use.

Thank you for the clarification niklasf, I will continue to use the workaround. 

It also sounds that is_game_over() will also return True before the 50-move rule has actually happened as well, this will need a different workaround.

**Comment by niklasf** [comment]
Ah, no. It's just that the 50-move rule has to be claimed. So `is_game_over(claim_draw=False)` won't do that.
