### ISSUE TITLE
Board object has no attribute is_repetition

### ISSUE THREAD

**Issue by JuanCCS** [niklasf/python-chess#414]
I'm having some issues loading pgn files into an ipython notebook in Google Colab, Game instance doesn't have attribute mainline_moves so I'm adding the moves manually to the board but then Board instance doesn't have attribute is_repetition. Has anybody experienced this? I'm loading this pgn: 

[Event "Corus Group C"]
[Site "Wijk aan Zee NED"]
[Date "2004.01.24"]
[EventDate "2004.01.10"]
[Round "12"]
[Result "1-0"]
[White "Magnus Carlsen"]
[Black "Sipke Ernst"]
[ECO "B18"]
[WhiteElo "2484"]
[BlackElo "2474"]
[PlyCount "57"]

1. e4 c6 2. d4 d5 3. Nc3 dxe4 4. Nxe4 Bf5 5. Ng3 Bg6 6. h4 h6
7. Nf3 Nd7 8. h5 Bh7 9. Bd3 Bxd3 10. Qxd3 e6 11. Bf4 Ngf6
12. O-O-O Be7 13. Ne4 Qa5 14. Kb1 O-O 15. Nxf6+ Nxf6 16. Ne5
Rad8 17. Qe2 c5 18. Ng6 fxg6 19. Qxe6+ Kh8 20. hxg6 Ng8
21. Bxh6 gxh6 22. Rxh6+ Nxh6 23. Qxe7 Nf7 24. gxf7 Kg7 25. Rd3
Rd6 26. Rg3+ Rg6 27. Qe5+ Kxf7 28. Qf5+ Rf6 29. Qd7# 1-0

Here's the function that returns the board object: 

```
def get_carlsen_game():
  downloaded.seek(0)
  pgn = io.StringIO(downloaded.read().decode("utf-8"))
  moves = []
  carlsen_game = chess.pgn.read_game(pgn)
  root_node = carlsen_game.root()
  node = carlsen_game.end()
  while not node == root_node:
    moves.insert(0,node.move)
    node = node.parent

  carlsen_board = chess.Board()
  for mv in moves:
    carlsen_board.push(mv)
  return carlsen_board
```

**Comment by JuanCCS** [comment]
I'm having some issues loading pgn files into an ipython notebook in Google Colab, Game instance doesn't have attribute mainline_moves so I'm adding the moves manually to the board but then Board instance doesn't have attribute is_repetition. Has anybody experienced this? I'm loading this pgn: 

[Event "Corus Group C"]
[Site "Wijk aan Zee NED"]
[Date "2004.01.24"]
[EventDate "2004.01.10"]
[Round "12"]
[Result "1-0"]
[White "Magnus Carlsen"]
[Black "Sipke Ernst"]
[ECO "B18"]
[WhiteElo "2484"]
[BlackElo "2474"]
[PlyCount "57"]

1. e4 c6 2. d4 d5 3. Nc3 dxe4 4. Nxe4 Bf5 5. Ng3 Bg6 6. h4 h6
7. Nf3 Nd7 8. h5 Bh7 9. Bd3 Bxd3 10. Qxd3 e6 11. Bf4 Ngf6
12. O-O-O Be7 13. Ne4 Qa5 14. Kb1 O-O 15. Nxf6+ Nxf6 16. Ne5
Rad8 17. Qe2 c5 18. Ng6 fxg6 19. Qxe6+ Kh8 20. hxg6 Ng8
21. Bxh6 gxh6 22. Rxh6+ Nxh6 23. Qxe7 Nf7 24. gxf7 Kg7 25. Rd3
Rd6 26. Rg3+ Rg6 27. Qe5+ Kxf7 28. Qf5+ Rf6 29. Qd7# 1-0

Here's the function that returns the board object: 

```
def get_carlsen_game():
  downloaded.seek(0)
  pgn = io.StringIO(downloaded.read().decode("utf-8"))
  moves = []
  carlsen_game = chess.pgn.read_game(pgn)
  root_node = carlsen_game.root()
  node = carlsen_game.end()
  while not node == root_node:
    moves.insert(0,node.move)
    node = node.parent

  carlsen_board = chess.Board()
  for mv in moves:
    carlsen_board.push(mv)
  return carlsen_board
```

**Comment by niklasf** [comment]
Can you please check `chess.__version__`? The latest release is v0.28.0.

**Comment by JuanCCS** [comment]
Yes that was it, thank you very much!
