### ISSUE TITLE
Read_headers example in the documentation.

### ISSUE THREAD

**Issue by spinor8** [niklasf/python-chess#417]
Hi, thanks for this great software. I just updated and noticed some breaking changes. Specifically the scan_headers(). I looked up the change logs and saw that this has been replaced by read_headers(). Looking up the example, I am a bit confused about what is going on.

I have written some code using scan_headers().
```
    for offset, headers in chess.pgn.scan_headers(pgn_handle):
        variant = headers.get('Variant', None)
        if variant == "Standard" or variant is None:
            if player_name in headers[_colour]:
                yield offset
```
This was intuitive. It is scanning the file and getting the offset and headers along the way. Then I was filtering by variant and colour to get the offset.

The example given by the current docs for read_headers is
```
while True:
    offset = pgn.tell()
    headers = chess.pgn.read_headers(pgn)

    if headers is None:
        break

    if "Kasparov" in headers.get("White", "?"):
        offsets.append(offset)
```
This has a different loop control. Is it possible to rewrite the documentation example into a for loop and with a more natural way of getting the offset?

I tried the following:
```
for header in chess.pgn.read_headers(pgn):
    offset = pgn.tell()

    if "Kasparov" in header.get("White", "?"):
        offsets.append(offset)
```
but for the header.get() line it throws the error
```
AttributeError: 'str' object has no attribute 'get'.
```

**Comment by spinor8** [comment]
chess.pgn.read_headers read a single game and the loop structure is messier because Python doesn't have a do-while lopp.

**Comment by niklasf** [comment]
One relatively concise way to do it is using `iter()` with a sentinel:

```python
import sys
import chess.pgn

pgn = open(sys.argv[1])

offset = 0
for headers in iter(lambda: chess.pgn.read_headers(pgn), None):
    print(offset, headers)
    offset = pgn.tell()
```

**Comment by spinor8** [comment]
Thanks for the example. I ended up rewriting my code so that I didn't have to use offsets. I used chess.pgn.read_game to read game by game into a sqlite database and queried that instead.
