### ISSUE TITLE
Only Python 3.5.3+ is supported, not 3.5+

### ISSUE THREAD

**Issue by 31m059** [niklasf/python-chess#418]
I am a new user of `python-chess` and am struggling to install it.

As stated in the documentation,
https://docs.python.org/3/library/typing.html#typing.ClassVar
`typing.ClassVar` was added in Python 3.5.3.  However, the documentation for this repo states that python-chess is compatible with 3.5+.

After installing python-chess with `pip3 install python-chess` on Windows Subsystem for Linux, Ubuntu (where python3 is Python 3.5.2), the following error results from `chess/__init__.py`, line 38:

```
from typing import ClassVar, Callable, Dict, Generic, Hashable, Iterable, Iterator, List, Mapping, MutableSet, Optional, SupportsInt, Tuple, Type, TypeVar, Union
ImportError: cannot import name 'ClassVar'
```

It would be preferable to support 3.5.2 if possible, but if not, the documentation and `setup.py` should be revised to document this more stringent version requirement.  Currently, `pip3` creates a broken installation instead.

Thank you for your time and consideration.

**Comment by niklasf** [comment]
Thanks, good catch! I updated the docs for now, but I'll try to find a good way to work around this.

**Comment by niklasf** [comment]
This is leading from one issue to the next (ClassVar, Type, https://github.com/python/typing/issues/266, get_running_loop). I'll just give up and keep the 3.5.3 requirement :disappointed:

**Comment by gbtami** [comment]
I don't know if it fits to the goals or not, but you can consider using stub files for typing.
