### ISSUE TITLE
Null move is considered a capture move as black

### ISSUE THREAD

**Issue by coreylowman** [niklasf/python-chess#420]
This happens because `Move.null()` is encoded as a move from `A1` to `A1`, and board.is_capture only looks for the presence of the opponent at the to_square.

Example:
```python
>>> import chess
>>> board = chess.Board()
>>> board.push(chess.Move(chess.E2, chess.E4))
>>> board.is_capture(chess.Move.null())
True
```

**Comment by niklasf** [comment]
Thanks. This is technically not a bug, because `board.is_capture()` is documented to require a pseudo -legal move (which null moves are not). Nonetheless it could be improved.

**Comment by coreylowman** [comment]
Ahh got it - that makes sense.
