### ISSUE TITLE
issue from install python modules

### ISSUE THREAD

**Issue by avex48** [niklasf/python-chess#423]
$ pip3 install chess
Collecting chess
  ERROR: Could not find a version that satisfies the requirement chess (from versions: none)
ERROR: No matching distribution found for chess
I also tried:
$ pip install chess
$ sudo pip3 install chess
with the same error.

If I launch python and python3:
$ python
Python 2.7.16 (default, Jun 12 2019, 13:28:30) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
$ python3
Python 3.6.8 (default, Jun 12 2019, 14:34:08) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
how can I fix it? Thank you.

**Comment by Mk-Chan** [comment]
The module name is python-chess I believe

**Comment by avex48** [comment]
Thank you so much, solved!!! 
I get the same error trying to install BGE (Blender game engine).
What is the name of this module?

**Comment by niklasf** [comment]
Sorry, not sure.
