### ISSUE TITLE
Make code more concise

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#424]
Please help me concise my code using comparison operator chaining:

```
if file < 0:
    file = 0

if rank < 0:
    rank = 0

if file > 7:
    file = 7

if rank > 7:
    rank = 7
```

**Comment by mdoege** [comment]
```rank = min(7, max(0, rank))```

**Comment by PedanticHacker** [comment]
That's not comparison operator chaining. I was thinking in terms of
```
if file < 0 > 7 and rank < 0 > 7:
    file = ?
    rank = ?
```
This is just an example. Please use comparison operator chaining and help me solve this darn thing.

**Comment by gbtami** [comment]
@PedanticHacker your initial problem can't be expressed with [operator chaining](https://docs.python.org/3/reference/expressions.html#comparisons).
@mdoege solution is your best bet if you want to shorten your original code.
Just note that github issue trackers are not public Python forums. For this kind of problems you should ask on https://python-forum.io/Forum-General-Coding-Help

**Comment by niklasf** [comment]
Nonetheless @mdoege gave you the best way to do it.

Also note that this question is unreleated to this library and this issue tracker isn't the right forum for it. You can ask basic Python questions on Stackoverflow, for example.
