### ISSUE TITLE
Failed to detect bestmove is illegal

### ISSUE THREAD

**Issue by fsmosca** [niklasf/python-chess#429]
### Test env
Windows 7
Python-chess v0.28.1
Python 3.7.3

### Issue desc
I have this uci engine tested and let it search for bestmove on position
`2b5/3R3k/3p1p1p/N3pP2/2P1P3/2nB4/2P3PP/6K1 b - - 0 1`
using engine.play()

According to log it sent a bestmove a1a1 which is illegal.
```
DEBUG:chess.engine:<UciProtocol (pid=4808)>: >> info depth 17 seldepth 32 time 1014 nodes 1360071 nps 1341293 tbhits 0
DEBUG:chess.engine:<UciProtocol (pid=4808)>: >> info time 1014 nodes 1360071 nps 1341293 cpuload 985
DEBUG:chess.engine:<UciProtocol (pid=4808)>: >> info hashfull 45
DEBUG:chess.engine:<UciProtocol (pid=4808)>: >> bestmove a1a1 ponder c6a5
```

But Python-chess did not see that a1a1 is illegal, but it did see that c6a5 the ponder move is illegal.
```
ERROR:chess.engine:engine sent invalid ponder move
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\chess\engine.py", line 1282, in _bestmove
    pondermove = engine.board.push_uci(tokens[2])
  File "C:\Python37\lib\site-packages\chess\__init__.py", line 2834, in push_uci
    move = self.parse_uci(uci)
  File "C:\Python37\lib\site-packages\chess\__init__.py", line 2821, in parse_uci
    raise ValueError("illegal uci: {!r} in {}".format(uci, self.fen()))
ValueError: illegal uci: 'c6a5' in 2b5/3R3k/3p1p1p/N3pP2/2P1P3/2nB4/2P3PP/6K1 w - - 1 2
```

**Comment by niklasf** [comment]
Thanks for reporting. `a1a1` is (incorrectly, strictly speaking) treated as a null move, here. This brings up another question. What should have happened if the engine sent `bestmove (none)` instead?

* Simply set `result.move` to `None`.
* Raise an exception, because `(none)` is invalid if the game is not yet over.

**Comment by fsmosca** [comment]
All right that is why a1a1 was not detected. I hope you will change it, as correct nullmove notation is 0000.

For bestmove (none), exception must be raised.
