### ISSUE TITLE
No way to get both bestmove and analysis

### ISSUE THREAD

**Issue by thomasahle** [niklasf/python-chess#433]
I would like to run a UCI engine with `chess.engine` and get both `multipv` results, as they become available, and the value of `bestmove`.

It seems that `engine.play(...)` has no way of returning multipvs before `bestmove` has been sent, while `engine.analysis(...)` simply throws away the value of `bestmove`.

Most of the times I can recover the `bestmove` from the first `pv`, but in the rare cases where the engine responds too fast to give any `info` lines, this doesn't work.

Am I missing something?

**Comment by niklasf** [comment]
Mhh yeah ... Btw, what engine are you using?

**Comment by thomasahle** [comment]
This is my own engine, so I might have misunderstood something in the UCI protocol.
It's just a bit slow, so sometimes it doesn't get around to sending any `multipv` before it decides on the move.
I could force it to do so though. I just didn't know if I was simply missing something in the api.

**Comment by niklasf** [comment]
At least that's what I've seen most engines do, i.e., print one final batch of `info` just before the search ends.

I am hesitating to add an API because there doesn't appear to be an XBoard equivalent.

**Comment by thomasahle** [comment]
Good point. I haven't looked at xboard for a while. Does it even support multipv?

I was just thinking of `analysis` could save the `bestmove` result. Right now [in line 1354](https://github.com/niklasf/python-chess/blob/master/chess/engine.py#L1354) it is simply thrown away, compared with [line 1265](https://github.com/niklasf/python-chess/blob/master/chess/engine.py#L1265) which stores it for `play`.
Just seems like a pitty to throw away good information on the hopes that previous lines might subsume it.

**Comment by thomasahle** [comment]
There seem to be a few other problems that'll require me to handle xboard separately.
Really what I'd like to do is to play an engine match, but have it report multipvs if they are available.
It seems that using `engine.analysis` for this doesn't work with xboard, since it for example doesn't support clock limits during analysis.

Perhaps instead of changing how `analysis` works, what would be nice was if `play` could return intermediate results, since xboard engines certainly display some information while searching.
