### ISSUE TITLE
Antichess move generation bug

### ISSUE THREAD

**Issue by ddugovic** [niklasf/python-chess#438]
By ICC rules, castling is legal in giveaway chess:
https://www.chessclub.com/help/Giveaway

Multi-Variant Stockfish supports castling in giveaway chess:

```
setoption name UCI_Variant value giveaway
position startpos moves g1f3 g8f6 g2g3 g7g6 f1g2 f8g7
go perft 1
a2a3: 1
b2b3: 1
c2c3: 1
d2d3: 1
e2e3: 1
h2h3: 1
g3g4: 1
a2a4: 1
b2b4: 1
c2c4: 1
d2d4: 1
e2e4: 1
h2h4: 1
f3g1: 1
f3d4: 1
f3h4: 1
f3e5: 1
f3g5: 1
b1a3: 1
b1c3: 1
g2f1: 1
g2h3: 1
h1f1: 1
h1g1: 1
e1f1: 1
e1g1: 1

Nodes searched: 26
```

**Comment by niklasf** [comment]
python-chess currently also supports this, but only when explicitly setting up a starting position with castling rights.

**Comment by ddugovic** [comment]
Good, thanks for the clarification.

**Comment by niklasf** [comment]
Perhaps there should be Giveaway with the original rules and starting position, and Antichess with the Lichess starting position?

**Comment by ddugovic** [comment]
Ironically... I think the Lichess (no castling) starting position is the "original" rule.

I like your suggestion and I should consider doing the same in multi-variant Stockfish (rename the variant to "antichess" using the Lichess starting position and reintroduce sub-variant "giveaway" using the ICC starting position which it currently uses).
