### ISSUE TITLE
Adding a pinners function

### ISSUE THREAD

**Issue by kraktus** [niklasf/python-chess#442]
When I used python-chess, several times I had to create my personal `pinners` function`. What do you think about adding a build-in function?

**Comment by PedanticHacker** [comment]
Share your pinners function then. Maybe it'll become a built-in function in python-chess. If @niklasf likes it, of course. 😉

**Comment by niklasf** [comment]
They already did in #441, and it's pretty straight forward. For now I am not convinced it's worth adding a shortcut for this.
