### ISSUE TITLE
High score from engine

### ISSUE THREAD

**Issue by clappis** [niklasf/python-chess#443]
I don't know if this is an error (I don't think so), but what's the meaning of these high values from score?

Is this a characteristic from stockfish or is it wrapper's?

```python
board = chess.Board("r7/pp2k3/1q2b3/2p1bpp1/2P1p3/1N2P3/PPQ1BPP1/2KR4 w - - 4 21")
engine = chess.engine.SimpleEngine.popen_uci("stockfish")
print(engine.id.get("name"))
info = engine.analyse(board, chess.engine.Limit(depth=20))
print("Score:", info["score"])
Stockfish 10 64
Score: +78
```

**Comment by LocutusOfPenguin** [comment]
what do y expect?
It means white is 0.78 pawns ahead

**Comment by niklasf** [comment]
Correct, scores are given in centipawns. See https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.Score and https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.PovScore.
