### ISSUE TITLE
Disable debug logging of engine (uci)

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#444]
before i can disable these uci-lines with

`logging.getLogger('chess.engine').setLevel(logging.INFO)`

now it only works with "chess._engine".
Why is that? Is there a better way (to keep with future versions)?

**Comment by niklasf** [comment]
You're probably on an old version that had seperate chess.xboard and chess.uci modules with shared imports from _engine.

It's back to `chess.engine` in the latest version and will stay that way.

**Comment by LocutusOfPenguin** [comment]
yep..im still on v0.25.1 cause i fear the work for the engine code updates.
