### ISSUE TITLE
No way to get piece position on board

### ISSUE THREAD

**Issue by PappaStalin** [niklasf/python-chess#445]
When trying to create an evaluation function for the a chessboard, I found that is currently no good way to get a piece's position on the chessboard. The simplest way I could find to do this without editing the module itself is to use the board.__str__() function to derive an array of the board. This method is messy and not computationally efficient, so I think that a method that returns an array representing board or some way of finding the position of each piece would be a good addition. 

I'd be happy to work on this if you think it's a useful contribution.

**Comment by dsblank** [comment]
There are ways to get a piece's position on the board. There are a couple of ways shown here: https://jupyter.brynmawr.edu/services/public/dblank/CS371%20Cognitive%20Science/2016-Fall/Programming%20a%20Chess%20Player.ipynb

**Comment by niklasf** [comment]
To summarize:

* By piece type and color: https://python-chess.readthedocs.io/en/latest/core.html#chess.BaseBoard.pieces
* By square: https://python-chess.readthedocs.io/en/latest/core.html#chess.BaseBoard.piece_at
* As a dictionary: https://python-chess.readthedocs.io/en/latest/core.html#chess.BaseBoard.piece_map
