### ISSUE TITLE
Can I use this module to read multiple games from a PGN?

### ISSUE THREAD

**Issue by JacoGuerra** [niklasf/python-chess#446]
As I read in the docs I am able to read a game from a file opened in text mode but only the first one, not the rest of the games that appear in the file, how can I make it possible? Also, Could I store all the games in the file in a dictionary using this module?

Thanks!

**Comment by niklasf** [comment]
You can call `chess.pgn.read_game()` multiple times to read the next game.

There aren't any helper functions to read all games into a list or dictionary, but of course you can simply put the games there yourself.

**Comment by JacoGuerra** [comment]
Hey, thanks for answering so fast!
Sorry but I don´t get it... How would I do that? 

Thanks!

**Comment by niklasf** [comment]
For example:

```python
import chess.pgn

f = open("data/pgn/kasparov-deep-blue-1997.pgn")

my_list = []

while True:
    game = chess.pgn.read_game(f)
    if game is None:
        break  # end of file

    my_list.append(game)
```

**Comment by JacoGuerra** [comment]
If I print my_list after copying your code (changing the file of course) what I is the following : 

`[<Game at 0x238e9b11588 ('Muratyoldas' vs. 'AlexandrGrigoryev', '2019.10.17')>, <Game at 0x238e9b36978 ('MBartoli' vs. 'RogueViking', '2019.10.17')>, <Game at 0x238e9b47198 ('moktainex' vs. 'Yaaseen', '2019.10.17')>` 

and so on

**Comment by niklasf** [comment]
Each entry in the list is then a `Game` object. See https://python-chess.readthedocs.io/en/latest/pgn.html#game-model.

**Comment by JacoGuerra** [comment]
I just want to build a dataframe in pandas and I think creating a dictionary with all the info is the best way, How could I do it using this module?

Thanks a lot for your help!

**Comment by niklasf** [comment]
A dictionary maps keys to values. What kind of info do you want to use as the keys and what kind of info do you want to use as the values?

**Comment by JacoGuerra** [comment]
The headers are the keys, the info are the values (including the moves of course)

**Comment by niklasf** [comment]
Could you please type out the dictionary you'd expect for the following example? I think that would help to clarify some things.

```
[White "foo1"]
[Black "bar1"]

1. e4 e5 0-1

[White "foo2"]
[Black "bar2"]

1. Nf3 1-0
```

**Comment by JacoGuerra** [comment]
Yes sure, here is what I am talking about:

Nested_dict = { 
  "Game1": {"white" : "foo1" , "Black" : "bar1" , "moves": "1. e4 e5 0-1"}
  "Game2": {"white" : "foo2" , "Black" : "bar2" , "moves": "1. Nf3 1-0"}
}

Thanks!

**Comment by niklasf** [comment]
Ok, this would work:

```python
import chess.pgn

f = open("a.pgn")

result = {}
i = 0
while True:
    i += 1
    game = chess.pgn.read_game(f)
    if game is None:
        break

    headers = dict(game.headers)
    headers["moves"] = game.board().variation_san(game.mainline_moves())

    result["Game{}".format(i)] = headers
```

Note that parsing the game only to convert it back to standard algebraic notation could be done more efficiently without python-chess.

**Comment by JacoGuerra** [comment]
Thanks a lot for your help!
