### ISSUE TITLE
Illegal position problem

### ISSUE THREAD

**Issue by narciso2019** [niklasf/python-chess#448]
Python chess won't recognize an illegal position... :-(
###############################
import chess.syzygy
tablebase = chess.syzygy.open_tablebase("./python-chess-master/data/syzygy/regular")
board = chess.Board("8/1k6/8/K7/4Q3/r7/8/8 w - - 0 1")
eval = tablebase.probe_wdl(board)
tablebase.close()
print(eval)
###############################
Prints out "2" and the position is illegal as Black king is in check while White is on the move.
Can you please fix that?
It would be much appreciated as I am using your code to verify positions for some endgame training modules on my website: https://chesswise.defiantchris.com/index.php/chess-endgames/basic-mates
Thank you in advance for any help you can offer :-)

**Comment by niklasf** [comment]
You can use [`board.is_valid()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.is_valid) or [`board.status()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.status). Since validation is not free, it's deliberately not done automatically everywhere.

**Comment by narciso2019** [comment]
Wow, thank you so very much for such a quick response and a very helpful one.
It worked like a charm! :-)
You just made my day!!!
Thank you so muuuuch again!!! :-)))

**Comment by niklasf** [comment]
Cheers.
