### ISSUE TITLE
Improper position evaluation?!

### ISSUE THREAD

**Issue by narciso2019** [niklasf/python-chess#449]
When I try the manual example code for position evaluation with Stockfish (see below) I get somewhat different results. I work on a Virtual Machine box with Win10 Pro x64, Python 3.7 x32, python-chess-v. 0.28.2.
####################
```python
import chess
import chess.engine
engine = chess.engine.SimpleEngine.popen_uci("./stockfish/stockfish_10_x64.exe")
board = chess.Board()
info = engine.analyse(board, chess.engine.Limit(time=0.100))
print("Score:", info["score"])
# Score: +20
board = chess.Board("r1bqkbnr/p1pp1ppp/1pn5/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR w KQkq - 2 4")
info = engine.analyse(board, chess.engine.Limit(depth=20))
print("Score:", info["score"])
# Score: #1
engine.quit()
```
####################
My scores are as follows:
Score: +97
Score: #+1
Well, I could accept some little difference, however it is much worse with another position that I tried (see code below). Chessbase Fritz 16 (depth=29) evaluation is ca. +=0.31, Stockfish (depth=30) on Lichess gives it ca. +0.8 assesment while python-chess evaluates it as -62 ?!!! BTW increasing the depth up to 30 made it even worse evaluating the position as -72 ?!!!
What am I doing wrong here?
####################
```python
import chess
import chess.engine
engine = chess.engine.SimpleEngine.popen_uci("./stockfish/stockfish_10_x64.exe")
board = chess.Board("r1bqk1nr/ppp1bppp/2np4/8/2BpP3/1QP2N2/PP3PPP/RNB1K2R b KQkq - 0 6")
info = engine.analyse(board, chess.engine.Limit(depth=20))
print("Score:", info["score"])
engine.quit()
```
####################
Your invaluable help on that would be much appreciated. Thank you in advance!

**Comment by niklasf** [comment]
For the first example: I get similar results with Stockfish 10. But anyway, evaluations can be quite volatile at very short time limits.

For the second example, note that engines give evaluations from the point of view of the side to move. Lichess (and probably Chessbase as well) convert scores to white's point of view. You can do `info["score"].white()` to achieve the same in python-chess.
