### ISSUE TITLE
Which side is to move?

### ISSUE THREAD

**Issue by narciso2019** [niklasf/python-chess#450]
I guess this will be a simple one:
How can I get the info on which side is to move in a given position. I know it is verbosely written in FEN notation, however, I would like to get it via python-chess API if possible.
Forgive my ignorance, however, I tried to find an answer in the manual to no avail...
Thank you so much for your help!
Best wishes!!!

**Comment by niklasf** [comment]
[`board.turn`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.turn) can be [`chess.WHITE`](https://python-chess.readthedocs.io/en/latest/core.html#chess.WHITE) or `chess.BLACK`.
