### ISSUE TITLE
Legal FEN

### ISSUE THREAD

**Issue by rsocor01** [niklasf/python-chess#452]
Hi. 

Is there a way to determine if a FEN is a legal position using python-chess? I have tried several commands without any luck. For example,

chess.Board.set_fen(board, fen='rnb**kk**bnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1') 

This FEN position has two black kings and the program took it as valid. Even it gave me a list of legal moves with board.legal_moves. Any help determining the validity of a FEN position is appreciated.

Thank you,

Robert

**Comment by niklasf** [comment]
By default only the syntax is validated. You can check for legality like this:
```python
>>> import chess
>>> board = chess.Board("rnbkkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1")
>>> board.status()
<Status.TOO_MANY_KINGS: 4>
>>> board.is_valid()
False
```

**Comment by rsocor01** [comment]
Thanks Niklasf. That works great.

**Comment by Avo-k** [comment]
would there be a way to check if a position is a real chess position or not ? 
for example "rnbqkbnr/1ppppppp/p7/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1" is a real chess fen, the syntax is right, but it is impossible to reach this position in a game, so I guess we could say the fen is illegal.
can python-chess somehow detect this ?

thanks in advance,

**Comment by jsonn** [comment]
If you define real chess position as "can be reached from the start position", that's actually a surprisingly difficult for arbitrary positions. It's in fact a sub-category of the problem chess category of retrograde analysis.
