### ISSUE TITLE
Anaconda 3 und python-chess

### ISSUE THREAD

**Issue by ccanger** [niklasf/python-chess#454]
Hi Niclas et. al.

I tried to install the module python-chess under anaconda 3. Unfortunately, the module is not displayed under the standard modules of anaconda. What can I do so that I can use python-chess under Anaconda?

thanks !

**Comment by niklasf** [comment]
I have never used Anaconda myself, but maybe we can still figure this out. What command are you using to install?

Note that the package is called `python-chess` but the provided module is simply called `chess`.

**Comment by ccanger** [comment]
Hi Niclas,

the problem is that the python package server has an older version of python-chess, which is not compatible with python 3.7. One would have to upload on anaconda.org therefore the latest version of python-chess. It's a bit too difficult for me.

here the links:

https://anaconda.org (there search to python-chess)
https://docs.anaconda.com/anaconda-cloud/user-guide/getting-started

**Comment by niklasf** [comment]
Is it possible to just use `pip`?

**Comment by ccanger** [comment]
...
the packet installer from anaconda is called conda (not pip) and he only looks for anaconda.org. I try to find out more details and then I send you a message ... (later).

Thanks and Greetings

**Comment by niklasf** [comment]
Looks like it's still possible to install and use pip, although I assume that's not idomatic: https://stackoverflow.com/a/50141879/722291

**Comment by ccanger** [comment]
I will try it in the next few days and get in touch again. thanks ..
