### ISSUE TITLE
Exception on engine.analysis when UCI_ShowWDL is enabled

### ISSUE THREAD

**Issue by CaryKnoop** [niklasf/python-chess#457]
To reproduce on Lc0 0.23

engine = chess.engine.SimpleEngine.popen_uci(leela_023)
engine.configure({'UCI_ShowWDL': 'true'})
info = engine.analyse(myBoard, chess.engine.Limit(depth=2))

Error: 
exception parsing score cp from info: 'depth 1 seldepth 2 time 16 nodes 1 score cp 72 wdl 249 747 4 hashfull 0 nps 400 tbhits 0 multipv 1 pv g4h4 e5d5'
......etc.

The program continues after exception.

**Comment by niklasf** [comment]
Thanks for reporting. Fixed in two steps:
* Rewrite for robustness when there are unknown tokens.
* Support for WDL, e.g., `w, d, l = info["wdl"]`.

**Comment by CaryKnoop** [comment]
I took the modified Engine.py and can confirm it works fine now.  
I can't wait for the next official release. :)
Thank you!

**Comment by niklasf** [comment]
Thanks for testing. Published as v0.29.0.
