### ISSUE TITLE
is_valid fails to detect more than 2 king attackers

### ISSUE THREAD

**Issue by oscardssmith** [niklasf/python-chess#458]
given the fen `1k1q1r2/8/8/6n1/8/5Kq1/8/8 w - - 0 1` which is an invalid board position since no move could have led to it (white king attacked by 3 pieces), is_valid returns true. Any chance this is easy/desirable to prevent?

**Comment by niklasf** [comment]
It's not hard to implement, but I am not sure if this should be part of validation. The line to a proof game solver has to be drawn somewhere ...

```python
king = board.king(board.turn)
checkers = board.attackers_mask(not board.turn, king)
if chess.popcount(checkers) > 2:
    # ...
```

I'll think about it some more.

**Comment by oscardssmith** [comment]
yeah I completely understand if you don't want to check it at least without specifying a thorough check. The reason I found out about it is that a tool related to leela segfaults on these positions.

**Comment by niklasf** [comment]
@oscardssmith To make the final decision: Which tool is this, and is validating the number of checkers alone sufficient, or is further validation required? For example, would an impossible configuration like the following be problematic?

![image](https://user-images.githubusercontent.com/402777/71768493-ac9d5700-2f16-11ea-9f52-bfc90a9d9e34.png)


---

* [ ] Standard chess (2)
* [ ] Suicide (no concept of check)
* [ ] Giveaway (no concept of check)
* [ ] Antichess (no concept of check)
* [ ] Atomic ([14](https://lichess.org/editor/3N1NB1/2N1Q1N1/3RkR2/2NP1PN1/3NKN2/8/8/n7_w_-_-_0_1), thanks @ddugovic)
* [ ] King of the Hill (same as standard)
* [ ] Racing kings (0)
* [ ] Horde (same as standard)
* [ ] Three check (same as standard)
* [ ] Crazyhouse (same as standard)

**Comment by oscardssmith** [comment]
The tool that was causing issues is pgn-extract which converts pgn data into lc0 training data. Adding the check you suggested fixed the error.

**Comment by niklasf** [comment]
Thanks. Next release will have STATUS_TOO_MANY_CHECKERS.

**Comment by oscardssmith** [comment]
Thanks so much!
