### ISSUE TITLE
Chessbase CTG opening book reading

### ISSUE THREAD

**Issue by niklasf** [niklasf/python-chess#46]
Reverse engineered specification: http://rybkaforum.net/cgi-bin/rybkaforum/topic_show.pl?tid=2319
Some freely available CTG files for testing: http://www.rybkachess.com/index.php?auswahl=Downloads (even smaller non-copyrighted books would be nice)
##

**Comment by sshivaji** [comment]
I have code to do this in C++ here - https://github.com/sshivaji/ctgreader

If anyone has time, we just need a python port.

**Comment by codingjerk** [comment]
Can we reopen this? I would write the implementation
