### ISSUE TITLE
Install problem with python version

### ISSUE THREAD

**Issue by kohout16** [niklasf/python-chess#460]
Hi, I'm not sure if I upgraded python correctly. I used command `python -V` for version check, but I'm not able to install python-chess.
Thanks for any help.
![Snímek z 2019-12-29 09-29-57](https://user-images.githubusercontent.com/43451966/71554605-8ad93700-2a21-11ea-93bb-aedd5814ab71.png)

**Comment by gbtami** [comment]
Try
`pip3 install python-chess`

**Comment by Harmon758** [comment]
This almost certainly isn't an issue with python-chess.
Your default pip version can be different from your default Python version.
You can use [the version option for the pip command](https://pip.pypa.io/en/stable/reference/pip/#cmdoption-version) to check what version of pip you're using.
You can also [run pip via a specific Python interpreter](https://pip.pypa.io/en/stable/user_guide/#running-pip).

**Comment by kohout16** [comment]
Thank you, pip3 worked flawlessly :-)
