### ISSUE TITLE
board.legal_moves allows capturing king

### ISSUE THREAD

**Issue by iamlucaswolf** [niklasf/python-chess#466]
Hi Niklas,

first of all thank you for your amazing work.

I am currently doing some research involving `python-chess` and stumbled over this bug:

```python
>>> board = chess.Board(fen='k7/1Q6/K7/8/8/8/8/8')
>>> [board.legal_moves]
[<LegalMoveGenerator at 0x7f095610f250 (Qc8#, Qb8+, Qxa8, Qh7, Qg7, Qf7, Qe7, Qd7, Qc7, Qa7#, Qc6+, Qb6, Qd5+, Qb5, Qe4+, Qb4, Qf3+, Qb3, Qg2+, Qb2, Qh1+, Qb1, Kb6#, Kb5+, Ka5+)>]
```

Clearly, `Qxa8` should not be considered legal, especially since `board.push_san('b7a8')` results in a `ValueError: illegal san: 'b7a8' in k7/1Q6/K7/8/8/8/8/8 w - - 0 1` being raised.

Thanks!

**Comment by niklasf** [comment]
Thanks for reporting, I'll investigate the difference between these. Meanwhile you can use [`board.is_valid()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.is_valid) to exclude positions like this.

**Comment by niklasf** [comment]
Alright ... so:
* King captures cannot happen in valid positions, so nothing needs to be done aside from ensuring consistent behavior.
* There is no inconsistency. `b7a8` is just not valid standard algebraic notation. Both `board.push_san("Qxa8")` and `board.push_uci("b7a8")` work.

**Comment by iamlucaswolf** [comment]
Right, I realized the situation arised due to an error in some testing code of mine that would generate these positions. Totally on me, sorry!

Nevertheless, I think it would be helpful to let `legal_moves` return an "empty" generator for invalid positions, which might a closer match to the semantics of legality in `python-chess`. Or maybe just add a short sentence on `legal_moves`' behavior in these scenarios to the documentaiton?

**Comment by niklasf** [comment]
Reopening to consider some options.
* [ ] For positions: Better documentation of validity invariants
* [ ] For moves: Perhaps there should be `push()` (applying full legality checks and raising `ValueError`) and `push_unchecked()` (caller is responsible).

**Comment by niklasf** [comment]
Via 47720244d19e624d6e924a54eaf799d4a61ea85d.

Regarding position validity:
```
+    :warning: It is possible to set up and work with invalid positions. In this
+        case :class:`~chess.Board` implements a kind of "pseudo-chess"
+        (useful for implementing chess variants).
+        Use :func:`~chess.Board.is_valid()` to detect invalid positions.
```
