### ISSUE TITLE
Should pawn drops in Crazyhouse reset the halfmove clock?

### ISSUE THREAD

**Issue by niklasf** [niklasf/python-chess#467]
Current behavior:

python-chess :-1: 
scalachess :-1:
shakmaty :-1:
chessops :-1:
cutechess :+1:
ddugovic/Stockfish :+1:

This is only a matter of style, but let's try to make this consistent. Any arguments for yes/no?

**Comment by QueensGambit** [comment]
In my opinion it makes sense to reset the halfmove clock after pawn drops.
A pawn drop is also a certain type of pawn move which changes the pawn structure.
I think the primary reason why it is not reset in some programs or libraries is because the same code as in classical chess was reused.

**Comment by niklasf** [comment]
@ddugovic Thoughts?

**Comment by QueensGambit** [comment]
I consulted the crazyhouse discord server about this. Here a few arguments for both sides:
:+1: :
* "I would argue that any drop should reset the counter. In chess the 50 move is to avoid shuffling with no purpose, but dropping a piece should be a significant change in the position and not count as shuffling. That is my view on it." -- gsvc
* "I would perhaps start from the thought that "special move" is a bit arbitrary and that "dropping mechanism" is an essential part of crazyhouse. Therefore, when you drop a pawn on the board, you place it on the board and make a pawn move." -- MMichael

:-1: :
* "But the thought that dropping doesn't ever count as shuffling, I don't like it for that reason."
 -- MMichael

**Comment by niklasf** [comment]
Thanks. All libs are now :+1:

**Comment by ddugovic** [comment]
Thanks, sounds good to me although prior to coding in SF I should have asked the community.
