### ISSUE TITLE
Moving another player's chess piece becoming my chess piece by using from_uci

### ISSUE THREAD

**Issue by gabrielchung** [niklasf/python-chess#470]
A simple case:
```
import chess
import chess.svg
board = chess.Board()
foo = chess.Move.from_uci('a7a6')
board.push(foo)
print(board)
```

Now, the chess piece at a6 becomes white (upper case) which should be black (lower case).
```
r n b q k b n r
. p p p p p p p
P . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R
```

**Comment by niklasf** [comment]
[`board.push()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.push) requires at least a pseudo-legal move, as documented.

You can use `board.is_legal(move)` to check legality, or use the shortcut `board.push_uci("a7a6")` which raises `ValueError`.
