### ISSUE TITLE
Additional Info regarding clock info will be very helpful

### ISSUE THREAD

**Issue by learnnshare** [niklasf/python-chess#472]
The docs for python-chess are very informative. The code snippets are very helpful for getting a basic structure.
But,I find no information on how to extract the clock information.  If one example on how to extract the clock information from PGN is included it will be very helpful:https://python-chess.readthedocs.io/en/latest/index.html. 
For example : 
first_game = chess.pgn.read_game(pgn)
for move in first_game.mainline_moves():
Gives me the entire move list. similarly, how can I get the associated clk information?
1. d4 { [%clk 0:02:00] } 1... d5 { [%clk 0:02:00] }

**Comment by gbtami** [comment]
See https://github.com/niklasf/python-chess/issues/253#issuecomment-444938283
