### ISSUE TITLE
Minor Cosmetic Typo in document

### ISSUE THREAD

**Issue by learnnshare** [niklasf/python-chess#474]
Very Minor  Typo in doc : 
"The input and input streams will be linebuffered and able both Windows and Unix newlines"
Nice to have :"The input and input streams will be linebuffered and enable/handle both Windows and Unix newlines"
https://python-chess.readthedocs.io/en/v0.16.2/uci.html
![image](https://user-images.githubusercontent.com/43683388/76137086-f8779400-605e-11ea-8f5c-40d1d2729bd3.png)

**Comment by niklasf** [comment]
Thanks, but v0.16.2 is more than 3 years old. The latest release is v0.30.1.
