### ISSUE TITLE
Board status does not cover all cases

### ISSUE THREAD

**Issue by sabit-zahin** [niklasf/python-chess#477]
To reproduce, follow the steps below

```
from chess import Board, Piece

board = Board()
board.clear()

board.set_piece_at(0, Piece.from_symbol('R'))
board.set_piece_at(7, Piece.from_symbol('R'))
board.set_piece_at(20, Piece.from_symbol('K'))
board.set_piece_at(4, Piece.from_symbol('k'))

print(board)

board.turn = False
print(board.is_valid())  # True
print(print(board.status()))  # Status.VALID
```

This is the board:
```
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . K . . .
. . . . . . . .
R . . . k . . R
```

Looks like the `status` method checks if there are too many checkers here: https://github.com/niklasf/python-chess/blob/c1282f9b79a3920f4cd0b28a28516ff9b20a747f/chess/__init__.py#L3141

Granted if there are more than 2 checkers, the configuration is invalid. But even if there are 2 checkers, the board configuration can still be invalid, as demonstrated in the scenario above.

**Comment by niklasf** [comment]
Thanks for reporting.

This is why I was hesitating (https://github.com/niklasf/python-chess/issues/458#issuecomment-560423253) to add STATUS_TOO_MANY_CHECKERS in the first place.

> The line to a proof game solver has to be drawn somewhere ...

Is there any software that actually has problems with this "invalid" position?

**Comment by sabit-zahin** [comment]
Nope, not to the best of my knowledge. I was checking out `python-chess` for a pet project and discovered this case. IMHO, I was expecting the library to catch this, particularly when there is an explicit flag called `STATUS_TOO_MANY_CHECKERS`. Do you think this should be addressed in some future release?

If not, we should at least update the docstring of `is_valid` and/or `status` to point out that the method might sometimes return false positives. Thanks!

**Comment by niklasf** [comment]
Clarified the documentation.

The strictest possible validity check is: Is the position reachable with a series of legal moves from the starting position? This is "proof game solving", and unfortunately this is not computationally feasible.

So instead I aim to meet all common requirements of existing software.
