### ISSUE TITLE
Game viewer

### ISSUE THREAD

**Issue by aole** [niklasf/python-chess#483]
Is it possible to have a full game viewer for notebooks?
With the ability to scrub thru' the moves.

**Comment by niklasf** [comment]
Sounds useful. Not planning to work on this myself, but happy to accept patches (with reasonable complexity).

**Comment by PedanticHacker** [comment]
Close this already!

**Comment by PedanticHacker** [comment]
If no one is going to implement what is discussed here, then this issue being open is just an annoyance.

**Comment by PedanticHacker** [comment]
This is too complex to implement. I'd close this issue.

**Comment by niklasf** [comment]
Landed via #740.
