### ISSUE TITLE
Info handler logic does not seem to work in infinite mode

### ISSUE THREAD

**Issue by sshivaji** [niklasf/python-chess#49]
Can info handler to extended to allow display intermediate output before best move is returned. In infinite mode, best move is never returned.

**Comment by niklasf** [comment]
Info handlers are working for me.

Infinite mode only will return when it is explicitly stopped - by a different thread or asynchronously.

```
#!/usr/bin/env python

import chess
import chess.uci

import time

class MyHandler(chess.uci.InfoHandler):
    def post_info(self):
        super(MyHandler, self).post_info()
        print(self.info)

engine = chess.uci.popen_engine("stockfish")
engine.info_handlers.append(MyHandler())

go_cmd = engine.go(infinite=True, async_callback=True)

time.sleep(3)

engine.stop()
print(go_cmd.result())
```

**Comment by sshivaji** [comment]
The analysis should be visible even without an explicit stop. When using
UCI engines with chess program UIs, you can see the output continuously
without issuing a stop.

**Comment by niklasf** [comment]
Of course the info handler also receives events before the stop (or if no stop is there at all). If it doesn't for you, then this is a bug.

Is the example working as expected?

**Comment by sshivaji** [comment]
Your code works. I have a request. Can you update your documentation example with the code you posted? I did not realize I have to override post_info to do what I need. Thanks!


e.g.

class MyHandler(chess.uci.InfoHandler):
    def post_info(self): # Will continously be called in the background.
        super(MyHandler, self).post_info()
        print(self.info)

**Comment by niklasf** [comment]
Updated the documentation. I just then realized that the documentation had an outdated example, where infinite search would be blocking forever as you described, because `async_callback=True` was missing.
