### ISSUE TITLE
Just a Suggestion:Reference to discussion forms  (if any) will help novice developers

### ISSUE THREAD

**Issue by learnnshare** [niklasf/python-chess#501]
I was wondering if there are any discussion forms related to python-chess where we can seek clarification in case we are stuck. a reference to the link on https://github.com/niklasf/python-chess similar to the existing "Selected use cases" will help.
Wanted to check the best place to contact for help and suggestions ( there could be many like me who would give up when they are stuck - The program and documentation is so well written but some help and assistance initially will help and motivate aspiring developers- The information is overwhelming when someone gets started) 
For example:
I wanted to just extract the headers and and also perform some operations on the game-text (directly - apply some regex).
but when I run chess.pgn.read_game(pgn) - it parses the game ( which currently I don't want) as it is adding overhead in performance with pypy3 also it adds 25 sec for 10000 games, I want to bring it down.  I am sorry , as I am aware github is not the place for requests like these, but did not know where to approach.
pgn = open(input_file)
first_game = chess.pgn.read_game(pgn)
is_header_valid,header_info_lst=extract_header_info(first_game.headers) --> This information is helpful .
But I want the game text.
raw_game_text = str(first_game)
raw_game_text=raw_game_text.split('\n\n')
 game_pgn=raw_game_text[1]
 game_pgn=game_pgn.replace('\n','')
Apply some regex on game_pgn

**Comment by niklasf** [comment]
Regarding discussion forums: For this library, there is currently GitHub and this Gitter Chat: https://gitter.im/python-chess/community.

Regarding the question: At least some tokenization is required to correctly determine where games end, so there is no exact match for your request. Perhaps visitors or [skimming](https://python-chess.readthedocs.io/en/latest/pgn.html#skimming) can get close. What's the regex you want to apply?

**Comment by learnnshare** [comment]
Thank you Niklas for the quick response. Thank you for the link related to the discussion forum.
Background:
I am trying to process the png files from database.lichess.org
The current issue is: The files are large, 100 GB uncompressed.
I need the data related to how long the game took, The PGN Files ( header section) there don’t have this info directly. So, I am parsing the game information which has the clock info for every move.
One I get some statistics then I will narrow and do detailed analysis for which the functionality in python-chess will be extremely useful.
Option 1:
First, I tried, using python-chess to read and parse the game , it worked fine but took me 140 seconds for 10000 games. ( which is very slow ) .
It took me more than a day to process just one day worth of data. When I profiled the data I found that the for loop that I was using to extract the clock info for every move taking the major chunk of time.
By using regex : COMMENT_COMMAND_REGEX = re.compile(r"\[%(\w+)\s+([-+/,.:#\"\w\s]+)\]")  for parsing { [%clk 0:01:57] } For every move.
Using ExtPgnVisitor as visitor :
first_game = chess.pgn.read_game(pgn, Visitor= ExtPgnVisitor)

ExtPgnVisitor(chess.pgn.GameBuilder):
……
    def visit_comment(self, comment):
        chess.pgn.GameBuilder.visit_comment(self, comment)
        node = self.variation_stack[-1]
        board = node.board()
        for match in re.finditer(COMMENT_COMMAND_REGEX, comment):
            movecount = board.fullmove_number - 1 if board.turn else board.fullmove_number
            command, text = match.groups()
            if command not in self.command_comments:
                self.command_comments[command] = []
            self.command_comments[command].append((movecount, node.san(), text))

Option 2: This speeded up the process and now the code runs 10000 games in 25 seconds ( with pypy3). But still slow.
so to avoid the forloop , I tried to run pattern = re.compile(r'\[\s*%clk\s*([0-9]+:[0-9]+:[0-9]+)\s*\]') on the entire game data by
pgn = open(input_file)
first_game = chess.pgn.read_game(pgn)
is_header_valid,header_info_lst=extract_header_info(first_game.headers) --> This information is helpful .
But I want the game text.
raw_game_text = str(first_game)
raw_game_text=raw_game_text.split('\n\n')
game_pgn=raw_game_text[1]
game_pgn=game_pgn.replace('\n','')
Apply some regex on game_pgn

option 3: I tried this but then I was not getting the game information.
first_game = chess.pgn.read_game(pgn, Visitor=chess.pgn.SkipVisitor)

option 4:
The end of the line is pretty straight forward in lichess games – headers( Start with [ and end with ] )  ( followed by a blank line) followed by the game ( followed by a blank line) [ most of the times the game record has Result :( 1-0, 1/2/ ½ 0-1 at the end of the game ) but some abandoned games don’t have this marker.
I could directly read from a file, but I wanted to make use of the existing library to the extent possible. ( and it takes  1 sec for 1000 games) but making use of just basic end of line markers – but this method is not very robust and want to avoid this route.

I am not very comfortable with python ( especially classes and hence struggling a bit )

Thanks
Amar

**Comment by niklasf** [comment]
Perhaps in this case it's better not to use the PGN parser at all. The Lichess exports are formatted very consistently, with none of the issues that usually make parsing PGNs tricky.

Headers, always starting with `[`. Empty line. Entire movetext on single line. Empty line. Repeat.

**Comment by learnnshare** [comment]
Thanks a lot Niklas. Regarding your earlier response : "Regarding discussion forums: For this library, there is currently GitHub and this Gitter Chat: https://gitter.im/python-chess/community." I have joined the gitter - Your response also mentions "For this library, there is currently GitHub" - so is it okay to post any question on github if I am stuck with something or need some clarification regarding usage of library (  ( I was under the impression that github is only for posting code and reporting issues).

**Comment by niklasf** [comment]
Policies vary across GitHub, but asking questions in GitHub issues is fine by me. Some might lead to improved documentation ...
