### ISSUE TITLE
En passant square not recorder properly

### ISSUE THREAD

**Issue by TheBookLvr** [niklasf/python-chess#530]
Hi, I run this code:

`import` chess.pgn
`testboard` = chess.pgn.Game().board()
`testboard.push(chess.Move.from_uci('d2d4'))`
`print(testboard.fen())`

It outputs : 
rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1

According to [FEN](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation)
definition number 4:

> If a pawn has just made a two-square move, this is the position "behind" the pawn. This is 
> recorded regardless of whether there is a pawn in position to make an en passant capture.[2]

Then the correct FEN should be : 
rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq d3 0 1

?

Your sincerely

**Comment by niklasf** [comment]
There are multiple refinements of the FEN specificaton:

```
>>> board.fen(en_passant="fen")
'rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq d3 0 1'
>>> board.fen(en_passant="xfen")
'rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1'
>>> board.fen(en_passant="legal") # default
'rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1'
```

https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.fen
