### ISSUE TITLE
[docs] Mention the type of colors and pieces in documentation

### ISSUE THREAD

**Issue by nikochiko** [niklasf/python-chess#532]
**Reference:** https://python-chess.readthedocs.io/en/latest/core.html#colors
The documentation does not mention the type of `chess.WHITE` and `chess.BLACK` within the scope of this library. So I am building a project on top of python-chess and I wanted to annotate the args. After looking through the codebase (reference: https://github.com/niklasf/python-chess/blob/master/chess/__init__.py), I came to know that the type should be `chess.Color`.
I think the documentation should mention this somewhere so it is more convenient. Same goes for `chess.PieceType`.

**Comment by niklasf** [comment]
Agreed, sounds useful to include. Found a way to update Sphinx on readthedocs and added these annotations.

**Comment by nikochiko** [comment]
Perfect! Thanks
