### ISSUE TITLE
Method to check if a move is a check

### ISSUE THREAD

**Issue by nikochiko** [niklasf/python-chess#535]
The scenario is that I have to check whether a move is a check before playing it on the board. I didn't see any direct methods for doing so. 
For now I am thinking of doing:
```python
legal_san = [board.san(move) for move in board.legal_moves]
check = board.san(given_move) + '+' in legal_san
```
or by playing it on the board, calling `board.is_check()` and undoing the move with `board.move_stack.pop()`.

So two things:
1. Is there a more efficient way to do it?
2. If it makes sense to include a method for that within the library

ps. i can create a PR with the additions if required

**Comment by niklasf** [comment]
There's [`board.is_into_check(move)`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.is_into_check). It's already more efficient than push/check/pop, but of course optimizations are welcome.

**Comment by nikochiko** [comment]
Yes, I was about to point out the same :smile:

**Comment by niklasf** [comment]
I would go with your second suggestion:

```def gives_check(board, move):
    board.push(move)
    try:
        return board.is_check()
    finally:
        board.pop()
```

I agree a more efficient implementation would be useful.

**Comment by nikochiko** [comment]
Yeah, this looks good for now. 
On the implementation, I think it could be done similar to [`is_into_check`](https://github.com/niklasf/python-chess/blob/master/chess/__init__.py#L1589-L1590) method where the `self._generate_evasions` method is used.
