### ISSUE TITLE
3 rep review

### ISSUE THREAD

**Issue by brianprichardson** [niklasf/python-chess#536]
There have been some posts on the Lc0 Discord about this game being correct or not for a 3 rep.  I'm not clear at all about what is happening, but in case there might be a problem wanted to call attention to it.  Here is a link to the game, I think:
https://lichess.org/bdJCtxlX#91

**Comment by niklasf** [comment]
This should be a three-fold repetition, because these positions are identical:

https://lichess.org/bdJCtxlX#83
https://lichess.org/bdJCtxlX#87
https://lichess.org/bdJCtxlX#91

Is it not recognized as such?

**Comment by brianprichardson** [comment]
I don't know what the Leela chess zero Discord folks think is the problem.
It is in the #dev-public channel with this "ID" 143240917602664448.
There is a claim it is a python-chess bug.
It might be an en passant issue.
It might be an old version of python-chess.
I am having trouble figuring it out.
If you can read the Discord chat maybe you will see what they mean.
If you don't want to bother, and can do a post asking for details that I can share with you.

**Comment by niklasf** [comment]
Thanks. It turned out to be basically this issue, which is not a bug in python-chess, nor the engine: https://github.com/ornicar/lila/issues/5547
