### ISSUE TITLE
Marking pawn promotion SAN without promotion piece as ambiguous?

### ISSUE THREAD

**Issue by nikochiko** [niklasf/python-chess#539]
As of now, calling `board.parse_san(move)` on a promotion move without mentioning the piece (i.e. simply `d8` instead of `d8=Q`), the error log shows 'illegal san'.
Perhaps calling the move ambiguous would be more precise since the pawn can be promoted to 4 different pieces, and this ambiguity was the cause of the error.

**Comment by niklasf** [comment]
I understand, but an alternative point of view is that `d8` is syntactically valid and matches no legal move (and is therefore illegal). Won't fix.
