### ISSUE TITLE
This code is amazing, and how can I display the moves in a more natural way?

### ISSUE THREAD

**Issue by zhaoshaojun** [niklasf/python-chess#543]
Hi all,
It code is pretty amazing, and I was able to get it to work on Mac OS. 

One question I have had since I checkout out the code: so we can display the games in a pretty SVG format in a juypter notebook, the only problem is when I want to look at the moves of a game, that SVG pictures become quite un-natural (too many SVG pictures). A chess GUI like xboard is a better choice to show the moves. I could have save a game in PGN file, and then open it with xboard. But what I really want to achieve is to generate or play games in python-chess, and see the moves in xboard at the same time. I do not want to wait until the end of the game, and save to PGN, and open the file in, say, xboard. 

So is there a way to stream the moves to xboard, or a GUI that accepts a stream of moves?
Best regards

**Comment by niklasf** [comment]
Thanks.

Besides the SVGs, there is currently no other Jupyter integration. It was already requested in #483, so closing this as a duplicate.
