### ISSUE TITLE
Coordinates layout issue

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#546]
I think there's something wrong with how the top and bottom (horizontal) coordinate strips are layed out. I made a screenshot of my application, portraying the issue. [Click!](https://ibb.co/ChLJz40)

Basically, the top coordinate strip is too far away from the top side of the chessboard (there's a too big of a gap and looks ugly) while the bottom coordinate strip is too close to the bottom side of the chessboard (so close, in fact, that the letters `b`, `d`, `f` and `h` overlap the chessboard).

The left and right (vertical) coordinate strips are okay.

**Comment by niklasf** [comment]
![image](https://user-images.githubusercontent.com/402777/80501440-b9373680-896f-11ea-9a19-2f43aef63a45.png)

**Comment by niklasf** [comment]
Will probably need a way to reproduce this, i.e., the generated SVG and the viewer that renders it in this way.

**Comment by niklasf** [comment]
I attempted a blind fix. Please update to latest master and check if that does anything. Also the font-family might be interesting to know.

**Comment by PedanticHacker** [comment]
I am on Manjaro Linux. I found where the svg.py file is on my system. I am editing it manually, saving the svg.py file and testing how do coordinates change if I do this or that. I edited it as you did it, but it all stays exactly the same, no change whatsoever. By playing around, I noticed that nothing affects these coordinates, whatever I give it. Strange. Only font size has noticeably increased if I gave a manual value of `30` instead of a calculated value. But the alignment stays the same, even if I pass in values like `top` or `bottom`.

**Comment by niklasf** [comment]
Are you using QtSvg, still?

**Comment by PedanticHacker** [comment]
Yes.

**Comment by PedanticHacker** [comment]
```
def _text(content: str, x: int, y: int, width: int, height: int) -> ET.Element:
    t = ET.Element("text", {
        "x": str(x + width // 2),
        "y": str(y + height // 1.5),
        "font-size": str(max(1, int(min(width, height) * 0.7))),
        "text-anchor": "middle",
        "alignment-baseline": "middle",
    })
    t.text = content
    return t
```

These settings seem to work okay for me. Can you try them on your end as well?

**Comment by PedanticHacker** [comment]
The issue seems to be in the `y` parameter. It works best if the dividing value is `1.5`.

**Comment by PedanticHacker** [comment]
![Screenshot_20200429_194654](https://user-images.githubusercontent.com/14254085/80629011-81ed8600-8a52-11ea-837b-f825a815bfeb.png)

This is how my chessboard coordinates look now after I fixed the _text() function in the svg module. Looking good!

**Comment by PedanticHacker** [comment]
Fixed my svg.py module according to 9baa1f9 and now I get this... [I had to take a picture of my laptop's screen with my iPhone 8 because the screenshot I made did not include the white fill, don't know why]

![F79056-BC-503-E-4-A6-D-99-D7-75-DBA59-D2068](https://user-images.githubusercontent.com/14254085/80634828-558a3780-8a5b-11ea-8e98-0d5582921195.jpg)

**Comment by niklasf** [comment]
Thanks for trying that branch. Looks like SVG Tiny has no reliable way to vertically align text. Prerendered everything as paths.

Reproducible using the following snippet, for future reference:

```python
import chess
import chess.svg
import sys

from PyQt5 import QtCore, QtWidgets, QtGui, QtSvg

class MainWindow(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.doc = QtSvg.QSvgRenderer(QtCore.QByteArray(
            chess.svg.board(chess.Board()).encode("utf-8")))

    def paintEvent(self, e):
        p = QtGui.QPainter(self)
        p.setViewport(0, 0, 400, 400)
        self.doc.render(p)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
```
