### ISSUE TITLE
Problem with legal moves after flipping the board

### ISSUE THREAD

**Issue by KingSlendy** [niklasf/python-chess#547]
Hi, the problem is that after flipping the board the legal moves seem to be vastly reduced, is it a bug or am I doing something wrong?

`board = chess.Board()

print(list(board.legal_moves)) #Here are the initial legal moves working as intended  

board.apply_transform(chess.flip_vertical)  

print(list(board.legal_moves)) #Here the legal moves are reduced to only 4 moves`

**Comment by niklasf** [comment]
After that transform the position is https://lichess.org/analysis/standard/RNBQKBNR/PPPPPPPP/8/8/8/8/pppppppp/rnbqkbnr_w_-_-_0_1, with white to move.

All the pawns are on the seventh rank and can't move forward, so the only possible moves are the four knight moves.

**Comment by KingSlendy** [comment]
Ohhh, I get it now, I was confusing myself, thanks!
