### ISSUE TITLE
Error with mainline_moves()

### ISSUE THREAD

**Issue by iitdanand** [niklasf/python-chess#548]
I am novice in python programming and i have started using python-chess. I tried a simple example and i am getting an error with mainline_moves(). Please see below for the code i used. 

Please help. Thanks, Anand.

![image](https://user-images.githubusercontent.com/56750544/80574261-ce5ca580-8a01-11ea-87d1-6e53bf836046.png)

![image](https://user-images.githubusercontent.com/56750544/80574112-85a4ec80-8a01-11ea-8d31-fa7725b32057.png)

**Comment by niklasf** [comment]
What's your `chess.__version__`?

**Comment by iitdanand** [comment]
Thank you. It worked now after updating the package to the latest version. I downgraded the package in order to follow the code given in the below link.
https://medium.com/@andreasstckl/chessviz-graphs-of-chess-games-7ebd4f85a9b9
The chess engine uci interface was not compatible with the latest version of python-chess.
I will stick to the latest version and try to adapt the engine uci related code.
Thanks again.
