### ISSUE TITLE
SF BMI2 v modern suggestion

### ISSUE THREAD

**Issue by brianprichardson** [niklasf/python-chess#550]
If including SF with python-chess then certainly the lowest common denominator version should be used. Many have PCs without BMI2 support (some even without popcnt). Python-chess should not be triggering problems with SF which is not part of this repo, IMHO. If you want to leave it as is with BMI2 that's fine. Then, if it triggers a bunch of "python-chess does not work for me anymore" issues it is easy to see if this is the cause and revert at that point.  I still just "don't get" Github and created a new issue to be noticed.  The numerous other related issues and PRs looked "done" and don't know how to reopen.  Feel free to close as appropriate.

**Comment by niklasf** [comment]
Stockfish is not included or packaged with python-chess. It's merely download on the CI infrastructure to test the UCI interface.
