### ISSUE TITLE
jupyter dark mode incompatible

### ISSUE THREAD

**Issue by zhaoshaojun** [niklasf/python-chess#552]
If I enable dark mode in jupyter lab, the chess board coordinates become invisible. Is this something can be fixed?

How to reproduce it: just enable dark mode in jupyter lab, and run
```
board = chess.Board()
board
```

**Comment by niklasf** [comment]
Possible ideas would be a background color for the coordinate margin or putting the coordinates on the board itself :thinking:

**Comment by PedanticHacker** [comment]
I’d rather see a background color for the coordinate margin, like a chessboard frame that would have the coordinates on it.

**Comment by niklasf** [comment]
Preview:
![image](https://user-images.githubusercontent.com/402777/80865792-dc255b80-8c8b-11ea-8773-fbdaa689cf4a.png)

**Comment by PedanticHacker** [comment]
Yeah, the preview looks amazing!

**Comment by zhaoshaojun** [comment]
@niklasf thank you for fixing this. I have been using dark mode all the time, and for a long time, I thought python-chess does not have coordinates.
