### ISSUE TITLE
SVG chessboard does not support onclick attribute

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#555]
It would be very nice to have each SVG piece and each SVG square to implement the onclick attribute so that we could use that attribute and link it with a function. That way we won’t need to do x and y coordinate calculations where in the x and y plane a mouse click was made. Is that something that is doable?

**Comment by niklasf** [comment]
Sorry, that's out of scope for the module. If anything interactive were going to happen, it would be a widget for Jupyter notebooks (#483).

**Comment by PedanticHacker** [comment]
Is it somehow possible to get the value (piece type) of an SVG piece via SVG code itself or maybe via CSS (besides the piece_type_at function)?

Also, is it possible to get values (names) of squares, like getting the SVG value of the bottom left square (if not flipped) to be returned as A1?
