### ISSUE TITLE
Bitboard caching during pgn parsing

### ISSUE THREAD

**Issue by asdfjkl** [niklasf/python-chess#56]
I have the following issue:

- I parse a pgn and get a resulting game
- each game node has self.board_cached = None initially
- suppose now I jump to move no. 80 and try to get that board (this can e.g. happen in my chess GUI, if the user decides to immediately to jump to that position. Then I need the san (for redrawing) which triggers the board as well as the board itself (for e.g. sending the fen position to the engine, or for checking validity of user inputed moves etc.)
- A call goes to node.board which triggers calls to recursively traverse up to the root node, compute board(), and back down in the tree. This is *SLOW*, especially IF the game is large. This game (http://www.chessgames.com/perl/nph-chesspgn?text=1&gid=1497429) with 271 moves is a nice example. It gets even worse if this game would be annotated with lots of variations.
- After that everything is fine, since all board_caches are "initialized". I can now get boards quickly; even if some nodes change: As long as not all parent nodes are changed, the board can quickly be rebuild by one of the parents, and I can quickly get e.g. the new san.

Current Solution:
- I currently load a game, and then afterwards traverse through the nodes and trigger calls to node.board() to initialize the whole tree. During that I present a "load screen" to the user. But this is actually quite slow on older systems, and makes the user wait to "just" load up a pgn, which is a bad user experience.

Question:
- Is it possible to somehow build up the board cache directly during pgn parsing in order to speed up the process? Unfortunately I have no clue about the bitboard representation, and if that would even bring a performance improvement...

thx

**Comment by niklasf** [comment]
Hi. I'll look into this soonish. I am sure there's room for improvement here, as you suggested.

Possible benchmark:

```
import chess
import chess.pgn
import timeit
import sys

def parse_pgn():
    with open("hikaru.pgn") as pgn:
        game = chess.pgn.read_game(pgn)
        _ = game.end().board()

        sys.stdout.write(".")
        sys.stdout.flush()

if __name__ == "__main__":
    print(timeit.timeit(
        stmt="parse_pgn()",
        setup="from __main__ import parse_pgn",
        number=100))
```

**Comment by niklasf** [comment]
Profiling revealed that just initializing fewer caches works best in the benchmark scenario, slightly improving parser speed and **making board accesses instant**.

This is included in the new `v0.12.4` release.

Please check out how this works in your use case.

**Comment by asdfjkl** [comment]
currently still using 0.8. will update to 12.4 as soon as I can and report. 
thx very much!

**Comment by niklasf** [comment]
Looking forward to it. If the custom patches are generally useful, I'd be happy to accept PRs, also making future updates easier.

**Comment by asdfjkl** [comment]
... have started integrating 12.5, and my first impression is that it seems magnitudes faster so far. 

My patches are mostly custom things to print an HTML/San representation of the game, that can be displayed in a QTextEdit. I feel they are very specific and not useful generally for the lib.

**Comment by niklasf** [comment]
Makes sense. Thanks for testing (and of course Jerry in general)! Feel free to reopen any time.
