### ISSUE TITLE
cannot import chess

### ISSUE THREAD

**Issue by ScarecrowY** [niklasf/python-chess#561]
Hi, when I tried to import chess, I always got the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named chess
```
But I have already installed the chess library

**Comment by niklasf** [comment]
Hi, please share more info about your OS, Python version, and the method you used to install the library.

**Comment by ScarecrowY** [comment]
Hi, I am using macOS Catalina. python version is 3.7.4. I used pip to install the library.

**Comment by niklasf** [comment]
What's your `pip --version` and what's the exact command you used to install python-chess?

**Comment by ScarecrowY** [comment]
my pip version is pip 20.1.1. And i used ```pip install python-chess```

**Comment by niklasf** [comment]
Sorry, I should have asked for the exact output of `pip --version`, e.g.
```
pip --version
pip 20.0.2 from /usr/lib/python3.8/site-packages/pip (python 3.8)
```
Importantly, does it match your python version?

**Comment by ScarecrowY** [comment]
Oh sorry, the out put for pip --version is 
```
pip --version
pip 20.1.1 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)
```
and I was doubting if the problem was because that the anaconda python was being used, so I tried both pythons. but neither of them worked

**Comment by ScarecrowY** [comment]
Also I think it matched my python version

**Comment by ScarecrowY** [comment]
I fixed it, i think it was because I was using my conda python. Thank you!
