### ISSUE TITLE
PV line becomes single move after several seconds

### ISSUE THREAD

**Issue by jackalsh** [niklasf/python-chess#57]
I try to probe pv over time with short intervals.
After a few seconds a long line of solution becomes single move.

Using Stockfish engine, no similar behaviour in different GUI's.

Code example:
http://paste.ofcode.org/RznVYxhb49MCSniJdKuYHG

Python version: 3.4.3
Library version: python_chess-0.12.3 (checked with several versions)

Output example:
http://paste.ofcode.org/c4p2JpkJTqNaJGnnxy73TU

**Comment by niklasf** [comment]
Hi. Thanks for reporting this. I can not reproduce it with ``Stockfish 170815 64``. Which specific version of Stockfish are you using? Which operating system?

Also the debug log might help. Can you please try adding
```
import logging                                                                  
logging.basicConfig(level=logging.DEBUG) 
```
at the start? The output is going to be very verbose but might help tracking down the problem.

---

Minor completely unrelated issue:
```
with handler:
    time.sleep(0.1)
    print(" ")
    print(handler.info['pv'])
```
It's a good practise to avoid long running operations (like sleeping) while holding the lock. Move sleeping outside the block.

**Comment by jackalsh** [comment]
Logging added.
http://paste.ofcode.org/hMbUTH5PT9vB2FeB3jZNDF
It seems to happen at the moment when engine sends the line 
####
DEBUG:chess.uci:<PopenProcess at 0x7f9683c10ef0 (pid=2927)> >> info depth 26 currmove f7b7 currmovenumber 1
####

Stockfish version: 101015 64 (Built from git sources)

I agree with you about bad practice. This is temporary code to show the problem.
Thanks.

**Comment by niklasf** [comment]
I think this kind of line is more relevant:
```
info depth 26 seldepth 54 multipv 1 score cp 1927 lowerbound nodes 10497070 nps 3291649 hashfull 997 tbhits 0 time 3189 pv f7b7
                                                                                                                        ^^^^^^^
```
**Stockfish actually sends a PV with one move.** Latest Stockfish official from Git also doesn't do this for me in the test position and there seem to be no recent related changes. Maybe I could try compiling the exact Git commit.

**Comment by asdfjkl** [comment]
maybe related: I observed similar behavior of stockfish. suddenly sends pv with one move once in a while. Stockfish 6 64, OSX. Not sure about version number, but MD5 (./stockfish_darwin_64) = 3ebc0257cf6ce184d0a06fcadc13c8dc
I didn't observe this behavior on other platforms. Also note that I don't use python-chess' uci functionality, but my own wrapper. So I think its definitely a stockfish issue...

**Comment by jackalsh** [comment]
You are right, this seems to be hash table's cuts. I need different approach building pv line.
Thanks.

**Comment by jackalsh** [comment]
I did some more checks and have something to say.
Indeed, it's completelly engine's issue, but there something more to say.
Let's take 3 different cases.
First, I run this code: http://paste.ofcode.org/4PsG7cB8qWCWEfQJ9f7ucf
As we have seen before, output is following: http://paste.ofcode.org/33XtUvLaXZfDev5MKEMyV2c
We see, that at one moment engine begin to send single move and pychess takes this move as main.

Second case is to configure engine to use MultiPV of 2.
engine.setoption({'MultiPV': 2})
Code: http://paste.ofcode.org/3arHqvztHj7t4YwvSesuLRR
Result: http://paste.ofcode.org/7FS4VMW4y2ntSBVH8nb7az
We see, that although engine's output the same, pv NOT BREAKS!!! This is the behaviour I seek!

My first idea was to use multipm of 1. Let's see what se have:
engine.setoption({'MultiPV': 1})
Code: http://paste.ofcode.org/33eHQVStA8psqAdsGALHhpJ
Result: http://paste.ofcode.org/Jx76T9Cvk8chC6VKyKX8KS
Unfortunately, the pv breaks as before. Using pv of 1 equally to not use it at all.

So the solution to my problem will be using multipv of 2 even if I don't need it and this is waste of resources.

Engine's output not changed, so it seems to be pychess's issue.
My suggestion is to make multipv mode of 1 the same behaviour.

Thanks in advance for your help.

**Comment by niklasf** [comment]
Intresting. Can you please provide the full output in the MultiPV 2 case? The ``currmove`` info is irrelevant for the ``pv``. Would be intresting to see what else Stockfish sends.

**Comment by niklasf** [comment]
Closing this now. I don't think I can do much on the Python side of things.
