### ISSUE TITLE
Suggest converting move returned by engine to lower case

### ISSUE THREAD

**Issue by hasnul** [niklasf/python-chess#571]
Running one of the examples from the uci communication section in the docs.
The engine I was using triggered an exception because it was promoting and the move string it returned to the program used a capital 'Q' rather than a small 'q' which is not in PIECE_SYMBOLS.

Exception:
ValueError: 'Q' is not in list

Logging snippet:
DEBUG:chess.engine:<UciProtocol (pid=None)>: >> bestmove b2b1Q ponder e7e8Q

Suggest lowering uci string in method Move.from_uci to make it more robust.

**Comment by niklasf** [comment]
Btw, which engine is this?

**Comment by hasnul** [comment]
AnMon 5.75

**Comment by niklasf** [comment]
Alright, added because it's trivial to do so. But the spec is clear on this, so this should also be reported as a bug to AnMon.
