### ISSUE TITLE
Support for xboard engines that don't have setboard feature i.e. setboard=0

### ISSUE THREAD

**Issue by hasnul** [niklasf/python-chess#573]
This came up today when I was trying Fairy-Max 5.0b which comes with the Xboard GUI and was confronted with the following error:

`chess.engine.EngineError: xboard engine did not declare required feature: setboard`

because Fairy-Max returned `setboard=0`. 

The way I've interpreted the spec at [https://home.hccnet.nl/h.g.muller/engine-intf.html](https://home.hccnet.nl/h.g.muller/engine-intf.html), if the engine says `setboard=0` then fall back to the `edit` command.

**Comment by niklasf** [comment]
> **edit**
> [Obsolete] A multi-line command that is the default method for letting the engine set up a position, used with engines that have not sent 'feature setboard=1'. The command will be terminated by a line consisting of a single period. Until then, each line can contain a piece ID plus square name (like Ng1 or Ke8), which will place the mentioned piece on the mentioned square. A line '#' will clear the board, a line 'c' will switch to placing pieces of the other color (which at the start of the edit command will be set to place white pieces).
> 
> There is no way to specify castling or e.p. rights; pieces placed on the same square as they are on in the initial position should be assumed to be virgin, and e.p. capture should be assumed impossible. (It is up to the GUI to devise work-arounds for positions where this is not desired.) The 'edit' command is made obsolete by the setboard command, where the FEN specifies castling and e.p rights without the aid of any kludges.

http://hgm.nubati.net/CECP.html

The en-passant limitation can be worked around by setting up the previous position and then playing the pawn advance, but properly setting castling rights does not seem feasible.

I'd rather not implement something that works most of the time but sometimes doesn't in subtle ways.

**Comment by hasnul** [comment]
A bit late here but an understandable decision.
