### ISSUE TITLE
How to Get Ponder Move?

### ISSUE THREAD

**Issue by hi5games** [niklasf/python-chess#575]
I want to play against the engine with pondering on. I am currently doing this but I think this is not the right way to do it.
```
board = chess.Board()

while not board.is_game_over():
     if board.turn == chess.BLACK:
        # do moves manually as i am black
        board.push(chess.Move.from_uci("c7c5"))
    else:
        #get ponder move for white
        result = engine.play(board, chess.engine.Limit(time=0.5), ponder=True)
        board.push(result.move)
```

**Comment by niklasf** [comment]
If the engine wants to ponder, [`result.ponder`](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.PlayResult.ponder) will be set to a move. python-chess will automatically let it think in the background until you issue the next command to the engine.

**Comment by hi5games** [comment]
ok, so I call `result.ponder` for the next move? by doing that I get  something like this 

```
board = chess.Board()
result = engine.play(board, chess.engine.Limit(time=1), ponder=True)
time.sleep(5) # think for a while (extra)
board.push(result.ponder)
print(board.fen())
```

[Board](https://lichess.org/analysis/standard/rnbqkbnr/pppp1ppp/4P3/8/8/8/PPPPPPPP/RNBQKBNR%20b%20KQkq%20-%200%201)

Can you please give an example of a simple while loop that I can play with the engine using ponder? 
Thanks in advance :)

**Comment by niklasf** [comment]
Your original example was pretty much complete. You don't have to do anything special about pondering, besides setting `ponder=True`. `result.ponder` is only relevant if you want to know what the engine is doing.

```python
import chess.engine

with chess.engine.SimpleEngine.popen_uci("stockfish") as engine:
    board = chess.Board()

    while not board.is_game_over():
        if board.turn == chess.BLACK:
            print()
            print(board)
            board.push_san(input("Black move: "))  # Engine will think while waiting for next command
        else:
            result = engine.play(board, chess.engine.Limit(time=0.5), ponder=True)
            print("White move:", board.san(result.move))
            board.push(result.move)
```
