### ISSUE TITLE
is there any way to Avoid draws?

### ISSUE THREAD

**Issue by hi5games** [niklasf/python-chess#577]
I am using stockfish and most of the time the match result is a draw I did some research (few google search) and found that it has a setting called "component setting" and it avoids draws/repeated moves to some extent. I want the game to end by time and not by moves so if it can do some extra moves that are not the best moves at that position just to avoid repetitive moves that will be helpful. How can I use that setting in python-chess or is it even possible to achieve this in any other way?

**Comment by niklasf** [comment]
You can [configure](https://python-chess.readthedocs.io/en/latest/engine.html#options) the engine with *Contempt*.

```python
engine.configure({"Contempt": 100})
```

Another common method is to start games from random book positions, because engines will otherwise often play similar games from the starting position.

**Comment by hi5games** [comment]
Thanks 👍  💯
