### ISSUE TITLE
Conda Support

### ISSUE THREAD

**Issue by MarioJayakumar** [niklasf/python-chess#578]
Would it be possible to add conda support for python-chess? Conda is used by many data scientists, as opposed to pip, so having this library available on Conda would be beneficial. Additionally, other libraries that are depend on python-chess would need this on Conda in order for full conda support. Additionally, the conda distribution is fairly simple as the only two commands needed are 

conda skeleton pypi python-chess

and 

conda-build python-chess

**Comment by niklasf** [comment]
I am clueless about the Conda ecosystem. It looks like someone else has packaged this: https://anaconda.org/pettingzoo/python-chess. Does that help?

**Comment by MarioJayakumar** [comment]
That is actually a version I uploaded to my channel while testing the conda build process. However I am not sure if I built the package correctly, and since I am not the package maintainer I thought it would not be a good idea for me to distribute it. Would it be possible for you guys to distribute it on your own official channel?

**Comment by niklasf** [comment]
Sorry, I feel like anyone who actually uses Conda would be a better judge of the packaging quality than myself.

(Also does this imply that most packages published on pypi should also be packaged for Conda? Doesn't seem reasonable, especially for packages that are pure Python and therefore don't require any special build steps.)
