### ISSUE TITLE
Unsupported variant on parsing PGNs

### ISSUE THREAD

**Issue by lpenaf** [niklasf/python-chess#579]
On parsing a PGN with multiple games downloaded from lichess the parser rises a ValueError on games with the header [Variant "From Position"] which is one of lichess' game modes.

`raise ValueError(f"unsupported variant: {name}")
ValueError: unsupported variant: From Position`

**Comment by niklasf** [comment]
Thanks for reporting, will be fixed in the next release. Meanwhile you can use the following hack before parsing the PGN:

```python
import chess

chess.Board.aliases.append("From Position")
```
