### ISSUE TITLE
Gaviota - 3 request issue

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#58]
(1)
Following the docu of gaviota, i get this error when i try:
```
>>> with chess.gaviota.open_tablebases("data/gaviota") as tablebases:
...     tablebases.probe_dtm(chess.Board("8/8/8/8/8/8/8/K2kr3 w - - 0 1"))
...
-10
```

but i get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: __exit__
```

(2)
also below this fen is not valid (in docu & file):
"4k3/8/B7/8/8/8/4K3 w - 0 1"

(3)
libgtb:
Could you please provide an example with using the shared lib?
(=what to enter in python after "make install"). Thanks

**Comment by niklasf** [comment]
As always, thanks for reporting!

(1) I forgot with-statement support for the Pure Python fallback. Fixed: 83cf049c4e3b1f2a092b94c3046861cafa01dab4.

(2) Something got cut off that FEN. Fixed: b18ad43ac3f6170392745f05de9c70830433b2c2.

(3) Usage in Python is just the same. Pure Python fallbacks should automatically be used if the library is not installed in the system.

**Comment by LocutusOfPenguin** [comment]
(2)
still a "-" missing ;-)

(3)
Yes, i know..I want it to be forced to use or fail. Its for my learning, ha

**Comment by niklasf** [comment]
(2) :flushed:

(3) If you really want that, you can use the undocumented `open_tablebases_native`. It was mostly intended for testing, but I can see how it might be generally useful. That said: The pure Python probing is not so bad and only slightly slower.

**Comment by LocutusOfPenguin** [comment]
i mean, tell me how to call it. Im too stupid.
def open_tablebases_native(directory, libgtb=None, LibraryLoader=ctypes.cdll):
what to put for "libgtb", and esp(!) for "LL"?

**Comment by niklasf** [comment]
The defaults should be fine. Just ignore them ;)

**Comment by LocutusOfPenguin** [comment]
du verstehst mich irgendwie nicht...Bei mir ist es nicht DEFAULT, weinen

I want to call the lib without installing it first. Its somewhere in the software tree and has another name (to make it 100% clear and complex). Now, how to tell him to use this one?

Jürgen (der noch nie eine C-Funktion von Python aus aufgerufen hat ,ha)

**Comment by niklasf** [comment]
D.h. du hast nicht `make install` ausgeführt, sondern nur mit `make` die Bibliothek compiliert? In dem Fall müsstest du den Pfad zur Bibliothek in einer Umgebungsvariable hinterlegen.

export LD_LIBRARY_PATH="/path/to/the/directory/with/libgtb/:${LD_LIBRARY_PATH}"

Man kann leider nicht einfach in Python den absoluten Pfad zur Bibliothek oder so angeben.

**Comment by LocutusOfPenguin** [comment]
bei mir würde es so gehen:

'''
import chess.gaviota
import ctypes

l = '../Gaviota-Tablebases/libjp.so'
p = './data/gaviota'
c = ctypes.cdll.LoadLibrary(l)
print(c)

with chess.gaviota.NativeTablebases(p, c) as tablebases:
   x = tablebases.probe_dtm(chess.Board("8/8/8/8/8/8/8/K2kr3 w - - 0 1"))
print(x)


das ist ja auch nur ein TEST (zum Lernen)...keine Sorge, so würde ich diese lib nicht verwenden ;-)

**Comment by niklasf** [comment]
Passt vom Prinzip her. Mich wundert, dass es mit dem relativen Pfad in `l` klappt.

**Comment by niklasf** [comment]
Noch ein Nachtrag: Falls das mit dem `with` unpraktisch ist, geht natürlich auch immer

```
tablebases = chess.gaviota.open_tablebases_native(p, l)
# ...
tablebases.close()
```

**Comment by LocutusOfPenguin** [comment]
aha.

Nun, ich muss C-Funktionen aufrufen aus Python. Und den Python Teil kupfere ich von anderen ab (habe vorhin http://stackoverflow.com/questions/5081875/ctypes-beginner gefunden).

Hat nun garnix mit deiner Gaviota zu tun (außer das es hier schon funktioniert). Deshalb war ich auch froh, das ich 2 Fehler gefunden hatte, ha....Für Hilfe fragen ist nun nicht gerade python-chess-issues gedacht.

Thanks & Close

**Comment by niklasf** [comment]
(Bugfix in `v0.12.5` enthalten.)
