### ISSUE TITLE
How to use books

### ISSUE THREAD

**Issue by hi5games** [niklasf/python-chess#580]
How do I use books? While playing a game like this?

```
board = chess.Board()

while not board.is_game_over():
     if board.turn == chess.BLACK:
        # do moves manually as i am black
        board.push(chess.Move.from_uci("c7c5"))
    else:
        #get ponder move for white
        result = engine.play(board, chess.engine.Limit(time=0.5), ponder=True)
        board.push(result.move)
```

**Comment by niklasf** [comment]
Do you mean Polyglot opening books? https://python-chess.readthedocs.io/en/latest/polyglot.html has a basic example for how to open and query a book, and there are some other methods like [`weighted_choice()`](https://python-chess.readthedocs.io/en/latest/polyglot.html#chess.polyglot.MemoryMappedReader.weighted_choice) to pick a book entry for you.

**Comment by hi5games** [comment]
Yes, I did some test game stockfish vs stockfish same resources were given but one was running in python and other in the arena and most of the time arena engine wins. So I think it's because of books?

**Comment by niklasf** [comment]
You could test this by starting with positions where both engines would be out of book.
