### ISSUE TITLE
board.is_capture() / board.is_en_passant() suggestion

### ISSUE THREAD

**Issue by bautoff** [niklasf/python-chess#581]
Checking board.is_capture(move) and board.is_en_passant(move) causes a lot of issues, especially working with the move stack. Is it possible to make those methods a part of Move class, so that each move would have move.capture and move.ep attributes (also move.turn would be useful)?

**Comment by niklasf** [comment]
The design choice here was to make `Move` exactly equivalent to UCI notation (e.g. `chess.Move.from_uci("e2e4")` or `chess.Move.from_uci("e7e8q")`). So it's basically a tuple `(from_square, to_square, promotion)`. That means it's not possible to answer many questions without the context of a board.

If you need this frequently you could write a small helper class that takes a move and a board and saves all the relevant move information.
