### ISSUE TITLE
Are clocks and evals parsed and available?

### ISSUE THREAD

**Issue by fingoldo** [niklasf/python-chess#582]
Thank you for this amazing library!
Can't find it in the docs, are clocks and evals parsed and available?
When I import pgn from lichess,I can see them as 
`21. Bf3 { [%clk 0:01:29] } Ng6 { [%clk 0:02:11] }`

thanks :-)

**Comment by niklasf** [comment]
Hi, `node.comment` is exposed but currently not parsed further. #253 already proposes to do that.
