### ISSUE TITLE
chess.engine.EngineProtocol.play() Feature Request

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#585]
I have a feature request for `chess.engine.EngineProtocol.play()`. I'd like to have a `color` argument that determines which color the engine should play, setting either `chess.WHITE` or `chess.BLACK`.

@niklasf, is this something that can be done?

**Comment by niklasf** [comment]
The engine plays `board.turn`. What would be supposed to happen if the opposite color is given?

**Comment by PedanticHacker** [comment]
So for the `board` argument of the `play()` method I pass in `board.turn`? In my app I just pass `board` (`chess.Board()` instance). Will that solve my problem that Stockfish is making moves for both sides and my code needing to have a flag `if board.turn == engine_turn`?

**Comment by niklasf** [comment]
Please explain more clearly what you are trying to do. If the engine plays one side, who is playing the other side?

**Comment by PedanticHacker** [comment]
If the chess engine plays as Black and the human player plays as White, the engine gives unusual output if a move that the human player made is popped (a wheel event occurs in the QSvgWidget that pops the last move from the move stack). I noticed that the engine goes berserk and if it moves, for example, its black Knight, that piece changes its color to become a white Knight; then the whole app crashes because the engine received an illegal position or something in those lines. It's very strange.

I need 2 flags to restrain the engine not to move on its own. Before a PyQt5 signal is emitted that the engine can move now after a human pushes a move, I use an `if self.board.turn == chess.WHITE and not self.engine_paused` flag. The `self.engine_paused` is set to `True` right after the engine makes a move so that it is restrained and waits until the value of `self.engine_paused` is set to `False`, which it is right after a human pushes a move.

I am using Python 3.8.3, python-chess 0.31.2 and PyQt5 5.15.0 (so all the official latest versions of the software I'm using to code my chess app). Oh, and I am on Windows 10 Home Edition, the latest version of it, i.e. 2004, and all updates to today.

The Stockfish version I use is downloaded from https://abrok.eu/stockfish, a build for 64-bit Windows for modern computers compiled on Saturday, July 11, 2020, so that's of today (the time of writing this). The official Stockfish 11 version produces the same issue, so must be something in python-chess to cause this.

If you need any more info to nail this bug, please let me know.

**Comment by niklasf** [comment]
To clarify expectations:
* `SimpleEngine` is supposed to be thread-safe, so using it from a QThread should be fine.
* `engine.play(board)` is supposed to find a move in the given position, respecting piece positions, turn(!), en passant, castling rights and move counters.

If either of these does not work, that would be considered a bug.

Maybe try to isolate the issue as follows: Print the board before running `engine.play()`, and after that print the board and the return value. Then try to reproduce the issue and share the output here.

**Comment by PedanticHacker** [comment]
I solved my issue. My application just needs more flags, I guess. (What do you mean by a _return value_? Do you mean a move that the engine produces?)

**Comment by niklasf** [comment]
Yeah, that's what I meant.

**Comment by PedanticHacker** [comment]
Say I don't want the engine to start at all when my application is executed (if platform.system() does not return the value "Windows" or "Linux") -- how should I do that? There's no Stockfish build for macOS, so in that case, I don't want chess.engine.SimpleEngine.popen_uci() to do anything.

**Comment by niklasf** [comment]
Then either don't call it or handle the exception. (Alternatively, builds for OS X do exist, of Stockfish as well as many other engines.)

**Comment by PedanticHacker** [comment]
Hmmm, on https://abrok.eu/stockfish there are no Stockfish builds for macOS. Where can I find those?

**Comment by niklasf** [comment]
Presumably https://stockfishchess.org/mac/ includes engine binaries. Or see the multi-variant Stockfish builds for Lichess's fishnet: https://github.com/niklasf/Stockfish/releases/tag/fishnet-20200613

**Comment by PedanticHacker** [comment]
Thanks for this!
