### ISSUE TITLE
How to get to a certain board position?

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#587]
I have a need to get to a certain board position. Say there are 20 moves in the move stack and I want to get to move number 10. And if I print the board, the position should be displayed as on move 10. How can I achieve that?

**Comment by niklasf** [comment]
How about something like this?

```python
while len(board.move_stack) > N:
    board.pop()
```

**Comment by PedanticHacker** [comment]
I have a table of moves (a `QTableWidget`) in which all moves are displayed in 2 columns (one for White and the other for Black player). I'd like to jump to a board position whenever the user clicks on a certain cell on that table. How can I revert to a certain board position that existed before? And if then the user clicks on the last move, the board position jumps back to that board position? Is that possible to code?

**Comment by niklasf** [comment]
In that case, store the full game data in a separate data structure (list of moves, `chess.pgn.Game`, ...) and replay the moves or use `chess.pgn.GameNode.board()`.

**Comment by PedanticHacker** [comment]
What about `chess.pgn.Game.from_board()`?

**Comment by PedanticHacker** [comment]
I tried `chess.pgn.GameNode.board()` but got an error: apparently, it is missing a `self`. Then I tried `chess.pgn.GameNode().board()` and got `AssertionError: cannot get board of dangling GameNode`. What gives?

**Comment by PedanticHacker** [comment]
What do you mean by

> replay the moves

Please elaborate on this.
