### ISSUE TITLE
The move stack is wiped if you set a FEN string to chess.Board()

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#589]
This is a possible bug I discovered while coding my app. If I have moves in the move stack and then do `board.set_fen(my_fen_string)`, the move stack is wiped (the return value of `print(board.move_stack)` is `[]`). I also checked `print(board._stack)` and it is also wiped (the return value is also `[]`).

Is this by design or have I stumbled upon a bug in python-chess?

**Comment by niklasf** [comment]
This is intentional.

https://github.com/niklasf/python-chess/blob/50d2e2fd8c03ceb113b02c0de01d475ab11844d1/chess/__init__.py#L2311

The moves might no longer make sense from a different starting position.

**Comment by PedanticHacker** [comment]
Ah, okay. Thanks for clearing this up. 🙂👍
