### ISSUE TITLE
Feature Request: Setting Castling Rights

### ISSUE THREAD

**Issue by asdfjkl** [niklasf/python-chess#59]
It would be nice to have the following high-level functions:

def set_kingside_castling_rights(color, bool_val)
def set_queenside_castling_rights(color, bool_val)

Also 
clean_castling_rights()
is not really clear to me. Does it reset the castling rights of the current board? If not, how do I have to reset? Like this: board.castling_rights = board.clean_castling_rights() ?!

Background: I have a "Enter Position" functionality in my chess GUI. So far I just copied & pasted the low-level bitmask manipulation from the python-chess lib-source code, but it seems to have changed from 0.8 to 12.5, and I am really lost in how they are encoded. Hence, having these high-level calls would be highly appreciated...
##

**Comment by niklasf** [comment]
I'll come up with something. In the meantime, in standard chess the full castling rights are:

````
board.castling_rights = chess.BB_A1 | chess.BB_H1 | chess.BB_A8 | chess.BB_H8
````

That is: The rook squares.

**Comment by niklasf** [comment]
After one year I finally settled on this: https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.set_castling_fen
