### ISSUE TITLE
pgn class. Can't parse the clock times with the moves.

### ISSUE THREAD

**Issue by ash-stew** [niklasf/python-chess#591]
Hi, Thank you for the excellent work,   I am having problems trying to parse clock times ( as clk:) in the game notation at the moment, I need to do this.    It is not letting me do chess.pgn.GameNode(clock()).  ( or chess.pgn.Game(clock)   ) What do I need to solve it so that I can get all the clock times after every move?   Thank you.

**Comment by niklasf** [comment]
Usage looks like `node.clock()`:

```python
import chess
import chess.pgn

with open("data/pgn/knightvuillaume-jannlee-zh-lichess.pgn") as pgn:
    game = chess.pgn.read_game(pgn)

    for node in game.mainline():
        print(node.move, node.clock())
```

**Comment by ash-stew** [comment]
Thank you for your response. I have tried the code AttributeError: 'GameNode' object has no attribute 'clock'. I believe I'm currently on (0.31.2), perhaps I need to upgrade it  to 0.31.3?

**Comment by niklasf** [comment]
Yes. Parsing PGN annotations is a new feature of v0.31.3: https://github.com/niklasf/python-chess/blob/master/CHANGELOG.rst#new-in-v0313

**Comment by ash-stew** [comment]
I am still struggling with  comments for the game pgn. I can get the pgn of the game printed, but can't include the comments/ clock times with it.  I have following structure  and the for nodes in node will print None
I need both the headers and the comments, so would that mean needing to use .Game and .GameNode?  
 here is just some of the code as example...

a while not board_is_game_over:

# Once the game is over
game_pgn = chess.pgn.Game.from_board(board)    
node = pgn.GameNode.mainline(game_pgn)
game_moves = pgn.GameNode()
clocks = pgn.GameNode()

for nodes in node:
print(game_moves.move, clocks.clock())  # This will print None for both.

How should it be in order to create those comments?

**Comment by ash-stew** [comment]
I have something like this. I can get the clock times, but I am stuck on how to include them as comments in the game annotation ( after the game moves in the pgn) as %clk.  What am I missing?    Please help.

 
    import chess
    import chess.engine
    import chess.pgn
    import datetime

    stockfish = chess.engine.SimpleEngine.popen_uci(stockfish)
    engine_opponent = chess.engine.SimpleEngine.popen_uci(engine_opponent)   
 
    for engine, options in zip([stockfish, engine_opponent], [stockfish_options, engine_opponent_options]):
          available = stockfish.options 
          options = {
            k: v
            for k, v in options.items() 
            if k in available and not available[k].is_managed()  
                           }
          engine.configure(options) 

    result = None   
    board = chess.Board(fen)

    whtime = pgn.GameNode()
    bltime = pgn.GameNode()

    time_control._start_new_game(whose_move=board.turn) 
                                                      
    engine_to_move = stockfish if board.turn == chess.WHITE else engine_opponent 


    while not board.is_game_over(): 

        engine_choice = engine_to_move.play(board, chess.engine.Limit(white_clock=time_control.wtime, 
        black_clock=time_control.btime, white_inc=time_control.increment, black_inc=time_control.increment),)
     
        engine_flagged = time_control._signal_move_made()

        if engine_flagged:
            if board.has_insufficient_material(not board.turn): 
                result = "1/2-1/2"      
            else: 
                result = "0-1" if board.turn == chess.WHITE else "1-0"  
            break                                                   

        board.push(engine_choice.move) 
       
        whtime.set_clock = time_control.wtime
        bltime.set_clock = time_control.btime

        #whtime.add_variation(engine_choice)
        #bltime.add_variation(engine_choice)

        whtime.comment = whtime.set_clock
        bltime.comment = bltime.set_clock

        white_time_comment = whtime.add_variation(engine_choice)
        white_time_comment = white_time_comment.add_variation(engine_choice)
        black_time_comment = bltime.add_variation(engine_choice)
        black_time_comment = black_time_comment.add_variation(engine_choice)


        print(whtime.comment , bltime.comment )
        
        engine_to_move = stockfish if board.turn == chess.WHITE else engine_opponent
         
        # End of the while loop, the following runs after the game has been completed...


        game_pgn = chess.pgn.Game.from_board(board)    
        node = pgn.GameNode.mainline_moves(game_pgn) 



        for nodes in node:
             print(white_time_comment.comment)

**Comment by niklasf** [comment]
Are you looking for `node.set_clock(seconds)`?

**Comment by ash-stew** [comment]
Probably. Though it's been giving me ValueErrors ( unknown format code)  when I try and use set_clock.  Iv'e tried both node.set_clock(seconds=1000)  and node.set_clock(1000)  (as float values).

e.g. something like  this will give me value error

 white_time = float(time_control.wtime)  # ( to cast as a float)
 whtime.set_clock(white_time)

**Comment by niklasf** [comment]
Oh, that's a bug! For now use `node.set_clock(int(wtime))` to work around.

**Comment by ash-stew** [comment]
Yes, that is a part solution.

I still have game_pgn = chess.pgn.Game.from_board(board).
  I'm wondering if it is still possible to iterate over game_pgn  and add the clock times after each move, or do I need to convert game_pgn to  something else, if so how?

**Comment by niklasf** [comment]
The best would probably be structuring it like this:

```python
import chess.pgn
import random

board = chess.Board()

game = chess.pgn.Game()
game.setup(board)
node = game  # Game is also the first node

while not board.is_game_over():
    move = random.choice(list(board.legal_moves))  # Or get from engine

    board.push(move)

    node = node.add_variation(move)
    node.set_clock(random.randint(0, 100))  # Or use the real time

print(game)
```

**Comment by ash-stew** [comment]
Niklas, you are brilliant!  I followed a similar structure and it gave me the result- I can now print the game as a pgn format including clock times {%clk    } after each move so I am really happy!     Thank you very much for your excellent work!  Keep it up!
