### ISSUE TITLE
chess.Board.set_fen() and chess.Board.set_board_fen()

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#594]
I can't get my answer from python-chess docs on the difference between `chess.Board.set_fen()` and `chess.Board.set_board_fen()`. When should one use one or the other?

**Comment by niklasf** [comment]
The distinction is between the board part of a FEN

```
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR
```

and full FEN

```
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
```
