### ISSUE TITLE
How does chess.Board().mirror() work?

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#599]
I am having trouble understanding how exactly does `chess.Board().mirror()` work. I applied it into my code and it doesn't work. Nothing happens, not even an error is thrown. The pieces should flip, but they don't. What gives?

**Comment by niklasf** [comment]
The starting position is symmetrical and `board.mirror()` also swaps the colors, as documented. So the resulting position is the same (except side to move).

Maybe you want `board.transform(chess.flip_vertical)`?

Also note that these methods return a new board, instead of modying the existing one.

**Comment by PedanticHacker** [comment]
How should I flip the existing board then? I have a tool bar button `Flip board` that should flip the board whenever it is clicked. So which method in python-chess should I use to do just that?

**Comment by niklasf** [comment]
There is also `board.apply_transform(chess.flip_vertical)`. Depending on context, this may or may not be the expected operation for "Flip board" in a GUI.

**Comment by PedanticHacker** [comment]
I tried everything and it does not produce the desired result. Any other ideas?

**Comment by niklasf** [comment]
What exactly did you try, what happened, and what exactly is the desired result?

**Comment by PedanticHacker** [comment]
Well, on clicking the `Flip board` button, function `flip_board()` is called. The function calls `board.mirror()`, which doesn't do anything. Then I tried calling `board.apply_transform(chess.flip_vertical)` instead. This code, however, swaps the pieces, but the functionality is not okay. Only certain moves can then be played by the side that was on the move when the flip occured, which is very strange.

**Comment by niklasf** [comment]
Sounds correct. The result will be https://lichess.org/analysis/standard/RNBQKBNR/PPPPPPPP/8/8/8/8/pppppppp/rnbqkbnr_w_-_-_0_1. White pawns are moving up, so the only legal moves are knight moves.

Perhaps you want to rotate the board display, instead of the position? That would be a job for the GUI itself. There's also `chess.svg.board(..., flipped=True)`.

**Comment by PedanticHacker** [comment]
Yes, I am using `chess.svg.board()` to display the SVG chessboard in my program. Actually, my `refresh_board()` method calls it every time a new move occurs.

How can I change just the value of the `flipped` argument in my `flip_board()` method? Calling just `chess.svg.board(flipped=True)` does not do the trick.

**Comment by PedanticHacker** [comment]
Good news! I've managed to make this work, finally. Thanks for the help.

**Comment by Aphexus** [comment]
> Good news! I've managed to make this work, finally. Thanks for the help.

And how did you do that?
