### ISSUE TITLE
A fundamental bug in python-chess

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#608]
I was debugging my program using Python's in-house debugger PDB and noticed something peculiar in python-chess.

```
(Pdb) chess.COLORS[True]
False
```

**_What?!_**

Then I noticed that the issue is here:
`COLORS = [WHITE, BLACK] = [True, False]`

This should have been
`COLORS = [BLACK, WHITE] = [False, True]`
because index `0` of a Python list evaluates to `False` and index `1` of a Python list evaluates to `True`.

**Comment by niklasf** [comment]
How is that a bug?

**Comment by PedanticHacker** [comment]
I expect the expression `chess.COLORS[True]` to return `True`. I don't understand why it doesn't.

**Comment by niklasf** [comment]
Can you explain why you believe it should return `True`.

**Comment by PedanticHacker** [comment]
Well, I guess I am expecting it to return `True`. I have figured out why it does quite the opposite.
```
>>> chess.COLORS
[True, False]
>>> chess.COLORS[True]
False
>>> chess.COLORS[False]
True
```
This is my verdict. Since `False` is basically `0` and `True` is basically `1`, the `chess.COLORS` list is `[True, False]`, meaning `index 0` of this list holds the value `True` and `index 1` holds the value `False`.

But why would you code it like this? The list order should be `[False, True]`, just like you would have `[0, 1]`. What's the purpose?

**Comment by niklasf** [comment]
That's an explanation for the current behavior, but for the potentially improved behavior you just say "the order *should be* ...".

I don't see a reason for that, or in fact a reason why `chess.COLORS[True]` should even be a sensible expression in the first place. In better languages that would be a type error. Unfortunately in Python `False` and `True` are interpreted as `0` and `1` in this context, as you say.

So which colors to assign to indexes`0` and `1`? I find it quite natural that White is the first color in a chess library, just like it is the first to move.

Which boolean value to assign to the constant `WHITE`? That is more arbitrary, and ideally it wouldn't be a boolean value at all, in a better language. But I like that the current assignment makes sense for `if board.turn: ...` from the usual perspective of looking at a board.

**Comment by PedanticHacker** [comment]
Ah, I understand. Thanks for the explanation! 👍
