### ISSUE TITLE
A GUI Implementation in Ren'Py & Pygame | Please add to use cases

### ISSUE THREAD

**Issue by RuolinZheng08** [niklasf/python-chess#612]
Hi there. I built a GUI with the [Ren'Py](http://renpy.org/) Visual Novel Engine and Pygame.
My repo is at https://github.com/RuolinZheng08/renpy-chess. If this is a relevant use case, could someone please add this to the README use case section? Thanks!

The line for the README:
- a GUI implementation in the [Ren'Py](http://renpy.org/) Visual Novel Engine - https://github.com/RuolinZheng08/renpy-chess

**Comment by niklasf** [comment]
Thanks for sharing. It seems to be currently built with a very old version of this library, so I don't think it's a good example for now.
