### ISSUE TITLE
How to get "Value" of board as it shows in Arena

### ISSUE THREAD

**Issue by justmaulik** [niklasf/python-chess#613]
I am trying to get this value of the board every x sec or after a move 
https://prnt.sc/u4rv7f

I tried this but I don't know how to convert it to the value that looks like an arena value.
```
board = chess.Board("r1bqkbnr/p1pp1ppp/1pn5/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR b KQkq - 2 4")

def Analysis():
    while True:
        with engine.analysis(chess.Board()) as analysis:
            for info in analysis:
                print(info.get("score"))
                time.sleep(2)

```

Output:

```
None
+14
+30
+33
+84
+24
+24
```

**Comment by niklasf** [comment]
The values you are seeing are instances of [`chess.engine.PovScore`](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.PovScore). Presumably Arena displays them 

1. from White's point of view (`pov_score.white()`),
2. identically to this library for mate scores,
3. and divided by 100 for centipawn scores.

```python
if pov_score is None:
    pass
elif pov_score.is_mate():
    print(str(pov_score.white()))  # 2
else:
    print(pov_score.white().score() / 100)  # 3
```

Note that using `time.sleep()` as you do is a bad idea. There is no backpressure, and so you do not see the engine's current evaluation at each iteration, but an old evaluation that has been buffered. Instead, ignore some iterations, or just deal with the stream of incoming evaluations. It is fast at low depths and should slow down eventually.

**Comment by hi5games** [comment]
I tried this but it's giving error.
```
pov_score = chess.engine.PovScore(chess.engine.Score, True)
if pov_score is None:
    pass
elif pov_score.is_mate():
    print(str(pov_score.white()))  # 2
else:
    print(pov_score.white().score() / 100)  # 3
```
Error
```
TypeError: is_mate() missing 1 required positional argument: 'self'
```

**Comment by niklasf** [comment]
The first argument to `PovScore` is supposed to be an *instance* of `Score`. Like:

```python
pov_score = chess.engine.PovScore(chess.engine.Cp(-31), chess.WHITE)
```

But anyway you're probably not going to construct scores yourself:

```python
pov_score = info.get("score")
```
