### ISSUE TITLE
Variations not added from PGN file with variations

### ISSUE THREAD

**Issue by purplefishies** [niklasf/python-chess#615]
Not sure if I'm using this incorrectly, but as I load a PGN file with many variations in it the chess.pgn.Game only contains one variation for the entire game.  

For example 
PGN game.pgn
```
[Event ""]
[Site "https://lichess.org/kc85XG7h"]
[Date "2020.08.22"]
[Round ""]
[White "Anonymous"]
[Black "Anonymous"]
[Result "0-1"]

1.e4 g6 2.d4 Bg7 3.f4 d6 4.Nf3 Nf6 5.Bd3 O-O 6.O-O Re8 7.e5 dxe5 8.fxe5 
Nfd7 9.c4 
    ( 9.Ng5 h6 
        ( 9...Nc6 )
        ( 9...Nb6 10.Nxf7 Qxd4+ 11.Kh1 )
    10.Nxf7 )
9...Nb6 10.Bf4 
    ( 10.Nc3 Nc6 11.Be2 Bg4 12.Be3 Qd7 13.Qd2 Rad8 14.Rad1 f6 15.Ne4 a6 
    16.Nc5 Qc8 17.e6 Bxe6 
        ( 17...Na8 18.d5 Nb8 19.Nh4 Bxe2 20.Qxe2 Rf8 21.Qg4 f5 22.Qg3 c6 
        23.Nxf5 Rxf5 24.Rxf5 Nc7 25.Rf7 Nxe6 26.Rxe7 Nxc5 )
    18.Nxe6 Qxe6 )
    ( 10.c5 Nd5 11.Nc3 Nxc3 12.bxc3 Nc6 13.Ng5 Rf8 14.Bc4 e6 15.Qg4 b6 16.
    Qh3 h6 17.Ne4 h5 18.g4 hxg4 19.Qxg4 Nxd4 20.Bg5 f6 21.Nxf6+ Rxf6 22.
    exf6 Bxf6 )
10...Bg4 11.Qd2 Bxf3 12.Rxf3 Nc6 13.Be3 
    ( 13.e6 Nxd4 
        ( 13...Qxd4+ 14.Be3 Qxb2 15.exf7+ Kh8 16.Bxg6 Qxd2 17.Nxd2 Rf8 18.
        Rh3 h6 19.Re1 Ne5 20.Bxh6 Bxh6 21.Rxe5 Kg7 22.Re6 Rad8 23.Ne4 )
    14.exf7+ Kxf7 15.Rf1 )
13...Nxd4 14.Bxd4 Qxd4+ 15.Kh1 Nxc4 16.Qe2 
    ( 16.Bxc4 Qxc4 17.Na3 Qc6 18.Rd3 Bxe5 19.Rc1 Qf6 20.Re1 c5 21.Nb5 a6 
    22.Nc3 Bxc3 23.bxc3 )
16...Nxe5 17.Be4 Nxf3 18.Qxf3 Qxb2 0-1
```

```{python}
pgn = open("game.pgn")
first_game = chess.pgn.read_game(pgn)
first_game.variations
[<GameNode at 0x7fd7f2b85320 (1. e4 ...)>]
```
1. I was expecting to see greater than 1. 
1. I would have to re-parse the game to iterate through and then add the variations manually ( using push_san() + add_variation )  which seems counter-intuitive since the game has already been parsed.

Is this a mistake on my part or an enhancement feature that might make it in later and if you'd accept a pull request is there a spec / idea you would like to see this adhere to ?

**Comment by niklasf** [comment]
`first_game.variations` are the variations for the first move.

Before I try to explain in detail, does the following make sense to you?

```python
node = first_game
while len(node.variations) == 1:
    node = node.variations[0]
# Now node is the first real branch in the game tree
print(node.variations)
```

**Comment by purplefishies** [comment]
Ok, gotcha. 

I wasn't aware that's how to traverse the game... I followed your example and at move 9 saw
```
In [152]: node.variations
Out[152]: [<GameNode at 0x7fd7f2b8c080 (8... Nfd7 ...)>]

In [153]: node = node.variations[0]

In [154]: node.variations
Out[154]: 
[<GameNode at 0x7fd7f2b8c160 (9. c4 ...)>,
 <GameNode at 0x7fd7f2b8c5f8 (9. Ng5 ...)>]
```

Is there a way I could help improve the documentation for this ? 

Thanks for this.

**Comment by niklasf** [comment]
Sure. If you can find a good way to clarify this, please send a pull request. The relevant file is `docs/pgn.rst`, with docstrings coming from `chess/pgn.py`.
