### ISSUE TITLE
Cannot restore to the last state of the board

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#616]
So I am manually restoring a board state by `board._stack[some_index].restore(board)`. Note that the `some_index` variable is a zero-based index. I have noticed that the board state is always one step behind what the `board.move_stack` is at. Why is that so?

**Comment by niklasf** [comment]
Because `_stack` is an internal structure used to implement `push()` and `pop()`, and (by definition) no move has been pushed onto the final position. `_stack` always has exactly as many elements as `move_stack`.

Also note that using internals like this is a forwards compability hazard.

**Comment by PedanticHacker** [comment]
So should I do `board.move_stack[some_index].restore(board)`. Is that what you are saying?

**Comment by PedanticHacker** [comment]
I have tried everything and nothing works! I am getting frustrated here. Please help me out. I am banging my head against the wall for more than one week now.

@niklasf, please explain what you ment by `a list of moves` and how to achieve this. Please be elaborate. Thanks.

**Comment by PedanticHacker** [comment]
I found this code which is just what I need, but it is not implemented.

    def visit_move(self, board: chess.Board, move: chess.Move) -> None:
        """
        Called for each move.

        *board* is the board state before the move. The board state must be
        restored before the traversal continues.
        """
        pass
