### ISSUE TITLE
Question: How else to change the state of the board?

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#618]
I know 2 ways of changing the state of the board: one is `push()` and the other is `set_fen()`. How else is one able to change the state of the board?

**Comment by niklasf** [comment]
There are many ways. What are you trying to achieve?

**Comment by niklasf** [comment]
Here is how to do the operations with python-chess datastructures:

```python
import chess.pgn

# How to append moves to a game
game = chess.pgn.Game()
node = game
node = node.add_variation(chess.Move.from_uci("e2e4"))
node = node.add_variation(chess.Move.from_uci("e7e5"))
node = node.add_variation(chess.Move.from_uci("g1f3"))
node = node.add_variation(chess.Move.from_uci("b8c6"))

# How to get the board of the nth node
n = 3
node = game
for _ in range(n):
    node = node.variations[0]
print(node.board())
```

You can also easily use your own list of moves.

**Comment by PedanticHacker** [comment]
What about using the `from_board()` class attribute instead? So like `chess.pgn.Game.from_board(board)`?

**Comment by PedanticHacker** [comment]
Why are doing this `node = game` thing? Is this really necessary?
