### ISSUE TITLE
Let #888 hex color code in chess.svg.Arrow() serve as a fallback

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#619]
![image](https://user-images.githubusercontent.com/14254085/91653507-e4f33600-eaa1-11ea-99a1-f993913aa3f6.png)

In the above picture, you can see a strange move arrow (actually just the head of the arrow) by passing the value `""` to the `color` argument of `chess.svg.Arrow()`.

As I noticed, every value that is out of hex color code space (or an erroneous name for a color, like `blues` instead of `blue`), produces this strange result. We should fall back to `#888` whenever that happens.

**Comment by niklasf** [comment]
That's already the default parameter. How about just passing `color or "#888"`?

**Comment by PedanticHacker** [comment]
Yes, passing `color` (like `blue`, `red`, ...) or `#888` is okay – but why do I get such a strange result if I don't?

**Comment by niklasf** [comment]
Garbage in, garbage out. I would add validation, but since this library is not rendering the SVG itself it's not in a good position to do that.
