### ISSUE TITLE
Feature Request: Support different locales like K,D,T instead of K,Q,R

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#62]
I would be fine if i can choose the locale for displaying the moves or the board display.

Esp the first i need for the picochess cause i want to implement (clock) messages in different languages. English should be standard (need german, french, english, spanish and dutch).
see: https://en.wikipedia.org/wiki/Algebraic_notation_(chess)

**Comment by niklasf** [comment]
Hi. Are you using some localization framework like gettext?

**Comment by LocutusOfPenguin** [comment]
no, not yet.

But in general it would be strange to have the moves displayed in english and the rest of program is f.e. german including the voices. For sure, i can transform the lib string to what i want myself, but thats not the right way ;-)

**Comment by niklasf** [comment]
Just going through the issue list.

Since localization depends a lot on the framework used, I'll leave this up to the application and won't do this in this library.
