### ISSUE TITLE
Why not allow string square as a parameter to piece_type_at / color_at / piece_at?

### ISSUE THREAD

**Issue by tanmay2004** [niklasf/python-chess#624]
While looking for a function which could tell me which piece was at a particular square, I found this: [piece_type_at](https://python-chess.readthedocs.io/en/latest/core.html#chess.BaseBoard.piece_type_at). I saw that it takes in an integer as input, which was very confusing because I didn't know what integer represented which square. After digging for a bit, I discovered it took integers from 0 to 63 representing each square from "a1" to "h8".

Then, I found the `chess.SQUARE_NAMES` constant. I used this to solve my problem, by first getting the index of my string square from it and then passing it as the parameter to `piece_type_at`. My question is: why not allow as input the square name, as a string? We could keep both options available by adding a parameter to the function. If the string is passed, we could easily get it's integer value. As I said, this can be easily accomplished outside of the module too, the user could get the index of the square and then pass it to `piece_type_at`, like I did. But, why not save him/her the trouble of having to figure it out?

I would be happy to make the changes and create a pull request :)

**Comment by niklasf** [comment]
Allowing both for every function that works with square indexes will be quite messy and a considerable slowdown. Let's improve the documentation instead. Perhaps adding a function like `chess.parse_square(name: str) -> Square` would be simplest?

**Comment by tanmay2004** [comment]
Oh, yeah that's true. `parse_square` seems like a good idea! Also, because a method to get the square as a string from it's integer value exists ([square_name](https://python-chess.readthedocs.io/en/latest/core.html#chess.square_name)), having the opposite available as well does make sense.
