### ISSUE TITLE
websockets/eventlet not working together with chess engine on Heroku

### ISSUE THREAD

**Issue by StevenDalderop** [niklasf/python-chess#628]
Hi, 

When running Stockfish engine on Heroku, I get this error. Locally everything works fine. Thanks! 

```
import chess
import chess.engine
from flask import Flask
import os
import stat
import sys

app = Flask(__name__)

@app.route('/')
def index():
    board = chess.Board()
    if sys.platform == "linux":
        os.chmod("./stockfish_20011801_x64", stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        engine = chess.engine.SimpleEngine.popen_uci("./stockfish_20011801_x64")
    else:
        engine = chess.engine.SimpleEngine.popen_uci("./stockfish_20011801_x64.exe")
    result = engine.play(board, chess.engine.Limit(time=3))
    board.push(result.move)
    return board.fen()
```

>  [2020-09-08 08:58:53,494] ERROR in app: Exception on / [GET]
> 2020-09-08T08:58:53.494843+00:00 app[web.1]: Traceback (most recent call last):
> 2020-09-08T08:58:53.494845+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
> 2020-09-08T08:58:53.494846+00:00 app[web.1]: response = self.full_dispatch_request()
> 2020-09-08T08:58:53.494847+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
> 2020-09-08T08:58:53.494848+00:00 app[web.1]: rv = self.handle_user_exception(e)
> 2020-09-08T08:58:53.494848+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
> 2020-09-08T08:58:53.494849+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
> 2020-09-08T08:58:53.494849+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
> 2020-09-08T08:58:53.494850+00:00 app[web.1]: raise value
> 2020-09-08T08:58:53.494850+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
> 2020-09-08T08:58:53.494851+00:00 app[web.1]: rv = self.dispatch_request()
> 2020-09-08T08:58:53.494851+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
> 2020-09-08T08:58:53.494852+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
> 2020-09-08T08:58:53.494852+00:00 app[web.1]: File "/app/app.py", line 14, in index
> 2020-09-08T08:58:53.494853+00:00 app[web.1]: result = engine.play(board, chess.engine.Limit(time=0.1))
> 2020-09-08T08:58:53.494853+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/chess/engine.py", line 2386, in play
> 2020-09-08T08:58:53.494854+00:00 app[web.1]: return future.result()
> 2020-09-08T08:58:53.494855+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/concurrent/futures/_base.py", line 439, in result
> 2020-09-08T08:58:53.494855+00:00 app[web.1]: return self.__get_result()
> 2020-09-08T08:58:53.494856+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
> 2020-09-08T08:58:53.494856+00:00 app[web.1]: raise self._exception
> 2020-09-08T08:58:53.494856+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
> 2020-09-08T08:58:53.494857+00:00 app[web.1]: return fut.result()
> 2020-09-08T08:58:53.494857+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/chess/engine.py", line 1316, in play
> 2020-09-08T08:58:53.494857+00:00 app[web.1]: return await self.communicate(UciPlayCommand)
> 2020-09-08T08:58:53.494857+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/chess/engine.py", line 768, in communicate
> 2020-09-08T08:58:53.494858+00:00 app[web.1]: return await command.result
> 2020-09-08T08:58:53.494858+00:00 app[web.1]: chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 0)
> 2020-09-08T08:58:53.496052+00:00 app[web.1]: 10.35.251.250 - - [08/Sep/2020:08:58:53 +0000] "GET / HTTP/1.1" 500 290 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"

**Comment by niklasf** [comment]
Please also provide the debug log, which might contain a hint: https://python-chess.readthedocs.io/en/latest/engine.html#logging

**Comment by StevenDalderop** [comment]
> 2020-09-08T12:52:37.663170+00:00 heroku[web.1]: Starting process with command `gunicorn app:app --log-file=- --worker-class eventlet -w 1`
> 2020-09-08T12:52:40.469372+00:00 app[web.1]: [2020-09-08 12:52:40 +0000] [4] [INFO] Starting gunicorn 20.0.4
> 2020-09-08T12:52:40.469907+00:00 app[web.1]: [2020-09-08 12:52:40 +0000] [4] [INFO] Listening at: http://0.0.0.0:38819 (4)
> 2020-09-08T12:52:40.469985+00:00 app[web.1]: [2020-09-08 12:52:40 +0000] [4] [INFO] Using worker: eventlet
> 2020-09-08T12:52:40.474061+00:00 app[web.1]: [2020-09-08 12:52:40 +0000] [9] [INFO] Booting worker with pid: 9
> 2020-09-08T12:52:40.918319+00:00 heroku[web.1]: State changed from starting to up
> 2020-09-08T12:52:41.000000+00:00 app[api]: Build succeeded
> 2020-09-08T12:52:42.653436+00:00 app[web.1]: DEBUG:asyncio:Using selector: SelectSelector
> 2020-09-08T12:52:42.659555+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: Connection made
> 2020-09-08T12:52:42.660107+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> Stockfish 11 64 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
> 2020-09-08T12:52:42.660494+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: << uci
> 2020-09-08T12:52:42.841515+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> id name Stockfish 11 64
> 2020-09-08T12:52:42.841635+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> id author T. Romstad, M. Costalba, J. Kiiski, G. Linscott
> 2020-09-08T12:52:42.841746+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >>
> 2020-09-08T12:52:42.841869+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name Debug Log File type string default
> 2020-09-08T12:52:42.842093+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name Contempt type spin default 24 min -100 max 100
> 2020-09-08T12:52:42.842218+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name Analysis Contempt type combo default Both var Off var White var Black var Both
> 2020-09-08T12:52:42.842341+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name Threads type spin default 1 min 1 max 512
> 2020-09-08T12:52:42.842508+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name Hash type spin default 16 min 1 max 131072
> 2020-09-08T12:52:42.842629+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name Clear Hash type button
> 2020-09-08T12:52:42.842842+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name Ponder type check default false
> 2020-09-08T12:52:42.843056+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name MultiPV type spin default 1 min 1 max 500
> 2020-09-08T12:52:42.843181+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name Skill Level type spin default 20 min 0 max 20
> 2020-09-08T12:52:42.843392+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name Move Overhead type spin default 30 min 0 max 5000
> 2020-09-08T12:52:42.843600+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name Minimum Thinking Time type spin default 20 min 0 max 5000
> 2020-09-08T12:52:42.843813+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name Slow Mover type spin default 84 min 10 max 1000
> 2020-09-08T12:52:42.844072+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name nodestime type spin default 0 min 0 max 10000
> 2020-09-08T12:52:42.844287+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name UCI_Chess960 type check default false
> 2020-09-08T12:52:42.844481+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name UCI_AnalyseMode type check default false
> 2020-09-08T12:52:42.844705+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name UCI_LimitStrength type check default false
> 2020-09-08T12:52:42.844846+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name UCI_Elo type spin default 1350 min 1350 max 2850
> 2020-09-08T12:52:42.845008+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name SyzygyPath type string default <empty>
> 2020-09-08T12:52:42.845215+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name SyzygyProbeDepth type spin default 1 min 1 max 100
> 2020-09-08T12:52:42.845406+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name Syzygy50MoveRule type check default true
> 2020-09-08T12:52:42.845539+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> option name SyzygyProbeLimit type spin default 7 min 0 max 7
> 2020-09-08T12:52:42.845742+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: >> uciok
> 2020-09-08T12:52:42.848355+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: << ucinewgame
> 2020-09-08T12:52:42.848457+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: << isready
> 2020-09-08T12:52:42.916904+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: Process exited
> 2020-09-08T12:52:42.917111+00:00 app[web.1]: DEBUG:chess.engine:<UciProtocol (pid=10)>: Connection lost (exit code: 0, error: None)
> 2020-09-08T12:52:42.922234+00:00 app[web.1]: ERROR:app:Exception on / [GET]
> 2020-09-08T12:52:42.922235+00:00 app[web.1]: Traceback (most recent call last):
> 2020-09-08T12:52:42.922235+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
> 2020-09-08T12:52:42.922236+00:00 app[web.1]: response = self.full_dispatch_request()
> 2020-09-08T12:52:42.922236+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
> 2020-09-08T12:52:42.922237+00:00 app[web.1]: rv = self.handle_user_exception(e)
> 2020-09-08T12:52:42.922237+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
> 2020-09-08T12:52:42.922237+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
> 2020-09-08T12:52:42.922238+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
> 2020-09-08T12:52:42.922238+00:00 app[web.1]: raise value
> 2020-09-08T12:52:42.922238+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
> 2020-09-08T12:52:42.922239+00:00 app[web.1]: rv = self.dispatch_request()
> 2020-09-08T12:52:42.922239+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
> 2020-09-08T12:52:42.922239+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
> 2020-09-08T12:52:42.922240+00:00 app[web.1]: File "/app/app.py", line 21, in index
> 2020-09-08T12:52:42.922240+00:00 app[web.1]: result = engine.play(board, chess.engine.Limit(time=3))
> 2020-09-08T12:52:42.922240+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/chess/engine.py", line 2386, in play
> 2020-09-08T12:52:42.922240+00:00 app[web.1]: return future.result()
> 2020-09-08T12:52:42.922241+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/concurrent/futures/_base.py", line 439, in result
> 2020-09-08T12:52:42.922241+00:00 app[web.1]: return self.__get_result()
> 2020-09-08T12:52:42.922241+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
> 2020-09-08T12:52:42.922241+00:00 app[web.1]: raise self._exception
> 2020-09-08T12:52:42.922242+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
> 2020-09-08T12:52:42.922242+00:00 app[web.1]: return fut.result()
> 2020-09-08T12:52:42.922242+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/chess/engine.py", line 1316, in play
> 2020-09-08T12:52:42.922242+00:00 app[web.1]: return await self.communicate(UciPlayCommand)
> 2020-09-08T12:52:42.922242+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/chess/engine.py", line 768, in communicate
> 2020-09-08T12:52:42.922243+00:00 app[web.1]: return await command.result
> 2020-09-08T12:52:42.922243+00:00 app[web.1]: chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 0)
> 2020-09-08T12:52:42.923537+00:00 app[web.1]: 10.11.131.158 - - [08/Sep/2020:12:52:42 +0000] "GET / HTTP/1.1" 500 290 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"

**Comment by StevenDalderop** [comment]
When I uninstalled eventlet it did work! I did use that for Flask-SocketIO before.

**Comment by StevenDalderop** [comment]
As a workaround I don't use websockets and eventlet anymore. Instead I use AJAX. But would be nice if you could use websockets and this library/the engine at the same time.

**Comment by niklasf** [comment]
A very interesting bug. Now that you know eventlet is involved, can you reproduce it locally as well? A minimal example would be great to narrow down the issue.

**Comment by StevenDalderop** [comment]
Until now, I haven't been able to reproduce it locally. I suspect it has something to do with asyncio not being compatible with the eventlet worker gunicorn starts. When I do use this library: https://github.com/zhelyabuzhsky/stockfish, the engine works fine, it doesn't use asyncio. Also the other functions of python-chess just work fine when using eventlet-worker. I did read that asyncio isn't compatible with Flask. Besides this is in the documentation of Gunicorn: 

> Async Workers
> The asynchronous workers available are based on Greenlets (via Eventlet and Gevent). Greenlets are an implementation of cooperative multi-threading for Python. In general, an application should be able to make use of these worker classes with no changes.
> 
> For full greenlet support applications might need to be adapted. When using, e.g., Gevent and Psycopg it makes sense to ensure psycogreen is installed and setup.
> 
> Other applications might not be compatible at all as they, e.g., rely on the original unpatched behavior.

**Comment by PedanticHacker** [comment]
Blah blah blah, close this already!

**Comment by niklasf** [comment]
@PedanticHacker First and final warning not to continue this behavior. This is a legitimate and useful report of a tricky bug.

**Comment by niklasf** [comment]
Unfortunately the patches appear to be too intrusive (and monkey patching the standard library is pretty questionable), so I don't see a way forward.

Perhaps the `PidfdChildWatcher` that's automatically used from Python 3.9+ (if run on Linux 5.3+) will work. But even if it does, there's no good way to make it available on previous versions.
