### ISSUE TITLE
New version requested! (python-chess v0.31.5)

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#631]
@niklasf, please release a new version of python-chess (v0.31.5). We will all benefit. There have been some cool features added. When you find the time. Thanks!

**Comment by PedanticHacker** [comment]
No response after 4 days? Wow!

**Comment by niklasf** [comment]
Imagine someone not responding within 4 days on a free and open source project they are maintaining in their spare time, on an issue that can easily be worked around with minor extra effort (e.g., `pip install git+https://github.com/niklasf/python-chess.git`).

**Comment by bgg-cyber** [comment]
Am fuckd up like nothing else
