### ISSUE TITLE
Insufficient material when both bishops on same colour square

### ISSUE THREAD

**Issue by dlbbld** [niklasf/python-chess#634]
Hi

It seems the is_insufficient_material() method returns a wrong result for KBvKB when both bishops are on the same colour square. It returns False instead of True. Can you please check.

#KBvKB, both bishops on white squares
board = chess.Board("5K2/8/8/1B6/8/k7/6b1/8 w - - 0 39")
self.assertEqual(board.is_insufficient_material(), True)

#KBvKB, both bishops on black squares
board = chess.Board("8/8/8/4k3/5b2/3K4/8/2B5 w - - 0 33")
self.assertEqual(board.is_insufficient_material(), True)

**Comment by niklasf** [comment]
Thanks for reporting. I must have broken this at some point in the past. Will investigate ...

**Comment by dlbbld** [comment]
Thanks, looks fine now to me.

**Comment by niklasf** [comment]
Fix included in new release, which happens to be v1.0.0.
