### ISSUE TITLE
Colors and objects not appearing, or strange behavior, v1.0.0 only

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#638]
My chess GUI, after updating python-chess to 1.0.0, displays arrows like in the image below, and it now doesn't display a circle at all. Everything worked in the version prior to 1.0.0. So, what gives? I thought changing the default value from `{}` to `DEFAULT_COLORS` of the argument `colors` of `chess.svg.board()` would fix the problem, but I was wrong. Anyway, take a look at this...
![image](https://user-images.githubusercontent.com/14254085/94179359-b009b180-fe9c-11ea-9e30-2702488b52cb.png)
Also, passing `chess.svg.DEFAULT_COLORS` to the argument `colors` has the same effect as opposed to passing my own values.

_Originally posted by @PedanticHacker in https://github.com/niklasf/python-chess/pull/637#issuecomment-698487132_

**Comment by niklasf** [comment]
Mhh ... so what code exactly are you using to produce the image, now?

**Comment by PedanticHacker** [comment]
https://github.com/PedanticHacker/ChessFighter
Take a look at the code in my GitHub repo. Using the same version of PyQt5 as before.

**Comment by PedanticHacker** [comment]
https://github.com/PedanticHacker/ChessFighter/blob/74c5d54719b01764df8491aad9ae22fdfebd19d6/source/window.py#L444
This line may be important. @niklasf, please investigate if I must change anything to accomodate v1.0.0. It's all so strange since it worked well in v0.31.4.

**Comment by niklasf** [comment]
Ah, it's because SVG Tiny (and Qt's renderer) cannot deal with the new default color `#15781B80` which includes its opacity. I'll implement a workaround.

**Comment by PedanticHacker** [comment]
The closest websafe color of `#15781B80` is `#006666`.

**Comment by PedanticHacker** [comment]
So I fixed my issue. `"arrow green": "#006666"` fixes the issue for me.

![image](https://user-images.githubusercontent.com/14254085/94186705-4e9b1000-fea7-11ea-8311-922eb2cfcc7f.png)
It doesn't look as cool as it would with some opacity, but I'm happy. The important thing is to only use default colors that are websafe.

@niklasf, but if you manage to make a workaround, that'd be awesome!

**Comment by PedanticHacker** [comment]
Now since `python-chess v1.0.1` is out, I will test with the default color `#15781B80` again. I just have to wait for `pip` to catch up.

**Comment by niklasf** [comment]
Published.

**Comment by PedanticHacker** [comment]
![image](https://user-images.githubusercontent.com/14254085/94193029-177d2c80-feb0-11ea-9fed-207b8ffc8df4.png)
It works now! Thanks a bunch, @niklasf!
