### ISSUE TITLE
cant use chess.uci with android buildozer

### ISSUE THREAD

**Issue by Abu3zzh** [niklasf/python-chess#65]
i'm a newb in both android dev and python 

but when i tried to make android apk my app just blinks and crashes

and after a hard fight i find out "import concurrent.futures" is giving the error

how can i solve it :(

**Comment by niklasf** [comment]
hi @Abu3zzh. i didn't try buildozer, but the issue is probably the following:

`concurrent.futures` is not included in python until version *3.2*. your options are:

* move to python 3
* somehow install https://pypi.python.org/pypi/futures as a dependency. not sure how this works with buildozer

let me know if you make any progress ;)

**Comment by Abu3zzh** [comment]
i should've put concurrent folder in the same folder is my main.py :)

that was me being dumb :D

now that i did import chess.uci , i dont know how to use stockfish arm engine with it

this is what i've done
`from kivy.app import App
from kivy.uix.label import Label
import chess
import chess.uci

class SimpleKivy(App):
    def build(self):
        engine = chess.uci.popen_engine('sf6')
        BM = engine.go(movetime = 1000)
     
        
        
        
        
        return Label(text=str(BM.bestmove.uci()))


if __name__ == "__main__":
    SimpleKivy().run()

`
i even tried linux way  (chess.uci.popen_engine('./sf6'))

is there anything wrong in what i've done ?

**Comment by niklasf** [comment]
Maybe try to look at the output of `os.getcwd()`, to see what the working directory of your app is. Then make sure you put Stockfish in there or specify the full path.

Besides: What error do you get with your above code?

**Comment by Abu3zzh** [comment]
i'm getting 'Permission Denied' error and i dont know the right 'android.permissions' i'm needing here

**Comment by niklasf** [comment]
Maybe someone from the Android/buildozer community has an idea. Feel free to keep me updated.
