### ISSUE TITLE
Fix sharnagl to scharnagl

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#651]
Reinhard **Scharnagl**, (died in August 2015)
was a German computer chess programmer, and author of the chess program SMIRF. Reinhard was pioneer in Fischer Random Chess (FRC / Chess960).

The Chess960 numbering scheme devised by Reinhard **Scharnagl** begins with 10, 96-length blocks of each knight (N) position. 

***

Argument names in python-chess for Chess960 stuff have a name `sharnagl`, which is wrong. Those names should be `scharnagl`. Please fix them, especially since Herr Scharnagl was your countryman, @niklasf.

**Comment by sebschger** [comment]
Thank you, I really appreciate it! 
Kind regards
