### ISSUE TITLE
Strange behaviors/bugs in Board.reset_board()

### ISSUE THREAD

**Issue by tanmay2004** [niklasf/python-chess#654]
Consider the following test:
```
import chess

board = chess.Board(chess.STARTING_FEN)
board.push_san("f3")
board.push_san("e5")
board.push_san("g4")
board.push_san("Qh4#")

print(board.is_game_over())
board.reset_board()
print(board.fen())

board.push_san("d4")
board.push_san("d5")
# board.push_san("e3")
print(board.is_game_over())
board.reset_board()
print(board.fen())

board.push_san("e4")
board.push_san("f6")
board.push_san("d4")
board.push_san("g5")
board.push_san("Qh5#")

print(board.is_game_over())
board.reset_board()
print(board.fen())

board.push_san("e4") # Throws error
```
The last line throws a `ValueError: illegal san`, and if you uncomment `push_san("e3")`, line 20 gives the same error. After some further experimentation and with the help of the `.fen()` prints, it was clear why this was happening. 

`reset_board()` resets the board position to what it was given initially, which may not have been `chess.STARTING_FEN`. But, when it does that, it doesn't reset the side whose move it was in that same initial position. Instead, the player to move is the opposite to the side which made the last move before the `reset_board()` was called. For example, after white does the fool's mate (with `Qh5`), and the board is reset, the program thinks that it is black's move even though it should be white's.

Now, I found that replacing `reset_board()` with `reset()` fixed my errors and did what I wanted, as it gave back the original starting position with white's move arbitrarily. But, the bug in `reset_board()` still remains I believe. It should fix the turn to be the same as what was there in the initial FEN passed as a parameter to the `Board` object.

Essentially, one of the simple tests of `reset_board()` is that for `chess.STARTING_FEN`, it should do the exact same thing that `reset()` does. Of course, there would be hundreds of other situations/examples where it doesn't fix the turn as desired.....

I feel like it's very probable that what I'm going to point out below may be something that was disrupted due to the release of v1.0.1 and/or because it's tests were missing. Oh wait, actually, I just tried it this hypothesis on repl, but it's giving the same errors. [Check it out here](https://repl.it/@TanmayGarg2/python-chess-bug-test). 

I hope I'm right in saying that this is a bug and if so, I'd also honestly be quite surprised that this hadn't been noticed before!

**Comment by PedanticHacker** [comment]
Interesting find! But I'm sure @niklasf will respond with: "This is by design."

Looking at the source code in `__init__. py`, I see that `chess.Board.reset_board()` does not reset the turn, only `chess.Board.reset()` does this.

We should wait for the jury. 😉

**Comment by tanmay2004** [comment]
Yeah that's true, I also saw that. It does seem likely to me too especially because it has been like this even in previous versions of `python-chess`. But, if it is so, I feel the docs need to be added to and it should be specified in both the description of `reset()` and `reset_board()` as to what they do to the side to move.

**Comment by PedanticHacker** [comment]
The python-chess docs are really bad. They don't explain anything. If someone tells you to go _read python-chess docs_, it's the same as that someone would tell you to go _f*** yourself_.

**Comment by niklasf** [comment]
Yes, in fact this is by design. It's because `reset_board()` is a method of `BaseBoard`, which only represents only the piece positions. Then `Board` inherits from `BaseBoard` and adds more properties, like `turn`.

```
class BaseBoard:
    def reset_board(self):
        # ...

class Board(BaseBoard):
    def reset(self):
        # ...
```

Currently the documentation for `reset_board()` says:

> Resets piece positions to the starting position.

The documentation of `reset()` says:

> Restores the starting position.

Pull requests to clarify are welcome.

**Comment by PedanticHacker** [comment]
Just created a PR to improve the docs.
