### ISSUE TITLE
Found a possible bug, worth investigating

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#656]
I may have stumbled upon a possible bug in `python-chess`. It may be by design, but I can't know for sure.

```
>>> import chess
>>> board = chess.Board()
>>> board.push(chess.Move.from_uci("e2e4"))
>>> board.push(chess.Move.from_uci("e7e5"))
>>> board._stack[0].restore(board)
>>> board
Board('rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')
```

Why is the board set to the starting position and not to a position of white playing `1.e4`?

**Comment by niklasf** [comment]
`board._stack` is an internal property of `chess.Board`. By using it in this way you are breaking an invariant that all public methods maintain. I have explained that doing so puts the board into an inconsistent state, and have given multiple alternatives. SInce you seem to be ignoring that, I'll stop answering related questions for some time.

As for the actual question: `board._stack[0]` is the state before the first move.

**Comment by PedanticHacker** [comment]
> As for the actual question: `board._stack[0]` is the state before the first move.

Consider this:
```
>>> import chess
>>> board = chess.Board()
>>> board._stack
[]
>>> board.push(chess.Move.from_uci("e2e4"))
>>> board._stack
[<chess._BoardState object at 0x000001C101218F70>]
>>> board
Board('rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1')
>>> board._stack[0].restore(board)
>>> board
Board('rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')
```

How can `board._stack[0]` be the state before the first move if `board._stack` is initially empty?

**Comment by niklasf** [comment]
The answer to that is in here: #616.

**Comment by PedanticHacker** [comment]
Those questions are related, yes. But I haven't got a definitive answer yet.

**Comment by PedanticHacker** [comment]
A logical assumption is that the first `chess._BoardState` object in `board._stack` is a state of the board of a pushed move. But this is not the case.

And since this is not the case, the first `chess._BoardState` object should be created at initialization of the board, i.e., when you do

`>>> board = chess.Board()`

and with this, `board._stack` should immediately have one `chess._BoardState` object (the starting position)
```
>>> board._stack
[<chess._BoardState object at 0x0000027B1CA38F70>]
```

Is that something that can be done?

**Comment by PedanticHacker** [comment]
It is interesting that after a move has been pushed, only then a board state object is created. And what is even more interesting is that this object holds the board state `prior` to the move being pushed. So `board._stack` and `board.move_stack` are not in sync: `board._stack` always lags behind.
