### ISSUE TITLE
no stockfish engine

### ISSUE THREAD

**Issue by yeranosyanvahan** [niklasf/python-chess#661]
hello
I have some questions regarding python-chess
I am using jupyter-notebook on my windows machine.
is it possibelto evaluate without running engines, cs I want something to evaluate my board, how do I do that?
Also I want to access the movement history and save it somewhere, how do I do that too?
and... check if en-passent has happened or not
during a game

Also I downloaded python-chess and couldn't figure out where is my stockfish engine is?
I am using windows btw.

**Comment by niklasf** [comment]
Duplicate of #660.
