### ISSUE TITLE
BaseVisitor.result() question

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#663]
https://github.com/niklasf/python-chess/blob/d85b7b807ee67142a813510c7e42bf3a8b4e79fe/chess/pgn.py#L973

Why does this method need to be explicitly denoted as being an abstract method? Also, it doesn't have the `pass` statement like most of them in the `BaseVisitor` abstract base class. Why?

**Comment by niklasf** [comment]
You can try these things by making the change and running the test suite and mypy.
