### ISSUE TITLE
Can't send options to Stockfish 12?

### ISSUE THREAD

**Issue by FrugoFruit90** [niklasf/python-chess#664]
Hi! I'm trying to analyze a game, and for that I want to turn off the "Analysis Contempt" option in Stockfish. However, it seems it doesn't work, and I don't know why. Neither configuring the engine nor setting the option did the job - the evaluation flips every move in a simple opening line (Spanish) - it gives white the advantage on white move and the same for black. Any idea what I'm doing wrong? I'm using Stockfish 12 as the engine.

EDIT: Just checked with Komodo 11 as well, and a similar thing happens, despite me setting both "Contempt" and "White Contempt" to 0
```
def get_best_move_score(board: chess.Board) -> int:
    engine_path = os.environ.get('STOCKFISH')
    engine = chess.engine.SimpleEngine.popen_uci(engine_path)
    engine.configure({'Analysis Contempt': 'Off', 'Contempt': "0"})
    analysis = engine.analyse(board, chess.engine.Limit(depth=20),
                              options={'Analysis Contempt': 'Off', 'Contempt': "0"})
    return analysis['score']


os.environ["STOCKFISH"] = "coach/charts/stockfish12"
file = open("coach/charts/game.pgn", encoding="utf-8-sig")

game = chess.pgn.read_game(file)
board = game.board()
previous_move = None
for move in game.mainline_moves():
    score = get_best_move_score(board)
    board.push(move)
    print(previous_move, score)
    previous_move = move
file.close()
```

**Comment by FrugoFruit90** [comment]
I just realized that evaluations are given from the playing side's perspective...

**Comment by niklasf** [comment]
Yep. For everyone stumbling upon this issue: [`chess.engine.PovScore`](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.PovScore) has some conversion methods. For example `score.white()` to consistently convert the scores to White's point of view.
