### ISSUE TITLE
Cannot pass a dict() function as the colors argument to chess.svg.board()

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#667]
If you pass a regular dictionary object as the `colors` argument to `chess.svg.board()` it works okay. Now try to pass a `dict()` function as the `colors` argument to `chess.svg.board()` and notice that you get errors. Errors arise because the keys of the dictionary need to have spaces. The regular `{}` dictionary has no issues with that, but it becomes an issue if you use the `dict()` function.

So how should one use the `dict()` function and pass that as the `colors` argument to `chess.svg.board()`?

**Comment by niklasf** [comment]
Dictionary literals are prefered, anyway.
