### ISSUE TITLE
Pawn capturing king on back rank without promotion not in pseudo legal moves.

### ISSUE THREAD

**Issue by AlexScheller** [niklasf/python-chess#669]
Currently, the pawn capturing the king on it's back rank is only represented in the set of pseudo legal moves if it also promotes. For example, if the king is on e8 and the attacking pawn is on f7, `f7e8` is not in the list of pseudo legal moves but `f7e8q` is.

Here is the relevant snippet:

https://github.com/niklasf/python-chess/blob/ec90b9b7cfc8ed3b4aa08824e86c643beaa723cb/chess/__init__.py#L1505-L1519

If a variant requires the king to be captured, it would be beneficial to be able to include the pawn capturing the king without promoting. This issue isn't difficult to work around, you can just append a queen promotion to the move when checking if a given move is in the set of pseudo legal moves without requiring the player to actually specify their promotion choice, but it would be cleaner if the move could be passed without the promotion.

This would make sense, as after the king is captured the game is likely over. Of course, if the variant includes capturing the king, but doing so doesn't end the game, then this change might make things messier for that variant.

If this change makes sense for the library I'd be happy to create a pull request, but I understand if the maintainers decide this use-case should require the workaround instead.

**Comment by PedanticHacker** [comment]
Maybe try the `find_move()` function of `chess.Board()`?

**Comment by niklasf** [comment]
Mhh ... seems looks like this is a bit of an edge case, so I think this should be handled by the variant subclass. Unless, of course, this happens to be a simplification in general.

Out of curiosity, which variant is this?

**Comment by PedanticHacker** [comment]
This is probably Suicide Chess.

**Comment by AlexScheller** [comment]
I'm using `python-chess` as a backend for an implementation of dark chess. After thinking about it more I think you're right this should be handled by the variant code, I don't see a way to change the above snippet to handle this case without complicating it.
