### ISSUE TITLE
[Feature Request] Board.is_promotion(move)

### ISSUE THREAD

**Issue by thesmartwon** [niklasf/python-chess#67]
It would be very simple to implement, just as a convenience. Currently to check if a move is a promotion, I have to use:
```
is_promotion = (board.piece_at(move.from_square).piece_type == chess.PAWN and
                          chess.rank_index(move.to_square) in [0, 7])
```
`is_promotion = board.is_promotion(m)` is much prettier, no?

Either way, this doesn't really matter, I'd just like to see it implemented, or hear your thoughts as to why it isn't already there!
Thanks

**Comment by niklasf** [comment]
How about `move.promotion`?

**Comment by thesmartwon** [comment]
I want a board.is_promotion because I make my own moves based off of wherever my user drags pieces. So if they drag a white pawn from a7 to a8, I make a chess.Move(chess.A7, chess.A8), verify it is legal (suppose it is) and afterwards check if it is a promotion to decide whether or not to prompt for the promotion type. Afterwards I push the move. So board.is_promotion(move) would be useful when making custom moves that don't know whether or not they should have a .promotion. My move a8 doesn't know it needs to be a promotion until after it knows it is a valid move.
