### ISSUE TITLE
is_game_over() of chess.Board() detects 3-fold repetition and returns True only after 8 repetitions

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#679]
As the title states, there's an issue with the is_game_over() method. Can anyone else test this? Maybe it's just my app that's at fault.

**Comment by niklasf** [comment]
I think it works: https://github.com/niklasf/python-chess/blob/f3ca606934cd2cd9b1baff81008720e00e1d640e/test.py#L1168-L1219

Please show the relevant portion of your code. That should help identify the mistake, whether in your code or this library.

Are you using `claim_draw=True`?

**Comment by PedanticHacker** [comment]
I didn't pass `claim_draw=True` to `board.is_game_over()`. The argument is `False` by default. I didn't know that. Sorry, my bad.

But it's nevertheless interesting that having the default `claim_draw=False` to behave in such a way. Is this by design?
