### ISSUE TITLE
Generating Captures

### ISSUE THREAD

**Issue by dfbenjamin** [niklasf/python-chess#68]
Is there currently an efficient way to generate only those moves that are captures?

Currently I can only achieve this, which isn't by any stretch of the imagination ideal:

    board = chess.Board()

    for move in board.legal_moves:

        if board.is_capture(move):

            do_something(move)

It would be nice to have a more efficient method for generating captures.

Thanks a lot for your work, by the way, python-chess has been incredibly useful to me recently!

**Comment by niklasf** [comment]
Makes sense. Plan to implement this efficiently:

1. Replace `board.generate_legal_moves(castling=True, pawns=True, knights=True, ...)` with `board.generate_legal_moves(from_mask=BB_ALL, to_mask=BB_ALL)`.
2. Add shortcut:

```
def generate_captures(self):
    yield from board.generate_legal_moves(to_mask=self.occupied_co[not self.turn])
    yield from en_passant_captures()
```

Might take a while to unfiddle the move generation ...

**Comment by niklasf** [comment]
Preparation completed. This is actually so useful, that it saved a lot of code internally:

```
 chess/__init__.py | 332 +++++++++++++++++++++++++++++++++----------------------------------------------
 chess/syzygy.py   |  23 ++----
 2 files changed, 147 insertions(+), 208 deletions(-)
```

**Comment by niklasf** [comment]
Efficiently generated captures are now available via `board.generate_legal_captures()` and `board.generate_pseudo_legal_captures()`.

Just pushed to master. Next release will be coming out soon.

**Comment by niklasf** [comment]
v0.14.0 released.
