### ISSUE TITLE
There's no way to change the color of the pieces

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#682]
The `DEFAULT_COLORS` dictionary in `svg.py` does not offer to change the color of the pieces. It would be great to change the color of the white pieces and the color of the black pieces. Is that something that can be done, or implemented?

**Comment by niklasf** [comment]
First step would be identifying and unifying the colors used in

https://github.com/niklasf/python-chess/blob/9d10ed8236d3d4aa0a0a4ec6bacff080b7ce4824/chess/svg.py#L35-L48

**Comment by PedanticHacker** [comment]
I see a lot of those `fill` attributes. Are those the one that provide color for a piece?

**Comment by PedanticHacker** [comment]
I am staring at the computer screen for 3 hours now and I can't figure out how to implement this feature. All I have deduced was that the `piece()` function in `svg.py` has to be given `2 new parameters`: `color`, and `opacity`. Everything else is beyond me.

**Comment by PedanticHacker** [comment]
@niklasf, when you find the time, please implement this.

**Comment by niklasf** [comment]
Gonna make the call that it's not worth it. `chess.svg` is for quick visualizations (e.g. in notebooks), not a definitive chess board rendering library.
