### ISSUE TITLE
info["score"] only provides PovScore(Cp(),Color) not evaluation

### ISSUE THREAD

**Issue by BlueDiamondHead** [niklasf/python-chess#683]
I've tried to get an engine evaluation score as an integer using as per an example on https://chess.stackexchange.com/questions/15723/returning-scores-for-all-possible-moves-from-a-chess-engine:
info = engine.analyse(board,chess.engine.Limit(depth=20))
EvaluationString = str(info["score"])
if EvaluationString.find("#") ==-1:
Evaluation = int(EvaluationString)

Yesterday this worked but today info["score"] doesn't return a evaluation score but a string PovScore(Cp(+66), WHITE).

**Comment by niklasf** [comment]
Sorry for the inconvenience. The string representation of `PovScore` changed in [v1.2.0](https://github.com/niklasf/python-chess/blob/master/CHANGELOG.rst#new-in-v120) and was never intended to be parsed this way.

Equivalent would be:

```python
evaluation = info["score"].relative.score()
```

This clarifies that scores are `relative` to the point of view. You can also use `white()` or `black()` instead. Details: https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.PovScore

`score()` returns the centi pawn-value as an integer, or `None` if the score is a mate score. Details: https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.Score.score

It's also worth mentioning that scores support comparisons without being converted to integers.
