### ISSUE TITLE
Communicate engine with running stockfish docker container.

### ISSUE THREAD

**Issue by mneira10** [niklasf/python-chess#691]
In the docs, one can communicate with a stockfish engine [using a local executable stockfish file](https://python-chess.readthedocs.io/en/v0.23.10/uci.html). I have stockfish running in a docker container and would like to connect to it with python-chess. There doesn't seem to be a trivial way to do this without messing with the [docker sdk for python's socket](https://stackoverflow.com/questions/46521166/how-to-write-to-stdin-in-a-tls-enabled-docker-using-the-python-docker-api). 

Any ideas of how to get this to work in a simple way?

**Comment by niklasf** [comment]
If it is possible to communicate with the engine in the container via stdin/stdout, then no special transport will be required. I don't recall the exact required arguments for `docker`, but the call will look something like:

```python
... = await chess.engine.popen_uci(["docker", "--arg", "value", "--second-arg", "value"])
```

**Comment by maxwell-oroark** [comment]
@mneira10 did you figure out the correct command here: `["docker", "--arg", "value", "--second-arg", "value"]`

Super curious. Currently I'm trying to create a multi-container app ( one running python-chess and another stockfish ) and trying to get them to play nice but I'm super new to docker.

**Comment by niklasf** [comment]
Try `docker run -it image/name` in the terminal. Then type `uci`. Does the engine respond? If so, the arguments should be:
```
["docker", "run", "-i", "image/name"]
```

**Comment by maxwell-oroark** [comment]
@niklasf thanks for the suggestion! I tried it and appears to be a valid command opening an interactive process on the running container. But when I type "uci" there is no response.

**Comment by maxwell-oroark** [comment]
@niklasf To get around the issue in the meantime, I am using `wget` in the dockerfile to download stockfish and unzip the binaries and then referencing the resulting path in `popen_uci`. I read that docker containers should not be multi-process and only do _one_ thing and do it _well_. I am not sure if stockfish binary applies in this instance to this philosophy or if it's a hack or not.

**Comment by zzstoatzz** [comment]
@maxwell-oroark in case its helpful, I am able to run a `chess.engine.SimpleEngine` by passing 

```
cmd = "docker run --rm -i -p 5000:5000 ghcr.io/x64squares/stockfish-socket-server stockfish".split()

engine = chess.engine.SimpleEngine.popen_uci(cmd)

```
[where i found the image
](https://github.com/x64squares/stockfish-socket-server)
