### ISSUE TITLE
Pip install can't find satistfactory chess version

### ISSUE THREAD

**Issue by wtsf** [niklasf/python-chess#695]
Greetings, fellow chess/Python addicts:

I've been trying to install chess, in every variant I could, and getting the following:
ERROR: Could not find a version that satisfies the requirement chess (from versions: none)
ERROR: No matching distribution found for chess

I tried specifying various earlier versions and always get the same error.

This also occurs when I try 
pip install --force-reinstall chess
(though I had never installed it before)

I've tried with Python 3.6 or 3.7, no difference. I'm on Mac OS 10.12.6, running the anaconda distribution. In general, pip works (e.g. can install django or other packages) - this is not the dreaded pip upgrade issue. Seems specific to the chess package.

Any help or suggestions appreciated!

**Comment by niklasf** [comment]
Python 3.7 or later is required. Please check `pip --version` to make sure you really tried the pip that belongs to Python 3.7.
