### ISSUE TITLE
Strange output when engine's ponder move is converted to SAN

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#697]
I get strange output if I convert the engine's ponder move into the SAN format.

If the engine's ponder move in the default LAN format is `g1f3`, its SAN format is displayed as `Nxf3+`. What is going on? That should have been `Nf3`.

I am using the `san()` method of `chess.Board()`, and pass it `result.ponder`. So `board.san(result.ponder)` is what I do. Here `result` is an instance of the `play()` method of `chess.engine.SimpleEngine`.

Am I doing it wrong?

**Comment by niklasf** [comment]
Ponder is what the engine expects to be played after the best move, not immediately. So getting the SAN would be:

```
board.push(result.move)
print(board.san(result.ponder))
```

**Comment by PedanticHacker** [comment]
![image](https://user-images.githubusercontent.com/14254085/100229530-ac3dee00-2f24-11eb-953a-6123342f33f1.png)

This is what I get. Notice at the bottom left that it displays `Nxf3+`. This is very strange.

**Comment by PedanticHacker** [comment]
![image](https://user-images.githubusercontent.com/14254085/100231241-063fb300-2f27-11eb-999f-84ed145882d8.png)

Notice here that it displays `dxd4` instead of `d4`. But if I don't `san()` the `result.ponder` move, it displays `d2d4`. So I guess there's a parsing issue.

**Comment by PedanticHacker** [comment]
I think I found the culprit.

https://github.com/niklasf/python-chess/blob/cde221f45368c21aaffac58ecf17ccb4587ac50b/chess/__init__.py#L2809

This internal method of `chess.Board()` (that `san()` relies upon) has this `capture` attribute which wrongly returns `True`, and adds an `x` to the `san` string.
https://github.com/niklasf/python-chess/blob/cde221f45368c21aaffac58ecf17ccb4587ac50b/chess/__init__.py#L2871
https://github.com/niklasf/python-chess/blob/cde221f45368c21aaffac58ecf17ccb4587ac50b/chess/__init__.py#L2872

Normally, `san()` works correctly, but if you pass `result.ponder` as a **move** argument to it, it goes berserk.

**Comment by PedanticHacker** [comment]
I solved my issue! I had to display the ponder move after the engine made its move. Sorry for spamming.

**Comment by niklasf** [comment]
Well, yes, that's exactly what I told you :shrug:
