### ISSUE TITLE
How to determine engine's name?

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#699]
So I have a question. How can one determine the name of a chess engine?

Say I have a file named `engine123.exe`. How can I extract information from the file whether it is `Stockfish`, `Houdini`, `Rybka`, or no engine at all? 🤔

I need to know this if the user of my app loads `Stockfish`, so that the app then loads the `NNUE` file as well. But if it's `Houdini`, or some other engine without `NNUE` support, then the `NNUE` file will not be loaded, just the engine will.

It would be nice to know how to extract the version of the engine as well, so that if the version of `Stockfish` is 12, the `NNUE` file loads, and doesn't for versions prior to 12.

Anyone has a hint?

**Comment by niklasf** [comment]
Try the `id` property: https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.Protocol.id

**Comment by PedanticHacker** [comment]
So if I have `engine, transport = chess.engine.SimpleEngine.popen_uci(...)`, do I have access to the `id` attribute via `transport`? 🤔

**Comment by PedanticHacker** [comment]
`engine.id["name"]` is the answer.

**Comment by niklasf** [comment]
> It would be nice to know how to extract the version of the engine as well, so that if the version of Stockfish is 12, the NNUE file loads, and doesn't for versions prior to 12.

Btw. it may be more robust to check for the presence of particular options (`engine.options`), rather than a particular engine version.
