### ISSUE TITLE
Illegal en-passant if captured pawn is covering a check

### ISSUE THREAD

**Issue by niklasf** [niklasf/python-chess#70]

**Comment by niklasf** [comment]
note that this is mitigated by the fact, that this position can not be reached with a sequence of legal moves

**Comment by dsjoerg** [comment]
Indeed!  Which makes me wonder, how was this "bug" discovered?

**Comment by niklasf** [comment]
I am rewriting parts of move generation, to support efficient selection of origin and target squares. In my development version I created a real en-passant bug. So I wrote test cases for all edge cases I could think of.

I realized the "mitigation factor" only afterward.

**Comment by niklasf** [comment]
Oh wow. Here's a real bug.

![image](https://cloud.githubusercontent.com/assets/402777/14325983/33346dc0-fc2c-11e5-8fcf-837974f7a183.png)


`8/8/8/r2Pp2K/8/8/4k3/8 w - e6 0 1`

**Comment by ddugovic** [comment]
Be careful about en passant diagonal discoveries such as `1b6/8/8/3Pp3/8/8/4k2K/8 w - e6 0 1`.

**Comment by niklasf** [comment]
Yep. I think Bountysource deleted my issue description.
