### ISSUE TITLE
Need an explanation how to use the *info* attribute of PlayResult()

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#700]
Yeah, me again. So I have now understood how to use the `move` and `ponder` attributes of `PlayResult()`. You just do `result.move` and `result.ponder`, where `result` is an instance of `PlayResult()`, and you get the engine's best move and the engine's ponder move. But I am having issues with this `info` attribute that `PlayResult()` has.

I wanted to retrieve some useful engine information out of that `result.info` dictionary by `result.info["score"]`, and it doesn't work. Also tried `result.info["INFO_SCORE"]`, `result.info["SCORE"]`. Apparently, no such dictionary keys exist.

How is this thing intended to be used? (The documentation is not of much help.)

**Comment by PedanticHacker** [comment]
This is not a trolling attempt, I honestly don't know. Please help.

**Comment by PedanticHacker** [comment]
As I `print(result.info)`, what I always get is `{}`, so I always get an empty dictionary. What am I doing wrong?

**Comment by niklasf** [comment]
During play, extra information is parsed only if requested. For example: `engine.play(..., info=chess.engine.INFO_ALL)`
