### ISSUE TITLE
Issue with UnicodeDecodeError: 'utf-8' codec can't decode [...]: invalid continuation byte

### ISSUE THREAD

**Issue by bjbraams** [niklasf/python-chess#704]
Don't know if this is a known issue. I am using chess.pgn on the ICCF database and the chess.pgn.read_game(pgn) command quickly fails with the error shown in the subject line. It is associated with non-standard characters in player names, like this one: [White "Helbich, Ján"]. Can this be addressed in the chess.pgn library or should I rather edit the input file?

**Comment by niklasf** [comment]
It should be possible to handle this by opening the file with the correct encoding, like `open("iccf.pgn", encoding="utf-8")` or `open("iccf.png", encoding="latin1")`.

If you are on Linux, `$ file iccf.pgn` can be used to determine the encoding.

**Comment by bjbraams** [comment]
Thank you niklasf! Opening the file with encoding="latin1" solves the problem. (The unix 'file' command tells me that it is an ISO-8859 text file.)
