### ISSUE TITLE
Given single move, find its piece

### ISSUE THREAD

**Issue by void4** [niklasf/python-chess#708]
Given a game.mainline Move.san() I need to find out which piece was moved, without instantiating a new Board (for elegance and performance reasons) like here: https://github.com/niklasf/python-chess/issues/200

Example use case: only analyzing the last move in many games

Is there a builtin method for this?

Examples:

Bf3 => B
Nd5 => N
g4 => P 

(or b,n or p, depending on who moved)

I feel like there should be a .piece field or property on every Move object that has this information

**Comment by niklasf** [comment]
Notation in PGNs can have many quirks, so `chess.pgn` does not rely on it and builds clean notation from scratch. So `node.san()` is literally implemented as:

```python
def san(self):
    return self.parent.board().san(self.move)
```

You might as well use:
```python
def moved_piece_type(node):
    return node.parent.board().piece_type_at(node.move.from_square)
```

`Move` itself does not carry this information.

**Comment by fsmosca** [comment]
Without board:

```python
def piece_type_moved(san_move, stm):
    """stm = side to move, True if white to move"""
    # castle move
    if '0-' in san_move or 'O-' in san_move:
        return 'KR' if not stm else 'kr'
    if san_move[0].isupper():
        return san_move[0] if not stm else san_move[0].lower()
    return 'P' if not stm else 'p'
```

**Comment by niklasf** [comment]
To clarify what I was trying to say: That's only more efficient when not using the `chess.pgn` parser. Otherwise generating `san_move` will require building a board anyway. If not, it's a good solution.
