### ISSUE TITLE
Draw detection - incorrect?

### ISSUE THREAD

**Issue by jackalsh** [niklasf/python-chess#71]
Let's take position with FEN 4rk2/p1p3pB/q4p2/2bpnQB1/8/2P5/PP3PPP/4R1K1 b - - 4 23 

I set Stockfish engine to multipv = 2 mode and start it to think on this position for 6 seconds.
All according to your official asynchronous API.

From your library I get:
2: Score(cp=None, mate=0, lowerbound=False, upperbound=True)}
Full output: https://gist.github.com/jackalsh/7679506069d74457a2559cb1584fd5d3

Arena detects this move as stalemate with score 0.00.
For some reason, draw score is translated into { score=None, mate=0 }.
For me, it's incorrect behaviour. Am I missing something?

**Comment by niklasf** [comment]
Hi. Thanks for reporting this. What you are seeing is definitely a bug. However I can't quite reproduce it.

```
import chess
import chess.uci
import logging

logging.basicConfig(level=logging.DEBUG)

engine = chess.uci.popen_engine(["stockfish"])
engine.uci()
engine.setoption({
    "MultiPV": 2,
})

board = chess.Board("4rk2/p1p3pB/q4p2/2bpnQB1/8/2P5/PP3PPP/4R1K1 b - - 4 23")
engine.position(board)

info_handler = chess.uci.InfoHandler()
engine.info_handlers.append(info_handler)
print(engine.go(movetime=6000))
print(info_handler.info)
```

And output is as expected:
```
BestMove(bestmove=Move.from_uci('e5f3'), ponder=None)
{'currline': {}, 'hashfull': 999, 'depth': 22, 'nps': 1989242, 'tbhits': 0, 'currmovenumber': 1, 'pv': {1: [Move.from_uci('e5f3'), Move.from_uci('g2f3'), Move.from_uci('e8e1'), Move.from_uci('g1g2'), Move.from_uci('a6f1'), Move.from_uci('g2g3'), Move.from_uci('f1f2'), Move.from_uci('g3h3'), Move.from_uci('c5d6'), Move.from_uci('g5f4'), Move.from_uci('d6f4'), Move.from_uci('f5f4'), Move.from_uci('e1g1'), Move.from_uci('f4g3'), Move.from_uci('g1g3'), Move.from_uci('h2g3'), Move.from_uci('f2f3'), Move.from_uci('h7g6'), Move.from_uci('f3f1'), Move.from_uci('h3g4'), Move.from_uci('f1e2'), Move.from_uci('g4h3'), Move.from_uci('e2b2'), Move.from_uci('h3g4'), Move.from_uci('b2c3'), Move.from_uci('g4f4'), Move.from_uci('c3d2'), Move.from_uci('f4f3'), Move.from_uci('d2a2'), Move.from_uci('f3e3'), Move.from_uci('c7c5'), Move.from_uci('e3f4'), Move.from_uci('a2f2'), Move.from_uci('f4g4')], 2: [Move.from_uci('a6a2'), Move.from_uci('e1b1'), Move.from_uci('e5f7'), Move.from_uci('g5d2'), Move.from_uci('f7d6'), Move.from_uci('f5d3'), Move.from_uci('d6e4'), Move.from_uci('d2e1'), Move.from_uci('e8e5'), Move.from_uci('h7g6'), Move.from_uci('e4d6'), Move.from_uci('g1h1'), Move.from_uci('a2c4'), Move.from_uci('f2f3'), Move.from_uci('e5e2'), Move.from_uci('e1g3'), Move.from_uci('c5e3'), Move.from_uci('b2b3'), Move.from_uci('c4d3'), Move.from_uci('g6d3'), Move.from_uci('e2a2'), Move.from_uci('d3g6'), Move.from_uci('a2a3'), Move.from_uci('c3c4'), Move.from_uci('d5c4'), Move.from_uci('b3c4'), Move.from_uci('a3c3'), Move.from_uci('b1b8'), Move.from_uci('f8e7')]}, 'nodes': 12046853, 'time': 6001, 'currmove': Move.from_uci('e5f3'), 'seldepth': 38, 'refutation': {}, 'score': {1: Score(cp=1101, mate=None, lowerbound=False, upperbound=False), 2: Score(cp=-18, mate=None, lowerbound=False, upperbound=False)}}
```

What would help?

* Try enabling debug logging as above. Maybe we can learn what's wrong by looking at the engine communication.
* Can you boil the problem down to a small code example that I can run and reproduce?
* Stalemate? How is that even relevant in this complicated position?

**Comment by jackalsh** [comment]
Sorry, this is a typo. Of course it's a draw, not stalemate!
Please see log:
https://gist.github.com/jackalsh/fa130e51725375d4a4b37847435f3c2c

As you see, same behaviour:
2: Score(cp=None, mate=0, lowerbound=False, upperbound=True)},

Stockfish 260316 64
python-chess (0.13.2)

**Comment by niklasf** [comment]
Strange behaviour. The second last info line is
```
info depth 23 seldepth 36 score mate 0 upperbound nodes 8457904 nps 1409180 time 6002 multipv 2 pv a6a2 e1b1 e5f7 g5d2 f7d6 f5d7 d6e4 b1f1 e4f2 h7g6 f2e4 g1h1 e4f2 h1g1
```
so the python-chess parser is correct. Do you get a similar result when using Stockfish on the command  line?

Maybe I must adjust python-chess to make it easy to get the last non-upperbound/lowerbound line. That would be

```
info depth 22 seldepth 36 score cp 0 nodes 7281545 nps 1414166 time 5149 multipv 2 pv a6a2 e1b1 e5f7 g5d2 f7d6 f5d7 d6e4 b1f1 e4f2 h7g6 f2e4 g1h1 e4f2 h1g1
```

and is what you are seeing in Arena.

**Comment by ddugovic** [comment]
How is that Stockfish output reproducible?  When I test this (Threads=4, MultiPV=2, movetime=30000) I observe:

```
info depth 25 seldepth 51 multipv 1 score cp 3056 nodes 62456714 nps 2851123 hashfull 999 tbhits 0 time 21906 pv e5f3 g2f3 e8e1 g1g2 a6f1 g2g3 f1f2 g3h3 c5d6 g5f4 d6f4 f5f4 e1g1 f4g3 g1g3 h2g3 f2f3 h7g6 f6f5 h3h2 f3e2 h2g1 e2g4 g6h7 g4g3 g1f1 g3h3 f1e1 h3h7 e1d2 h7h2 d2c1 f5f4 c1b1 f4f3 a2a4 f3f2 b1a1 f2f1q a1a2 f1c4 a2a3 c4c5 a3a2
info depth 24 seldepth 51 multipv 2 score cp 0 nodes 62456714 nps 2851123 hashfull 999 tbhits 0 time 21906 pv a6a2 e1b1 e5f7 g5d2 f7d6 f5d7 d6e4 b1f1 e4f2 h7g6 f2e4 g1h1 e4f2 h1g1 f2e4 g1h1 e4f2 h1g1
```

**Comment by jackalsh** [comment]
Once again I tested this with raw uci in console and the output is the same:
[input.txt](https://github.com/niklasf/python-chess/files/209979/input.txt)
[output.txt](https://github.com/niklasf/python-chess/files/209980/output.txt)

Engine evaluates as normal, but to the end returns "score mate 0 upperbound".
Should we report this as bug to Stockfish team? Or this is normal?
I am not new person in chess programming, even wrote engine by myself and never heard about mate 0 convention, so for me it's like bug, which ruins logics of my scripts.

**Comment by niklasf** [comment]
Let's report it. It's at least very unexpected to me. Maybe they have some insights into this ...

**Comment by jackalsh** [comment]
I opened a ticket:
http://support.stockfishchess.org/discussions/problems/7617-incorrect-draw-detection?unresolve=true

**Comment by jackalsh** [comment]
After some research I can tell, that this is very common Stockfish behaviour, probably because of  hash table aggressive optimizations and various pruning technics.
http://chess.stackexchange.com/questions/7680/stop-sf-multipv-from-returning-an-upperbound
http://support.stockfishchess.org/discussions/problems/3344-mate-0

Currently, I use infinite loop to check for best pv/score and update it only if it's not mate 0. This works, but infinite synchronious loop eat resources of my machine.
Can we add some option to python chess to handle this situation authomatically?

Thanks in advance.

**Comment by niklasf** [comment]
In the meantime, here is a workaround:

```
import chess
import chess.uci


engine = chess.uci.popen_engine("stockfish")
engine.uci()

class MyInfoHandler(chess.uci.InfoHandler):
    def score(self, cp, mate, lowerbound, upperbound):
        if not lowerbound and not upperbound:
            super(MyInfoHandler, self).score(cp, mate, lowerbound, upperbound)


info_handler = MyInfoHandler()
engine.info_handlers.append(info_handler)

engine.go(movetime=2000)

print(info_handler.info["score"])
```

Actually, situations where the bounds are useful are rare. I might make this the default in the next release.
