### ISSUE TITLE
chess.Piece hash is incorrect

### ISSUE THREAD

**Issue by bartekspitza** [niklasf/python-chess#711]
The `__hash__` function I believe is incorrectly implemented for `chess.Piece`. For example:

`chess.Piece.from_symbol('P').__hash__() -> 2`
`chess.Piece.from_symbol('n').__hash__() -> 2` 

Is this intended? I was implementing a zobrist hash function and used the `__hash__` as an index to to random numbers, which of course led to the zobrist not functioning correctly.

**Comment by niklasf** [comment]
Good catch, thanks for reporting! Technically it's not a violation of the guarentees offered by `__hash__()` (in that `return 0` would also be a valid implementation), but it's definitely not intended.

**Comment by niklasf** [comment]
Fixed by using a natural mapping into `0, 1, ..., 10, 11`.
