### ISSUE TITLE
Traverse mainline and variations in a game

### ISSUE THREAD

**Issue by jkrooskos** [niklasf/python-chess#712]
Hello I'm really enjoying this library so far, thank you. Sorry if this is the wrong place to place this type of request.

I am trying to obtain the fen string for every move in a game (mainline and variations). So far, I figured out how to achieve this for the mainline moves with:

```python
with open('test.pgn') as pgn:
    while True:
        game = chess.pgn.read_game(pgn)
        if game:
            board = game.board()
            for move in game.mainline_moves():
                board.push(move)
                print(board.fen())
        else:
            break
```
Is there a preferred way to recursively traverse all moves and variations for a game?

Thank you.

**Comment by niklasf** [comment]
This might be a good use case for [visitors](https://python-chess.readthedocs.io/en/latest/pgn.html#visitors). Visitors can be used to traverse the PGN tree (optionally, without even building the actual tree as a Python object).

```python
import sys
import chess.pgn

class PrintAllFensVisitor(chess.pgn.BaseVisitor):
    def visit_board(self, board):
        print(board.fen())

    def result(self):
        return True

with open(sys.argv[1]) as pgn:
    while True:
        found_game = chess.pgn.read_game(pgn, Visitor=PrintAllFensVisitor)
        if not found_game:
            break
```

**Comment by jkrooskos** [comment]
Thank you so much, exactly what I was looking for. Assuming the user wants to obtain metadata for later use, would this be an intended use of result?

```python
import sys
import chess.pgn

class PrintAllFensVisitor(chess.pgn.BaseVisitor):
    def __init__(self):
        super(PrintAllFensVisitor, self).__init__()
        self.fens = []

    def visit_board(self, board):
        self.fens.append(board.fen())

    def result(self):
        return self.fens

with open(sys.argv[1]) as pgn:
    while True:
        fens = chess.pgn.read_game(pgn, Visitor=PrintAllFensVisitor)
        print(fens)
        if not fens:
            break
```

**Comment by niklasf** [comment]
Yep, absolutely. A lot cleaner than performing side effects like printing directly in the visitor.

**Comment by jkrooskos** [comment]
Fantastic. Thanks for the help @niklasf, much appreciated.

**Comment by thedtripp** [comment]
> This might be a good use case for [visitors](https://python-chess.readthedocs.io/en/latest/pgn.html#visitors). Visitors can be used to traverse the PGN tree (optionally, without even building the actual tree as a Python object).
> 
> ```python
> import sys
> import chess.pgn
> 
> class PrintAllFensVisitor(chess.pgn.BaseVisitor):
>     def visit_board(self, board):
>         print(board.fen())
> 
>     def result(self):
>         return True
> 
> with open(sys.argv[1]) as pgn:
>     while True:
>         found_game = chess.pgn.read_game(pgn, Visitor=PrintAllFensVisitor)
>         if not found_game:
>             break
> ```

Thank you for providing this example! I think it should be added to the documentation. (I'd be happy to submit a PR for that if you agree.)
