### ISSUE TITLE
Some of the images for selected projects don't work right on github dark mode

### ISSUE THREAD

**Issue by justinkterry** [niklasf/python-chess#713]
Like most major websites, github now supports a dark mode, which I'm sure many people use or are using. The PettingZoo logo, the maia chess logo, and the top part of the Syzygy logo all don't work right in dark mode because they're black. For PettingZoo, we had this problem with the website favicon and just used a grey. You could also just add a white background to them

**Comment by justinkterry** [comment]
The specific hex code pettingzoo uses for its favicon is A0A0A0, if that's helpful

**Comment by niklasf** [comment]
I added a white background now. Refinements welcome.
