### ISSUE TITLE
Feature Request: Side-to-Move Indicators

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#715]
It would be useful to have a visual indicator near the bottom right corner of the coordinate margin to indicate that it is White's turn, and near the top right corner to indicate that it is Black's turn.

If the orientation of the board is flipped, the indicators should flip as well.

I am not knowledgeable enough to implement this. It, however, would be useful.

**Comment by niklasf** [comment]
If the last move is available, simply highlighting that implies to the side to move, but it may not always be.

**Comment by PedanticHacker** [comment]
A lot of those chess GUIs have like a shiny dot, or a rectangle, on the coordinate margin of the chessboard that indicates which turn it is.

I was just wondering if that could be implemented by python-chess.

`chess.svg.board()` could get a new boolean parameter, named `turn_indicator`. I was thinking of a yellow gradient dot on the coordinate margin.

We could rely on `board.turn` to get the turn. Just a quick thought.

**Comment by PedanticHacker** [comment]
I guess no one is interested in implementing this. Too bad.
