### ISSUE TITLE
Add depth to set_eval

### ISSUE THREAD

**Issue by ulthiel** [niklasf/python-chess#718]
One can add the depth to the evaluation comment in a PGN like e.g. [%eval 2.5,11] (score 2.5 at depth 11). It would be nice if set_eval could be extended to include this.

**Comment by niklasf** [comment]
Interesting. Can I read up on this somewhere? Are there any programs that support this already?

**Comment by ulthiel** [comment]
Well, none of this (even the [%eval ...] without the depth) is in the official PGN standards. But I checked with ChessBase and HIARCS Chess Explorer: both interpret this correctly.

**Comment by niklasf** [comment]
For some bikeshedding: I suppose the corresponding getter should return the parsed evaluation and depth as a tuple. Any suggestions for the name? Thinking about something like `eval_at`, `eval_depth`, ...

**Comment by PedanticHacker** [comment]
`eval_depth` seems a good name.
