### ISSUE TITLE
Is Board.generate_legal_moves() deterministic

### ISSUE THREAD

**Issue by void4** [niklasf/python-chess#719]
I tested it a few times in different positions and this seems to be the case, I also grepped through the source and random wasn't mentioned very often. But I want to be sure, can you confirm this?

**Comment by niklasf** [comment]
It is deterministic right now, but that is not a guarantee. A future release of python-chess might give the moves in a different order (very likely) or not in a deterministic order at all (unlikely).

If you're doing something that depends on determinism, sorting moves is a good way to guarantee it.

**Comment by void4** [comment]
> sorting moves is a good way to guarantee it.

That makes perfect sense, thank you :)
