### ISSUE TITLE
Anyone know why I'm getting flipping signs for chess evaluations?

### ISSUE THREAD

**Issue by Nixonite** [niklasf/python-chess#72]
Hi python chess people,

So I noticed that in my stockfish centipawns output, I get flipping signs for centipawn scores of consecutive positions. This is very unusual given the large numbers and also high elo for players. e.g. 

565
-561
630
-638
638
-638
957
-670
775
-767
755
-715
791
-711

Here's some of my code, anyone know what I'm doing wrong?

```
pgn = open("million_base_pgn_files/game-"+str(game_num)+".pgn")
node = chess.pgn.read_game(pgn)
scores = []
engine.ucinewgame()
while not node.is_end():
            next_node = node.variation(0)
            engine.position(next_node.board())
            command = engine.go(depth=20)
            scores.append(info_handler.info['score'][1].cp)
            node = next_node
            time.sleep(.25)
```

I kind of suspect that these evaluations are right, but the signs are messed up. Like... maybe a positive score is good for black if it's scoring on black's turn, and vice versa? I have only known centipawn scores to be positive if white is in the lead, but this other idea would make these numbers make sense.

**Comment by dsjoerg** [comment]
Hi, Stockfish's evaluations are always given in terms of the side whose turn it is to move.

**Comment by Nixonite** [comment]
Ah! Thank you. I have only used GUIs which incorporated stockfish so I guess they were always transforming the signs for me. That totally makes sense then, great.

**Comment by jackalsh** [comment]
Why you don't use asyncronious interface?
Why you don't use isready command to be sure you are syncronized with engine?
Why you making sleep in the while loop?

**Comment by niklasf** [comment]
I can answer the first two:

* Sometimes the synchronous interface does just fine: Analyze positions, one at a time.
* `chess.uci` already uses `isready` internally. No need for manual calls.

The sleep is mysterious to me, too.

While we are doing code review: It can be advantageous to analyze games backwards. This improves transposition table usage.

**Comment by jackalsh** [comment]
Thanks for the tips. It will be very useful for me.

**Comment by Nixonite** [comment]
I'm using multiprocessing so this is only one of 4 processes being run, and I'm using the sleep command to keep my CPU temperature sane since it's on so many cores.
