### ISSUE TITLE
PGN writing: efficiently appending a move to the mainline

### ISSUE THREAD

**Issue by void4** [niklasf/python-chess#723]
Is this the required method to append a move to a chess.pgn.Game mainline?

```python
game = chess.pgn.Game()
board = game.board()

move = chess.Move.from_uci(uci)

board.push(move)

mainline = list(game.mainline())
lastnode = mainline[-1] if mainline else game
lastnode.add_variation(move)
```

Or is there a faster way of appending to the end? Didn't see anything in the readthedocs

**Comment by niklasf** [comment]
Shortcut: `game.end().add_variation(move)`

Btw, in your example, `board` is the starting position, but you append the move to the final position.

**Comment by void4** [comment]
For longer games, maybe the last node could be cached so the mainline doesn't have to be traversed anytime. Not sure how hard this is to implement though. Thanks!

**Comment by niklasf** [comment]
There was some caching in older versons, but then all other use cases are paying the price of keeping the cache valid. I think it's best just to let users keep a reference to the end (`node = node.end(); node = node.add_variation(move)`), if they frequently use it.

**Comment by void4** [comment]
Makes sense, thanks! :)
