### ISSUE TITLE
[Quick fix] Clock doesn't work for milliseconds

### ISSUE THREAD

**Issue by warouvideo** [niklasf/python-chess#727]
Hi, the regex for the clock doesn't work when it has also milliseconds (like games on chess.com).
I added an example below to quickly showcase the format of milliseconds and why parsing it doesn't work with the actual regex.

CLOCK_REGEX = re.compile(r"""\[%clk\s(\d+):(\d+):(\d+)\]""")

[%clk 0:04:44]         => WORKS

[%clk 0:04:44.7]      => Doesn't WORK

**Comment by niklasf** [comment]
It wasn't included in https://www.enpassant.dk/chess/palview/enhancedpgn.htm, but seems common. Added.
