### ISSUE TITLE
Issue parsing fen?

### ISSUE THREAD

**Issue by djdekker** [niklasf/python-chess#73]
Some engines seem to have problems working together with uci.py. I'm wondering what could be the cause of the difficulties?

For example, I (White) was playing the following moves against Cinnamon 2.0 (Black) using PicoChess, which uses uci.py from the python-chess package:
1. f3 e5
2. g4
Already Black's first move resulted in a Python error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 595, in _bestmove
    self.bestmove = self.board.parse_uci(tokens[0])
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 2686, in parse_uci
    raise ValueError("illegal uci: {0} in {1}".format(repr(uci), self.fen()))
ValueError: illegal uci: 'e7e5' in rnbqkbnr/pppp1ppp/8/4p3/6P1/5P2/PPPPP2P/RNBQKBNR b KQkq - 0 2
```

From other games I have the impression that this is happening with the first non-book move that the engine has to make.

**Comment by niklasf** [comment]
Yep, I can reproduce a problem with Cinnamon, even without PicoChess. I'll try to pinpoint it and fix it later.

**Comment by niklasf** [comment]
So I finally got around to doing this. It is actually a bug in the UCI protocol implementation of Cinnamon. I have provided a patch: gekomad/Cinnamon#3.

**Comment by niklasf** [comment]
The fix got merged :)

I'll just assume that was it. If there is anything else, please open another issue.
