### ISSUE TITLE
Text overlay on arrows

### ISSUE THREAD

**Issue by josephernest** [niklasf/python-chess#731]
Congrats for this project @niklasf !
How is it possible to add a text overlay on a `chess.Arrow`?

Example:

```
import chess, chess.svg, chess.pgn, io
fen = 'rnbqkbnr/ppp1pppp/8/3p4/2PP4/8/PP2PPPP/RNBQKBNR b KQkq - 1 1'
board = chess.Board(fen)
arrows = []
for san in ['c6', 'e6', 'dxc4']:
    m = board.parse_san(san)
    arrows.append(chess.svg.Arrow(tail=m.from_square, head=m.to_square))
boardsvg1 = chess.svg.board(board=board, flipped=board.turn == chess.BLACK, arrows=arrows)
with open('_opening.svg', 'w') as f:
    f.write(boardsvg1)
```

Here is what I want to achieve:

![image](https://user-images.githubusercontent.com/6168083/104839738-57cf4300-58c3-11eb-93c9-3bb14e4fdf66.png)

**Comment by niklasf** [comment]
Sorry, I think this feature is reasonable, but `chess.svg` is intended only for more basic visualizations.

It is also very hard to do proper text positioning in SVG Tiny, to the point that the board coordinates on the margin are not actual text, but prerendered paths.

If you do not care about SVG Tiny, you can of course calculate the positions and insert custom elements into the SVG.
