### ISSUE TITLE
Parallel analysis

### ISSUE THREAD

**Issue by ludaavics** [niklasf/python-chess#732]
Hi,

Thanks for the great library!

I am trying to get the score for each position in a game. I can do it sequentially:

```python
board = chess.Board()
moves = chess.pgn.read_game(io.StringIO(game.pgn)).mainline_moves()
engine = chess.engine.SimpleEngine.popen_uci(engine_path)

positions = []
for move in moves:
    board.push(move)
    positions.append(board.fen())

def score(position):
    board = chess.Board(position)
    result = engine.analyse(
        board, chess.engine.Limit(nodes=nodes), info=chess.engine.INFO_SCORE
    )
    return result["score"]

scores = [score(position) for position in positions]
```

But when I try to stick calls to `score` into a thread pool, i get an `asyncio.exceptions.InvalidStateError: invalid state`.

I guess I somehow have to use `chess.engine.Protocol` instead of the simple engine, but I struggle a bit to put all the pieces together. Any pointers appreciated!

**Comment by niklasf** [comment]
Hi. Can you please show the failing example with the thread pool?

**Comment by ludaavics** [comment]
Hi,

Thanks for the quick response.

I managed to get somewhere by creating a new engine process for each task.

```python
async def score(position: str, side: chess.Color) -> float:
    """
    Return the score of a given FEN position.
    """
    try:
        _, engine = await chess.engine.popen_uci(engine_path)
        await engine.configure(engine_options)
        board = chess.Board(position)
        result = await engine.analyse(
            board,
            chess.engine.Limit(nodes=nodes),
            info=chess.engine.INFO_SCORE,
        )
    finally:
        await engine.quit()

    return getattr(
        result["score"], {chess.WHITE: "white", chess.BLACK: "black"}[side]
    )().score(mate_score=MATE_SCORE)

# _, engine = await chess.engine.popen_uci(engine_path) <-- single engine doens't work
scores = await asyncio.gather(
    *(asyncio.create_task(score(position, side)) for position in positions)
)
```

When I use a single engine across all tasks, i get the `asyncio.exceptions.InvalidstateError`. Is that expected? 
Or am I missing and I should be able to achieve concurrency with a single engine?

**Comment by niklasf** [comment]
Ok, thanks. That clarifies it.

And yes, engines are not able to analyse multiple positions at the same time. So some strategies to take advantage of concurrency are:
* `await engine.setoption({"Threads": n})` to use multiple threads on the same position, and analyse sequentially
* Spawn multiple engine instances as you have shown, but careful not too spawn a huge amount of processes
* Spawn a fixed number of engine instances, each pulling from a queue of positions

The particular way this currently fails (`InvalidStateError`) is still a bug. Will investigate and fix, soon.

**Comment by ludaavics** [comment]
Gotcha thanks.

FWIW, and for anyone reading this in the future, according to [one of the guys behind stockfish](https://blog.playmagnus.com/generating-tactical-puzzles-with-stockfish-and-chess-jl-part-i/), when analyzing multiple positions, it's more efficient to concurrently run single-threaded engines than sequentially run a multi-threaded engine. 🤷🏿‍♂️ 

That being said, a queue sounds like a much more sound approach, thanks for the pointer, I'll go down that road.

Thanks again for your work and the responsiveness! I probably can't help much on the technical side, but if you want to create issues on the documentation side, I'd be happy to take a crack at one or two!

**Comment by niklasf** [comment]
Thanks. Maybe a small section about concurrency in the engine docs could be useful?
