### ISSUE TITLE
chess.square() question

### ISSUE THREAD

**Issue by tank-overlord** [niklasf/python-chess#734]
I think there's a some mix-up in this function.

It should be the following:

def square(file_index: int, rank_index: int) -> Square:
    """Gets a square number by file and rank index."""
    return **file_index * 8 + rank_index**

For example:
'd5' should be rank = 3, file = 4, and chess.D5 = 35 but if you do chess.square(4, 3), you got 28 instead

**Comment by niklasf** [comment]
But isn't d5 on the d-file, thus file index 3, and the fifth rank, thus rank index 4?

**Comment by tank-overlord** [comment]
on a second thought, you are right.
Each square is file idx ('A' - 'H', col) + rank idx (1 - 8, row), so 'D5' is indeed 'D' (file idx = 3) and '5' (rank idx = 4).
It is correct that the square is rank_index * 8 + file_index
I think I somehow double flipped it.
