### ISSUE TITLE
Pass UCI_Elo as an option

### ISSUE THREAD

**Issue by ScarecrowY** [niklasf/python-chess#738]
I am using python-chess to communicate with stockfish 12, and I want to limit the engine's strength to a specific ELorating. I noticed that there's a UCI_Elo option in stockfish 12, and I wonder if there is a way that I can pass in UCI_Elo as a parameter? Thanks in advance!

**Comment by trevorbayless** [comment]
You can do this by setting the engine configuration options for `UCI_LimitStrength` and `UCI_Elo`.

**Comment by niklasf** [comment]
Hi, I deleted the corresponding discussion (#737). Please don't double post.

The example on https://python-chess.readthedocs.io/en/latest/engine.html#options shows how to set the `Hash` option. You can adjust that to set the options that @trevorbayless mentioned.

**Comment by ScarecrowY** [comment]
Oh, sorry for double posting. Just to confirm, ```engine.options``` is for printing the relevant options, to set an option, I need to use ```engine.configure()```, right?

**Comment by niklasf** [comment]
Yep, correct.

**Comment by ScarecrowY** [comment]
I am actually using an old version of the library (v 0.25.0), I think I can use the ```setoption``` function?

**Comment by ScarecrowY** [comment]
Hi, I have a follow-up question. Start from which version, we could pass in options ```UCI_LimitStrength``` and ```UCI+Elo```? Thanks!
