### ISSUE TITLE
Xboard time control implemented incorrectly

### ISSUE THREAD

**Issue by MarkZH** [niklasf/python-chess#742]
I believe that the implementation of Xboard time control is incorrect in two aspects:

1. The `level` and `st` commands are sent on every move, when they should only be sent before a game starts and only resent when time control changes. Only `time` and `otim` should be sent before most moves.

From the [Xboard spec](https://www.gnu.org/software/xboard/engine-intf.html#11):

> Example: if at the start of the game "level 40 60 0" was given (40 moves per hour), and the engine receives "level 20 22 0" just before move 41, it should understand that it should do the next 20 moves in 22 minutes (pehaps because the secondary session was 20 moves per 15 minutes, and it had 7 minutes left on its clock after the first 40 moves). 

2. If a time control is used with no `remaining_moves` and no `increment` (e.g., each player has 10 minutes for all their moves), then the `level` command is never sent, when `level 0 10 0` should be. This is because, as it is now, `level` is only sent when `remaining_moves` or `increment` are truthy, which zero is not ([line 2050 in chess/engine.py](https://github.com/niklasf/python-chess/blob/1b21b80fb9b574085c245e1261b103cfa5cdcf6f/chess/engine.py#L2050)). Since `st` and `level` time controls are mutually exclusive, perhaps something like the following could work:
```python
if limit.time is not None:
    engine.send_line(f"st {max(0.01, limit.time)}")
else:
    base_mins, base_secs = divmod(int((limit.white_clock if board.turn else limit.black_clock) or 0), 60)
    engine.send_line(f"level {limit.remaining_moves or 0} {base_mins}:{base_secs:02d} {increment}")
```

For reference, [here's a link to how I'm avoiding these issues with the upgraded version of python-chess for lichess-bot](https://github.com/MarkZH/lichess-bot/blob/01e2a36f9929afe6c2f8418ff162911d66fd4eaf/engine_wrapper.py#L135). The `level` command is sent manually at the beginning of a game using the `SimpleEngine.protocol.send_line()` command (line 132). Thereafter, I create a `Limit` instance with only the `white_clock` and `black_clock` fields set so only `time` and `otim` commands are sent to the engine (line 139). If I'm doing this wrong, please advise on the correct way to do this.

**Comment by MarkZH** [comment]
I'm now thinking that it's the user's responsibility to send the correct `Limit` to python-chess so that the correct Xboard commands are sent. The code in my first comment (`if limit.time is not None:` etc.) wouldn't work because it would still send `level` commands on every move.

I think the only change needed in python-chess is for [line 2050 in engine.py](https://github.com/niklasf/python-chess/blob/1b21b80fb9b574085c245e1261b103cfa5cdcf6f/chess/engine.py#L2050) to be changed to:
```python
if limit.remaining_moves is not None or increment is not None:
```
so that both values can be zero without skipping the sending of the `level` command.

With that change, I believe the following sample user code would correctly set an Xboard engine to play a game:

```python
engine = chess.engine.SimpleEngine.popen_xboard("/path/to/xboard_engine")
new_time_control = True
while True:
    clock = get_clock_from_game_server()
    time_limit = chess.engine.Limit(white_clock=clock.time_left(white),
                                    black_clock=clock.time_left(black))
    if new_time_control:
        time_limit.time = clock.move_time() # returns None if time per move is not used
        time_limit.remaining_moves = clock.moves_until_next_period() # returns None if time per move is used
        time_limit.white_inc = clock.increment(white) # returns None if time per move is used
        time_limit.black_inc = clock.increment(black) # returns None if time per move is used
        new_time_control = False

    board = get_board_state_from_game_server()
    play_result = engine.play(board, time_limit)
    send_move_to_game_server(play_result.move)
```
This way, the engine only receives `level` or `st` at the beginning of the game, and `time` and `otim` thereafter.

**Comment by niklasf** [comment]
Thanks for reporting and investigating.

From a design perspective, the API is intended to be mostly idempotent. The user should send a limit with updated remaining time at that point, repeating unchanged parameters (like increment). Then the module should do whatever necessary to make that happen.

The most important thing to clarify seems to be: Does the spec prohibit sending `level` or `st` multiple times during the same game?

**Comment by MarkZH** [comment]
The spec requires sending `level` or `st` commands during a game each time time control changes. For example, all [FIDE events](https://handbook.fide.com/chapter/C07) use this time control:

> There is a single time control for all major FIDE events: 90 minutes for the first 40 moves followed by 30 minutes for the rest of the game with an addition of 30 seconds per move starting from move one.

So, an Xboard engine would receive `level 40 90 0` at the start of the game, then `level 0 30 30` after the 40th move. Every other move just gets `time` and `otim` commands.

I think it's wrong to send `level` commands before every move. [The GNU xboard spec](https://www.gnu.org/software/xboard/engine-intf.html#11) says
> In conventional clock mode, every time control period is the same. That is, if the time control is 40 moves in 5 minutes, then after each side has made 40 moves, they each get an additional 5 minutes, and so on, ad infinitum.

There's no need to send the `level` command again unless the time control changes. Same goes for `st`.

For a specific example of the problem:
1. python-chess sends `level 40 1 0` to indicate 40 moves must be played in one minute.
2. The engine takes 57 seconds to play 39 moves. Each time, python-chess sends `level 39 0:58 0`, `level 38 0:57 0`, etc.
3. python chess sends `level 1 0:03 0` before the 40th move.
4. The engine will assume that it will only get an extra 3 seconds added to its time for the next 40 moves and allot time accordingly.

Perhaps the logic inside the `XBoardProtocol.play()` method should be something like this:
```python
# self.previous_limit is stored from previous move
send_time_control = False
if limit.time != self.previous_limit.time:
    send_time_control = True
elif limit.white_inc != self.previous_limit.white_inc:
    send_time_control = True
elif limit.black_inc != self.previous_limit.black_inc:
    send_time_control = True
elif self.previous_limit.remaining_moves - limit.remaining_moves != 1:
    if self.previous_limit.remaining_moves != 0 or limit.remaining_moves != 0:
        send_time_control = True

if send_time_control:
    # send level or st command

# send time and otime

self.previous_limit = limit
```
This will send a new `level` command after then last move of any time control period specified by a `level` command with a non-zero move count (after the 40th move of a `level 40 90 0` game). But, since it's a new time control period anyway, this bit of redundancy doesn't matter.

I am starting to develop some sympathy for programmers who only want to deal with UCI.

**Comment by niklasf** [comment]
For `st`, I think it's clear that there is no need to repeat it unchanged, but also no harm.

For `level`, your interpretation of the quotes seems reasonable, but is later contradicted by the following paragraph in blue.

> The number of moves given in the level command (when non-zero) should be taken as the number of moves still to do before the specified time will be added to the clock, if the "level" command is received after some moves have already been played. The time given should be interpreted as the time left on its clock (including any time left over from the previous sessions), **and not necessarily the time that will be added to the clock after the specified number of moves has been played.**

The rest of the paragraph is backpedalling, saying it is only relevant for a specific implementation:

> This is only relevant in WinBoard 4.3.xx, which might send the engine "level" commands during a game, just before the engine has to start thinking about the first move of a new time-control session. Example: if at the start of the game "level 40 60 0" was given (40 moves per hour), and the engine receives "level 20 22 0" just before move 41, it should understand that it should do the next 20 moves in 22 minutes (pehaps because the secondary session was 20 moves per 15 minutes, and it had 7 minutes left on its clock after the first 40 moves).

That seems non-normative, though. All in all, current python-chess behavior is arguably correct.

**Comment by MarkZH** [comment]
"Arguably correct" is a good way to put it. I'll drop the point.

The second issue in my original post is still important. Calling the `play()` method with `chess.engine.Limit(white_clock=600, black_clock=600)` should result in `level 0 10 0` being sent to the engine, but nothing is sent except `time` and `otim`. I can create a pull request to fix this similar to the code in the original post.

**Comment by niklasf** [comment]
Oh, right. Yes, please.
