### ISSUE TITLE
About using the return value of engine.play

### ISSUE THREAD

**Issue by ScarecrowY** [niklasf/python-chess#744]
I am trying to update our code (written by someone else)  to the latest python-chess version which was using python-chess 0.25.0. After calling ```result = engine.go(movetime=2000)```, we used the return value as ```result = result.bestmove.uci()```. I saw ```engine.go()``` in the old version returns a ```BestMove```, but the latest version uses ```engine.play()``` and returns a ```PlayResult```. Are they essentially the same thing? Or any suggestions on changing my code? Thanks in advance!

**Comment by niklasf** [comment]
Yep, [`play_result.move`](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.PlayResult.move) would be equivalent to the old `result.bestmove`.

**Comment by ScarecrowY** [comment]
Thanks for your response. May I ask what does ```.uci()``` do? Do I still need it now?

**Comment by niklasf** [comment]
You're getting a `Move` object, just like before, so [`.uci()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Move.uci) can be used to convert it to a string, if that's needed.

**Comment by ScarecrowY** [comment]
thank you so much!
