### ISSUE TITLE
How to extract opening names and time spent in openings as a csv file?

### ISSUE THREAD

**Issue by Johnne32** [niklasf/python-chess#745]
Hello all, 
I have a pgn file that I want to extract the opening names, times spent in the opening ( say the first 15 moves), and possibly the chess notation/moves of the opening as a CSV file for further analysis. The goal is to figure out those chess openings that consume time in a game of chess.
I have gone through past issues here but have not really seen one that gives me some ideas on how to proceed. So far, I have read in the pgn file and iterated over multiple games from the pgn files but I really don't know how to proceed.
I don't even know if python chess would be suitable for this task so I would greatly appreciate some guidance here. Thanks in advance. 

Below is an example of the supposed output:

| ID | Openings names                            | Opening time spent |  
|----|---------------------------------------|----------------------|
| 1  | French defense:Advance variation | 23.0s                         |   
| 2  | Queen's pawn opening                  | 15.0s                         |  
| 3  | Owen defense                                | 34.0s                         |

**Comment by Johnne32** [comment]
This is a link to the sample pgn files.

**Comment by Johnne32** [comment]
This is a link to the sample pgn files.
https://drive.google.com/file/d/1jjGQjw89BOG-s-CL0eRhG-lvDEkuU0Xh/view?usp=drivesdk

**Comment by Johnne32** [comment]
> This is a link to the sample pgn files.
> https://drive.google.com/file/d/1jjGQjw89BOG-s-CL0eRhG-lvDEkuU0Xh/view?usp=drivesdk


> Can you please share (one game of) the input file, to see what the format is like?

This is a link to the sample pgn files.
https://drive.google.com/file/d/1jjGQjw89BOG-s-CL0eRhG-lvDEkuU0Xh/view?usp=drivesdk

**Comment by Johnne32** [comment]
> Can you please share (one game of) the input file, to see what the format is like?

This is a link to the sample pgn files.
https://drive.google.com/file/d/1jjGQjw89BOG-s-CL0eRhG-lvDEkuU0Xh/view?usp=drivesdk

**Comment by niklasf** [comment]
Ok. Here are some hints that should get you started:

```python
import chess.pgn

pgn = open("lichess_jc52766_2021-03-02.pgn")
game = chess.pgn.read_game(pgn)

# Checking the remaining time of a player
mainline = list(game.mainline())
print("Time at ply 0:", mainline[0].clock())
print("Time at ply 30:", mainline[30].clock())

# Iterate from the end of the game until a matching opening name is found
book = {
    "rnbqkbnr/ppp1pppp/8/3p4/3P1B2/8/PPP1PPPP/RN1QKBNR b KQkq -": "Queen's Pawn Game: Mason Variation",
}

board = game.end().board()
while board.move_stack:
    epd = board.epd()
    try:
        print("Found opening name:", book[epd])
        break
    except KeyError:
        board.pop()
```

For a possible source of opening names, you could read the TSV files from https://github.com/niklasf/eco.
