### ISSUE TITLE
 Cp as an integer and not as PovScore (Cp (+20), WHITE)

### ISSUE THREAD

**Issue by sggghss** [niklasf/python-chess#749]
I am trying to get the value of Cp as a number. From what I have read in the documentation it seems that there is a method to do it like: score (*, mate_score: int) but I can't get it to work, Currently I have:

    
     board = chess.Board()

    info =  engine.analyse(board, chess.engine.Limit(time=0.1))

    print(info["score"])

    # Score: PovScore(Cp(+20), WHITE)

**Comment by niklasf** [comment]
See https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.PovScore. So one way to get it from White's point of view would be:

```python
info["score"].white().score()
```
