### ISSUE TITLE
syzygy example won't work with 6-men TB

### ISSUE THREAD

**Issue by rwst** [niklasf/python-chess#75]
The example from the readme with 6-men syzygy TB:
```
In [1]: import chess.syzygy

In [2]: tablebases = chess.syzygy.open_tablebases("/home/ralf/tb/src")
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-2-8d57410d19b9> in <module>()
----> 1 tablebases = chess.syzygy.open_tablebases("/home/ralf/tb/src")

/home/ralf/python-chess/chess/syzygy.py in open_tablebases(directory, load_wdl, load_dtz)

/home/ralf/python-chess/chess/syzygy.py in __init__(self, directory, load_wdl, load_dtz)

/home/ralf/python-chess/chess/syzygy.py in open_directory(self, directory, load_wdl, load_dtz)

/home/ralf/python-chess/chess/syzygy.py in __init__(self, directory, filename, suffix)

/home/ralf/python-chess/chess/syzygy.py in __init__(self, directory, filename, suffix)

error: [Errno 24] Too many open files
```
This is on Linux with 32GB RAM. I think you should not open all files at once, so I think this is clearly a bug. You can send the $100 via Paypal to `ralf@ark.in-berlin.de`. I'll report here if successful.

**Comment by niklasf** [comment]
Thanks for reporting. There's a story to this.

The first project I developed with the syzygy module is https://syzygy-tables.info. Back then I was using an early version with lazy file opening. Additionally, for such a service, there is no point in ever closing tables.

Initially everything worked fine. But a couple hundred requests later the service stopped working. You can probably guess what happened: The limit for open file descriptors was exhausted, eventually.

I strongly dislike stuff that blows up after a while in production, but not in testing. So this motivated the decision to mmap all the files at startup. This way you can tell there is a problem right away. (More expensive parts of table initialization are still done lazily.)

Check out `ulimit -a | grep descriptors`. You can set a higher limit like `ulimit -n 4096`.

---

I agree that python-chess could handle this better. Maybe a parameter for maximum open file descriptors and closing LRU files would do. This way the user can decide, if it is common for their use case, to open many/all of the tables, or if they only need some.

---

(Finally, sorry. This is not elegible for the bug bounty, which only applies for the core module. I'm slightly less confident in the much younger submodules.)

**Comment by rwst** [comment]
> I agree that python-chess could handle this better. 

Yes, because here on OpenSuSE the bash handles ulimits, and there seems to be a max of 2000 hardcoded for the max of files open, and this does not suffice apparently.

**Comment by niklasf** [comment]
I find it unlikely, that there is no way to go beyond 2000. But this is really cumbersome, then.

Meanwhile, I'd be intrested if the following workaround does anything useful:

```
import resource
soft, hard = resource.getrlimit(resource.RLIMIT_NOFILE)
print(soft, hard)
resource.setrlimit(RLIMIT_NOFILE, (4096, hard))

# syzyg open ...
```

**Comment by rwst** [comment]
```
In [5]: resource.setrlimit(resource.RLIMIT_NOFILE, (4096, hard))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-cb86588eefbd> in <module>()
----> 1 resource.setrlimit(resource.RLIMIT_NOFILE, (4096, hard))

ValueError: current limit exceeds maximum limit
```
It works if I su root, set ulimit, su user, then run ipython.

**Comment by niklasf** [comment]
Ok. (But obviously that is not acceptable.)

**Comment by niklasf** [comment]
New parameter added: `open_tablesbases(max_fds=128)`. Please try it out and open another issue, if there's a problem. I'll release it soon.

**Comment by rwst** [comment]
I confirm opening works with a directory full of 4,5,6-men rtbw/rtbz files. `probe_dtz` also gave the right rexult for one 4-men and one 6-men position. Nice work.

**Comment by oscardssmith** [comment]
Sorry to necro, but if I'm opening all the tables at random, is passing `None` in going to speed up queries noticeably? What effect will it have on ram (for 6 man)? Thanks!
