### ISSUE TITLE
About pawn promotion.

### ISSUE THREAD

**Issue by 9acca9** [niklasf/python-chess#750]
Hello. 
Is it possible to make a move like a7a8 with a pawn to promote? Or does it always have to be entered with the style a7a8q (for example)? I ask because before I used a library that allowed to ask the reason why a movement could not be added. Among the reasons one of them was "must be promotion". So this served me to present a menu on the screen where the user chooses the piece (Queen, Rook, etc.) and then through the code added to the movement the selected value "q, r, n, b".
In this case, a good Samaritan gave me part of his code. What he does is check what kind of piece makes the move, and if it is a pawn, see if it is moving towards the position that it would "promotion" (then I can intervene).
But python-chess doesn't have a function that does this?
The only thing I found is a function that returns if there was, that is, if a promotion has already occurred.
Thanks.

**Comment by niklasf** [comment]
Hi. If I understand your intend correctly, you could use [`find_move()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.find_move) for that purpose. Example:

```python
if board.find_move(chess.B7, chess.B8).promotion:
    # ...
```

**Comment by 9acca9** [comment]
> Hi. If I understand your intent correctly, you could use [`find_move()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.find_move) for that purpose. Example:
> 
> ```python
> if board.find_move(chess.B7, chess.B8).promotion:
>     # ...
> ```

Hello.
Yes, that's exactly what I want.
I make a query. 
Tried this and it didn't work:

`   if board.find_move(chess.mover[0:2], chess.mover[2:4]).promotion:
        print("Esto es una promocion")`

mover is my move like "e2e4" ("mover" is not a chess method. okay.)

Neither this...
```

escInicial = (mover[0:2]).upper()
    escInicial = "chess." + escInicial
    print(escInicial)
    escFinal = (mover[2:4]).upper()
    escFinal = "chess." + escFinal
    print(escFinal)

    if board.find_move(escInicial, escFinal).promotion:
        print("This is a promotion move")
```
In this case: "TypeError: list indices must be integers or slices, not str"

The type of coordinates that I need to pass are of the type "e2e4".

What would the matter be like?
Thanks.

**Comment by niklasf** [comment]
Starting with a string like "e2e4" you should first parse it:

```python
import chess

board = chess.Board()
move = chess.Move.from_uci("e2e4")
if board.find_move(move.from_square, move.to_square, move.promotion).promotion:
    print("This is a promotion move")
```
