### ISSUE TITLE
problem with "legal" move

### ISSUE THREAD

**Issue by 9acca9** [niklasf/python-chess#754]
Hello.
I have this little problem. It is in a game with a physical chess board.

When I move the piece I have a function that before sending it (push), see what kind of move it was (if it was a castling, or a pawn in passing), then I check if the move is the start of a pawn promotion (example b7a8 ). Since it is a physical board, my idea was always once done b7a8 then present a menu in which you choose what you want to promote.
Then I add the letter to the movement and send that (example b7a8q).

After this with a function I verify if the movement is valid. and if it is valid I send it (push).

The problem is that if I make an invalid move, this move reaches the "if" that checks if it is a promotion ... and the result is that the program "fails" because what reaches the "if" is not a legal move.

But, if I check if it is a legal move before verifying if it is a promotion then the moves of the promotion style (b7a8) are illegal ... because the function where this move is "corrected" has not yet been started by adding the letter corresponding (q, r, n, b).

I can only beg not to commit an illegal move while playing, or .... present in the menu all the time the option to "promote" and before making the move execute the menu that adds the "corresponding letter (q, r , n, b) before sending it ... (option I don't like).

Maybe there is some function that I don't know about. or some better logic.
Any ideas??

Thanks.
Relevant code.....:

```
if board.find_move(mover_objeto.from_square, mover_objeto.to_square, mover_objeto.promotion).promotion: #for give the user a menu to add q,r,n,b (his choice)
        menu_promocion()
        eleccion = nombrar(pos_flecha)
        mover = mover + eleccion
        mover_objeto = chess.Move.from_uci(mover)

 while mover_objeto not in board.legal_moves: 
        print ("This is not a valid move.")
        mover = getboard().lower() #Tomamos el movimiento
        mover_objeto = chess.Move.from_uci(mover) #Lo convertimos en un objeto de python-chess
```

**Comment by niklasf** [comment]
Hi. How about

```python
move = ...

try:
    move = board.find_move(move.from_square, move.to_square, move.promotion)
except ValueError:
    print("Illegal move!")
else:
    if move.promotion:
        # select promotion piece
        move.promotion = chess.KNIGHT

    # move is guaranteed to be legal here
    board.push(move)
```

**Comment by 9acca9** [comment]
Yep, that works! Thanks!
