### ISSUE TITLE
Your lib found another use

### ISSUE THREAD

**Issue by asdfjkl** [niklasf/python-chess#76]
... wrote a small tool to convert a pgn file into an [Anki](http://ankisrs.net) for opening study (memorization), hosted @ https://github.com/asdfjkl/pgn2anki
You might (or might not) want to add this to your list of applications that use python-chess.

and I am using this post to again thank you for your lib and all the effort and work that went into.

**Comment by niklasf** [comment]
Nice. It's been a while since I used Anki. I'll give it a try ;)
