### ISSUE TITLE
Bug multipv dicts ?

### ISSUE THREAD

**Issue by ccanger** [niklasf/python-chess#760]
Hi Niclas,

I am trying to write a program with multiple dictionaries, but there are always times in a game where this error occurs. About 97 percent of all positions work with the program, the others do not. Here's an example. What can I do ?

Hallo Niclas,

ich versuche ein Programm mit multiplen Wörterbüchern zu schreiben, aber bestimmte Stellungen führen zu diesem Fehler:

IndexError: list index out of range

The chess position is correct, I have lots of positions which not work.

this is the example ...
########################################

Created on Thu Mar 25 11:22:01 2021

```python
import chess
import chess.engine

multipv_wert=6

engine = chess.engine.SimpleEngine.popen_uci("stockfish13.exe")

# this position don't work
board = chess.Board("r2q1rk1/ppp3pp/2n5/8/1P2Q3/P3Pp2/R2b1PPP/4KB1R w K -")

# this position work
# board = chess.Board("r1bqkbnr/p1pp1ppp/1pn5/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR w KQkq - 2 4")

info = engine.analyse(board, chess.engine.Limit(depth=1),multipv=multipv_wert)

for x in range(0,multipv_wert-1,1):
    print ("x: ",x)
    print (info[info[x]["multipv"]]["pv"])
engine.quit()
```

#########################################

**Comment by ccanger** [comment]
I have problems with the font size, sorry !

**Comment by niklasf** [comment]
Hi.

`info[info[x]["multipv"]]["pv"]`is almost certainly incorrect. You probably just want `info[x]["pv"]`. The corresponding range would be `range(0, multipv_wert)`.

You're also assuming that every position has 6 legal moves. But the [example](https://lichess.org/analysis/standard/r2q1rk1/ppp3pp/2n5/8/1P2Q3/P3Pp2/R2b1PPP/4KB1R_w_K_-) doesn't. To fix that, it's better not to use ranges at all:

```python
for x, line in enumerate(info):
    print("x:", x)
    print(line["pv"])  # or line.get("pv", []) to default to [] if pv was not sent by engine
```

**Comment by ccanger** [comment]
Thank you, I will try it ... and I will give you a answer ...

**Comment by ccanger** [comment]
I should have checked the legal moves before.That was my fault.
Thank you !

**Comment by ccanger** [comment]
And now ? The engine show two chess moves in debugging, but the dicts only one ? Where is my fault ? 


##### -*- coding: utf-8 -*-

import chess
import chess.engine
import logging

logging.basicConfig(level=logging.DEBUG)

multipv_wert=5

engine = chess.engine.SimpleEngine.popen_uci("stockfish13.exe")

board = chess.Board("r2q1rk1/ppp3pp/2n5/8/1P2Q3/P3Pp2/R2b1PPP/4KB1R w K -")

info = engine.analyse(board, chess.engine.Limit(depth=2),multipv=multipv_wert)

legale_zuege=board.legal_moves.count()

print ("es gibt ",legale_zuege,"legale Züge...")

print ("mit Index 0: ",0,info[info[0]["multipv"]])
print ("mit Index 1: ",1,info[info[1]["multipv"]])

engine.quit()

**Comment by ccanger** [comment]
debugging output:

DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:chess.engine:<UciProtocol (pid=14300)>: Connection made
DEBUG:chess.engine:<UciProtocol (pid=14300)>: << uci
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> Stockfish 13 by the Stockfish developers (see AUTHORS file)
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> id name Stockfish 13
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> id author the Stockfish developers (see AUTHORS file)
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> 
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name Debug Log File type string default 
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name Contempt type spin default 24 min -100 max 100
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name Analysis Contempt type combo default Both var Off var White var Black var Both
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name Threads type spin default 1 min 1 max 512
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name Hash type spin default 16 min 1 max 33554432
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name Clear Hash type button
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name Ponder type check default false
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name MultiPV type spin default 1 min 1 max 500
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name Skill Level type spin default 20 min 0 max 20
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name Move Overhead type spin default 10 min 0 max 5000
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name Slow Mover type spin default 100 min 10 max 1000
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name nodestime type spin default 0 min 0 max 10000
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name UCI_Chess960 type check default false
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name UCI_AnalyseMode type check default false
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name UCI_LimitStrength type check default false
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name UCI_Elo type spin default 1350 min 1350 max 2850
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name UCI_ShowWDL type check default false
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name SyzygyPath type string default <empty>
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name SyzygyProbeDepth type spin default 1 min 1 max 100
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name Syzygy50MoveRule type check default true
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name SyzygyProbeLimit type spin default 7 min 0 max 7
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name Use NNUE type check default true
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> option name EvalFile type string default nn-62ef826d1a6d.nnue
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> uciok
DEBUG:chess.engine:<UciProtocol (pid=14300)>: << setoption name UCI_AnalyseMode value true
DEBUG:chess.engine:<UciProtocol (pid=14300)>: << setoption name MultiPV value 2
DEBUG:chess.engine:<UciProtocol (pid=14300)>: << ucinewgame
DEBUG:chess.engine:<UciProtocol (pid=14300)>: << isready
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> readyok
DEBUG:chess.engine:<UciProtocol (pid=14300)>: << position fen r2q1rk1/ppp3pp/2n5/8/1P2Q3/P3Pp2/R2b1PPP/4KB1R w K - 0 1
DEBUG:chess.engine:<UciProtocol (pid=14300)>: << go depth 2
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> info string NNUE evaluation using nn-62ef826d1a6d.nnue enabled
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> info depth 1 seldepth 1 multipv 1 score cp 28 nodes 30 nps 30000 tbhits 0 time 1 pv a2d2 f3g2 d2d8 g2h1q e4h1 a8d8
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> info depth 1 seldepth 1 multipv 2 score cp -648 nodes 30 nps 30000 tbhits 0 time 1 pv e1d1
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> info depth 2 seldepth 2 multipv 1 score cp 567 nodes 121 nps 121000 tbhits 0 time 1 pv a2d2 a7a6 d2d8
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> info depth 2 seldepth 2 multipv 2 score cp -648 nodes 121 nps 121000 tbhits 0 time 1 pv e1d1 f3g2
DEBUG:chess.engine:<UciProtocol (pid=14300)>: >> bestmove a2d2 ponder a7a6
es gibt  2 legale Züge...
in der Schleife:  0 {'depth': 2, 'seldepth': 2, 'multipv': 2, 'score': PovScore(Cp(-648), WHITE), 'nodes': 121, 'nps': 121000, 'tbhits': 0, 'time': 0.001, 'pv': [Move.from_uci('e1d1'), Move.from_uci('f3g2')]}
Traceback (most recent call last):

 
    print ("in der Schleife: ",1,info[info[1]["multipv"]])

IndexError: list index out of range
