### ISSUE TITLE
SVG rendering not working with Google Colab

### ISSUE THREAD

**Issue by ChristianVaughn** [niklasf/python-chess#762]
Not sure if this is an issue with python-chess, or with how Google Colab differs from a regular Jupyter notebook, but when trying to draw a chessboard the output cell just shows the large chunk of SVG tags. 

the board will display when I download the notebook and run through jupyter notebook installed on my pc through anaconda, so I'm thinking it is an issue with how google colabatory works

**Comment by dsblank** [comment]
It just worked for me:

![Screenshot from 2021-03-26 16-55-14](https://user-images.githubusercontent.com/168568/112703423-3e231c80-8e6d-11eb-9628-2005ada9a3e8.png)

Are you doing something different?

**Comment by ChristianVaughn** [comment]
Thanks for the reply. That does work. I was following the [SVG rendering doc page](https://python-chess.readthedocs.io/en/latest/svg.html) because it said mostly for IPython/Jupyter Notebook integration, so didn't think to try just calling the board variable.
