### ISSUE TITLE
board.is_game_over() should return what caused gameover

### ISSUE THREAD

**Issue by WieeRd** [niklasf/python-chess#765]
`is_game_over()` is commonly used to end loop in programs using python-chess.  
But since it only returns boolean value, methods like `is_checkmate()` has to be run afterwards to know what caused game over.  
Obviously I could run every single `is_` methods in the first place, but modifying(or adding variant) `is_game_over()` to return something like`gameState.CHECKMATE` would help a lot simplifying the code.

**Comment by niklasf** [comment]
I agree. I will consider adding an API to get game end, reason, and winner (if any).

**Comment by niklasf** [comment]
I have added [`board.outcome()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.outcome).

**Comment by WieeRd** [comment]
Ayyy thanks :D  
Didn't expect to get response this fast!
