### ISSUE TITLE
Faster threefold repetition checking

### ISSUE THREAD

**Issue by acostarelli** [niklasf/python-chess#769]
I was too lazy to make a pull request, but I came up with this little construction:
```python
class History():
    def __init__(self):
        self.once_set = set()
        self.twice_set = set()

    def add(self, pos):
        """
        Returns True if a threefold repetition has been reached.
        """
        pos = str(pos)

        if pos in self.once_set:
            if pos in self.twice_set:
                return True
            else:
                self.twice_set.add(pos)
        else:
            self.once_set.add(pos)

        return False
```

Example use:

```python
board = Board()
history = History()
...

board.push(move)
is_threefold = history.add(move)

if is_threefold:
    ...
```

Maybe the history object could instead set an internal property called `threefold_reached` or something, which could be accessed at any time (and `add` wouldn't have to return anything).

IDK some food for thought.

**Comment by niklasf** [comment]
Hi, thanks for sharing. Did you benchmark this, and what python-chess function did you compare it to?

**Comment by acostarelli** [comment]
I haven't, but I assumed it would be faster since the time complexity is `O(1)`. I was comparing (mentally) to `Board.can_claim_threefold_repetition()`, which is reportedly slow because "In the worst case scenario, every legal move has to be tested and the entire game has to be replayed because there is no incremental transposition table."

**Comment by niklasf** [comment]
Ok, thanks. It's not that slow, just slower than what you'd expect from incremental zobrist hashing. Speeding it up the way you proposed (or with a dictionary mapping positions to number of occurences), seems straight forward enough to implement in applications that need it. So closing for now.
