### ISSUE TITLE
Question on generating analysis for games

### ISSUE THREAD

**Issue by Nixonite** [niklasf/python-chess#77]
If I wanted to find the scores of 5 games, move by move centipawn scores, would I need to go through each node/move in each game and tell stockfish to go to depth 16 (my desired depth)? 

I'm asking this because it sounds like a lot of computation if I wanted to do a few more. Just curious if this is the only way of doing it, or if stockfish might be storing some other future move scores that I can catch instead of starting from scratch at those moves. 

Thanks a lot for your time, this is a very cool repo.

**Comment by ddugovic** [comment]
This is an open problem, as chess has not yet been solved; however, there are two factors to consider:

1.  Programs like ChessMaster, Fritz, etc. start analysis from the end of a game and work backwards, reusing cached evaluations.
2.  Stockfish and other engines have time management for playing a game from start to finish, the same way that human chess players are familiar with time management.  It's not entirely clear what the best way to allocate time for analysis (from finish to start of a game) is.

**Comment by jackalsh** [comment]
I will have to write this functionality by yourself if you want to use python-chess library. Engine has nothing to do with complex analysis and just provide simple API for position evaluation.
Each modern engine have hash table, which allows storing scores of already evaluated positions.

**Comment by Nixonite** [comment]
Thanks for the input. I was searching around for chess cluster projects, few exist and none are popular. I suppose the good ones are all proprietary in this case... except LiChess though I haven't looked into it since I'm looking for a python solution. I'll look into optimizing the parameters of stockfish then with the setoptions method.
