### ISSUE TITLE
ImportError: cannot import name 'Color' from 'chess'

### ISSUE THREAD

**Issue by Russell3162001** [niklasf/python-chess#771]
Getting ImportError: cannot import name 'Color' from 'chess' when trying to run - even with a two line script Import Chess and Import Chess.Engine

Must be doing something very basic wrong!

**Comment by niklasf** [comment]
Hi, maybe try `import chess; print(chess.__version__)`. The latest version is 1.5.0. Very old versions didn't have the `Color` type alias yet.

**Comment by Russell3162001** [comment]
Thanks - sorted now, it was an installation problem
