### ISSUE TITLE
Changing color of specified pieces/square sets

### ISSUE THREAD

**Issue by keener101** [niklasf/python-chess#774]
Hello, great library! 

I was interested in doing some more visualization with your SVG tool - I saw this issue that was tagged as "wontdo": https://github.com/niklasf/python-chess/issues/682, and decided that I'd probably pick it up myself. 

I did want to confirm that there wasn't existing functionality that I might have missed that already did this with squares though - is there no way to specify what squares should have different colors? It appears that you're doing it at _some_ level with the last move coloration.

Thanks!

**Comment by niklasf** [comment]
Hi there! Sounds like a reasonable feature that doesn't exist yet. The closest thing right now is drawing circles with arbitrary colors, like the blue one on h7:

![image](https://user-images.githubusercontent.com/402777/116007169-b0268700-a60e-11eb-91e6-2dd866016e9a.png)
