### ISSUE TITLE
Running a non std UCI command

### ISSUE THREAD

**Issue by Russell3162001** [niklasf/python-chess#778]
A noob question I am sure

Ive used the engine = chess.engine.SimpleEngine.popen_uci..... protocol

and want to send a non standard uci command (expex in Eman, a stockfish derivative)

How do I send the command?

ID guess something similar to the eval command in a previous issue?

**Comment by niklasf** [comment]
Hi, do you need to be able to parse the output of the command, or is it just triggering some action?

**Comment by Russell3162001** [comment]
just triggering an action

**Comment by niklasf** [comment]
Switching to the asyncio variant, it would look like:

````python
import chess.engine
import asyncio

async def main():
    transport, engine = await chess.engine.popen_uci(...)
    engine.send_line("custom command")

asyncio.run(main())
````

With the synchronous variant it's not so easy, and requires using some undocumented internals:

````python
import chess.engine
import asyncio

engine = chess.engine.SimpleEngine.popen_uci(...)

async def send_custom_command(protocol):
    protocol.send_line("custom command")

with engine._not_shut_down():
    future = asyncio.run_coroutine_threadsafe(send_custom_command(engine.protocol), engine.protocol.loop)

future.result()
````

Both snippets untested.

**Comment by Russell3162001** [comment]
Thanks - I will give them a try
