### ISSUE TITLE
Some attributes missing when board initiallized in jupyter

### ISSUE THREAD

**Issue by coolsidd** [niklasf/python-chess#780]
I initialised a new board in jupyter (google colab) and I recieve the following error

```
board = chess.Board()
print(board.outcome())
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-28-747149ede5fb> in <module>()
      1 board = chess.Board()
----> 2 print(board.outcome())

AttributeError: 'Board' object has no attribute 'outcome'
```

The same 2 lines run fine on my laptop, board.outcome() returns None.

**Comment by niklasf** [comment]
`board.outcome()` is a new feature in v1.5.0. You can check the version using `print(chess.__version__)`.

**Comment by coolsidd** [comment]
For some reason colab defaults to version 0.23.11

**Comment by coolsidd** [comment]
I don't think this is an issue at your end so I am closing this issue. Will reopen if version 1.5.0 (whenever it becomes available on colab) also has this problem. Currently the latest version on colab is 1.2.0 (presumably due to python 3.7 and older pip)

**Comment by coolsidd** [comment]
For others who may face the same issue, the issue was that I was using `pip install python-chess` instead of `pip install chess`, the latter gives the correct updated version.
