### ISSUE TITLE
Engine communication outside play() and other methods

### ISSUE THREAD

**Issue by MarkZH** [niklasf/python-chess#781]
I'm trying to implement the handling of draw offers and resignations in [lichess-bot](https://github.com/ShailChoksi/lichess-bot/). I have a question about getting messages sent by an engine when not invoking `play()`, `analyze()` or other engine methods.

Here's a stripped down version of the main game-playing loop with an XBoard engine:

```python
engine = chess.engine.SimpleEngine.popen_xboard(configuration)
while True:
    game = get_game_state_from_server()
    if game.is_over():
        break
    play_result = engine.play(game.board, game.clock)
    send_move_to_server(play_result.move)
```

In order to handle draw offers, I've changed the loop to the following:

```python
engine = chess.engine.SimpleEngine.popen_xboard(configuration)
while True:
    game = get_game_from_server()
    if game.is_over():
        break
    if game.draw_offered():
        engine.protocol.send_line("draw")
    play_result = engine.play(game.board, game.clock)
    send_move_to_server(play_result.move, play_result.draw_offered)
```

My question is about the time between the `send_line("draw")` and the `engine.play()`. If the engine sends "offer draw" (to accept the draw) before the `engine.play()` method is invoked, is there a way to retrieve that communication? Or, is there a better way to go about this?

**Comment by niklasf** [comment]
Maybe we could add `engine.play(..., draw_offered=True)` sending `draw`, so it would be guaranteed that the play command is active already?

**Comment by MarkZH** [comment]
Does it matter that `draw_offered` is unused inside `UCIProtocol.play()`?

**Comment by niklasf** [comment]
I think it's fine. UCI engines simply never accept draws then, which they don't do anyway. I'll add a note to the documentation.

**Comment by MarkZH** [comment]
I meant more in the sense of python linters. Are any code testers going to complain about the unused variable?

**Comment by niklasf** [comment]
Ah ... at least flake8 doesn't seem to mind.
