### ISSUE TITLE
FEN representation missing enpassant information

### ISSUE THREAD

**Issue by aduerig** [niklasf/python-chess#782]
I think enpassant info is missing in FEN notation. From [Wikipedia](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation) FEN has the fourth field defined as:
_"En passant target square in algebraic notation. If there's no en passant target square, this is "-". If a pawn has just made a two-square move, this is the position "behind" the pawn. This is recorded regardless of whether there is a pawn in position to make an en passant capture.[6]"_

But, if I just make the move "e4" on an empty board, the enpassant field is "-" instead of the expected "e3". Here is the behavior in action:
![image](https://user-images.githubusercontent.com/9120862/118381869-90ef9980-b5bd-11eb-9fed-e93290304c51.png)

I think it's just listing it as "-" because there are no pawns able to capture it, but I think it might still be useful in keeping the FEN specifications for easier compatibility with other engines.

**Comment by niklasf** [comment]
You can use `board.fen(en_passant="fen")`, `board.fen(en_passant="xfen")`, and `board.fen(en_passant="legal")` (the default), depending on which specification you want to follow.

**Comment by jeffarjeffar** [comment]
Just a comment:
As mentioned, the standard definition says that
> This is recorded regardless of whether there is a pawn in position to make an en passant capture.[6]
It would be better if you changed the default value for `en_passant` to `"fen"`
