### ISSUE TITLE
Using "UCI_LimitStrength" and "UCI_Elo"

### ISSUE THREAD

**Issue by ScarecrowY** [niklasf/python-chess#786]
Hi, I am wondering start from which version, we could pass in options UCI_LimitStrength and UCI+Elo? Thanks!

**Comment by niklasf** [comment]
Setting options in one way or another was supported for a long time even before 1.x. But I recommend updating to the latest version and configuring options as documented here: https://python-chess.readthedocs.io/en/latest/engine.html#options

**Comment by ScarecrowY** [comment]
I know we could use ```configure``` or pass in the configurations in one single move, but the problem is my currently environment is using python 3.6, and you said the latest version requires python 3.7 or above. I wonder if there is a version that I could use the ```UCI_LimitStrength``` and ```UCI_Elo``` while I am using python 3.6? There would be a lot of problems to solve in my project if I create another venv using python 3.7. Thank you so much!

**Comment by niklasf** [comment]
Yep, that's correct.
