### ISSUE TITLE
Extracting moves from a pgn file with multiple games

### ISSUE THREAD

**Issue by kapilg1997** [niklasf/python-chess#787]
I have a pgn file which contains a large amount of games. I am having trouble extracting move information from the file. But moves of only first game is extracted. I have written the following code:

import chess.pgn 
pgn_file = open('chess_game.pgn')
current_game = chess.pgn.read_game(pgn_file)
pgn_text = str(current_game.mainline_moves())

print(pgn_text)

where the chess_game.pgn  = 
[Event "Wch U16"]
[Site "Wattignies"]
[Date "1976.??.??"]
[Round "?"]
[White "Van der Wiel, John TH"]
[Black "Kasparov, Gary"]
[Result "1-0"]
[WhiteElo ""]
[BlackElo ""]
[ECO "B93"]

1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 a6 6.f4 Qc7 7.a4 g6 8.Bd3 Bg7
9.Nf3 Bg4 10.Be3 Nc6 11.O-O O-O 12.Qe1 Bxf3 13.Rxf3 e6 14.Qh4 Qd8 15.Rh3 h5
16.Be2 d5 17.e5 Nd7 18.Qf2 Qe7 19.g4 hxg4 20.Bxg4 Rad8 21.Rd1 f5 22.Bf3 Rf7
23.Kh1 g5 24.Bh5 g4 25.Bxf7+ Qxf7 26.Rg3 Qh5 27.Kg2 Nf8 28.Ne2 Ng6 29.h3 Nh4+
30.Kf1 Kf7 31.Ng1 d4 32.Bc1 gxh3 33.Qe2 Qxe2+ 34.Nxe2 Ng6 35.Rxh3 Bf8 36.Rb3 Rd7
37.Rbd3 Bc5 38.c3 Ba7 39.Be3 Rd5 40.cxd4 Nb4 41.Rb3 a5 42.Bd2  1-0

[Event "Wch U16"]
[Site "Wattignies"]
[Date "1976.??.??"]
[Round "?"]
[White "Dunne, David Joseph"]
[Black "Kasparov, Gary"]
[Result "0-1"]
[WhiteElo ""]
[BlackElo ""]
[ECO "B51"]

1.e4 c5 2.Nf3 d6 3.Bb5+ Nd7 4.d4 Nf6 5.Nc3 cxd4 6.Qxd4 e5 7.Qd3 h6 8.Be3 Be7
9.O-O O-O 10.Rad1 a6 11.Bc4 Qc7 12.a4 Nc5 13.Bxc5 Qxc5 14.Nd5 Nxd5 15.Bxd5 Rb8
16.Nd2 Bd7 17.Bb3 b5 18.a5 Rbc8 19.Nf3 Be6 20.Rfe1 Rfd8 21.Re2 Rc7 22.Red2 Rdc8
23.h3 Qb4 24.Bxe6 fxe6 25.Qb3 Rc4 26.Re2 Qxb3 27.cxb3 Rc1 28.Rxc1 Rxc1+ 29.Kh2 Kf7
30.Ne1 Bd8 31.Nd3 Rd1 32.Nb4 Bxa5 33.Nxa6 Rc1 34.b4 Bb6 35.b3 Rc3 36.Ra2 Rxb3
37.Rc2 Bd4 38.Rc7+ Kf6 39.f3 Ra3 40.Rc6 Rc3 41.Rc7 Rxc7 42.Nxc7 Bc3 43.Nxb5 Bxb4
44.Na7 Kf7 45.Kg3 Ke8 46.Kg4 Kd7 47.f4 g6 48.h4 Kc7 49.f5 exf5+ 50.exf5 gxf5+
51.Kxf5 Kb7 52.Nb5 Kb6 53.Nxd6 Bxd6 54.g4 Kc6 55.g5 hxg5 56.hxg5 Kd5 57.g6 Bf8  0-1

[Event "Wch U16"]
[Site "Wattignies"]
[Date "1976.??.??"]
[Round "?"]
[White "Kasparov, Gary"]
[Black "Rogers, Ian"]
[Result "1-0"]
[WhiteElo ""]
[BlackElo "1865"]
[ECO "B33"]

1.e4 c5 2.Nf3 Nc6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 e5 6.Ndb5 d6 7.Bg5 a6 8.Na3 Be6
9.Nc4 Rc8 10.Ne3 Be7 11.Bxf6 Bxf6 12.Bc4 O-O 13.Bb3 Nd4 14.O-O Bg5 15.Ncd5 Nxb3
16.axb3 g6 17.Kh1 Bh6 18.Qd3 f5 19.exf5 gxf5 20.f4 Kh8 21.Rad1 Qh4 22.Qe2 exf4
23.Nc4 Bf7 24.Qd3 Bh5 25.Nxd6 Bxd1 26.Nxc8 Bh5 27.Nce7 f3 28.gxf3 Qh3 29.Nf4 Qh4
30.Qd4+ Qf6 31.Qxf6+ Rxf6 32.Nxh5 Rf7 33.Nd5 f4 34.Re1  1-0

[Event "Wch U16"]
[Site "Wattignies"]
[Date "1976.??.??"]
[Round "?"]
[White "Kasparov, Gary"]
[Black "Cramling, Pia"]
[Result "1/2-1/2"]
[WhiteElo ""]
[BlackElo ""]
[ECO "C42"]

1.e4 e5 2.Nf3 Nf6 3.Nxe5 d6 4.Nf3 Nxe4 5.Qe2 Qe7 6.d3 Nf6 7.Bg5 Nbd7 8.Nc3 Qxe2+
9.Bxe2 h6 10.Bh4 g6 11.d4 a6 12.O-O-O Bg7 13.Rhe1 O-O 14.Bc4 b5 15.Bd5 Rb8
16.Bc6 Nb6 17.a3 Bb7 18.Bxb7 Rxb7 19.Bxf6  1/2-1/2

[Event "Wch U16"]
[Site "Wattignies"]
[Date "1976.??.??"]
[Round "?"]
[White "Kasparov, Gary"]
[Black "Sendur, Adnan"]
[Result "1-0"]
[WhiteElo ""]
[BlackElo ""]
[ECO "B08"]

1.e4 d6 2.d4 Nf6 3.Nc3 g6 4.Nf3 Bg7 5.Be2 Nbd7 6.O-O O-O 7.e5 dxe5 8.dxe5 Ng4
9.e6 Nde5 10.Qxd8 Rxd8 11.Nxe5 Nxe5 12.Nb5 c6 13.Nc7 Rb8 14.f4 Ng4 15.Bxg4 Bd4+
16.Kh1 Bb6 17.f5 Bxc7 18.fxg6 fxg6 19.Bh6 Be5 20.Rad1 Rxd1 21.Rxd1 Bd6 22.Rf1  1-0

[Event "Telechess ol1 7778"]
[Site "telex"]
[Date "1977.??.??"]
[Round "?"]
[White "Kasparov, Gary"]
[Black "West, Guy"]
[Result "1-0"]
[WhiteElo ""]
[BlackElo ""]
[ECO "B40"]

1.e4 c5 2.Nf3 Nf6 3.Nc3 e6 4.d4 cxd4 5.Nxd4 Bb4 6.e5 Nd5 7.Bd2 Nxc3 8.bxc3 Bf8
9.Bd3 d6 10.Qe2 Nd7 11.Nxe6 Qb6 12.Nc7+  1-0

[Event "URS-ch sf"]
[Site "Daugavpils"]
[Date "1978.??.??"]
[Round "?"]
[White "Tseshkovsky, Vitaly"]
[Black "Kasparov, Gary"]
[Result "1/2-1/2"]
[WhiteElo "2570"]
[BlackElo "2200"]
[ECO "B19"]

1.e4 c6 2.d4 d5 3.Nd2 dxe4 4.Nxe4 Bf5 5.Ng3 Bg6 6.h4 h6 7.Nf3 Nd7 8.h5 Bh7
9.Bd3 Bxd3 10.Qxd3 Qc7 11.Rh4 e6 12.Bf4 Qa5+ 13.Bd2 Qc7 14.Bf4 Qa5+  1/2-1/2

[Event "URS-ch sf"]
[Site "Daugavpils"]
[Date "1978.??.??"]
[Round "?"]
[White "Kasparov, Gary"]
[Black "Panchenko, Alexander N"]
[Result "1-0"]
[WhiteElo "2200"]
[BlackElo "2495"]
[ECO "B67"]

1.e4 c5 2.Nf3 Nc6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 d6 6.Bg5 e6 7.Qd2 a6 8.O-O-O Bd7
9.f4 b5 10.Nxc6 Bxc6 11.Bd3 Be7 12.e5 dxe5 13.fxe5 Nd7 14.Bxe7 Qxe7 15.Be4 Bxe4
16.Nxe4 Nxe5 17.Qd4 f6 18.Nd6+ Kf8 19.Rhf1 Kg8 20.g4 h6 21.h4 Nf7 22.Qe4 Rf8
23.Nf5 Qe8 24.Nd4 e5 25.Nf5 h5 26.Rg1 Rh7 27.Qb7 Kh8 28.gxh5 Qe6 29.Nxg7 Qxa2
30.Qe7 Rg8 31.Qxf6 Qa1+ 32.Kd2 Qa5+ 33.Ke2 Rgxg7 34.Rxg7 Rxg7 35.Rg1  1-0

 And the output of the code is:

1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 a6 6.f4 Qc7 7.a4 g6 8.Bd3 Bg7
9.Nf3 Bg4 10.Be3 Nc6 11.O-O O-O 12.Qe1 Bxf3 13.Rxf3 e6 14.Qh4 Qd8 15.Rh3 h5
16.Be2 d5 17.e5 Nd7 18.Qf2 Qe7 19.g4 hxg4 20.Bxg4 Rad8 21.Rd1 f5 22.Bf3 Rf7
23.Kh1 g5 24.Bh5 g4 25.Bxf7+ Qxf7 26.Rg3 Qh5 27.Kg2 Nf8 28.Ne2 Ng6 29.h3 Nh4+
30.Kf1 Kf7 31.Ng1 d4 32.Bc1 gxh3 33.Qe2 Qxe2+ 34.Nxe2 Ng6 35.Rxh3 Bf8 36.Rb3 Rd7
37.Rbd3 Bc5 38.c3 Ba7 39.Be3 Rd5 40.cxd4 Nb4 41.Rb3 a5 42.Bd2

**Comment by niklasf** [comment]
You can call `read_game()` multiple times, possibly looping until you get `None`:

```python
first_game = chess.pgn.read_game(pgn_file)
second_game = chess.pgn.read_game(pgn_file)
```

**Comment by kapilg1997** [comment]
> You can call `read_game()` multiple times, possibly looping until you get `None`:
> 
> ```python
> first_game = chess.pgn.read_game(pgn_file)
> second_game = chess.pgn.read_game(pgn_file)
> ```

Worked. Thanks
