### ISSUE TITLE
Length of board.legal_moves

### ISSUE THREAD

**Issue by Pikamander2** [niklasf/python-chess#789]
What's the proper way to get the number of legal moves that a board state has?

Right now I'm using `sum(1 for move in board.legal_moves)`, but that feels like a hack compared to `len(board.legal_moves)` (which throws a TypeError).

Would it be possible to make `len()` work with LegalMoveGenerator? From what I understand, generators don't automatically allow `len()` because of infinite loop concerns, but in this case there would always be a finite number of board states, so it sounds like it would be possible.

**Comment by niklasf** [comment]
You can use `board.legal_moves.count()`.

(It is intentionally not providing `__len__`, because computing the length is just as slow as generating all moves, and may otherwise be automatically used by various iteration protocols.)
