### ISSUE TITLE
chessengine.close() timeout issue

### ISSUE THREAD

**Issue by WolfgangFahl** [niklasf/python-chess#791]
https://github.com/WolfgangFahl/play-chess-with-a-webcam/commit/a403e80 makes my CI fail on play-chess-with a webcam.
I still have to analyze this but i assume the async-Io handling might need changes on my side.

I used to have
```python
def close(self):
        '''
        close the given engine
        '''
        if self.engine is not None:
            try:
                self.engine.quit()
            except concurrent.futures._base.TimeoutError:
                # so what?
                if self.debug:
                    print ("timeout after %1.f secs for %s on close forcing close now ..." % (self.timeout,self.name))
                self.engine.close()    
                pass
```
what should i do now?

**Comment by niklasf** [comment]
The exception type now is `asyncio.TimeoutError`.

Btw. it's also possible to use the engine as a context manager to ensure it gets killed no matter what. For example, the following script will fail due to an uncaught timeout error, but at least shutdown cleanly.

```python
with chess.engine.SimpleEngine.popen_uci(["/bin/bash", "-c", "sleep 1 && echo uciok && sleep 120"]) as engine:
    engine.quit()
```
