### ISSUE TITLE
Can't parse chessbomb pgns -> mainline_moves() empty

### ISSUE THREAD

**Issue by trhr** [niklasf/python-chess#794]
I'll probably submit a PR for this unless someone gets to it first. Should be a fairly easy fix.

Also, I watch game.errors for errors, and an empty PGN doesn't even throw a warning? Seems like it should.

```
[Site "http://www.chessbomb.com"]
[Event "2021-goldmoney-asian-rapid-knockout"]
[White "Carlsen, Magnus"]
[Black "So, Wesley"]

1. c4 {[%clk 0:15:20]}  e5 {[%clk 0:15:20]} 2. Nc3 {[%clk 0:14:38]}  Nf6 {[%clk 0:15:26]}
```
....and so on

**Comment by trhr** [comment]
An OK workaround...

```
import subprocess, io
e = subprocess.Popen(['/usr/games/pgn-extract'], stdin=open('test.pgn'), stdout=subprocess.PIPE)
e_out = e.stdout.read()
game = chess.pgn.read_game(io.StringIO(str(e_out)))
```

**Comment by niklasf** [comment]
Thanks for reporting. I tried to reproduce the issue, but the PGN snippet you provided works just fine. Can you maybe upload the original file, in case there is some subtlety with encoding or so, that would otherwise be lost?

**Comment by trhr** [comment]
[2021-grand-chess-tour-croatia-rapid-and-blitz_01-Anand_Viswanathan-Van_Foreest_Jorden.txt](https://github.com/niklasf/python-chess/files/6783555/2021-grand-chess-tour-croatia-rapid-and-blitz_01-Anand_Viswanathan-Van_Foreest_Jorden.txt)

**Comment by niklasf** [comment]
It's due to the two empty lines between game headers and moves, which I don't think is valid.

Unfortunately the python-chess parser cannot work around that, because by design it's a line-wise parser without any lookahead.

**Comment by trhr** [comment]
It may be outside the scope of what you're trying to accomplish, but a "pre-cleanup" function could just awk away any nonsense like this whenever its reported.

**Comment by niklasf** [comment]
Do you think there is any hope of Chessbomb fixing their PGNs? That would be much better for everyone.
