### ISSUE TITLE
Broken output from Board.san(move)

### ISSUE THREAD

**Issue by cosmobobak** [niklasf/python-chess#797]
![move_san_broken](https://user-images.githubusercontent.com/56003038/125344023-adeee180-e34e-11eb-8b9e-f17d21890043.jpg)

Small reproducible example - the fen 'rnbqkb1r/pppppppp/5n2/8/8/8/PPPPPPPP/RNBQKBNR b KQkq - 3 2' produces Nxh3 for the move g1h3 when Nh3 should be produced.

**Comment by cosmobobak** [comment]
Whoops! Apologies for this issue being raised - I had missed that the fen makes it Black's turn to move - in this case, I'm not sure what the correct behaviour would be, and I can only assume this behaviour is intentional. Feel free to close this issue.

**Comment by niklasf** [comment]
No worries. Yeah, it's not intentionally like that, but for illegal moves no guarantees are made.
