### ISSUE TITLE
Outcome of the game?

### ISSUE THREAD

**Issue by JernejHenigman** [niklasf/python-chess#803]
Hi,

https://python-chess.readthedocs.io/en/latest/core.html#outcome 

I would like to use winner: Optional[chess.Color]
The winning color or None if drawn.

How can I call this method?

import chess
board = chess.variant.AntichessBoard()

board.outcome() does not seem to be working.

Can anybody help?

Regards
Jernej

**Comment by niklasf** [comment]
Works for me. Note that `board.outcome()` will be `None` if the game is not over.

```python
outcome = board.outcome()
if outcome:
    if outcome.winner == chess.WHITE:
        print("white won")
    elif outcome.winner == chess.BLACK:
        print("black won")
    else:
        print("draw")
else:
    print("game not yet over")
```

**Comment by JernejHenigman** [comment]
`import chess
board = chess.Board()

outcome = board.outcome()
if outcome:
    if outcome.winner == chess.WHITE:
        print("white won")
    elif outcome.winner == chess.BLACK:
        print("black won")
    else:
        print("draw")
else:
    print("game not yet over")`

**Comment by JernejHenigman** [comment]
Thank you for the answer, but the issue remains. I literally copied your code and it seems that it does not work. What could be the isssue?

import chess
board = chess.Board()

outcome = board.outcome()
if outcome:
    if outcome.winner == chess.WHITE:
        print("white won")
    elif outcome.winner == chess.BLACK:
        print("black won")
    else:
        print("draw")
else:
    print("game not yet over")




Traceback (most recent call last):
  File "X", line 170, in <module>
    outcome = board.outcome()
AttributeError: 'Board' object has no attribute 'outcome'
