### ISSUE TITLE
not an issue just a question

### ISSUE THREAD

**Issue by Geronium** [niklasf/python-chess#807]
Hello, 

i used python-chess to generate chess games, i have some chess games and movements, and the corlor of the players who make the movement

S1, S2, S3, S4, S5,S6 ....
W,B,W,B,W,B

when i have a checkmate status (chess.Board.is_checkmate()) , how i can know the color of the winner of the game ? 

i have just to take the color of the last player, is already the loser ? or an other fonction give the color of the winner of the game ? 

Thank you.

**Comment by Geronium** [comment]
I find what i need with result fonction.

Thank you

**Comment by niklasf** [comment]
Yep, that works. Also `board.outcome().winner`.
