### ISSUE TITLE
Legal_moves can't be pushed

### ISSUE THREAD

**Issue by jjoshua2** [niklasf/python-chess#81]
I think this qualifies for the bug bounty, the following causes an exception in the core. Somehow the move c6 is interpreted as the pawn starting from c5 instead c7.

```
import chess
b=chess.Board('r1bqk2r/ppp1bppp/3p1n2/nB2p3/4P3/2PP1N2/PP3PPP/RNBQ1RK1 b kq - 2 7')
for m in b.legal_moves:
  print(m) #3rd move prints c5c6 and crashes on push since there is no piece there
  b.push(m)
  b=chess.Board('r1bqk2r/ppp1bppp/3p1n2/nB2p3/4P3/2PP1N2/PP3PPP/RNBQ1RK1 b kq - 2 7')
```

**Comment by niklasf** [comment]
Thanks, this is an intresting pitfall. (There's probably no bug in move generation, here, though.)

In Python the for-head is evaluated once to get an iterator. And then that same iterator is used for all iterations. That means resetting b by assigning to it does not change what you are iterating over. Changing b by modifying it *does* have effects. This equivalent code might clarify what is happening:

```
import chess                                                                    
                                                                                
b = chess.Board('r1bqk2r/ppp1bppp/3p1n2/nB2p3/4P3/2PP1N2/PP3PPP/RNBQ1RK1 b kq - 2 7')
                                                                                
old_legal_moves_iterator = iter(b.legal_moves)                                  
                                                                                
for m in old_legal_moves_iterator:                                              
    print(m) #3rd move prints c5c6 and crashes on push since there is no piece there
    b.push(m)                                                                   
    b = chess.Board('r1bqk2r/ppp1bppp/3p1n2/nB2p3/4P3/2PP1N2/PP3PPP/RNBQ1RK1 b kq - 2 7')
```

Or as an analogy:
```
b = [1, 2, 3]                                                                   
                                                                                
for m in b:                                                                     
    print(m)                                                                    
    b.clear()                                                                   
    b = [1, 2, 3]
```
This does not print 1 2 3.

Recommended solution: Use `b.pop()` to undo a push when iterating. This works because it changes the actual contents of b, instead of assigning something new to the reference.

```
for m in old_legal_moves_iterator:                                              
    print(m)
    b.push(m)
    b.pop()
```

**Comment by jjoshua2** [comment]
I tried this on thousands of other positions and it worked fine. I tested the pop method and it seemed to work for this position. However, there is still something fishy with this position. If I do b.pseudo_legal_moves I get <PeusdoLegalMoveGenerator at 0x75ec50 (a5b3, a5c4, Nc6, f6e4, f6g4, f6d5, f6h5, Nd7, f6g8, e7f8, a8b8, c8h3, c8g4, c8f5, c8e6, Bd7, Qd7, e8d7, Kf8, h8f8, h8g8, d6d5, a7a6, b7b6, c6, g7g6, h7h6, c7c5, g7g5, h7h5)>
See how that troublesome c6 is not fully complete to say where it is coming from like all the other pawn moves? c6 is a valid move, but only if it comes from c7 and not c5.

**Comment by niklasf** [comment]
My guess is that there would still would have been problems with most of the other positions, maybe just not lucky enough to actually trigger an exception.

The human readable repr of pseudo_legal_move generator shows SANs for completely legal moves and UCI notation for pseudo legal moves. For example Qd7 would be legal, and is therefore also not displayed in its full UCI form (d8d7).

The move object is ok, though:

```
In [1]: import chess

In [2]: b = chess.Board("r1bqk2r/ppp1bppp/3p1n2/nB2p3/4P3/2PP1N2/PP3PPP/RNBQ1RK1 b kq - 2 7")

In [3]: b.pseudo_legal_moves
Out[3]: <PeusdoLegalMoveGenerator at 0x7f19fc4ce320 (a5b3, a5c4, Nc6, f6e4, f6g4, f6d5, f6h5, Nd7, f6g8, e7f8, a8b8, c8h3, c8g4, c8f5, c8e6, Bd7, Qd7, e8d7, Kf8, h8f8, h8g8, d6d5, a7a6, b7b6, c6, g7g6, h7h6, c7c5, g7g5, h7h5)>

In [4]: list(b.pseudo_legal_moves)
Out[4]: 
[Move.from_uci('a5b3'),
 Move.from_uci('a5c4'),
 Move.from_uci('a5c6'),
 Move.from_uci('f6e4'),
 Move.from_uci('f6g4'),
 Move.from_uci('f6d5'),
 Move.from_uci('f6h5'),
 Move.from_uci('f6d7'),
 Move.from_uci('f6g8'),
 Move.from_uci('e7f8'),
 Move.from_uci('a8b8'),
 Move.from_uci('c8h3'),
 Move.from_uci('c8g4'),
 Move.from_uci('c8f5'),
 Move.from_uci('c8e6'),
 Move.from_uci('c8d7'),
 Move.from_uci('d8d7'),
 Move.from_uci('e8d7'),
 Move.from_uci('e8f8'),
 Move.from_uci('h8f8'),
 Move.from_uci('h8g8'),
 Move.from_uci('d6d5'),
 Move.from_uci('a7a6'),
 Move.from_uci('b7b6'),
 Move.from_uci('c7c6'), # <--
 Move.from_uci('g7g6'),
 Move.from_uci('h7h6'),
 Move.from_uci('c7c5'),
 Move.from_uci('g7g5'),
 Move.from_uci('h7h5')]
```

**Comment by niklasf** [comment]
Anyway ... closing this now, since I am pretty confident there's nothing wrong with the given position. But feel free to reopen or open another issue (preferably with another concrete code snippet).
