### ISSUE TITLE
Is it possible to convert the chess.board to PGN?

### ISSUE THREAD

**Issue by pavolkacej** [niklasf/python-chess#811]
I have read the documentation about parsing pgn available here https://python-chess.readthedocs.io/en/latest/pgn.html
I find it useful, but I want to ask if there is a way to convert all info from my chess.board to PGN at once.
I have to do for example something like:

```
moves = my_board.move_stack
game = chess.pgn.Game()
node = game.add_variation(chess.Move.from_uci("e2e4"))
for m in moves:
     node = node.add_variation(m)
```

Another logical continuation is that I have to do something like:
`game.headers["Date"] = date.today()`
     
Also `game.headers["Result"] `could be somehow easily obtained from board - as the board has info about the result 

etc. etc.
Are there already such things implemented (that will convert my whole board to PGN), or do I have to do this step by step myself?
Thanks

**Comment by niklasf** [comment]
The following shortcut exists:

```python
game = chess.pgn.Game.from_board(my_board)
```

The result tag is set, but of course a real game might have things like resignation, which can not be inferred from the position.

Meta-data like `Date` is *not* set.

**Comment by pavolkacej** [comment]
That's that I was looking for! Thanks @niklasf for sharing this!
