### ISSUE TITLE
Pop moves from the board

### ISSUE THREAD

**Issue by adriaarbat** [niklasf/python-chess#812]
Hi, I've been getting an error while undo moves, in one case I did e4 and I wanted to undo that move using the function undo, and I get a move that wasn't e4, and this makes errors on my code, is there any function to undo moves (peek function works properly it returns the move correctly, so the error isn't that I didn't push the move).

Thanks in advance.

Adrià

**Comment by niklasf** [comment]
Hi, can you please show some example code where this happens? It is definitely supposed to work, and I [don't see why it wouldn't](https://github.com/niklasf/python-chess/blob/52dbcf05930e7580c3c489e71e7f51d74646eb28/chess/__init__.py#L2261-L2277).
