### ISSUE TITLE
How to run stockfish with python-chess on mac OS?

### ISSUE THREAD

**Issue by JernejHenigman** [niklasf/python-chess#817]
My code for running stockfish with python-chess on Windows is:
`engine = chess.engine.SimpleEngine.popen_uci("fairy-stockfish-largeboard_x86-64.exe")
`
which works fine!

Then I want to run same command on mac os with stockfish version suitable for max os of course

`engine = chess.engine.SimpleEngine.popen_uci("fairy-stockfish-largeboard_x86-64")
`
I get the following error : [Errno 8] Exec format error: 'fairy-stockfish-largeboard_x86-64'

How to run stockfish with python-chess on mac OS then?

Tried adding `#!/usr/bin/env python` at the begining of file, but it does not help

**Comment by niklasf** [comment]
python-chess is compatible with mac OS, but you also need to download or build an engine that is compatible. Very likely the `fairy-stockfish-largeboard_x86-64` you got is a Linux binary.

**Comment by JernejHenigman** [comment]
Thank you. We can close the issue.
