### ISSUE TITLE
override chess.uci

### ISSUE THREAD

**Issue by lucasart** [niklasf/python-chess#82]
Is it possible to read/write lines of text from/to the engine directly, when you're using chess.uci ?
Or do I need to avoid chess.uci completely and do everything myself with subprocess.Popen and friends ?

**Comment by niklasf** [comment]
It's possible. Example:

```
import chess
import chess.uci

class MyEngine(chess.uci.Engine):
    def send_line(self, line):
        print("sending to engine:", line)
        super(MyEngine, self).send_line(line)

    def on_line_received(self, buf):
        # Careful: This can be called from a different thread
        print("received from engine:", buf)
        super(MyEngine, self).on_line_received(buf)

engine = chess.uci.popen_engine("stockfish", engine_cls=MyEngine)
print(engine.go(movetime=1000))
```

If you want to do something general enough, we can also think about building it in to core.

**Comment by lucasart** [comment]
Thanks

**Comment by lucasart** [comment]
@niklasf: I'm starting a Python rewrite of cutechess-cli, if you're interested. [https://github.com/lucasart/zinc/](url). I would love to have some feedback on it, if you're curious to try it out.

**Comment by niklasf** [comment]
Cool. I'll keep an eye on it.
