### ISSUE TITLE
Add 'spin board' transform

### ISSUE THREAD

**Issue by Lou-E-303** [niklasf/python-chess#821]
Hi!

Loving the library so far - super simple and intuitive.

I have however been very confused by the (as far as I can see) lack of implementation of a simple 'flip board' function _as you would expect such a function to behave_. On Lichess, Chess24 and The Other One, 'flip board' means to literally spin the board 180 degrees, the move stack still makes sense for the new orientation, and the colours are preseved. Neither `transform(flip_vertically) `or `mirror()` seems to achieve this.

I therefore propose a simple new transform be added, which does something akin to the following:

![image](https://user-images.githubusercontent.com/75304578/140626283-82c3368d-2619-41d8-aa46-302f9660958e.png)

We flip diagonally, then anti-diagonally. The board appears exactly as it would if I had stood up, walked to the other side and sat down again, and all text move inputs work exactly as you would expect. This is for ASCII output, if that helps to clarify things. An example of the correct behaviour:

![image](https://user-images.githubusercontent.com/75304578/140626358-911fb3d6-26f0-479e-9eb2-81ddc457847c.png)

With the other two options (flip vertically and mirror), this behaviour was not achievable. 

Of course, it's entirely possible that this functionality exists or is much easier to do than I'm making it, and I know my solution _is_ quite simple, but as a newcomer to the library I spent a good hour trying to figure this out and it would be nice to just have all of that abstracted away by a simple transform.

Thanks!

**Comment by hasnul** [comment]
The `transform()` and `mirror()` methods return copies of the board modified by their transformation functions. If you just want to display the state of the board from a specific point of view or orientation, the transformations are probably not what you want; the game model is changed. I don't think `print()`-ing the board has option to change the orientation. The SVG rendering module, however, has an optional parameter for orientation when displaying boards. Personally, I only use the textual representation for debugging and the lack of orientation is not a difficulty.

**Comment by Lou-E-303** [comment]
Okay, I'll look into replacing the text output with SVG. Is there an example of a simple implementation of this?
