### ISSUE TITLE
[question] Function chess.pgn.read_game

### ISSUE THREAD

**Issue by OlivierLuG** [niklasf/python-chess#822]
I'm working on a project that download pgn from api. I'm then getting pgn games as text objects (`str`). I do not want to write them as a file.
Is there a way to convert a `str` to a `chess.pgn.Game` object ?

**Comment by niklasf** [comment]
Hi, yes. You can use `io.StringIO`. https://python-chess.readthedocs.io/en/latest/pgn.html#parsing has an example.
