### ISSUE TITLE
is_fifty_moves() is not documented

### ISSUE THREAD

**Issue by pavolkacej** [niklasf/python-chess#824]
I just found a method that fits my needs - unlike `can_claim_fifty_moves()`, this checks 100 halfmoves.
But I had to find it in code, documentation did not help. Are you planning to add `is_fifty_moves()` to the docs?

Thank you

**Comment by niklasf** [comment]
Thanks. Makes sense to at least mention it in the docs. Doing so, now.

**Comment by pavolkacej** [comment]
Thank you for swift reaction. It feels good that the library is actively supported, unlike other ones, where person need to wait for multiple months for answer. Thanks again!
