### ISSUE TITLE
After vertical flip, pawns still move the same way

### ISSUE THREAD

**Issue by pavolkacej** [niklasf/python-chess#826]
If I run following code:

```
chess_squares = chess.Board()
chess_squares.apply_transform(chess.flip_vertical)
```

The board gets transformed correctly, but black pawns are still moving down, and white pawns up:

![image](https://user-images.githubusercontent.com/75344937/144934346-3c8525ca-3a0c-409a-868e-0c8f1396b4bc.png)
![image](https://user-images.githubusercontent.com/75344937/144934393-e6be5216-dad0-4fe6-bf9a-0e5906d6d542.png)

Is this as expected? Is there a way to do the vertical flip, but also flip the way pawns move? I just basically want to keep the same behavior, but visually the pieces are swapped.

**Comment by pavolkacej** [comment]
Basically I want to have exactly same position (castling rights included), but every white piece is black, and every black piece is white

**Comment by pavolkacej** [comment]
I can obtain the expected transformation using this code. However, direction of pawns is wrong, and move_stack gets cleared:
```
chess_squares = chess.Board()
chess_squares.apply_transform(chess.flip_vertical)
chess_squares.apply_mirror()
```
Do you think it is worth adding a method that will do this transform, with correct pawn direction?

**Comment by niklasf** [comment]
Hi, do you really want to change the position (in the abstract sense), or the presentation of the board? If the latter, you can use:

```python
import chess
import chess.svg

chess.svg.board(board, orientation=chess.BLACK)
```

**Comment by pavolkacej** [comment]
Hi @niklasf 
Thank you for suggestion. However, I need the first thing you mentioned. Is it possible to add this, or just obtain it using existing functionality?

**Comment by niklasf** [comment]
Reading everything again, what you're asking does not appear to be possible (with this library). Pawns do not intrinsically have a direction, only a color. And abstractly, white pawns always move up the ranks, black pawns always move down the ranks.

**Comment by pavolkacej** [comment]
I will try to workaround this in my code somehow. Thanks for answer anyway!
