### ISSUE TITLE
How to use older version ? (on Linux)

### ISSUE THREAD

**Issue by tissatussa** [niklasf/python-chess#827]
I discovered that several "EPD test suites" exist to test the strength (rating) of a chess engine by feeding them several test positions with a known Best Move (bm). however, i'm on Linux and i find that most programs / scripts to run such test are for Windows .. i'm on Xubuntu 20.04

Then i found a nice simple Python script, called "analyze.py" by Jon Dart (author of the Arasan engine) at http://talkchess.com/forum3/viewtopic.php?t=58712&start=20 (i want to use the Python 3 version) but it needs an older version of your python "chess" module : according to this talkchess post, i need version 0.25.1 because it uses "chess.uci", which was later removed (see also #415 ). So i downloaded that package from your release pages, but now i'm stuck : how to install / use it BESIDES my current version ?

To solve this, i found https://www.marsja.se/pip-install-specific-version-of-python-package/ which tells it's best to run analyze.py with 'virtualenv' and how. Indeed, a Python virtual environment makes it possible to safely install modules (by pip), also older versions, but i get an error :

```
$ pip install chess==0.25.1
ERROR: Could not find a version that satisfies the requirement chess==0.25.1 (from versions: 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.5.0, 1.6.0, 1.6.1, 1.7.0)
ERROR: No matching distribution found for chess==0.25.1
```

So, i guess v0.25.1 must be installed by hand. The package v0.25.1 comes with a setup.py and release.py but it's unclear to me how to use it .. i tried this (in the virtual env) but at the end i get an error :

```
$ python ./release.py 
--- CHECK DOCS ---------------------------------------------------
python3 setup.py --long-description | rst2html --strict --no-raw > /dev/null
--- TEST ---------------------------------------------------------
tox --skip-missing-interpreters
GLOB sdist-make: /home/tissatussa/Apps/EPD_TEST_PY/python-chess-0.25.1/setup.py
py34 create: /home/tissatussa/Apps/EPD_TEST_PY/python-chess-0.25.1/.tox/py34
SKIPPED: InterpreterNotFound: python3.4
py35 create: /home/tissatussa/Apps/EPD_TEST_PY/python-chess-0.25.1/.tox/py35
SKIPPED: InterpreterNotFound: python3.5
py36 create: /home/tissatussa/Apps/EPD_TEST_PY/python-chess-0.25.1/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py37 create: /home/tissatussa/Apps/EPD_TEST_PY/python-chess-0.25.1/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
pypy3 inst-nodeps: /home/tissatussa/Apps/EPD_TEST_PY/python-chess-0.25.1/.tox/.tmp/package/1/python-chess-0.25.1.zip
pypy3 installed: cffi==1.14.0,greenlet==0.4.13,python-chess @ file:///home/tissatussa/Apps/EPD_TEST_PY/python-chess-0.25.1/.tox/.tmp/package/1/python-chess-0.25.1.zip,readline==6.2.4.1
pypy3 run-test-pre: PYTHONHASHSEED='4192560519'
pypy3 run-test: commands[0] | python test.py --verbose
test_atomic_capture (__main__.AtomicTestCase) ... ok
test_atomic_castle_with_kings_touching (__main__.AtomicTestCase) ... ok
test_atomic_en_passant (__main__.AtomicTestCase) ... ok

[..long list..]

test_engine_offer_draw_during_human_turn (__main__.XboardEngineTestCase) ... ok
test_human_offer_draw_during_engine_search (__main__.XboardEngineTestCase) ... ok
test_human_offer_draw_during_human_turn (__main__.XboardEngineTestCase) ... ok
test_options (__main__.XboardEngineTestCase) ... ok
test_resign_during_engine_turn (__main__.XboardEngineTestCase) ... ok
test_resign_during_human_turn (__main__.XboardEngineTestCase) ... ok

======================================================================
FAIL: test_sf_analysis (__main__.EngineTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 57, in _wrapper
    return f(self)
  File "test.py", line 3266, in test_sf_analysis
    self.assertEqual(analysis.info["score"].relative, chess.engine.Mate(+3))
AssertionError: Mate(+2) != Mate(+3)

----------------------------------------------------------------------
Ran 272 tests in 8.942s

FAILED (failures=1, skipped=15)
ERROR: InvocationError for command /home/tissatussa/Apps/EPD_TEST_PY/python-chess-0.25.1/.tox/pypy3/bin/python test.py --verbose (exited with code 1)
___________________________________________________________________________________________________________________________________ summary ____________________________________________________________________________________________________________________________________
SKIPPED:  py34: InterpreterNotFound: python3.4
SKIPPED:  py35: InterpreterNotFound: python3.5
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
ERROR:   pypy3: commands failed

```

Btw. i had to install 'tox' by pip, and also 'rst2html' for Ubuntu (see eg. https://manpages.ubuntu.com/manpages/focal/man1/rst2html.1.html ) because it seems setup.py is piping its output to rst2html :

`python3 setup.py --long-description | rst2html --strict --no-raw > /dev/null`

Note: i think this 'rst2html' is NOT rst2html.py, as found in the docutils module (it has /tools/rst2html.py), which was confusing ..

Am i on the right track ?
What's wrong ?

---

BTW. to run EPD test suites i also found these tools :

- Arena -- can do it, but users mention it's buggy when running EPD test suites.
- SAN KIT - Collection of C Source Code to aid in chess programming ( https://sourceforge.net/projects/sankit/ )
- EPD2WB -- compiling it fails because the C-code is typical Windows (i read newer versions can also do UCI)
- Polyglot -- i found the source package and probably i can compile it, but did not try yet (but isn't Polyglot for creating opening books ?)
- ChessGUI -- only for Windows
- [...]

**Comment by niklasf** [comment]
Back then the package was still called `python-chess` on PyPI. Any luck with something like
`pip install python-chess==0.25.1`?

**Comment by tissatussa** [comment]
that did the trick !
and i understand the version mechanism now.
thanks !

**Comment by tissatussa** [comment]
Regarding software to run EPD test suites.

Recently i found another nice Rust (!) script that can feed a list of test positions to one engine to solve all. The input format is a .epd file with 'bm' info (=Best Move solution) - no 'am' info allowed though (Avoid Move).

See https://github.com/cosmobobak/uci-suite

It consists only of 1 Rust file (.rs) which i managed to alter : this way i set custom time-per-puzzle-position (ms) and the epd-file, and that's all i want. A custom engine (UCI only) is set by a parameters of the binary. Although simple, compiling this script went flawless and it works well on my Linux. Its output is colorized and simple but complete for me - example terminal output 
[uci-suite-output.pdf](https://github.com/niklasf/python-chess/files/13222143/uci-suite-output.pdf)
