### ISSUE TITLE
suppress output ?

### ISSUE THREAD

**Issue by tissatussa** [niklasf/python-chess#828]
In my Python script, using your newest python-chess module, i get an "Unexpected engine output" in this code piece :

```
engine = chess.engine.SimpleEngine.popen_uci(Goptions.engine)

with engine.analysis(
	board   = Gposition.board,
	limit   = chess.engine.Limit(time=Goptions.time),
	multipv = Goptions.multipv
) as analysis:

	# at this point the message "<UciProtocol (pid=75444)>: Unexpected engine output: 'readyok'"
	# is output to terminal, but no print command is given in the script .. 

	for info in analysis:
		process_info(info)
```

The script does not crash, it continues after the output of "<UciProtocol (pid=75444)>".

The PeSTO engine 'suffers' from this - until now i discovered no other engines with this 'behaviour' - so it's no big problem but i like to solve it.

How can i suppress the output of my code part ?
Can i add an option / parameter to engine.analysis() ?
Or can Python suppress output - temporarily, only in a code part ?

**Comment by tissatussa** [comment]
At https://stackoverflow.com/questions/2125702/how-to-suppress-console-output-in-python i found a simple solution to temporarily suppress Python output. Now my code part looks like this :

# disable output
sys.stdout = open(os.devnull, "w")
sys.stderr = open(os.devnull, "w")

with engine.analysis(
	board   = Gposition.board,
	limit   = chess.engine.Limit(time=Goptions.time),
	multipv = Goptions.multipv
) as analysis:
	for info in analysis:
		process_info(info)

# enable output again
sys.stdout = sys.__stdout__
sys.stderr = sys.__stderr__

I should have known this general Python functionality, but i never needed it ..

**Comment by niklasf** [comment]
The library uses the `logging` module, so you can control the output more elegantly in that way. The messages have different levels of severity, for example this would exclude such a warning and only show errors:

```python
import logging

logging.getLogger("chess.engine").setLevel(logging.ERROR)
```

There's also [many other options](https://docs.python.org/3/library/logging.html), like logging to a file instead.

That said, of course the real solution would be reporting a bug to the engine author, if it truly sends a stray `readyok`. The logs are definitely useful in many cases, so don't forget to turn it back on when debugging any problems.
