### ISSUE TITLE
detect engine is UCI ?

### ISSUE THREAD

**Issue by tissatussa** [niklasf/python-chess#831]
I'm using `chess.engine.SimpleEngine.popen_uci()` to open an engine.
How can i detect if the loaded engine can do the UCI protocol ?
At this moment i just use some try-except code to catch a crashed binary ..

**Comment by niklasf** [comment]
There's no other way than to try it, which can have arbitrary effects if the binary does something else.

```python
import asyncio
import chess.engine

try:
    engine = chess.engine.SimpleEngine.popen_uci("/bin/bash", timeout=2)
    engine.timeout = 10  # Allow more time for following operations
except asyncio.TimeoutError:
    print("unlikely to be uci")
```

**Comment by tissatussa** [comment]
perfect !
this works !
