### ISSUE TITLE
clear hash ?

### ISSUE THREAD

**Issue by tissatussa** [niklasf/python-chess#832]
when an engine plays several games in a row, or 'solves' the same EPD chess position with several configurations (but eg. with a different `go movetime`), can its cache be emptied ?  Also for engines which lack the ClearHash option ?  Or is this auto, so not needed ?  In my case i want the engine to be 'fair' : it should have the same status before start, no 'history data' by caching.

**Comment by niklasf** [comment]
You can use the `engine.play(..., game=...)` or `engine.analyse(..., game=...)` to do this.

> An arbitrary object that identifies the game. Will automatically inform the engine if the object is not equal to the previous game (e.g., `ucinewgame`, `new`).

Since `object() != object()`, using `game=object()` will always clear the hash before each new search.
