### ISSUE TITLE
how to code engine.analysis parameters ?

### ISSUE THREAD

**Issue by tissatussa** [niklasf/python-chess#833]
i use this construct to get the analysis info :

```
with engine.analysis(
	info    = chess.engine.INFO_ALL,
	limit   = chess.engine.Limit(time=10),
	multipv = 3,
	board   = myboard
) as analysis:
	for dInfo in analysis:
		[..some code..]
```

this works, but i have questions :

Is it possible to set these parameters 'info', 'limit'. 'multipv' and 'board' by `engine.configure()` ?
I guess not .. how are they different ?
'multipv' can also be set with `engine.configure()` !

what does `INFO_ALL` do ? Is it needed ? What is the default of the 'info' parameter ?

i find the doc https://python-chess.readthedocs.io/en/v1.7.0/engine.html?highlight=engine.analysis#id1 : is says analysis() "accepts a dictionary of options" .. but it's not clear to me how to code this options parameter .. can you give an example with proper syntax, also for multi options ? 

```
with engine.analysis(
	options = ??
) as analysis:
	[..]
```

**Comment by niklasf** [comment]
Some details about options can be found in this section: https://python-chess.readthedocs.io/en/latest/engine.html#options

There's a distinction between options that are just passed verbatim to the engine, and options that influence what this library does. `engine.configure(...)` and `engine.analysis(..., options=...)` can be used exclusively for the former.

An example with multiple options would be `engine.configure({"UCI_LimitStrength": True, "UCI_Elo": 1600})` or equivalently `engine.analysis(..., options={"UCI_LimitStrength": True, "UCI_Elo": 1600})`.

Parameters for the library itself, like `multipv` and `info` have to be passed on each call. You can find their meaning, accepted types and default values [in the documentation](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.Protocol.analysis).
