### ISSUE TITLE
Elapsed Move Time in the pgn file

### ISSUE THREAD

**Issue by aipv** [niklasf/python-chess#836]
Hello guys, great library!

I am working on the pgn files generated from electrical boards, there are ``[%emt ...]`` annotations (Elapsed Move Time) in the pgn files, they are quite useful as they show the elapsed time that the players used for the commented move. However, currently it cannot be read from the GameNode directly.

Do you think it makes sense to introduce emt() and set_emt() functions in the GameNode? similar like the clock() function and set_clock() function for the ``[%clk ...]`` annotations?  Thank you very much!

**Comment by niklasf** [comment]
Yes, indeed, this would be nice to have.

**Comment by niklasf** [comment]
Added via #837.

**Comment by niklasf** [comment]
Included in v1.8.0.
