### ISSUE TITLE
board.set_epd() : ValueError meaning ?

### ISSUE THREAD

**Issue by tissatussa** [niklasf/python-chess#839]
the definition of chess.board.set_epd(..) at https://python-chess.readthedocs.io/en/v1.7.0/core.html?highlight=set_epd#chess.Board.set_epd reads :

_raises a `ValueError` if the EPD string is invalid_

and indeed :

```
try:
  myboard.set_epd(line)
except ValueError:
  print(str(ValueError))
```

shows `<class 'ValueError'>` .. but where can i find the possible Values and their meaning ?  I compare it to error codes .. i guess `set_epd()` can fail due to several causes .. or does `ValueError` mean the EPD line was 'just' invalid ?

**Comment by niklasf** [comment]
In your code `ValueError` is the class, not the exception that was raised. The syntax to refer to the exception is:

```python
try:
   myboard.set_epd(line)
except ValueError as err:
    print(err)
```
