### ISSUE TITLE
PGN wrapping

### ISSUE THREAD

**Issue by lucasart** [niklasf/python-chess#84]
I'm trying to write a PGN, using line wrapping.

First I build a `chess.pgn.Game` object:
```
game = chess.pgn.Game.from_board(board)
```
Then I write it to a file to a file:
```
print(game, file=f, end='\n\n')
```
All good, except that the game is on a single line, and I would like to use 80 columns wrapping for example.

I tried:
```
print(textwrap.fill(game), file=f, end='\n\n')
```
but it failed, with the error message that game is not an `str` object.

what's the best way to do this ?

**Comment by niklasf** [comment]
Try this: https://python-chess.readthedocs.io/en/latest/pgn.html#chess.pgn.StringExporter

You can use the *columns* argument of `chess.pgn.StringExporter`.

**Comment by lucasart** [comment]
Thanks. Problem solved.

I found the API a bit strange though. Shouldn't StringExporter be a function instead of a class ? I mean, creating an exporter, then doing a `game.accept(exporter)` is really weird. Instead a simple function like `string_export(Game, ...)` would be more natural.
