### ISSUE TITLE
how to set 'ucinewgame' ?

### ISSUE THREAD

**Issue by tissatussa** [niklasf/python-chess#844]
in the (unofficial) UCI definition i read :

_ucinewgame
this is sent to the engine when the next search (started with "position" and "go") will be from
a different game. This can be a new game the engine should play or a new game it should analyse but
also the next position from a testsuite with positions only._

with your python-chess module i wrote a script to let an UCI engine analyse several testsuite positions.
it works with most engines, but not all : while trying to solve that issue, i stumbled upon the '`ucinewgame`' command, which is normally given at start, but my script doesn't use it yet .. here's a simplified version : 

```
myEngine = chess.engine.SimpleEngine.popen_uci( params, timeout=2 )
myEngine.timeout = 10  # allow more time for following operations; non-UCI engines will hang ..

dConfig = {}

# set some UCI options : 
dConfig.update( { 'Use MCTS': True } )
dConfig.update( { ... } )

myEngine.configure(dConfig)

with myEngine.analysis(
	game    = object(),  # clear cache
	info    = chess.engine.INFO_ALL,
	limit   = chess.engine.Limit(time=30),
	multipv = 3,
	board   = myBoard
) as myAnalysis:

	for dAna in myAnalysis:
		...

```

is '`ucinewgame`' set automatically ?
if not, how can i add '`ucinewgame`' to my script ?
at https://python-chess.readthedocs.io/en/v1.7.0/engine.html?highlight=engine.analysis#id1 i read about the '`game`' parameter :

_game – Optional. An arbitrary object that identifies the game. Will automatically inform the engine if the object is not equal to the previous game (eg. ucinewgame, new)._

at this moment my script has `game = object()` to clear the cache ..
so, how to (also) add '`ucinewgame`' ?  And which syntax should it be ?  `game = chess.engine.ucinewgame`  ?

**Comment by tissatussa** [comment]
Note: you gave some info about such settings at #832 and #833 .. maybe i should clear the cache by dConfig.update( { 'Clear Hash': True } ) ?

**Comment by niklasf** [comment]
The library should already send `ucinewgame` before the first analysis, and `game=object()` should already trigger `ucinewgame` between each analysis. You can verify this by viewing the [debug log](https://python-chess.readthedocs.io/en/latest/engine.html#logging).
