### ISSUE TITLE
Add chess.Board.defenders

### ISSUE THREAD

**Issue by kdave** [niklasf/python-chess#851]
As a counterpart to `attackers()`, I've implemented a naïve "find all defenders of a piece" method, it's useful to do analysis and visualization:

```
def find_defenders(board, square):
    piece = board.piece_at(square)
    color = piece.color
    d = []
    for sq in chess.SQUARES:
        sqpiece = board.piece_at(sq)
        if not sqpiece or sq == square:
            continue
        if sqpiece.color != color:
            continue
        attacks = board.attacks(sq)
        if square in attacks:
            d.append(sq)
    return d
```

Example game: `1. e4 d5 2. exd5 Qxd5`, defenders of d2 pawn are squares 1, 2, 3, 4, pieces N b1, B c1, Q d1, K e1. Implementation is perhaps slow but works. The attackers() uses bitboards, same can be done here but I'm not much familiar with that. Please let me know if you're ok with the above, I'll send a PR. It can be optimized later as it's not be a heavily used function.

**Comment by niklasf** [comment]
This would basically just be [`board.attackers(defender_color, square)`](https://python-chess.readthedocs.io/en/latest/core.html#chess.BaseBoard.attackers). That's because defending and attacking a square is semantically the same, and `attackers` is the counterpart to `attacks`.
