### ISSUE TITLE
Nags property in chess.Move

### ISSUE THREAD

**Issue by icannos** [niklasf/python-chess#853]
Hi,

I would like to be able to call Board.variation_san(moves) to get the string notation of a variation but with the nags in it. For now I do not see any easy way to achieve this. I was thinking we could put the `nags : Set[int]` inside the chess.Move class instead of in a GameNode.  This way it would be easy to update the code of Board.variation_san to display them.

Is there another way achieve this without changing anything ? If not would you see any problems if I submit a PR with theseupdates ?

**Comment by niklasf** [comment]
Hi, `chess.Move` is supposed to be the minimal information that specifies a move, so I don't like adding extra properties.

You could build a `chess.pgn.Game` without headers:

```python
import chess.pgn

root = node = chess.pgn.Game.without_tag_roster()
node = node.add_variation(chess.Move.from_uci("d2d5"))
node.nags.add(chess.pgn.NAG_GOOD_MOVE)
node = node.add_variation(chess.Move.from_uci("h7h5"))

print(root)  # 1. d5 $1 h5 *
```
