### ISSUE TITLE
[%eval ] in PGN records always from white's perspective

### ISSUE THREAD

**Issue by MarkZH** [niklasf/python-chess#856]
Is it intended behavior that the scores written to PGN files as `[%eval ]` comments should always be from white's perspective? For example:

```python
import chess
import chess.pgn
import chess.engine
game_record = chess.pgn.Game()
node = game_record.game()
node = node.add_main_variation(chess.Move.from_uci('e2e4'))
node = node.add_main_variation(chess.Move.from_uci('e7e5'))
pv_node = node.parent.add_line([chess.Move.from_uci('e7e5'), chess.Move.from_uci('d2d4')])
pv_node.set_eval(chess.engine.PovScore(chess.engine.Cp(100), chess.BLACK), 2)
print(game_record)
```
results in
```
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]

1. e4 e5 ( 1... e5 2. d4 { [%eval -1.00,2] } ) *
```
I would expect the printed scores to be from the perspective of the player on move at the nearest mainline. In -chess/engines.py on line 431
https://github.com/niklasf/python-chess/blob/ad279165c78ec46ecc9a4d03004ce20b61f41ecf/chess/pgn.py#L431 the `white()` score is used to create the `[%eval ]` comment. Should the `score.relative.score()` score be used instead?

**Comment by niklasf** [comment]
I believe this is working as intended. I can't find a specification for `%eval`, but at least the PGNs I can find (including PGNs from Lichess) have evaluations always from White's point of view.

**Comment by MarkZH** [comment]
Thanks for the answer. I'll make a note of the score perspective in the PR linked above.
