### ISSUE TITLE
strange moves

### ISSUE THREAD

**Issue by Noob-A** [niklasf/python-chess#859]
```python
board = chess.Board(fen)
print("FEN BEFORE: "+fen)
print("BOARD BEFORE: \n"+str(board))
best_move = engine.play(board, chess.engine.Limit(time=3))
board.push(best_move.move)
print("BOARD AFTER: \n" + str(board))
```
results in this strange move:
```
FEN BEFORE: RNBKQBNR/PPP3PP/8/3PPP2/8/n4n2/pppppppp/r1bkqb1r b - - 0 1

BOARD BEFORE: 

R N B K Q B N R
P P P . . . P P
. . . . . . . .
. . . P P P . .
. . . . . . . .
n . . . . n . .
p p p p p p p p
r . b k q b . r

BOARD AFTER: 

R N B K Q B N R
P P P . . . P P
. . . . . . . .
. . . P P P . .
. . . . . . . .
n . . . . n . .
p p p p p p . p
r . b k q b q r
```
two queens?

**Comment by niklasf** [comment]
Yes. Note that you set up the board such that all black pawns are one step from promotion:

![](https://backscattering.de/web-boardimage/board.svg?fen=RNBKQBNR/PPP3PP/8/3PPP2/8/n4n2/pppppp1p/r1bkqbqr%20w%20-%20-%200%202&lastMove=g2g1q)

**Comment by Noob-A** [comment]
i think engine is having a problem with understanding sides

**Comment by niklasf** [comment]
This is not about the engine, it's about the FEN that you provided. Carefully check the image above. Note that white is moving up and black is moving down.

**Comment by Noob-A** [comment]
where do you render it?

**Comment by niklasf** [comment]
I am using https://github.com/niklasf/web-boardimage.

**Comment by Noob-A** [comment]
i reversed fen, and got this: r1bqkb1r/pppppppp/2n4n/8/2PPP3/8/PP3PPP/RNBQKBNR b KQkq - 0 1
```
FEN BEFORE: r1bqkb1r/pppppppp/2n4n/8/2PPP3/8/PP3PPP/RNBQKBNR b KQkq - 0 1
BOARD BEFORE: 

r . b q k b . r
p p p p p p p p
. . n . . . . n
. . . . . . . .
. . P P P . . .
. . . . . . . .
P P . . . P P P
R N B Q K B N R

BOARD AFTER: 

r . b q k b . r
p p p p . p p p
. . n . . . . n
. . . . p . . .
. . P P P . . .
. . . . . . . .
P P . . . P P P
R N B Q K B N R
```
it is correct, but now white is at the bottom
d4e5 is not a correct move:
![image](https://user-images.githubusercontent.com/59875489/156345352-d64ef903-1b76-44e1-a1cc-8ba76aa6dabf.png)

**Comment by niklasf** [comment]
There should be a way to flip the board in the viewer (often keyboard shortcut with `f`). The position itself is definitely more sensible now. See how the white pieces are mostly on rank 1 and 2, where they usually start.

**Comment by Noob-A** [comment]
best_move.move = d4e5
board.move_stack = [Move.from_uci('e7e5')]
i will get the right move from board.move_stack
