### ISSUE TITLE
Missing tag pair using chess.pgn.read_game() or chess.pgn.scan_headers()

### ISSUE THREAD

**Issue by gbtami** [niklasf/python-chess#86]
According to [pgn standard spec](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8.1) tag pair names can contain underscores, but python-chess pgn parser ignores such names.

```
[Event "Local event"]
[Site "London"]
[Date "2000.01.01"]
[Round "1"]
[White "First Player"]
[Black "Second Player"]
[Result "1/2-1/2"]
[1Underscored_Tag "tag value"]

1. e4 c5 1/2-1/2
```

Telling the truth I'v never met any .pgn containing nor digits nor underscores in any tag, but the standard enables it, so it's better to handle it.

**Comment by niklasf** [comment]
Fixed via #87.
