### ISSUE TITLE
question: does stockfish uses previous moves to make better move?

### ISSUE THREAD

**Issue by Noob-A** [niklasf/python-chess#860]
I'm clearing the board every iteration of game and there is no previous moves on it. Does it affect moves quality?

**Comment by niklasf** [comment]
No, this should be neutral (unless the moves have a repetition that Stockfish will now no longer know about, so it can't avoid or aim for a threefold-repetition).

This might be different for engines other than Stockfish.

**Comment by Noob-A** [comment]
and also: how can i improve stockfish results?

**Comment by piotr-dobrogost** [comment]
> No, this should be neutral (unless the …

This means the answer is yes :)

**Comment by niklasf** [comment]
> and also: how can i improve stockfish results?

Give it more time, a larger hashtable, tablebases, better hardware, ...
