### ISSUE TITLE
question: can i make the engine play an error?

### ISSUE THREAD

**Issue by Noob-A** [niklasf/python-chess#861]
So for *personal reasons* i want to make the engine make a minor error in it's turn. Is it possible? (sorry for a lot of questions)

**Comment by niklasf** [comment]
Depending on how grave you want the error to be, and it it must be a guaranteed error
* You could do a search for multiple lines and select the last one (see `multipv` argument of https://python-chess.readthedocs.io/en/latest/engine.html#analysing-and-evaluating-a-position).
* Pick a lower skill level (option named `Skill Level` accepts value between `0` and `20`, see https://python-chess.readthedocs.io/en/latest/engine.html#options). Weaker play does not mean every move will be an error.
* Give Stockfish insufficient resources (something like `chess.engine.Limit(nodes=1000)` would not be enough for the engine to reliably pick a good move). Might sometimes pick a good move by pure luck.

**Comment by Noob-A** [comment]
Thank you :heart:
