### ISSUE TITLE
time issues

### ISSUE THREAD

**Issue by Noob-A** [niklasf/python-chess#862]
```python
import time

import chess.engine

engine = chess.engine.SimpleEngine.popen_uci(
            r'C:\Users\User\PycharmProjects\stock_test\stockfish_14.1_win_x64_avx2\stockfish_14.1_win_x64_avx2.exe')
engine.configure({"Threads": 16})
engine.configure({"Skill Level": 20})
s = time.time()
best_move = engine.play(chess.Board(), chess.engine.Limit(depth=32))
e = time.time()
print(f"took {e-s} sec")
```
it prints "took 37.16223120689392 sec", but i think this is really long for my processors (two xeon gold 6130)
![image](https://user-images.githubusercontent.com/59875489/156723360-fe5996a7-f358-4f96-a325-b5119f71a313.png)

**Comment by Noob-A** [comment]
![image](https://user-images.githubusercontent.com/59875489/156724800-c4f67fe5-3923-46c2-b2c9-03929a1be458.png)
16 threads benchmark

**Comment by Noob-A** [comment]
i can use depth=20, but i want to know why i have so low nps

**Comment by niklasf** [comment]
Maybe people in the [Stockfish Discord](https://discord.gg/aefaxmq) can help, as this appears to be about using Stockfish rather than using this library.
