### ISSUE TITLE
chess.svg: readthedoc difference between v:1.8.0 and v: latest

### ISSUE THREAD

**Issue by RainMa22** [niklasf/python-chess#865]
in the [readthedoc website(v:latest), in "SVG Rendering"](https://python-chess.readthedocs.io/en/latest/_modules/chess/svg.html), it is said that `fill` is an accepted parameter when creating a SVG board. 

However, this functionality is not supported in the current version of `chess==1.8.0`, 
```
TypeError: board() got an unexpected keyword argument 'fill'
```
nor is it mentioned in [readthedoc(V:1.8.0)](https://python-chess.readthedocs.io/en/v1.8.0/svg.html).

Current workaround is to simply copy the [`chess.svg` code](https://python-chess.readthedocs.io/en/latest/_modules/chess/svg.html) from readthedoc(v: latest) into the `site-packages/chess/svg.py` file.

Proposed solution: A updated package to PyPI will be appreciated.

Thanks in advance

**Comment by niklasf** [comment]
Yep, this happens for every new and unreleased feature. I'll make a release soon.

**Comment by RainMa22** [comment]
Oh, Ok. I am really sorry for rushing you.

**Comment by niklasf** [comment]
No worries. It's good to know that someone is eagerly awaiting the feature.
