### ISSUE TITLE
Reading PGN records where moves have multiple comments

### ISSUE THREAD

**Issue by MarkZH** [niklasf/python-chess#866]
When reading a PGN game record with `chess.pgn.read_game()`, multiple comments on the same move will be joined into a single comment with line breaks. This makes for unwanted line breaks when the game is written out. For example:
```python
import chess.pgn
import io

game = chess.pgn.read_game(io.StringIO("1. h4 { [%clk 0:03:00] } { A00 Kadas Opening } 1... e5 { [%clk 0:03:00] }"))
print(game)
```
results in
```pgn
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]

1. h4 { [%clk 0:03:00]
A00 Kadas Opening } 1... e5 { [%clk 0:03:00] } *

```
This happens in [this line](https://github.com/niklasf/python-chess/blob/eef8a29907e91662a24a4f0a79416f14c8a6d24c/chess/pgn.py#L1149) and [this line](https://github.com/niklasf/python-chess/blob/eef8a29907e91662a24a4f0a79416f14c8a6d24c/chess/pgn.py#L1153) in `chess.pgn.GameBuilder`. I think a single space would be a better joiner for multiple comments, or perhaps a slash surrounded by spaces (` / `) to distinguish the previously separate comments.

For context, games downloaded from lichess.org will feature these multiply commented moves as in the example.

**Comment by niklasf** [comment]
Mhh ... I agree \n is a bit weird. Spaces are probably best. Changed.
