### ISSUE TITLE
Illegal move not detected as such

### ISSUE THREAD

**Issue by Ronnypetson** [niklasf/python-chess#870]
Hello,

I was checking some synthetic PGN sequences generated from language models when I found out that

1. e4 c5 2. c4 e6 3. Nf3 d5 4. e5 Nc6 5. d4 Nh6 6. Nbd2 Nf5 7. Bd3 Be7 8. O-O O-O 9. b3 Na5 10. Bb2 b6 11. a3 Bb7 12. Qe2 Rc8 13. Bb1 c4 14. Bc2 b5 15. Bd3 a6 16. Bb1 g6 17. Bd3 Nc6 18. Bb1 Na5 19. Bc2 Qd7 20. Bd3 Nac6 21. Bb1 Na5 22. Bc2 Nac6 23. Bd3 Na5 24. Bb1 Nac6 25. Bd3 Na5 26. Bb1 Nac6 27. Bd3 Na5 28. Bb1 Nac6 29. Bd3 Na5 30. Bb1 Nac6 31. Bc2 Na5 32. Bb1   1/2-1/2

should not be allowed at move 13. ... c4 (I checked by loading the PGN on chess.com), but python-chess allows such move.

**Comment by Ronnypetson** [comment]
Here is a print up to move 13. Bb1
![image](https://user-images.githubusercontent.com/15349283/163731911-73be4200-0328-4688-b298-f0721098d8e0.png)
 We can see clearly that c4 is not possible.

**Comment by Ronnypetson** [comment]
Here is a similar sequence

1. c4 c5 2. e4 d6 3. g3 e5 4. d3 Nc6 5. Bg2 Nf6 6. Nge2 Nd4 7. O-O a6 8. Na3 Be6 9. Nc2 Be7 10. Ne3 O-O 11. Nd5 Ne8 12. Bd2 Nf6 13. Bc3 Bd7 14. Bd2 Rc8 15. b3 b5 16. Ne3 g6 17. Nd5 Ne8 18. Ne3 Nc7 19. Nd5 Ne8 20. Ne3 Nc7 21. Nd5 Be6 22. Ne3 f5 23. f4 e4

**Comment by niklasf** [comment]
Thanks for reporting. It "works" because `c4` is interpreted as "pawn move to c4", which has a unique matching move `dxc4`, so that one is selected. I agree that it should probably be rejected, instead.
