### ISSUE TITLE
python chess is 1000x slower than c++ 🤔

### ISSUE THREAD

**Issue by movepicker** [niklasf/python-chess#874]
hi niklas

i ask the same question but i cant find the answer 

i had two perft test  in cpp-chess & python-chess

```
Perft 5 c++ nodes: 4865609
===========================
Total time (ms) : 29
Nodes searched  : 4865609
Nodes/second    : 167779620
```

```
Perft 5 python nodes: 4865609
===========================
Total time (ms) : 13447
Nodes searched  : 4865609
Nodes/second    : 361836
```

the result is cpp chess board 1000 times faster than python chess board !!!!!!!!!!!!!!

why python is too slow ?

**Comment by niklasf** [comment]
That's more like 500x, which is sadly not unheard of for (somewhat idiomatic) Python vs. native code, especially the task can utilize hardware to the fullest.

I believe the best way forward is probably https://github.com/niklasf/python-chess/issues/722.

**Comment by niklasf** [comment]
With all the work that went into JITs, JavaScript is generally much faster than Python.

If decently optimized Python is really supposed to be at 50x, it should be easy to identify a few optimizations 🤷

**Comment by niklasf** [comment]
The Python version doesn't generate any moves, because the generator is lazy.

**Comment by niklasf** [comment]
No, it does not. `board.legal_moves` is simply a `LegalMoveGenerator` object that does nothing unless it is actually iterated over.

**Comment by niklasf** [comment]
Yes, or just

```python
for _ in board.legal_moves:
    pass
```

if you only want to measure move generation, not move making.

Ok ... so we narrowed it down from perft being slower to move generation being slower.

Check out the underlying [`generate_legal_moves()`](https://github.com/niklasf/python-chess/blob/56b2410513ff6e64305ef5caed7eda68826145ed/chess/__init__.py#L3505). It's easy to follow for the position at hand. With the huge performance gap, surely it will be easy to find a part that is inefficient or can be optimized, if only for part of the gap.

**Comment by niklasf** [comment]
Measure Python again with the fix above, and compare it to your Javascript version.

**Comment by msuleman67h** [comment]
> hi niklas
> 
> i ask the same question but i cant find the answer
> 
> i had two perft test in cpp-chess & python-chess
> 
> ```
> Perft 5 c++ nodes: 4865609
> ===========================
> Total time (ms) : 29
> Nodes searched  : 4865609
> Nodes/second    : 167779620
> ```
> 
> ```
> Perft 5 python nodes: 4865609
> ===========================
> Total time (ms) : 13447
> Nodes searched  : 4865609
> Nodes/second    : 361836
> ```
> 
> the result is cpp chess board 1000 times faster than python chess board !!!!!!!!!!!!!!
> 
> why python is too slow ?

Seems about right. That is how much C++ is faster than python in general.
