### ISSUE TITLE
have more notation sytems for humans

### ISSUE THREAD

**Issue by sugizo** [niklasf/python-chess#875]
currently have : uci, san, lan
nice to have more notation sytems for humans, e.g. MAN, FAN, RAN, CRAN, FCRAN, smith, descriptive, coordinate, iccf

**ref**
https://en.wikipedia.org/wiki/Chess_notation#Notation_systems_for_humans

best regards

**Comment by niklasf** [comment]
I am not opposed to adding additional notation systems, but only if there's a convincing real-world use case. What do you want to do with all of these formats?

**Comment by sugizo** [comment]
What do you want to do with all of these formats?
not for me, perhaps others more convinience to read in another notation sytems for humans

**Comment by niklasf** [comment]
> not for me, perhaps others more convinience to read in another notation sytems for humans

I think nowadays SAN and UCI are predominant, for humans and computers respectively. Having less choice is good for interoperability, so let's not add any formats preemptively, and reconsider when someone has a concrete use-case.
