### ISSUE TITLE
Using Python-Chess in conjunction with Pytorch for deep learning

### ISSUE THREAD

**Issue by VovaTch** [niklasf/python-chess#885]
I'm implementing my own self-play algorithm style AlphaZero, and I've found out that converting the Py-Chess board representation to a Pytorch tensor is a major computational bottleneck, especially when I try to parallelize Monte-Carlo Tree Search instances to take full advantage of my GPU memory. Is there an efficient way of doing so with Python-Chess? How do I get to the underlying board representation?

**Comment by niklasf** [comment]
Hi. What target representation are you going for?

**Comment by VovaTch** [comment]
I'm going for an 8x8x16 representation, dtype is float. 12 layers are for pieces, encoding the piece locations as 1, attacking squares as 0.25, x-ray squares but blocked as 0.1. Indices 12 and 13 (starting from 0) represent board coordinates, index 14 player turn, index 15 the number of piece attacking each square, +1 for each white piece and -1 for each black one. The immediate answer I think would be converting to a longer binary representation, but it seems to me now that the bottleneck is caused by slow Pytorch indexing, using Numpy instead speeds it up, but there is the question of converting it to Pytorch again.

**Comment by VovaTch** [comment]
While this question remains interesting, I think I can close this issue. Aside from slow Pytorch indexing, several other improvements allowed me to significantly accelerate game generation. I used deep-copying using copy.deepcopy() and it is very slow, the board.copy() method is significantly faster, the next one is sampling from Dirichlet distribution is much faster in Numpy. None of them are directly related to Python-Chess, and querying the board seems to be sufficiently fast.

**Comment by niklasf** [comment]
Thanks for the heads up.

As for populating a vector from a board, it's probably best to allocate/zero it first, and then iterate to set specific values. For example:

```python
features = [0] * 64
for square in chess.scan_forward(board.pawns):
    features[square] = 1
```
