### ISSUE TITLE
Manual start of pondering

### ISSUE THREAD

**Issue by Torom** [niklasf/python-chess#886]
Hey, first of all thanks for this great library, I use it for engine communication in my Lichess bot [BotLi](https://github.com/Torom/BotLi).

Now I had the following idea: I want to inform the engine about moves that were not played by the engine, i.e. moves from the book or from chessdb. The goal is to have the engine already calculating on these moves and ready when needed. I guess pondering would be the right thing to do. As I see it, there is currently no way to start pondering manually. Would it be possible to add this? Is this the right approach?

So far I have found the possibility to let the engine analyze infinitely with `engine.analysis()` and then interrupt that with `engine.play()` when it should determine the next move, which goes already in the right direction, but I think is not yet optimal.

Thanks in advance :)

**Comment by niklasf** [comment]
As far as the UCI protocol is concerned, there are two problems with pondering in this situation:
* [`go ponder`](https://backscattering.de/chess/uci/#gui-go-ponder) considers the last move as uncertain (which makes sense when it is the expected opponent's move, not a fixed book move).
* The only way to get a (potential) advantage over infinite analysis, is the ability to use [`ponderhit`](https://backscattering.de/chess/uci/#gui-ponderhit). But this means time based limits start from the moment you started pondering, not from the moment you sent `ponderhit`.

For most engines (including Stockfish) the approach with infinite analysis followed by new search is *nearly* optimal.

So all things considered, python-chess does not implement anything better for this situation. There is `engine.play(..., ponder=True)`, but it will only start pondering after the engine played a move (if the engine itself determined a move it likes to ponder on).

**Comment by Torom** [comment]
Thank you for your reply.

I understand, I think that the second point would even be an advantage. But I don't know how to determine the pondermove in a sensible way.

But good to know that my approach with infinite analysis should work almost as good.
