### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by muddycamel** [niklasf/python-chess#892]
Dear all,

I'm sorry for asking this rudimentary question, but where exactly do I type "pip install chess"? I've downloaded and unzipped a folder called "python-chess-master" but I don't know what to do after that. I've also downloaded python and it looks kind of like the windows command prompt. Typing it there, I got SyntaxError: invalid syntax. 

Again, I'm cringing at how dumb this question may seem.

**Comment by a2zquizanswers** [comment]
Tried it on the command line, says:
    Could not find a version that satisfies the requirement chess (from versions: )
    No matching distribution found for chess

Have Python 2.7.17 setup on the server.

**Comment by a2zquizanswers** [comment]
I upgraded python as well...

$ python3 --version
Python 3.10.5

$ pip install chess
Collecting chess
  Could not find a version that satisfies the requirement chess (from versions: )
No matching distribution found for chess

**Comment by niklasf** [comment]
Can you show `pip --version` and `python3 -m pip --version`, please? If they are different, `python3 -m pip install chess` might be worth a shot.
