### ISSUE TITLE
Crazyhouse Movegen sometimes fails

### ISSUE THREAD

**Issue by dave7895** [niklasf/python-chess#893]
for me the generation of legal moves in Crazyhouse sometimes fails with the following error:
```
File "/home/dave/dev/lichess-bot/venv/lib/python3.10/site-packages/chess/variant.py", line 963, in generate_pseudo_legal_drops
    for pt, count in self.pockets[self.turn].pieces.items():
RuntimeError: dictionary changed size during iteration
```
whereboard.legal_moves gets used like
```python
for m in board.legal_moves:
        board.push(m)
        tempScore = -negamax(board, depth - 1, ply + 1, -beta, -alpha)[0]
        board.pop()
        if tempScore > bestScore:
            bestScore = tempScore
            bestMove = m
            if bestScore > alpha:
                alpha = bestScore
        if alpha >= beta:
            break
```
in this specific instance the fen is `2rn1b1r/1pp2n1p/B1PBk1pP/5p1P/P5p1/2P2RP1/RP1QNP2/1NBK4[QPp] w - - 1 31` and the function errors as soon as the depth gets larger than 2

At first I thought that it was caused by the existence of a capture in the searched game tree, but in this position there are immediate captures available, so they would already be searched at depth 1

**Comment by niklasf** [comment]
Thanks for reporting. I can see the issue, but I didn't actually get the exception, so I attempted a blind fix. Can you please confirm if it's fixed in the latest development version? (`pip install git+https://github.com/niklasf/python-chess.git`)

**Comment by dave7895** [comment]
Thank you for the quick fix. So far no issues, all tests so far ran error-free
