### ISSUE TITLE
{set|from}_chess960_pos() functions are missing

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#90]
Hi,

the {set|from}_chess960_pos() functions seems to not be inside.

Also i would like to propose a feature:
get_chess960_pos() to get the number of the board.
or at least:
valid_ches960_pos() to check that a setup pos is valid (esp test the starting position => test for mirrored pieces).

I would need the last, to prevent users to going over "setup pos" , and "set uci960"
Jürgen

**Comment by niklasf** [comment]
Can't reproduce. Can you give me exact code that fails?

```
>>> import chess
>>> chess.__version__
'0.14.1'
>>> b = chess.Board()
>>> b.set_chess960_pos(123)
>>> print(b)
n q r n b k r b
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
N Q R N B K R B
```

I'll be working on the second issue.

**Comment by LocutusOfPenguin** [comment]
OK, i still have 0.14.0...so its logical i get this:

>>> b.set_chess960_pos(123)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Board' object has no attribute 'set_chess960_pos'


But i cant update either cause running
pip3 install --upgrade -r requirements.txt
now gives me:
AttributeError: 'Requirement' object has no attribute 'project_name'


For the second case its what i want to get:
user sets up a (starting) pos. Now you can have a standard setup or a uci960 one. I need a way to know its "new game in uci960 mode".
But i guess, to get the uci960 code is in general better..cause opens more use-cases, and i can just check for error/false and the number returned (= *i* just need a bool, not the uci960 number).

Can be done that i do a board(fen)...and it sets the uci960 flag internally, and i can ask for this, and -as bonus- its uci-code...anyway, what is easiest for you

**Comment by niklasf** [comment]
What's your `pip --version`?

**Comment by LocutusOfPenguin** [comment]
pip3 --version
pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5)

but with  8.1.2 (seen on iNet) i find this error cause changed their api.
So, even --version saying 8.1.1, im not sure :-)

**Comment by niklasf** [comment]
Please try `pip3 install --upgrade python-ches` directly and provide the full output.

**Comment by LocutusOfPenguin** [comment]
i got it working now (starting with yr command - which runs successfully at first try).
But even it did, afterwards i had 0.14.0 & 0.14.1 depending on "root", "user" or "virtualenv" that includes "user" sometimes saying 14.0, sometimes 14.1. Argh :-)
Now, they all same (but dont ask me, why this changed).

Surely, now this main ticket can be regarded closed...These commands are there. Thanks.
If y can still do my "feature request" would be good.
Jürgen

**Comment by niklasf** [comment]
Alright.

The latest development version now has `Board.chess960_pos(ignore_turn=False, ignore_castling=False, ignore_counters=True)` that returns a value between 0 and 959 or None.

**Comment by LocutusOfPenguin** [comment]
Hi @niklasf 
Now, i had time to test it out with picochess. But i still get problems..Here is an example:

`import chess
chess.__version__
'0.14.1'
b = chess.Board('nqrnbkrb/pppppppp/8/8/8/8/PPPPPPPP/NQRNBKRB w - - 0 1')
print(b.chess960_pos())
None
`

No matter if i try another chess960 pos, i always get None as result.

If y fix this, or tell me the problem...can y create another version number? This is esp needed for the engines problem, y fixed lately. Thx.
Jürgen

**Comment by niklasf** [comment]
The given position is not a valid starting position because of the missing castling rights. Please try `b.chess960_pos(ignore_castling=True)` or set castling rights.

I'll release a new version soon. I just need to do some more testing of the recent changes.

**Comment by LocutusOfPenguin** [comment]
yes, with "ignore_castling=True" it works together with using "- -"
If i change this to "KQkq" and not putting this flag inside , i must also say "chess960=true" otherwise getting None again. Hmm.

Thats so far OK, but if i do a "b = chess.Board(), and asking for the pos960 code, i get "518".
This leads me to believe, y should return also "None", cause im not in chess960 mode (to make it similar to the above example).

Actually, the current way is easier for me...but is it logical? How y think?

**Comment by niklasf** [comment]
I see the point, but I think it's fair to say that the standard chess starting position is identical to FR 518 in every way, independent of the chess960 flag.

For most other positions the chess960 flag is relevant: KQkq without chess960=true means those castling rights are not actually available and therefore it is not a valid FRC starting position.

**Comment by niklasf** [comment]
v0.15.0 just released. Enjoy! :)
