### ISSUE TITLE
PGN: Moves are not parsed if a header name contains a colon

### ISSUE THREAD

**Issue by laniakea64** [niklasf/python-chess#900]
I have a PGN file with a header `[BlackType: "program"]`.  If I try to load this file using `chess.pgn`, none of the moves are loaded, it only loads the headers.

Reduced testcase:
`test.pgn`
```
[Event "Test"]
[Date "2022-06-22"]
[Result "0-1"]
[BlackType: "program"]

1. f4 e5 2. g4 Qh4
0-1
```
```
import chess.pgn
with open('test.pgn', 'r') as f:
  game = chess.pgn.read_game(f)

print(game, game.end().board(), sep='\n')
```

The following monkeypatch based on the [PGN spec](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c7) gets it working as expected -
```
chess.pgn.TAG_REGEX = re.compile(r"^\[([A-Za-z0-9_+#=:-]+)\s+\"([^\r]*)\"\]\s*$")
chess.pgn.TAG_NAME_REGEX = re.compile(r"^[A-Za-z0-9_+#=:-]+\Z")
```

Would it be helpful if I make a pull request of that as a proper patch?

**Comment by niklasf** [comment]
Yes, please.
