### ISSUE TITLE
lichess winning model doesn't look right

### ISSUE THREAD

**Issue by alexlopespereira** [niklasf/python-chess#902]
These two formulas look quite different:

Lichess (lila): https://github.com/lichess-org/lila/blob/c48da4e2cd22837a9f6e8b7eb4a59924967aec3f/ui/ceval/src/winningChances.ts#L11

python-chess attempt to replicate lichess winning model: https://github.com/niklasf/python-chess/blob/43dc84ad41b78997a6873e9855d2d4fb57d67735/chess/engine.py#L656

Am I missing something here? Are these two really meant to be the same?

Thanks.

**Comment by niklasf** [comment]
Those should be equivalent, up to scaling.

Lichess calls it winning chances, but the scale actually goes from -1 (lost) over 0 (equal) to 1 (won).

`chess.engine.Wdl(wins=..., draws=..., losses=...)` shows the expected stats for a number of games, 1000 by default, as `UCI_ShowWdl` does.

**Comment by alexlopespereira** [comment]
I can see they are equivalent. I'm quite new to python-chess, then I'm not sure the purpose of this feature. 

![image](https://user-images.githubusercontent.com/6627726/175835067-df285249-7447-4cf0-b6df-a951e70e06a4.png)

But if you call "the win rate model used by Lichess" I believe users will undestand this is exactly the formula used to display the winning chances in the app and in the lichess website (see the picture below).

![image](https://user-images.githubusercontent.com/6627726/175835325-95a93e3e-9511-45c6-b122-581bfabf519c.png)

Am I missing something?

**Comment by niklasf** [comment]
The circled value is the score in pawns, i.e. White has an advantage equivalent to a bit more than half a pawn.

Lichess uses the winning chances only as thresholds to classify inaccuracies/blunders/mistakes and to scale graphs. The raw value is never displayed.

**Comment by alexlopespereira** [comment]
Alright. Now I understand that. But I still don't get something. Why not to use the same formula to classify inaccuracies/blunders/mistakes as lichess does when you call it by a lichess parameter?

My suggestion would be adding another parameter (lichess_something) and put the other formula there.

**Comment by niklasf** [comment]
The signature of the method is essentially `def wdl(score: Score, model: "sf" | sf15" | "sf14" | "sf12" | "lichess") -> Wdl`, so a common interface for various models. `Wdl` then offers various methods

```
 |  drawing_chance(self) -> 'float'
 |      Returns the relative frequency of draws.
 |
 |  expectation(self) -> 'float'
 |      Returns the expectation value, where a win is valued 1, a draw is
 |      valued 0.5, and a loss is valued 0.
 |
 |  losing_chance(self) -> 'float'
 |      Returns the relative frequency of losses.
 |
 |  winning_chance(self) -> 'float'
 |      Returns the relative frequency of wins.
```

with clear mathematical definitions. The raw value between -1 and 1 wouldn't make sense for any of those.
