### ISSUE TITLE
Threefold repetition claimed before third repetition

### ISSUE THREAD

**Issue by ben-1634** [niklasf/python-chess#907]
If you start with a new chess.Board, and you repeat Nf3, Nf6, Ng1, Ng8 (shuffling the knights back and forth), threefold repetition should occur after the second Ng8 (because the starting position will occur 3 times, one at the start, and twice when the black knight reaches it's starting square twice). Using board.outcome(claim_draw=True) or board.is_game_over(claim_draw=True), it returns that the game is over due to threefold repetition before the second Ng8 is played, which means that no position has been reached 3 times. Here the code I ran it with:
```
import chess
board = chess.Board()
print(board)
print(board.is_game_over(claim_draw=True), end="\n\n")
for move in ["g1f3", "g8f6", "f3g1", "f6g8", "g1f3", "g8f6", "f3g1"]:
	board.push_san(move)
	print(board)
	print(board.is_game_over(claim_draw=True), end="\n\n")
```

**Comment by niklasf** [comment]
Hi. This is in line with FIDE rules. See [`board.can_claim_threefold_repetition()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.can_claim_threefold_repetition) and [`board.is_repetition()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.is_repetition) for an exaplanation.

**Comment by ben-1634** [comment]
Sorry, I didn't think of that!
