### ISSUE TITLE
How to play a game?

### ISSUE THREAD

**Issue by dsblank** [niklasf/python-chess#91]
Looking to use python-chess in a Cognitive Science course, examining AI and symbolic reasoning. As part of that, I want to make a simple framework for students to select among the set of possible moves. Looking for examples of a simple random chess player. Is this all that I need to play a complete, legal game?

```python
move_count = 0
while not board.is_game_over():
    move_count += 1
    print("Move:", move_count)
    display(board)
    m1 = random.choice([move for move in board.legal_moves])
    uci = m1.uci()
    print("Play:", uci)
    board.push_uci(uci)
    display(board)
```
BTW, if you do this:
```python
board._repr_html_ = board.__html__
```
then you will get the nice HTML display in the Jupyter Python notebook.

**Comment by niklasf** [comment]
Hi, yes. That'll do. A couple notes:

* There's also `board.fullmove_number` starting at 1 and incremented each time both players complete their turn. `len(board.moves)` is the number of moves pushed so far.
* `move.uci()` is totally fine if you rather pass around strings than move objects. If `move` is guaranteed to be legal you could also directly use `board.push(move)`.
* If there are any chess players among your students they will probably find `san = board.san(move)` as a human readable representation most intuitive.

```
board._repr_html_ = board.__html__
```
Intresting. I'll checkout IPython and make that adjusment.

**Comment by dsblank** [comment]
Thanks for the confirmations, and notes! Much appreciated.

BTW, I am getting huge spikes in CPU when displaying the HTML representations in Chrome on Linux. Do you have any idea what might cause huge CPU usage for rendering the board? I've tried removing some of the html attributes, but haven't been able to identify the cause.

**Comment by niklasf** [comment]
I have added SVG rendering and replaced `__html__` with `_repr_svg_` which seems to be more appropriate anyway. Maybe that fixes the problem. Examples: https://python-chess.readthedocs.io/en/latest/svg.html

**Comment by dsblank** [comment]
Fantastic! Thank you so much. I'll provide a link to the course resources when ready.

**Comment by niklasf** [comment]
Cool. Looking forward to it.

**Comment by dsblank** [comment]
FYI, here is a link that will be refined over time, but has everything needed to program a game of chess:

https://athena.brynmawr.edu/jupyter/hub/dblank/public/CS371%20Cognitive%20Science/2016-Fall/Programming%20a%20Chess%20Player.ipynb

**Comment by niklasf** [comment]
Thanks for sharing :+1:
