### ISSUE TITLE
chess.svg line 295: TypeError: unsupported operand type(s) for ^=: 'str' and 'bool'

### ISSUE THREAD

**Issue by jimratliff** [niklasf/python-chess#910]
When I call chess.svg.board, I get a fatal error at line 295 of chess/svg.py, corresponding to:
```
orientation ^= flipped
```
The error is:
```
TypeError: unsupported operand type(s) for ^=: 'str' and 'bool'
```
This occurs whether or not I supply a `flipped` argument.

I'm puzzled because this seems to be a show stopper for running chess.svg.board at all, so I’m surprised I’m experiencing it.

Also, I see a comment that `flipped` is deprecated. You might want to add that fact to the ReadTheDocs documentation, because I was puzzled at the coexistence of both an `orientation` and a `flipped` parameter. I was experimenting to see what the difference was.

**Comment by jimratliff** [comment]
Addendum: I see now that in fact the documentation *does* mention the deprecation. It shows up below the exhibit chessboard image, rather than where the parameter is first disclosed, and I missed it.

**Comment by niklasf** [comment]
Note that `Color` is `chess.WHITE` or `chess.BLACK`, not the string `"white"` or `"black"`.

**Comment by jimratliff** [comment]
Thanks for the quick response! (I had been using backscattering.de, and was converting to this method. That difference slipped past me.)
