### ISSUE TITLE
Info["string"] support for multiple returns

### ISSUE THREAD

**Issue by Piriprimey** [niklasf/python-chess#914]
If an UCI engine sends multiple "info string" lines, the InfoDict returned by chess.engine.analyse() only contains the last "info string" line sent as the "string" value.

**Comment by niklasf** [comment]
Hi. This is by design, and the same for any info value, though I see how `string` could be different.

You can use the approach from https://python-chess.readthedocs.io/en/latest/engine.html#indefinite-or-infinite-analysis to observe all intermediate values.
