### ISSUE TITLE
Get the total number of moves of a game

### ISSUE THREAD

**Issue by alexlopespereira** [niklasf/python-chess#917]
How do we get the total number of moves of a game (besides iterating over all moves) ?

**Comment by alexlopespereira** [comment]
I've made this:

match = chess_pgn.read_game(pgn)
list(match.mainline())[-1].ply()

I believe it gives me the final match ply.

**Comment by niklasf** [comment]
Your solution works. Equivalent:

```python
match.end().ply()
```

Note that the game is represented as a tree of linked nodes, so this still involves iteration.

Another pitfall is that games may be set up to start at some ply greater than 0. Use

```python
sum(1 for _ in game.mainline())
```

if you want to count actual moves.
