### ISSUE TITLE
Retrieve image in .jpg format from board state

### ISSUE THREAD

**Issue by markobogoevski** [niklasf/python-chess#919]
Hello, I am parsing lots of .pgn files into game objects using the .read_game function. I was wondering if there is a way to automate image retrieval for each move in the game. Is this https://github.com/niklasf/web-boardimage the way to do it?

**Comment by niklasf** [comment]
Hi, yep, that would work. Check out [the implementation](https://github.com/niklasf/web-boardimage/blob/f94b1134214ae268693a2318a8574df6434156b4/server.py#L89-L104) of web-boardimage. It's just a call to `chess.svg.board(...)` followed by image format conversion using `cairosvg`. You could do this directly in your script.
