### ISSUE TITLE
Obsolete version used in google colab and missing version() and dates in history/changelog

### ISSUE THREAD

**Issue by m-f-h** [niklasf/python-chess#922]
Hello, I'm really happy about the existence of this library and it's availabilty and will try to contribute to make it even better!

* Unfortunately, the version used in google colab notebooks appears to be very old and obsolete: in particular, it lacks the very useful `Board.outcome` which was introduced in v1.5.0 as I found out from the CHANGELOG. (So they must use v1.4 or older -- from when date these (see below)? I wonder whether they're not older than google colab altogether... strange!!)
* So I wondered what were the approximate dates (at least the year) of these releases, and I regret that there seems to be absolutely no information on that in the changelog file -- wouldn't it be useful to include such information, at least for some milestones?
* I will try to file a "bug" in google colab so that they'd update the version that is used., but maybe you have a more direct / efficient connection to signal that and request such an update -- in that case, thanks in advance!
* That brings me to the last suggestion in this issue: wouldn't it also be useful / good (if not standard) practice to have an attribute `chess.version` that would provide a string with the version number and date?
Thanks in advance and keep up the good work.

**Comment by niklasf** [comment]
Hi. Answering out of order:

* The convention is to use `__version__`, e.g., `chess.__version__`.
* When I create a new notebook, for some reason Colab has an ancient version v0.23.11 from December 2018 preinstalled. To be honest, I would not expect any version to be installed. You can do
  ```
  !pip install --upgrade chess
  ```
  to update to the latest version.
* The exact release timestamps can be found on https://github.com/niklasf/python-chess/releases. I agree that it would make sense to have the information also in `CHANGELOG.md`
