### ISSUE TITLE
Derive short algrabraic notation from Move class

### ISSUE THREAD

**Issue by maxwell-oroark** [niklasf/python-chess#926]
`move.uci()` returns string of move in long algebraic notation format.

Is there an equivalent method for returning the short algebraic notation? e.g. `e4` instead of `e2e4`

**Comment by niklasf** [comment]
Creating SAN requires the position for context, so that's not possible with the [information stored in `Move`](https://python-chess.readthedocs.io/en/latest/core.html#moves). Instead, use [`board.san(move)`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.san).

**Comment by maxwell-oroark** [comment]
@niklasf exactly what I was looking for. thanks!
