### ISSUE TITLE
chess.svg board is not working

### ISSUE THREAD

**Issue by rydz99** [niklasf/python-chess#928]
Hi, I'm trying to display image of chessboard 

I'm using code snippet from docs (https://python-chess.readthedocs.io/en/latest/svg.html)

```python
import chess
import chess.svg


board = chess.Board("8/8/8/8/4N3/8/8/8 w - - 0 1")
chess.svg.board(
    board,
    fill=dict.fromkeys(board.attacks(chess.E4), "#cc0000cc") | {chess.E4: "#00cc00cc"},
    arrows=[chess.svg.Arrow(chess.E4, chess.F6, color="#0000cccc")],
    squares=chess.SquareSet(chess.BB_DARK_SQUARES & chess.BB_FILE_B),
    size=350,
)
```

But actually nothing was displayed. I'm on mac machine and use python 3.9.12 (conda)

**Comment by niklasf** [comment]
The `>>>` is meant to indicate an interactive console session. `chess.svg.board()` returns a string that would be visible then (as XML in the terminal, or an image in a Jupyter Notebook).

You could also do something like:

```python
with open("example.svg", "w") as file:
    file.write(chess.svg.board())
```
