### ISSUE TITLE
Abbreviated san notation does not work since 1.9.1

### ISSUE THREAD

**Issue by DroZ-hun** [niklasf/python-chess#930]
Hi,

Sine 1.9.1 I cannot use shortened san notation for `parse_san()` and `push_san()`, I get illegal san `ValueError`.

For example, n `"rnbqkbnr/pp2pppp/3p4/2p1P3/8/5N2/PPPP1PPP/RNBQKB1R b KQkq - 0 1"` state, `board.parse_san("dxe5")` works, but `"xe5"` and `"e5"` does not:

    `board.parse_san("dxe5")` -> `Move.from_uci('d6e5')`
    `board.parse_san("xe5")`  -> `ValueError:` illegal san: 'xe5' in rnbqkbnr/pp2pppp/3p4/2p1P3/8/5N2/PPPP1PPP/RNBQKB1R b KQkq - 0 1
    `board.parse_san("e5")`   -> `ValueError:` illegal san: 'e5' in rnbqkbnr/pp2pppp/3p4/2p1P3/8/5N2/PPPP1PPP/RNBQKB1R b KQkq - 0 1

These worked before, and still works in 1.9.0, but not since 1.9.1.

If this is intended, then is it possible to provide optional parameter to `parse_san()` and `push_san()` to accept abbreviations like these?

Thanks for your help!

**Comment by niklasf** [comment]
Hi. Sorry, this is an intended [change from v1.9.1](https://github.com/niklasf/python-chess/blob/master/CHANGELOG.rst#new-in-v191-28th-may-2022):

> ## New in v1.9.1 (28th May 2022)
> Bugfixes:
> 
> * Reject pawn capture SAN if the original file is not specified, e.g., d5 will no longer match cxd5.
>
> [...]

I would be really hesitant to optionally reenable this.

**Comment by DroZ-hun** [comment]
I see. Well, thank you for the response.
In this case you can close the ticket. I just liked to abbreviate san notations as much as possible.
