### ISSUE TITLE
generation of a SquareSet as a result of attack fields considering the blocked (occupied) squares

### ISSUE THREAD

**Issue by cherepanovic** [niklasf/python-chess#933]
How do I get the SquareSet that represents the attacked squares on a chess board considering the blocked squares using your great library?

an simple and operation between all pieces and attacks() of a piece is not enough, since it does not consider the blocked squares

as an example here attacks from bishop.
```
. . . . . . 1 .
. . . . . 1 . .
1 . . . 1 . . .
. 1 . 1 . . . .
. . . . . . . .
. 1 . 1 . . . .
1 . . . 1 . . .
. . . . . 1 . .
```
here is my given chess board as a bitboard. 
```
1 . . 1 . 1 1 .
1 1 1 1 1 . 1 1
. . . 1 1 . . .
. . 1 . . 1 . .
. . 1 1 . . . 1
. . 1 . 1 . . .
1 1 . . . 1 1 .
1 . . 1 1 . . 1
```

could you give me an advice? Thank a lot!

**Comment by tissatussa** [comment]
i think i understand your question, but i'm not sure .. could you elaborate on this and define your question more explicit ? I worked with the python-chess library and i can state : everything is possible. Maybe i can point you in a direction.

**Comment by cherepanovic** [comment]
my desired result is a SquareSet which represents attacked squares by a piece being on its square.  
For all figures except bishop, queen and rook it is a simple AND operation of possible attacks of a figure and the given board of opposite color, however, it is not enough as already said for bishop, queen and rook since for them you need to consider the "blockers".

This issue is written down here https://www.chessprogramming.org/Efficient_Generation_of_Sliding_Piece_Attacks

I hope now I have described precisely enough.

Thanks in advance!

**Comment by cherepanovic** [comment]
For that I need to know how to get the slides of rook and bishop for each square on the board then the calculation happens for each attack side as far I remember (*), that is why the reverse function is also needed. 

* - occupied X OR (occupied - (2*slider))

As this library does have already such a function as generate_legal_moves(), then my described problem should also be already realized

**Comment by cherepanovic** [comment]
thanks!
