### ISSUE TITLE
One more query and request

### ISSUE THREAD

**Issue by amalrajjs** [niklasf/python-chess#935]
Is there a software or code that can convert Lichess puzzle database from UCI move format to SAN move format?

**Comment by niklasf** [comment]
I am not aware of any, but maybe people in the [Lichess Discord](https://discord.gg/lichess) are. It's definitely something that this library could be useful for, but it will require some programming.

```python
>>> import chess
>>> board = chess.Board("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1")
>>> board.variation_san(chess.Move.from_uci(uci) for uci in "e2e4 e7e5".split())
'1. e4 e5'
```
