### ISSUE TITLE
Possible Issue with 'or' operator in example code

### ISSUE THREAD

**Issue by lineality** [niklasf/python-chess#936]
https://python-chess.readthedocs.io/en/latest/svg.html

Using the pipe "|" generates an error, while "or" does not.

![Screenshot from 2022-11-14 20-23-33](https://user-images.githubusercontent.com/26224792/201803533-c079daeb-cd61-4f3c-9f5d-8c9389c1c6f5.png)

![Screenshot from 2022-11-14 20-23-01](https://user-images.githubusercontent.com/26224792/201803536-f4450e07-6cab-4a36-bd2f-0d0b7a80c707.png)

**Comment by niklasf** [comment]
Hi. That's not quite the same:

```python
>>> dict.fromkeys(board.attacks(chess.E4), "#cc0000cc") | {chess.E4: "#00cc00cc"}
{11: '#cc0000cc', 13: '#cc0000cc', 18: '#cc0000cc', 22: '#cc0000cc', 34: '#cc0000cc', 38: '#cc0000cc', 43: '#cc0000cc', 45: '#cc0000cc', 28: '#00cc00cc'}
>>> dict.fromkeys(board.attacks(chess.E4), "#cc0000cc") or {chess.E4: "#00cc00cc"}
{11: '#cc0000cc', 13: '#cc0000cc', 18: '#cc0000cc', 22: '#cc0000cc', 34: '#cc0000cc', 38: '#cc0000cc', 43: '#cc0000cc', 45: '#cc0000cc'}
```

Looks like the former requires Python 3.9 for [PEP 584](https://peps.python.org/pep-0584/). I'll try to make the example more widely compatible.
