### ISSUE TITLE
Board not honoring side to move in fen

### ISSUE THREAD

**Issue by jshriver** [niklasf/python-chess#947]
When setting the Board using a fen with either Board(fen) or board.set_fen(fen) it's not changing the side to move to reflect it. 

Example:
import chess

seedfen = "2kr3r/1pp2ppp/p2bpn2/4n1q1/P2N4/1PP1B1PP/5PB1/R2R2K1 w - -"
board = chess.Board(seedfen)
print("White value: ", chess.WHITE)
print("Black value: ", chess.BLACK)

seedfen = "2kr3r/1pp2ppp/p2bpn2/4n1q1/P2N4/1PP1B1PP/5PB1/R2R2K1 b - -"
board = chess.Board(seedfen)
print("White value: ", chess.WHITE)
print("Black value: ", chess.BLACK)

Will output White no matter what.
White value:  True
Black value:  False
White value:  True
Black value:  False

Tried both methods to set the fen state.

**Comment by niklasf** [comment]
`chess.WHITE` is a constant and alias for `True`, `chess.BLACK` is a constant and alias for `False`. Maybe you meant to print `board.turn`?
