### ISSUE TITLE
FileExporter sometimes fails to export the whole game

### ISSUE THREAD

**Issue by IndeedLad** [niklasf/python-chess#948]
Hi,

I am working on program which generates quite big opening PGNs. In some cases I noticed that exporting Game object to PGN file is not working. Generated PGN is split after some quite big chunk of proper PGN notation. Mostly that happens when generated opening PGN is quite large but it does not happen all the time even with big PGNs and I wonder if this issue is generated on my part.

I wrote a code based on docs:

```
new_pgn = open(f"PGN/{variation_overview.opening_name}.pgn", "a", encoding="utf-8")
exporter = chess.pgn.FileExporter(new_pgn)
variation_overview.pgn_tree.accept(exporter)
```

pgn_tree is a chess.pgn.Game() object

Here is a generated PGN it contains 3 analysed openings. The last one Chigorin variation has that issue which I noticed (PS. Github is not supporting PGN file type so it's a txt)
[Repertoire against 1. d4 patch.txt](https://github.com/niklasf/python-chess/files/10355764/Repertoire.against.1.d4.patch.txt)

**Comment by niklasf** [comment]
Hi, are you looking at the file while the program is still running? If so, the result is expected due to output buffering in Python.

You can close the file

```python
new_pgn.close()
```

or keep it open and flush the output buffer

```python
new_file.flush()
```
or wait for the entire program to end.

**Comment by IndeedLad** [comment]
Oh, that was an elementary mistake on my part. Now it works like a charm. Thank you sir!
