### ISSUE TITLE
How to traverse the board in reverse order?

### ISSUE THREAD

**Issue by Nixonite** [niklasf/python-chess#95]
Hi,

First of all, big time fan of the project. This isn't really an issue, more of a question on how to use the library. 

I was told by the niklasf sometime ago in a previous issue that it would be faster to score moves in a game by stockfish in reverse order, but I have no idea how to do this nicely. My code thus far uses what I think is found in the docs and it goes in forward motion throughout the games like so:

```
node = chess.pgn.read_game(f)

def method(node):# found that 2 threads and 256 hash is ideal for 16 depth w.r.t. speed.
	engine = uci.popen_engine("stockfish")
	engine.uci()
	engine.setoption({"Threads":1, "Hash":64})
	info_handler = uci.InfoHandler()
	engine.info_handlers.append(info_handler)
	scores = []
	engine.ucinewgame()
	while not node.is_end():
		next_node = node.variation(0)
		engine.position(next_node.board())
		command = engine.go(depth=16)
		temp_score = info_handler.info
		scores.append(temp_score)
		node = next_node	
	return scores
```

How would I change this to look at the game nodes in reverse order?

**Comment by niklasf** [comment]
Hi. To clarify: Reverse order is not nescessarily faster, but it makes information from later positions available in the hashtable. You can iterate in reverse order this way:

```
node = node.end()
while node:
    print(node.move)
    node = node.parent
```

One potential pitfall: `info_handler.info` will get updated with information from the latest search and your above snippet will always reference that latest info. Be sure to make actual copies (e.g. `import copy; temp_score = copy.copy(info_handler.info)`).

**Comment by Nixonite** [comment]
Ah yeah I remember the idea behind the hashtable, but I didn't consider the infohandler thing. Good tip. This looks good to me!

```
def backward(node):# found that 2 threads and 256 hash is ideal for 16 depth w.r.t. speed.
    t1 = time.time()
    engine = uci.popen_engine("stockfish")
    engine.uci()
    engine.setoption({"Threads":2, "Hash":256})
    info_handler = uci.InfoHandler()
    engine.info_handlers.append(info_handler)
    scores = []
    engine.ucinewgame()
    node = node.end()
    while node:
        engine.position(node.board())
        command = engine.go(depth=16)
        temp_score = info_handler.info
        scores.append(temp_score)
        node = node.parent
    return (scores, time.time()-t1)

def forward(node):# found that 2 threads and 256 hash is ideal for 16 depth w.r.t. speed.
    t1 = time.time()
    engine = uci.popen_engine("stockfish")
    engine.uci()
    engine.setoption({"Threads":2, "Hash":256})
    info_handler = uci.InfoHandler()
    engine.info_handlers.append(info_handler)
    scores = []
    engine.ucinewgame()
    while not node.is_end():
        next_node = node.variation(0)
        engine.position(next_node.board())
        command = engine.go(depth=16)
        temp_score = copy.copy(info_handler.info)
        scores.append(temp_score)
        node = next_node
    return (scores, time.time()-t1)
```

If I don't add the `copy` part, you're right it just continues to say the move is e2e4 for everything. 

I tried both on one game to compare times. Forward was 30.159 seconds, backward was 28.89 seconds. 

Tried another game, forward was 17.93 seconds, backward was 16.36 seconds.

Close, but yeah slightly faster. Definitely good stuff. Thanks!
