### ISSUE TITLE
Support uci `go perft`

### ISSUE THREAD

**Issue by thomasahle** [niklasf/python-chess#951]
Many engines, such as Stockfish, support a non-standard UCI command `go perft <depth>`. This would be very useful to have in python-chess as a way to test engines.

This could be implemented using a `Limit()`. Alternatively, is there a good way to send custom commands and read the output through python-chess?

**Comment by thomasahle** [comment]
I ended up writing this code:
```
async def uci_perft(engine, depth):
    class UciPerftCommand(BaseCommand[UciProtocol, None]):
        def __init__(self, engine: UciProtocol):
            super().__init__(engine)
            self.moves = []

        def start(self, engine: UciProtocol) -> None:
            engine.send_line(f"go perft {depth}")

        def line_received(self, engine: UciProtocol, line: str) -> None:
            match = re.match("(\w+): (\d+)", line)
            if match:
                move = chess.Move.from_uci(match.group(1))
                cnt = int(match.group(2))
                self.moves.append((move, cnt))

            match = re.match("Nodes searched: (\d+)", line)
            if match:
                self.result.set_result(self.moves)
                self.set_finished()

    return await engine.communicate(UciPerftCommand)
```

**Comment by niklasf** [comment]
This is mostly Stockfish and derivates, right? Maybe not standardized enough to add to the API, but your snippet makes for a good example of custom engine communication. Then again, adding it to the documentation means that `engine.communicate()` would become a stable/public interface. I am on the fence ...

**Comment by thomasahle** [comment]
I noticed it in a few other engines:
 - https://github.com/kirillbobyrev/pabi/issues/60
 - https://github.com/hiblom/DoctorB
 - https://github.com/gflohr/Chess-Plisco

But I guess it's bad to support non-standard syntax. 

A supported way to do non-standard communication would be nice though. It allows writing general tools for testing chess engines. The engines only have to support a few "debug" commands (like perft) and the testing tool can run a suite of tests.

Btw, did you see this effort to formalize uci? https://talkchess.com/forum3/viewtopic.php?f=7&t=81233
