### ISSUE TITLE
Illegal move from a seemingly legal move?

### ISSUE THREAD

**Issue by Denzeduous** [niklasf/python-chess#952]
Hello everyone,

I'm not the greatest at Chess, but to me this looks like a legal move. I want to move a pawn from g7 to h8 by taking a rook and promote to a queen. However, I get this error when I attempt this and try to calculate the score via StockFish:
```
chess.IllegalMoveError: illegal uci: 'g7h8q' in 1rbqkb1r/pp1p1p1p/5P2/2p1B3/QnP4P/8/P2PP3/RN1PKBNR b KQk - 0 16
```
What is the problem with this move?

**Comment by trevorbayless** [comment]
The issue is that a pawn doesn't exist on g7, nor is anything promotable in the FEN you provided. Here's a visual of the FEN you provided: https://lichess.org/editor/1rbqkb1r/pp1p1p1p/5P2/2p1B3/QnP4P/8/P2PP3/RN1PKBNR_b_KQk_-_0_16?color=white
