### ISSUE TITLE
How do I use books and tablebases

### ISSUE THREAD

**Issue by DarkReaper231** [niklasf/python-chess#958]
I am pretty new to this and python overall. I found myself nice project utilizing this library and was capable to modify it to use lc0 with maia9
https://github.com/CSSLab/maia-chess

But how would I also apply opening books and tablebases and which would you suggest me to download?

```
def best(board, engine, moves):
    suggestions = engine.analyse(board, chess.engine.Limit(depth=1, nodes=1))
    next = []
    try:
        length = min(moves, len(suggestions['pv']))
        for i in range(length):
            next.append(suggestions['pv'][i])
        return next
    except KeyError:
        print('Something went wrong')
```

**Comment by niklasf** [comment]
Hi. Did you already see the examples on https://python-chess.readthedocs.io/en/latest/polyglot.html?

The tablebase documentation (https://python-chess.readthedocs.io/en/latest/syzygy.html) also has usage examples, but I don't think it makes sense to augment the intentionally human-like maia with perfect endgame knowledge.

**Comment by DarkReaper231** [comment]
Okay so best would be to only use polyglot?

Also I have read the documentation but I'm not quite sure how to implement it to the code I have provided. I still need to return **next** at the end.

Do you know where can I download a good .bin file for maia9 that would still result in human like moves but also pushed it's rating tiny bit higher than 1900?

**Comment by DarkReaper231** [comment]
I found myself a decent human like polyglot but I am confused about it's usage

```
       if our_turn:
            with chess.polyglot.open_reader(os.path.join(SCRIPT_DIR, 'bin', 'polyglots', 'Human.bin')) as reader:
                for entry in reader.find_all(board):
                    if entry != Null:
                        result = entry
                    else:
                        result = _engine.play(board, chess.engine.Limit(depth=1, nodes=1), game=object,
                                            info=chess.engine.INFO_NONE)
```

This always returns the first move. And doesn't proceed to the next one

**Comment by DarkReaper231** [comment]
I have figured out opening books

```
        # only get best move once
        if our_turn:
            with chess.polyglot.open_reader(os.path.join(SCRIPT_DIR, 'bin', 'polyglots', config["engine"]["Polyglot"] + ".bin")) as reader:
                move = reader.get(board)
                if move is not None:
                    result = move
                else:
                    # depth=25, nodes=3500000 for stockfish
                    result = _engine.play(board, chess.engine.Limit(depth=config["engine"]["Depth"].isdigit(), nodes=config["engine"]["Nodes"].isdigit()), game=object, info=chess.engine.INFO_NONE)
```

I don't know how to do the same with tablebases

**Comment by DarkReaper231** [comment]
@niklasf Is this the best way to do it for my needs?

```python
class TableBase:
    def __init__(self, move):
        self.move = move

    def __repr__(self):
        return f"TableBase(move={self.move})"


# get the tablebase move for the current position
def get_best_tablebase_move(board):
    tablebase = chess.syzygy.open_tablebase(os.path.join(SCRIPT_DIR, 'bin', 'syzygy'))
    best_score = -9999
    best_move = None
    for move in board.legal_moves:
        board.push(move)
        if board.has_castling_rights(True) or board.has_castling_rights(False) or board.piece_map().__len__() > 5:
            board.pop()
            continue
        score = tablebase.probe_wdl(board)
        board.pop()
        if score > best_score:
            best_score = score
            best_move = move
    if best_move is not None:
        return TableBase(best_move)
    else:
        return None
```

```python
        # only get best move once
        if our_turn:
            with chess.polyglot.open_reader(os.path.join(SCRIPT_DIR, 'bin', 'polyglots', config["engine"]["Polyglot"] + ".bin")) as reader:
                move = reader.get(board)
                if move is not None:
                    print("[INFO] :: Evaluated from opening book.")
                    result = move
                else:
                    tb_move = get_best_tablebase_move(board)
                    if tb_move is not None:
                        print("[INFO] :: Evaluated from tablebase.")
                        result = tb_move
                    else:
                        print("[INFO] :: Evaluated from neural network.")
                        result = _engine.play(board, chess.engine.Limit(depth=config["engine"]["Depth"].isdigit(), nodes=config["engine"]["Nodes"].isdigit()), game=object, info=chess.engine.INFO_NONE)
```

**Comment by niklasf** [comment]
* Looks like it could be simplified a fair bit. The tablebase API documents that `moves` is already sorted:
   ```
   Array of objects (Move)
   Information about legal moves, best first
   ```

* It's probably also a good idea to check the number of pieces (`chess.popcount(board.occupied)`), before making a network request to the tablebase.

* Is `.isdigit()` really what you want?

* Did you mean `object()`? Note that this would clear the hash table on each turn.

**Comment by DarkReaper231** [comment]
> 

I think the whole code for the API is wrong. I am picking a move with win category and using it's uci but that makes no sense here.

![image](https://user-images.githubusercontent.com/38611351/219989954-b1e91600-ebbb-47e1-86af-aabc44a5f556.png)

That makes no sense

![image](https://user-images.githubusercontent.com/38611351/219989982-1550528d-31c0-4251-a7db-727ae0fb534f.png)

I don't understand what the moves and categories mean. Actually the bot picks completely wrong moves. It goes for draw even when it can checkmate me. So the code must be wrong due to lack of understanding how the data actually work.

It is very confusing, we have a category loss but then in the moves it says win????? Sometimes it says null????? What is going on? I will need help from someone who understands the data better. I have no idea what the data mean and what moves should I pick fro mthe moves list. Could you help me?

**Comment by DarkReaper231** [comment]
OOOOOOOOOOOOOOOOOOOOOH MY GOOOOD
So all I had to do was just pick index 0 I am so stupid. What the hell. But in that case the categories are completely misleading

**Comment by DarkReaper231** [comment]
Okay this is the final product

```python
# get the tablebase move for the current position
def get_best_tablebase_move(board):
    num_pieces = chess.popcount(board.occupied)
    if num_pieces < 7:
        return None

    fen = board.fen()
    url = f"http://tablebase.lichess.ovh/standard?fen={fen}"
    response = requests.get(url)
    if response.status_code != 200:
        return None

    data = response.json()
    if 'moves' not in data or len(data['moves']) == 0:
        return None

    return TableBase(data['moves'][0]['uci'])
```

The our_turn didn't change. And .isdigit is there because the config library I am using would otherwise return it as string

**Comment by DarkReaper231** [comment]
If you see any other improvements, I'd be glad to know.

**Comment by niklasf** [comment]
Looks ok now. The category of moves might be confusing, because it's from the perspective of the position after the move.
