### ISSUE TITLE
Support for Python 3.10?

### ISSUE THREAD

**Issue by arctic420** [niklasf/python-chess#959]
Can I use this with python 3.10 ? Wondering as I get errors on just importing it.
`import chess
import chess.engine

board = chess.Board()`

Gives me 'ModuleNotFoundError: No module named 'chess.engine'; 'chess' is not a package'
Do I need to downgrade to use it?

**Comment by trevorbayless** [comment]
I'm using it on 3.10 without issue and 3.10 is listed as a supported version. Did you remember to `pip install chess`? What's your output when you run `pip show chess`?

**Comment by arctic420** [comment]
I did
`Name: chess
Version: 1.9.4
Summary: A chess library with move generation and validation, Polyglot opening book probing, PGN reading and writing, Gaviota tablebase probing, Syzygy tablebase probing, and XBoard/UCI engine communication.
Home-page: https://github.com/niklasf/python-chess
Author: Niklas Fiekas
Author-email: niklas.fiekas@backscattering.de
License: GPL-3.0+
Location: c:\users\....
Requires:
Required-by:`

This is what I get

**Comment by arctic420** [comment]
> I did
> 
> Name: chess Version: 1.9.4 Summary: A chess library with move generation and validation, Polyglot opening book probing, PGN reading and writing, Gaviota tablebase probing, Syzygy tablebase probing, and XBoard/UCI engine communication. Home-page: https://github.com/niklasf/python-chess Author: Niklas Fiekas Author-email: [niklas.fiekas@backscattering.de](mailto:niklas.fiekas@backscattering.de) License: GPL-3.0+ Location: c:\users.... Requires: Required-by:
> 
> This is what I get

Oddly I installed python 3.9 + chess but running it with py 3.10 suddenly works. So this issue is closed - but a new one opened :D
