### ISSUE TITLE
Incorrect FEN generation

### ISSUE THREAD

**Issue by ajpower** [niklasf/python-chess#96]
`Board.fen()` does not product a correct FEN representation of the position.

Example:
```python
>>> import chess
>>> board = chess.Board()
>>> board.push_san('e4')
>>> print(board.fen())
rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
```

As you can see, despite the double-square pawn advance on the last move, the 'target square' field of the FEN string is still a dash. [According to Wikipedia](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation#Definition), the target square is the position behind a pawn that just made a two-square move.

**Comment by niklasf** [comment]
See https://github.com/niklasf/python-chess/issues/66#issuecomment-192999948.
