### ISSUE TITLE
Report site/game when hitting IllegalMoveError

### ISSUE THREAD

**Issue by greg-finley** [niklasf/python-chess#961]
Thanks for this amazing library! 🙌 

While trying to [parse the Lichess history](https://github.com/greg-finley/lichess-bigquery/blob/9bec90592700807d3da68337ad468338127e2d7c/main.py#L52) for variants, sometimes hit an error like this:

```
error during pgn parsing
Traceback (most recent call last):
  File "/home/gregoryfinley/.local/lib/python3.9/site-packages/chess/__init__.py", line 2997, in parse_san
    return next(move for move in self.generate_castling_moves() if self.is_kingside_castling(move))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gregoryfinley/.local/lib/python3.9/site-packages/chess/pgn.py", line 1685, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "/home/gregoryfinley/.local/lib/python3.9/site-packages/chess/pgn.py", line 1059, in parse_san
    return board.parse_san(san)
  File "/home/gregoryfinley/.local/lib/python3.9/site-packages/chess/__init__.py", line 3001, in parse_san
    raise IllegalMoveError(f"illegal san: {san!r} in {self.fen()}")
chess.IllegalMoveError: illegal san: 'O-O' in 1rkrb3/ppppppb1/5n2/8/2PP2q1/PN2PQ2/1BP2P2/1RKR2N1 b KQkq - 1 14
```

I love that the code just keeps going when hitting this error, but I'm also curious which games it's happening on (I'd love to go see what happened). It would be nice if the game header like `[Site "https://lichess.org/J5v0n3my"]` were logged here as well. I don't think a `Board` would know this though, nor would it be worthwhile to add it just for this case?

Alternatively, what happens in such cases? Do I just end up with the moves before the parse error?

**Comment by niklasf** [comment]
> Alternatively, what happens in such cases? Do I just end up with the moves before the parse error?

Correct. You will receive a game where `game.errors` is a non-empty list of exceptions, and the problematic variations have been truncated at the illegal move. So you can check the game headers and moves of such games yourself.

That said, the logging could still offer more context by default.

**Comment by greg-finley** [comment]
Cool. That works enough for me to close out this issue, if the extra logging context isn't worth the trouble.
