### ISSUE TITLE
The piece capturing a pinned piece is now considered pinned

### ISSUE THREAD

**Issue by donkawechico** [niklasf/python-chess#967]
I see from [this issue](https://github.com/niklasf/python-chess/issues/375) that the `is_pinned` function is intended to be fairly rudimentary and that even empty squares can be considered "pinned".

But I have a situation that I thought I'd double-check whether it's intended or a bug. 

The situation is where a square with an actual PIECE on it is considered pinned even when that piece is the _opposite_ color as the king it's "pinned" against. In this situation, the opposite-color piece has no restrictions to its movement so seems like it shouldn't be considered a "pinned" piece.

For example, see below where a white knight is pinned by a black bishop and attacked by a black pawn. If the pawn takes the knight, then _the pawn_ is considered "pinned" against the white king. This isn't really a pin but a revealed check situation.

# Code repro
```
import chess

board = chess.Board('rnbqk1nr/ppp2ppp/4p3/8/1b1pP3/2NP1N2/PPP2PPP/R1BQKB1R b KQkq - 1 5')
print(board)

board.is_pinned(chess.WHITE, chess.C3) # Knight is pinned by bishop, and attacked by pawn

board.push(chess.Move(chess.D4, chess.C3)) # Capture with Pawn
print(board)

board.is_pinned(chess.WHITE, chess.C3) # Black pawn occupies C3, but is still considered pinned to the White king
```

# Output of above code
<img width="833" alt="image" src="https://user-images.githubusercontent.com/1480827/220407451-c83d95d5-7f05-445a-8055-b61189ea1f6c.png">

**Comment by niklasf** [comment]
Hi, thanks for reporting. This does match the intended behavior, that is, it only considers the king, blockers, and the square, regardless of any piece on it.
