### ISSUE TITLE
Docs: engine.configure() or await engine.configure()

### ISSUE THREAD

**Issue by jamesbraza** [niklasf/python-chess#973]
https://python-chess.readthedocs.io/en/latest/engine.html sometimes uses:
- `engine.configure`
- `await engine.configure`

In `chess==1.9.4` it seems `engine.configure` returns `None`, so there's nothing to `await`.

Can the docs on this be standardized to one approach or the other?  Or if there's not a clear answer, can we document when to use one, and when to use the other?

**Comment by niklasf** [comment]
Each example is given twice.

* Synchronous, with `chess.engine.SimpleEngine`. All methods block and return the result (in this case `None`).
* Async, with `await`.

The latter is preferred:

> The preferred way to use the API is with an [asyncio](https://docs.python.org/3/library/asyncio.html) event loop. The examples also show a synchronous wrapper [SimpleEngine](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.SimpleEngine) that automatically spawns an event loop in the background.
