### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 506: illegal multibyte sequence

### ISSUE THREAD

**Issue by Neutrino-Go** [niklasf/python-chess#983]
Error
Traceback (most recent call last):
  File "D:\文档\Python\chess\python-chess-master\test.py", line 4574, in test_lichess_pgn
    game = chess.pgn.read_game(pgn)
  File "D:\文档\Python\chess\python-chess-master\chess\pgn.py", line 1504, in read_game
    line = handle.readline().lstrip("\ufeff")
UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 506: illegal multibyte sequence

**Comment by niklasf** [comment]
Hard to tell without context, but it looks like you may have opened a file via something like `open("...", encoding="gbk")`, or maybe that encoding is the default on your system, but the file contains some text that is not strictly valid under gkb and/or uses a different encoding.
