### ISSUE TITLE
Why do `chess.pgn.Headers` require `str:str` mapping?

### ISSUE THREAD

**Issue by asy51** [niklasf/python-chess#997]
https://github.com/niklasf/python-chess/blob/bd371f68b631499d9107c20f1f785b111c547f62/chess/pgn.py#L887-L888

There are some header vals like player ELO that would be better represented as `int`s, `float`s, etc. Is there a reason why every header key and value must be of type `str`?

**Comment by niklasf** [comment]
It avoids answering some questions:
* Would the type be chosen dynamically based on the content, or statically for each header name?
* When parsing, how to handle PGNs not matching the expected type?
* When working with a parsed PGN, which types do I need to expect/handle?
* For floats, how exactly should they be formatted?

That said, typed getters/setters for specific headers could be convenient.
